### ISSUE TITLE
attribute "accuarcy" should be "accuracy"

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/eac-cpf-schema#1]

**Comment by karinbredenberg** [comment]
Check that the schema has the correct spelling.

**Comment by fordmadox** [comment]
Just a note that the 3 schemas have this bug, but the tag library does not.

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
We are going to fix this bug by changing the 3 schemas. 
By solving this issues the updated schema won’t be 100% backward compatible. During the feedback period with the community, we are going to highlight this schema update and are going to ask for special feedback here.

**Comment by fordmadox** [comment]
Just a quick note that I've added a branch for this issue: https://github.com/SAA-SDT/eac-cpf-schema/tree/issue_1  

I expect that as these issues are discussed, tested, and approved, we'll then move them into this branch: https://github.com/SAA-SDT/eac-cpf-schema/tree/phase-1-revision-2018

**Comment by fordmadox** [comment]
Just a note that the only change for the 2018 revision is fixing the typo of the attribute name.  For the next EAC revision, I'd suggest that this attribute (and all others) not be so permissive as to allow text when xs:token would suffice.

**Comment by SJagodzinski** [comment]
I'm still wondering about the possible and reasonable attributes value here. Couldn't find any example, neither in the tag libraries, nor in the example files.
We are going to aks the community for feedback with the call for comments.

**Comment by SJagodzinski** [comment]
According to the feedback we got during the call for comments, this attribut isn't used at all.
Solved with 2010_revised
