### ISSUE TITLE
<languageDeclaration>: should be repeatable

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#10]
Make `<languageDeclaration>` within `<control>` repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<languageDeclaration>` within `<control>` should be repeatable

## Context
Following EAD 3 schema.

Allows to define multiple languages for an EAC-CPF instance.

> It is true that `<languageDeclaration>` is designed to declare “the primary language and script in which the EAC-CPF instance is written”. But EAC-CPF schema (unlike other authority formats which have been designed long before the recent evolutions that make possible other conceptualizations of authority centered initiatives and developments, such as aggregation) assumes to be able to aggregate other alternative instances for the same entity in `<alternativeSet>` element. In the “Introduction: Concepts” section of the TL it is assumed that “Alternative EAC-CPF instances may be in different languages or in the same language.
> What if, par example, the EAC-CPF instance is a machine-generated aggregation of instances coming from different repositories in different languages?

[French archivists, 2012]

**Comment by karinbredenberg** [comment]
Agreed! Align with EAD3.

**Comment by SJagodzinski** [comment]
EAD 3 has `<languageDeclaration>` optional and repeatable within `<control>`. 
Adapt schema and tag library accordingly.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
