### ISSUE TITLE
<abbreviation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#101]
## Abbreviation
- rename to `<shortCode>`
- add **attributes:**
`@audience`
`@id`
`@languageOfElement`
`@scriptOfElement`
- keep scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
An element for encoding the shortened form of a word or phrase.

**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@expan` - Optional
`@lang` - Optional
`@script` - Optional

**May contain**: [text]

**Additional parent elements**: 
`<abstract>`, `<addressline>`, `<archref>`, `<author>`, `<bibref>`, `<citation>`, `<container>`, `<date>`, `<datesingle>`, `<didnote>`, `<dimensions>`, `<edition>`, `<emph>`, `<entry>`, `<event>`, `<fromdate>`, `<head>`, `<head01>`, `<head02>`, `<head03>` , `<item>` , `<label>` , `<materialspec>` , `<num>` , `<p>` , `<part>` , `<physdesc>` , `<physfacet>` , `<physloc>` , `<publisher>` , `<quote>` , `<ref>` , `<sponsor>` , `<subtitle>` , `<titleproper>` , `<todate>` , `<unitdate>` , `<unitid>` , `<unittitle>`

**Availability**:
Within `<conventiondeclaration>`: Optional, not repeatable
Within other elements: Optional, repeatable

## Context
The `<abbreviation>` element contains an abbreviation or code for identifying a thesaurus, controlled vocabulary, or other standard used in formulating and compiling the EAC-CPF description.

**May contain**: [token]
**May occur within**: `<conventionDeclaration>` , `<localTypeDeclaration>` , `<rightsDeclaration>` 
**Attributes:** `@xml:id` - optional
**Availability:** Optional, Non-repeatable

## Solution documentation: 
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<conventionDeclaration>`, `<localTypeDeclaration>` , `<rightsDeclaration>` 
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageOfElement` - optional 
`@scriptOfElement` - optional 
**Availability:** solution to follow

- New or other example needed?
- Topic for Best Practise Guide?

## Example encoding
```
<conventionDeclaration>
 <shortCode audience="external" id="shortCode1" languageOfElement="en" scriptOfElement="lat">acronym, abbreviation or short code of the convention</shortCode>
 <reference>externe reference to the convention</reference>
 <descriptiveNote>
  <p>decriptive note for convention declaration</p>
 </descriptiveNote>
</conventionDeclaration>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**`<shortCode>`   Short Code**

**Summary:** An optional element for encoding the shortened form of a word or phrase.
**May contain:** [text]
**May occur within:** `<conventionDeclaration>`, `<localTypeDeclaration>` , `<rightsDeclaration>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Description and Usage:** 
Used to record the shortened form of a word or phrase, for example, an acronym.
Use `<shortCode>` within `<conventionDeclaration>` or `<localTypeDeclatation>` to identify the code for a thesaurus, controlled vocabulary, or another standard used in creating the EAC-CPF description. Use within `<rightsDeclaration>` to provide an abbreviated name for the rights statement.
To improve interoperability, it is recommended that the value be selected from an authorized list of codes such as the MARC Code List (http://www.loc.gov/marc/sourcelist/).
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element Abbreviation:
Element becomes shortCode **Ok in both schemas**
May occur within conventionDeclaration 0..1, localTypeDeclaration 0..1 , rightsDeclaration 0..1  **Ok in both schemas**
Contains text  **Ok in both schemas**
@audience - optional (values limited to: external, internal)  **Ok in both schemas**
@id - optional  **Ok in both schemas**
@languageOfElement - optional **Needs to be added**
@scriptOfElement - optional  **Needs to be added**

**Result**: The attributes @languageOfElement and @scriptOfElement needs to be added in both schemas.

**Comment by fordmadox** [comment]
Just updated with https://github.com/SAA-SDT/eac-cpf-schema/commit/7d08f8ced13f5b4edf7329d9823d13bac0b6a726.  

I think there's still an open question about whether we need to enforce the order of these elements, but keeping it as-is from EAC for now.

**Comment by karinbredenberg** [comment]
Retested. 
@languageOfElement - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**

**Result**: Element ok in both schemas.
