### ISSUE TITLE
<rightsDeclaration>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#103]
## Rights Declaration
- add **attributes:**
`@audience`
`@scriptOfElement`
`@valueURI` 
`@vocabularySource`
`@vocabularySourceURI`
- remove xml namespace
- keep element definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
Additional EAD 3 attributes
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
An optional child element of `<control>` that indicates a standard rights statement associated with the EAC-CPF instance.

**May contain**: `<abbr>` , `<citation>` , `<descriptiveNote>`
**May occur within**: `<control>`

**Attributes:** `@xml:id`, `@xml:lang`, `@localType` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: 
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<shortCode>` , `<reference>` , `<descriptiveNote>`
**May occur within**: `<control>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability:** Optional, repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<control>
 <recordId>record identifier</recordId>        
 <maintenanceStatus value="new"/>
 <publicationStatus value="inprocess"/>
 <maintenanceAgency> [...] </maintenanceAgency>
 <rightsDeclaration audience="external" id="rightsdeclaration1" languageOfElement="en" scriptOfElement="lat" valueURI="conventionURI" vocabularySource="source" vocabularySourceURI="sourceURI">
  <shortCode>acronym, abbreviation or short code of the rights declaration</shortCode>
  <reference>externe reference to the rights declaration</reference>
  <descriptiveNote>
   <p>descriptive note for rights declaration</p>
  </descriptiveNote>
 </rightsDeclaration>
 <maintenanceHistory>  [...]  </maintenanceHistory>
</control>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<control>` that indicates a standard rights statement associated with the EAC-CPF instance.
**May contain:** `<descriptiveNote>` (0..1), `<reference>` (1..1), `<shortCode>` (0..1)
**May occur within:** `<control>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement `- optional
`@scriptOfElement` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:**
Use `<rightsDeclaration>` to provide structured information about the usage rights of the EAC-CPF instance. `<rightsDeclaration>` should only be used to reference shared published licenses, such as Creative Commons, RightsStatements.org, and published locally-defined licenses.
`<shortCode>` may be used to provide the abbreviated name for the rights statement. The value of `<shortCode>` should align with the rights statements referenced by `<reference>` and `<descriptiveNote>`.
`<reference>` must be used to provide a machine-readable reference to a license statement (for example, a dereferenceable URI).
`<descriptiveNote>` may be used to provide a human-readable description of the license statement.
**Availability:** Optional, repeatable

**Comment by karinbredenberg** [comment]
Test of element rightsDeclaration:
May occur within: <control> 0..n **Ok in both schemas**
May contain: <descriptiveNote> (0..1),  **Ok in both schemas**
<reference> (1..1),  **Ok in both schemas**
<shortCode> (0..1) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

In both the schemas but not in the TL attributes list:
@localType - optional
@localTypeDeclaration - optional
@target

**Result**: @ailie-s just want to check with you about the extra attributes and their be or not. Element being ready depends on that reply.

**Comment by fordmadox** [comment]
Example encoding above does include the localType attributes, but I don't remember which elements in control got to use those attributes vs. which didn't. Whatever was decided, that will eventually need to be spelled out clearly in the documentation.  It's confusing.  So confusing that maybe we can just remove localType attributes from everywhere and the local* elements from 'control' altogether?????  😅   (just my wish, I know)

**Comment by SJagodzinski** [comment]
@fordmadox : My fault, didn't removed `@localType` from `<rightsDeclaration>`.

Decision about `@localType` in `<control>` was taken in our [first November meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/20201106_EAC-CPF_minutes.pdf):

> - Use @localType for otherRecordId, otherAgencyCode, and localControl (which are semantically weak) and remove from 5 other elements in EAC-CPF and/or EAD3 

> - agreed to keep @localType within `<representation>`

**Comment by fordmadox** [comment]
Thanks, @SJagodzinski!:  I just fixed the schema with https://github.com/SAA-SDT/eac-cpf-schema/commit/2104d1283fe5d39d7f7b89fa1b1741899c6550d7.  @karinbredenberg this should be ready to test again, and what's in the TL is already set.

When it comes time to adding an example, we could encode one of the examples from TS-DACS, e.g. https://github.com/saa-ts-dacs/dacs/blob/ed0b5cfe5912fa08dd2557c7bdcf346f6354ebb5/part_II/chapter_13/10_rights_statement_for_archival_authority_records.md

**Comment by karinbredenberg** [comment]
Retested element:
@localType - **Not present in any of the schemas**
@localTypeDeclaration - **Not present in any of the schemas**
@target - **Optional in both schemas**

**Result**: Element ready.
