### ISSUE TITLE
<sources>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#106]
## Sources
- add optional attributes:
`@audience`
`@base`
`@scriptOfElement`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@localtype` - Optional
`@script` - Optional

## Context
A grouping element to record of the sources used for the description of the CPF entity in the EAC-CPF instance. 

**May contain**: `<source>`
**May occur within**: `<control>`
**Attributes:** `@xml:base`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<source>`, `<descriptiveNote>`
**May occur within**: `<control>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Availability:** Optional, Not repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<control>
 <recordId>record identifier</recordId>
 <maintenanceStatus value="new"/>
 <publicationStatus value="inprocess"/>
 <maintenanceAgency> [...] </maintenanceAgency>
  <maintenanceHistory>  [...] </maintenanceHistory>
 <sources audience="external" base="baseURI" id="sources1" languageOfElement="eng" scriptOfElement="lat">
  <source>[...]<source>
  <descriptiveNote>
   <p>description for all sources</p>
  </descriptiveNote>
 </sources>
</control>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<control>` that groups one or more `<source>`s of evidence used in description of the CPF entity in the EAC-CPF instance.
**May contain:** descriptiveNote (0..1), source (1..n)
**May occur within:** control
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Attribute Usage:**
Use `@base` to specify a URI (other than the base URI of the EAC-CPF instance) to be used for resolving relative URIs within `<sources>` or descendant elements.
**Description and Usage:**
Use `<sources>` to bind together one or more `<source>` elements
**Availability:** Optional, Not repeatable

**Comment by kerstarno** [comment]
Schema team, schema tests:

I've tested the draft XSD and RNG schemas for EAC-CPF 2.0 with regard to "sources" and can confirm the following:
- `<sources>` itself is optional within `<control>` in both XSD and RNG
- `<sources>` itself cannot be repeated
- `<sources>` requires the sub-element `<source>` in both XSD and RNG
- `<sources>`allows for the optional attributes `@audience`, `@id`, `@base`, `@languageOfElement`, and `@scriptOfElement`
- `<sources>` also allows for the inclusion of attributes from other namespaces - I've tested with some XLink attributes, which validated fine in XSD and RNG

What's currently missing is:
- `<sources>` does not allow for the optional sub-element `<descriptiveNote>`, neither in XSD nor in RNG, which is an addition following the general model for plural elements

What's currently in the XSD and RNG, but shouldn't be:
- `<sources>` currently allows for the optional attributes `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`, but shouldn't

**Comment by kerstarno** [comment]
I have updated the XSD and RNG schemas in development as well as the control.rng in the "source/modules" folder to address the pending issues mentioned in the previous comment. Schema tests have now been successful in all aspects.
