### ISSUE TITLE
<term>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#110]
## Term
- add optional attributes
`@audience`
`@conventionDeclarationReference`
`@id` 
`@maintenanceEventReference`
`@sourceReference`

- keep name
- change availability to required and repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@identifier` - Optional
`@rules` - Optional
`@source` - Optional
`@script` - Optional

**Additional attributes in EAC-CPF**
`@scriptCode` - optional
`@vocabularySource` - optional

**Additional parent elements in EAC-CPF**
`<function>` , `<legalStatus>` , `<localDescription>` , `<mandate>` , `<occupation>` , `<place>`

## Context
A generic element used to encode a descriptive term in accordance with local descriptive rules.

**May contain**: [text]
**May occur within**: `<function>` , `<legalStatus>` , `<localControl>`,  `<localDescription>` , `<mandate>` , `<occupation>` , `<place>`
**Attributes:** `@lastDateTimeVerified`, `@scriptCode`, `@transliteration`, `@vocabularySource`, `@xml:id`, `@xml:lang`
**Availability:** Optional, Non-repeatable

## Solution documentation

**May contain**: [text]
**May occur within**: list to follow
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventionDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Mandatory, Repeatable

- Topic for Best Practise Guide: `<functions>` (0..1) – `<function>` (1..n) – `<term>` (1..n) with @langugeOfElement to enter translation of a term.

**Comment by fordmadox** [comment]
@SJagodzinski :  this all makes sense to me.  One open question I still have, though, is around ```@transliteration```.  Either we keep that attribute (I know I argued to replace it and point to conventionDeclaration, which I think is the right way to go still since it allows users to add a URI and other data) or we need to add ```@conventionDeclarationReference``` to this element (and possibly the other _Reference attributes). 

I think the good news is that we're basically down to questions about the availability of attributes :smile:.

**Comment by fordmadox** [comment]
Just re-reading the "vocab*" minutes again, though, and it looks like this was the decision:

```Decision: <part> and <term> will NOT have the vocabulary attributes, but call for comments will ask for examples when people want to have vocabulary attributes on other elements```

Is that still right?  I added these attributes to ```term``` previously, but very easy to change that.

**Comment by kerstarno** [comment]
> @SJagodzinski : this all makes sense to me. One open question I still have, though, is around `@transliteration`. Either we keep that attribute (I know I argued to replace it and point to conventionDeclaration, which I think is the right way to go still since it allows users to add a URI and other data) or we need to add `@conventionDeclarationReference` to this element (and possibly the other _Reference attributes).
> 
> I think the good news is that we're basically down to questions about the availability of attributes 😄.

At the EAC Chicago meeting, 31 July, we decided that we would not have `@transliteration`, but use `<conventionDeclaration>` to specify transliteration rules and `@conventionDeclarationReference` to point to a specific `<conventionDeclaration>`. And if I am not mistaken, we also decided at this meeting that the `@...Reference` attributes would be added to all non-empty elements within `<cpfDescription>`, which does include `<term>`.

**Comment by SJagodzinski** [comment]
@fordmadox 

> Just re-reading the "vocab*" minutes again, though, and it looks like this was the decision:
> 
> `Decision: <part> and <term> will NOT have the vocabulary attributes, but call for comments will ask for examples when people want to have vocabulary attributes on other elements`
> 
> Is that still right? I added these attributes to `term` previously, but very easy to change that.

Yes, true, intially we decided to add the vocab attributes to //term, but decided in our October meeting to use the parent elements for these attributes. So, for the call for comments release they should be removed from the schema.

**Comment by SJagodzinski** [comment]
@fordmadox : 

> @SJagodzinski : this all makes sense to me. One open question I still have, though, is around `@transliteration`. Either we keep that attribute (I know I argued to replace it and point to conventionDeclaration, which I think is the right way to go still since it allows users to add a URI and other data) or we need to add `@conventionDeclarationReference` to this element (and possibly the other _Reference attributes).
> 
> I think the good news is that we're basically down to questions about the availability of attributes 😄.

Sorry, I just forgot that one here. I'll add the reference attributes. Thanks a lot for the reminder!

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An element used to specify a descriptive term in accordance with local rules.
**May contain:** [text]
**May occur within:** function, legalStatus, localControl, localDescription, mandate, occupation, otherEntityType
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventionDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<term>` is a required child element of `<function>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<mandate>`, `<occupation>` and `<otherEntityType>`, used to specify a descriptive term in accordance with local rules.
`<term>` can be repeated within its parent element to include translations of the same term. Use the `@languageOfElement `attribute to identify the language used in each `<term>` grouped within a single parent element.
**Availability:** Required, repeatable

**Comment by fordmadox** [comment]
@SJagodzinski , @ailie-s :  did we decide to remove `@lastDateTimeVerified` from this element (as well as from placeRole)???  I added that attribute to both, previously, since it is in EAC 1.0 (see https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-term).  I can remove it, of course (as I've now done from placeRole), but just wanted to make sure.  

Also, if it is removed, if anyone has any suggestions for how to handle that during the transformation process, please let me know.  At the very least, any existing values could be moved to a comment node.

**Comment by SJagodzinski** [comment]
@fordmadox : No idea, if we discussed about and agreed on that question, but we decided that we don't add the vocabulary attributes to `<term>`. Also there is not `@href` attribute, so there is no `@lastDateTimeVerified` necessary. Please remove.

Transformation: Values from //term@vocabularySource goes to parents @vocabularySourceURI. Value from //term@lastDateTimeVerified goes to ??? Do we need a place for it?

**Comment by fordmadox** [comment]
Ok, got it.  I just removed that attribute.  Once we confirm that we can remove or keep `@target`, it should be good :smile:   Everything else should hopefully match the above description now.  I think that I'll just migrate any existing term/@lastDateTimeVerified values to a comment node.  I could put them in an attribute of another namespace, but I don't know of any standards that already define that, so I'll probably go with a comment rather than making up a namespaced attribute.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `<term>` is a sub-element of `<localControl>`, `<otherEntityType>`, and the singular elements `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, and `<occupation>`
- in all of these contexts, `<term>` is required
- in all of these contexts, `<term>` can be repeated
- `<term>` can contain text,  but does not have any sub-elements itself
- `<term>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`  
- `<term>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to the RNG and the XSD schemas alike. 

The element is ready.

@ailie-s As a note, `@target` is missing yet from the TL draft.
