### ISSUE TITLE
<p>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#111]
## Paragraph
- add **attributes:**
`@audience` 
`@conventationDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21 
Child elements of singular/plural elements #61 
Suggestion to add <title> to EAC-CPF #60 

## EAD3 Reconciliation
**Additional EAD3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@script` - Optional

**Additional child elements in EAD3**
`<abbr>` `<corpname>` `<date>` `<emph>` `<expan>` `<famname>` `<footnote>` `<foreign>` `<function>` `<genreform>` `<geogname>` `<lb>` `<list>` `<name>` `<num>` `<occupation>` `<persname>` `<ptr>` `<quote>` `<ref>` `<subject>` `<title>`

**Availability:**
Within `<descriptivenote>:` Required, repeatable
Within all other parents: Optional, repeatable

## Context
A generic element used within other elements of <description> that marks one or more sentences that form a logical prose passage.

**May contain**: [text]
**May occur within**: `<biogHist>`, `<descriptiveNote>`, `<functions>`, `<generalContext>`, `<legalStatuses>`, `<localDescriptions>`, `<mandates>`, `<occupations>`, `<places>`, `<structureOrGenealogy>`
**Attributes:** `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation

**May contain**: [text], `<span>` (0..n), `<reference>` (0..n)
**May occur within**: `<biogHist>`, `<descriptiveNote>`, `<generalContext>`, `<structureOrGenealogy>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** 
- Within `<descriptivenote>:` Required, repeatable
- Within all other parents: Optional, repeatable

## Solution schema
 ```
<descriptiveNote>
  <p audience="external" conventionDeclarationReference="conventiondeclaration1" id="p1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">A generic element used within other elements of `<description>` that marks one or more sentences that form a logical prose passage. Repeat this element `<p>` in order to add more paragraphs or translations</p>
</descriptiveNote>
```

**Comment by ailie-s** [comment]
Tag Library Text: 

**Summary:** A general purpose element used to encode blocks of text.
**May contain:** [text], span (0..n), reference (0..n)
**May occur within:** biogHist, descriptiveNote, generalContext, structureOrGenealogy
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
Use `<p>` for bounding blocks of text. A paragraph may be a subdivision of a larger composition or it may exist alone. It is usually typographically distinguished: A line space is often left blank before it; the text begins on a new line; and the first letter of the first word may be indented, enlarged, or both.
**Availability:**
Within `<descriptivenote>`: Required, repeatable
Within all other parents: Optional, repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<p>` is a required and repeatable sub-element of `<descriptiveNote>`
- `<p>` is an optional and repeatable sub-element of `<biogHist>`, `<generalContext>`, and `<structureOrGenealogy>`
- `<p>` can have text
- `<p>` allows for the optional sub-elements `<span>` and `<reference>`; both sub-elements are repeatable
- `<p>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`  
- `<p>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to the RNG and the XSD schemas alike. 

The element is ready.
