### ISSUE TITLE
<objectBinWrap>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#113]
## Object Bin Wrap

Remove this element without any replacement.

Provide an example how to link to an imge file via relation in the Best Practise Guide.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
This element provides a place for a base64-encoded binary representation of a resource.

**May contain**: base64Binary
**May occur within**: `<cpfRelation>` , `<functionRelation>` , `<resourceRelation>`, `<setComponent>` , `<source>`
**Attributes:** `@xml:id` - Optional
**Availability:** Optional, Non-repeatable

## Solution documentation
- Example for Best Practise Guide needed (within //relation)

**Comment by SJagodzinski** [comment]
TS EAS meeting 6 August 2020:

Remove element <objectBinWrap> and provide example for linking images in Best Practise Guide.

**Comment by karinbredenberg** [comment]
Tested and non-existing in both schemas.

**Comment by SJagodzinski** [comment]
Linking to images/photos is described in BPG _Relation to Resource_.
