### ISSUE TITLE
<identity>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#114]
## Identity
- add optional attributes:
`@audience`
`@base`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`
- keep name and scope
- add **new optional element** `<otherEntityTypes>`
- add **renamed element** `<identityId>` and remove `<entityId>`
- add **renamed element** `<nameEntrySet>` and remove `<nameEntryParallel>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Add new content for `<entityType>` #44 
`<entityId>:` definition #55 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
A wrapper element for the name or names related to the identity being described within the `<cpfDescription>` element in the EAC-CPF instance. In case of multiple identities, a separate `<identity>` element is contained in each of the `<cpfDescription>` elements of instance.

**May contain**: `<descriptiveNote>` , `<entityId>` , `<entityType>` , `<nameEntry>` , `<nameEntryParallel>`
**May occur within**: `<cpfDescription>`
**Attributes:** `@identityType`, `@localType`, `@xml:base`, `@xml:id`, `@xml:lang`
**Availability:** Mandatory, Non-repeatable

## Solution documentation: 
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<descriptiveNote>`, `<entityType>`, `<identityId>`, `<nameEntry>`, `<nameEntrySet>`, `<otherEntityTypes>`
**May occur within**: `<cpfDescription>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@conventationDeclarationReference` - optional
`@id` - optional
`@identityType` - optional (values limited to: given, acquired)
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Required, Not repeatable

- Modify example encoding

## Example encoding
```
<cpfDescription>
 <identity audience="external" base="identiybaseURI" conventionDeclarationReference="conventiondeclaration1" id="identity1"  identityType="given" languageOfElement="en" localType="localtype" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
  <identityId></identityId>
  <entityType></entityType>
  <nameEntry>
   <part></part>
  </nameEntry>
  <nameEntrySet>
   <nameEntry></nameEntry>
   <nameEntry></nameEntry>
  </nameEntrySet>
  <descriptiveNote>
   <p></p>
  </descriptiveNote>
 </identity>
</cpfDescription>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<cpfDescription>` used to encode the name or names related to the identity being described within the EAC-CPF instance.
**May contain:** descriptiveNote (0..1), entityType (1..1), identityId (0..n), (nameEntry or nameEntrySet (1..n)), otherEntityTypes (0..n)
**May occur within:** cpfDescription
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base `- optional
`@conventationDeclarationReference` - optional
`@id `- optional
`@identityType` - optional (values limited to: given, acquired)
`@languageOfElement `- optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement `- optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<identity>` is a wrapper element used to group the elements necessary to encode the name or names related to the identity of the CPF entity within the `<cpfDescription>` element.
Within this element the `<entityType>` element is required and specifies the type of entity (i.e., corporateBody, family, or person). The optional `<otherEntityTypes>` element can be used to encode other entity types used in the local context. An optional `<identityId>` is available for any identifiers associated with the CPF entity.
One or more `<nameEntry>` elements and/or one or more `<nameEntrySet>` elements must be included. All names by which the identity, being described within one `<cpfDescription>` element in the EAC-CPF instance is known are provided within `<identity>`. Each of the names, whether authorized or alternatives, should be recorded in a separate `<nameEntry>` element. `<identity>` may accommodate two or more parallel names in different languages or scripts. In countries where there is more than one official language, such as Canada or Switzerland, names of CPF entities are frequently provided in more than one language. Within `<identity>`, a `<nameEntrySet>` element should be used to group two or more `<nameEntry>` elements that represent parallel forms of the name of the CPF entity being described.
Within `<identity>`, a `<descriptiveNote>` element may be used to record other information in a textual form that assists in the identification of the CPF entity.
In case of multiple identities of the same entity in one EAC-CPF instance, a separate `<identity>` element is contained in each of the `<cpfDescription>` elements of the EAC-CPF instance.
**Availability:** Required, Not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `<identity>` is a required sub-element of `<cpfDescription>`
- `<identity>` cannot be repeated
- `<identity>` itself first requires the sub-element `<entityType>`, which cannot be repeated and comes with the mandatory attribute `@value`
- `<identity>` then requires either `<nameEntry>` or `<nameEntrySet>` to be present, both of which can be repeated as well as they can be used alongside each other
- `<identity>` also allows for the optional sub-elements `<otherEntityTypes>`, which cannot be repeated, `<identityId>`, which can be repeated, and `<descriptiveNote>`, which cannot be repeated; these three are available in the order they have been mentioned here
- `<identity>` furthermore allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@identityType`(with values "given" and "acquired"), `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`
  - @fordmadox - `<identity>` is currently missing `@base`
- `<identity>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD. 

Awaiting addition of `@base` before retesting. 

@ailie-s - the draft TL is currently missing `@target`

**Comment by fordmadox** [comment]
@kerstarno Just updated this with https://github.com/SAA-SDT/eac-cpf-schema/commit/46b12080dc7bee681a7634531529ddfeb8473101.  I also checked the base issue, https://github.com/SAA-SDT/eac-cpf-schema/issues/149, and I believe that 'base' is now added to all elements identified on that issue.

**Comment by kerstarno** [comment]
@fordmadox Thank you. Will re-test in a minute. And, yes, I also had a look at #149 earlier and it seemed to me that all other elements that are meant to use `@base` have it (at least judging from a quick search in the draft schemas directly :-) ). To be confirmed, once we move to testing the attributes' issues.

**Comment by kerstarno** [comment]
Re-tested with regard to `@base`. 

- I can confirm, that `<identity>` now also allows for the optional attribute `@base`. 

Element is ready.
