### ISSUE TITLE
<entityType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#116]
## Entity Type
- **add new mandatory attribute** `@value` with restricted values (corporateBody, person, family)
- **add optional attribute**:
`@audience`
- remove xml namespace
- change content definition to no text (empty element)
- keep availability
- specify Best Practise Guide for usage and examples for local entity types in connection with `<entityType>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Add new content for `<entityType>` #44 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
The type of CPF entity being described. Values available are: person, corporateBody, or family.

**May contain**: "person" or "corporateBody" or "family"
**May occur within:** `<identity>`
**Attributes:** `@xml:id` - Optional
**Availability:** Mandatory, Not repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: value to follow (no text, no terms, empty element)
**May occur within**: `<identity>`
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@value` - required (values limited to: corporateBody, person, family)
**Availability**: Required, not repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<identity>
 <identityId>[...]</identityId>
 <entityType audience="external" id="entitytype1" value="family"/>
 <nameEntry> [...] </nameEntry>
</identity>

```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<identity>` encoding the type of CPF entity being described.
**May contain:** [empty]
**May occur within:** identity
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@target` - optional
`@value` - required (values limited to: corporateBody, person, family)
**Description and Usage:** Within `<identity>` the required <`entityType>` element specifies the type of CPF entity being described in the EAC-CPF instance as being a corporateBody, person, or family.
**Attribute Usage:** `<entityType>` must include the `@value `attribute with one of the values corporateBody, person or family.
**Availability:** Required, not repeatable

**Comment by fordmadox** [comment]
Another good reason to remove '@target' from all elements :smile:

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<entityType>` is required as sub-element of `<identity>`
- `<entityType>` cannot be repeated
- `<entityType>` cannot have text
- `<entityType>` requires the attribute `@value` (with the possible value "person", "corporateBody", or "family")
- `<entityType>` allows for the optional attributes `@audience`, `@id`, and `@target`
- `<entityType>` furthermore allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD. 

The element is ready. 

@ailie-s - the TL draft is currently missing `@target`.
