### ISSUE TITLE
<nameEntry>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#118]
## Name Entry
- keep name and scope
- **remove child elements** `<alternativeForm>`, `<authorizedForm>`, `<preferredForm>`
- **add renamed parent element** `<nameEntrySet>`
- review **attributes:**
a) remove xml namespace
b) add attributes
`@audience`
`@conventionDeclarationReference`
`@localTypeDeclarationReference`
`@maintainenceEventReference`
`@scriptOfElement`
`@sourceReference`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`

c) **add new optional attribute** `@status` with a closed list ("authorized" and "alternative") 
d) **add new optional attribute** `@preferredForm` with a closed list ("true" and "false")
- specify **Tag Library** and **Best Practise Guide** for usage and examples for parallel names and for new encoding

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_names_20200130.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/names/Topic_names_20200130.pdf)
`<nameEntry>:` add @rules #68 
`<nameEntry>:` add @idref #69 
`<nameEntry>:` add @normal #72 
`<nameEntry>:` usage of @localType #76 
Names control #26 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
An element containing a name entry for a corporate body, person, or family. `<nameEntry>` is made up of one or more `<part>` elements so that the CPF entity can be identified with certainty and distinguished from others bearing the same or similar names.

**May contain**: `<alternativeForm>`, `<authorizedForm>`, `<part>`, `<preferredForm>`, `<useDates>`
**May occur within**: `<identity>` , `<nameEntryParallel>`
**Attributes:** `@localType`, `@scriptCode`, `@transliteration`, `@xml:id`, `@xml:lang`
**Availability:** Mandatory, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**:  `<part>`, `<useDates>`
**May occur within**: `<identity>` , `<nameEntrySet>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)  
`@conventionDeclarationReference` - optional  
`@id` - optional  
`@languageOfElement` - optional  
`@localType` - optional   
`@localTypeDeclarationReference` - optional (highly recommended when @localType is used)  
`@maintainenceEventReference` - optional  
`@preferredForm` - optional (values limited to: true, false)  
`@scriptOfElement` - optional  
`@sourceReference` - optional  
`@status` - optional (values limited to: authorized, alternative)  
`@valueURI` - optional  
`@vocabularySource` - optional  
`@vocabularySourceURI` - optional  
**Availability:** Mandatory, Repeatable

- New or other example needed
 - use French name example from issue #26 for encoding
- Topic for Best Practise Guide
> Use existing attribute `@localType` with data type anyURI in `<nameEntry>` as child of `<nameentryset>` to specify the type to indicate what kind of parallel name is used, eg former, translation etc.

>  if the authorised, and with it the normalised, form of the name is known, it has to be encoded as name entry.

## Example encoding
```
<identity>
 <entityType></entityType>
 <nameEntrySet>
   <nameEntry audience="external" conventionDeclarationReference="#conventionDeclaration1" id="nameentry1" languageOfElement="en" localType="localtype" localTypeDeclarationReference="#localTypeDeclaration1" maintainenceEventReference="#maintenaceEvent1" preferredForm="true" scriptOfElement="lat" sourceReference="#source1" status="authorized" valueURI="nameURI" vocabularySource="VIAF" vocabularySourceURI="http://viaf.org/viaf/data">
   <part></part>
   <useDates></useDates>
  </nameEntry>
  <nameEntry audience="external" conventionDeclarationReference="#conventionDeclaration1" id="nameentry1" languageOfElement="en" localType="localtype" localTypeDeclarationReference="#localTypeDeclaration1" maintainenceEventReference="#maintenaceEvent1" preferredForm="true" scriptOfElement="lat" sourceReference="#source1" status="authorized" valueURI="nameURI" vocabularySource="VIAF" vocabularySourceURI="http://viaf.org/viaf/data">
   <part></part>
  </nameEntry>
  <useDates></useDates>
 </nameEntrySet>
</identity>
```

**Comment by SJagodzinski** [comment]
EAD-EAC-CPF joint meeting, 10 July 2020:

> While we see a clear parallel in these elements and their use, there was agreement to keep the elements (names and content model) as they are and to rather have a look at the documentation in order to clarify how they differ nonetheless. 
> Question was raised whether this is something users actually wonder about.
> Maybe not generally, but most likely in the context of extracting EAC-CPF from EAD3 and especially when thinking of a shared schema in future.  
>

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 29 July 2020:

Need to apply the same principle to `<nameEntry>`, ie if describing same name in a different language, needs to be a separate `<nameEntry>`, not additional `<part>`s with different language attributions.

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 31 July 2020:

Use 2 Hannah Arendt examples for name entry and update convention declaration encoding:

```
<conventionDeclaration audience="external" id="cd1" localtype="transliteration">
  <abbreviation>DIN 32708:2014</abbreviation>
<citation href="https://www.iso.org/standard/9029.html">Information and documentation - Romanization of Japanese</citation>
  <descriptiveNote id="dn1">
<p id="p1" languageOfElement="de">Angewendet werden nur die eigentlichen Umschriftvorgaben, nicht aber die Regeln zur Wortbildungin der lateinischen Umschrift. Diese erfolgt analog der Praxis von NACSIS.</p>
</descriptiveNote>
</conventionDeclaration>
[...]
<nameEntrySet localType="parallel">
<nameEntry languageOfElement="de" scriptOfElement="Latn" preferredForm="true" status="authorized" localType="native">
  <part localType="surname">Arendt</part>
  <part localType="firstname">Hannah</part>
</nameEntry>
<nameEntry languageOfElement="ja" scriptOfElement="Jpan" preferredForm="false" status="authorized" conventionDeclarationReference="#cd1">
  <part localType="surname">アーレント</part>
  <part localType="firstname">ハナ</part>
</nameEntry>
<nameEntry languageOfElement="en" scriptOfElement="Latn" preferredForm="false" status="authorized">
  <part localType="surname">Arendt</part>
  <part localType="firstname">Hannah</part>
</nameEntry>
<useDates>
  <dateSet>
	<dateRange>
   	<fromDate standardDate="1906">1906</fromDate>
   	<toDate standardDate="1975">1975</toDate>
	</dateRange>
  </dateSet>
</useDates>
</nameEntrySet>
```

**Comment by ailie-s** [comment]
Tag Library text:

**Summary**: An element containing a name entry for a corporate body, person, or family.
**May contain**:  `<part>` (1..n), `<useDates>` (0..1)
**May occur within**: `<identity>` , `<nameEntrySet>`
**Description**: 
Within `<identity>`, the element `<nameEntry>` is used to record a name by which the corporate body, person, or family described in the EAC-CPF instance is known.
When `<nameEntry>` occurs within `<nameEntrySet>` it is used to record two or more parallel forms of a name, for example official forms of the name in different languages and/or scripts.
Each form of the name is recorded in a separate `<nameEntry>` element.
Each `<nameEntry>` must contain at least one `<part>` element. Within `<nameEntry>` each of the component parts of a name may be recorded in a separate `<part>` element.
The `<nameEntry>` element may also contain a `<useDates>` element to indicate the dates the name was used.
**Attributes:**
`@audience` - optional (values limited to: external, internal)  
`@conventionDeclarationReference` - optional  
`@id` - optional  
`@languageOfElement` - optional  
`@localType` - optional   
`@localTypeDeclarationReference` - optional (highly recommended when @localType is used)  
`@maintenanceEventReference` - optional  
`@preferredForm` - optional (values limited to: true, false)  
`@scriptOfElement` - optional  
`@sourceReference` - optional  
`@status` - optional (values limited to: authorized, alternative)  
`@valueURI` - optional  
`@vocabularySource` - optional  
`@vocabularySourceURI` - optional  
**Attribute Usage:**
The `@status` attribute may be used to indicate whether the `<nameEntry>` is an authorized or alternative form of the name.
The attributes `@scriptOfElement` and `@languageOfElement` can be used to specify the script and language of each name recorded in `<nameEntry>`.
**Availability:** 
Within `<identity>`: one of `<nameEntry>` or `<nameEntrySet>` required, repeatable
Within `<nameEntrySet>`:  two or more `<nameEntry>`  required, repeatable
**Examples:**
```
<conventionDeclaration audience="external" id="cd1">
  <shortCode>DIN 32708:2014</shortCode>
<reference href="https://www.iso.org/standard/9029.html">Information and documentation - Romanization of Japanese</reference>
  <descriptiveNote id="dn1">
<p id="p1" languageOfElement="de">Angewendet werden nur die eigentlichen Umschriftvorgaben, nicht aber die Regeln zur Wortbildung in der lateinischen Umschrift. Diese erfolgt analog der Praxis von NACSIS.</p>
</descriptiveNote>
</conventionDeclaration>
[...]
<nameEntrySet localType="parallel">
<nameEntry languageOfElement="de" scriptOfElement="Latn" preferredForm="true" status="authorized" localType="native">
  <part localType="surname">Arendt</part>
  <part localType="firstname">Hannah</part>
</nameEntry>
<nameEntry languageOfElement="ja" scriptOfElement="Jpan" preferredForm="false" status="authorized" conventionDeclarationReference="#cd1">
  <part localType="surname">アーレント</part>
  <part localType="firstname">ハナ</part>
</nameEntry>
<nameEntry languageOfElement="en" scriptOfElement="Latn" preferredForm="false" status="authorized">
  <part localType="surname">Arendt</part>
  <part localType="firstname">Hannah</part>
</nameEntry>
<useDates>
        <dateRange>
   	<fromDate standardDate="1906">1906</fromDate>
   	<toDate standardDate="1975">1975</toDate>
	</dateRange>
</useDates>
</nameEntrySet>
```

**Comment by karinbredenberg** [comment]
Test of element nameEntry:
May contain: part (1..n), useDates (0..1) **Ok in both schemas**
Within identity: one of nameEntry or nameEntrySet required, repeatable **Ok in both schemas** 
Within nameEntrySet: two or more nameEntry required, repeatable **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventionDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional (highly recommended when @localType is used) **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@preferredForm - optional (values limited to: true, false) **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@status - optional (values limited to: authorized, alternative) **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: Element ready
