### ISSUE TITLE
@audience

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#119]
## Audience
Add optional attribute `@audience` with with closed lists of predefined values to all elements.

Availability: optional
Values: external, internal
May occur within: all elements

Rename attribute group "am.common.empty" from EAD3.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of `<control>` in both standards.

**Summary:**
An attribute that helps control whether the information contained in the element should be available to all viewers or only to repository staff. Available for all elements except <lb> and <colspec>. The attribute can be set to "external" in <archdesc> to allow access to all the information about the materials being described in the finding aid, but specific elements within <archdesc> can be set to "internal" to reserve that information for repository access only. This feature is intended to assist application software in restricting access to particular information by explicitly identifying data that is potentially sensitive or may otherwise have a limited audience. Special software capability may be needed, however, to prevent the display or export of an element marked "internal" when a whole finding aid is displayed in a networked environment.

**Values:** external, internal

## Context
EAD3 specific attribute.

## Solution documentation

**Summary:** An attribute that helps control whether the information contained in the element should be available to all viewers or only to repository staff. Available as global attribute for all elements. The attribute can be set to "external" in `<cpfDescription>` to allow access to all the information about the entity being described, but specific elements within `<cpfDescription>` can be set to "internal" to reserve that information for repository access only. This feature is intended to assist application software in restricting access to particular information by explicitly identifying data that is potentially sensitive or may otherwise have a limited audience. Special software capability may be needed, however, to prevent the display or export of an element marked "internal" when a whole finding aid is displayed in a networked environment.

**Values:** external, internal

**May occur within**: all elements

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

Keep the attribute as is. No need to add additional use cases as all agree it is clear at the moment.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@audience` is available with all 89 elements of EAC-CPF 2.0
- It can have the values "external" and "internal"
- Its data type is _token_
- It is always available alongside `@id`
- It is always available alongside `@target`, with the exception of `<eac>` where `@target` is not available

The above applies to both schemas, RNG and XSD.

The attribute is ready.
