### ISSUE TITLE
@countryEncoding

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#120]
## Country Encoding
Add optional attribute `@countryEncoding` with closed lists of predefined values to `<control>.`  Use schematron to validate ISO code.

Availability: optional
Values: iso3166-1, otherCountryEncoding
May occur within: `<control>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit#)
`<ontrol>` #81 

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of `<control>` in both standards.

**Summary:**
The authoritative source or rules for values supplied in countrycode in `<maintenanceagency>` and `<unitid>.` If the value "othercountryencoding" is selected an alternate code list should be specified in `<conventiondeclaration>.` Available only in `<control>.`

**Values:** iso3166-1, othercountryencoding

## Context
EAD3 specific attribute.

## Solution documentation
- Topic for Best Practise Guide: Schematron validation

**Summary:** The authoritative source or rules for values supplied in `@countryCode` in `<maintenanceAgency>` and `<placeName>.` If the value "otherCountryEncoding" is selected an alternate code list should be specified in `<conventionDeclaration>.` Available only in `<control>.`

**Values:** iso3166-1, othercountryencoding

**May occur within**: `<control>`

## Example encoding
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" repositoryEncoding="iso15511" scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceStatus value="new"/>
  <maintenanceAgency>[...]</maintenanceAgency>
  <maintenanceHistory>[...] >/maintenanceHistory>
 </control>
</eac>
```

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@countryEncoding` is an optional attribute in `<control>`
- It can have the values "iso3166-1" or "otherCountryEncoding"
- It has the data type _token_ as in EAD3

The above applies for both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox With regard to Schematron: I'm assuming, the EAD3 Schematron currently only includes checks for ISO 3166-1, as we wouldn't know what other country encoding people might want to use instead of this. But I was wondering, if Schematron documentation could include something about what to do when using "otherCountryEncoding" as the value here? Not necessarily for Schematron only, but also in terms of e.g. a recommendation as to where to define such other country codes (e.g. `<localControl>`?) next to mentioning the standard itself in `<conventionDeclaration>`.

**Comment by fordmadox** [comment]
Good question!  I haven't given the Schematron much thought yet, but we should see if we can find a time to get that framework started next week.

**Comment by kerstarno** [comment]
@fordmadox Please let me know if I can be of any help with that. Don't have any experience with Schematron yet, but happy to learn - and will be good for a head-start re EAD revision :-)
