### ISSUE TITLE
@languageEncoding

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#121]
## Language Encoding
Add optional attribute `@languageEncoding` with closed lists of predefined values to `<control>.`

Availability: optional
Values: iso639-1, iso639-2b, iso639-3, otherLangEncoding
May occur within: `<control>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / document
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit#)
`<control>` SAA-SDT/EAD3#81 
Language codes: adopt EAD 3 solution SAA-SDT/EAD3#29 

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of <control> in both standards.

**Summary:**
Specifies which standard list of codes is used to identify the language of the EAD instance and languages represented in the materials. The codes themselves are specified in langcode in `<language>` and lang in all non-empty elements. Available in <control>. If the value "otherlangencoding" is selected an alternate code list should be specified in `<conventiondeclaration>.`

**Values:** iso639-1, iso639-2b, iso639-3, otherlangencoding

## Context
EAD3 specific attribute.

## Solution documentation
- Topic for Best Practise Guide: Schematron validation; use schematron to validate ISO code

**Summary:** Specifies which standard list of codes is used to identify the language of the EAC-CPF instance and languages represented in the materials. The codes themselves are specified in `@languageCode` in `<language>` and `languageOfElement` in all non-empty elements. Available in `<control>.` If the value "otherLangEncoding" is selected an alternate code list should be specified in `<conventionDeclaration>.`

**Values:** iso639-1, iso639-2b, iso639-3, otherLangEncoding

**May occur within**: `<control>`

## Encoding example
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" repositoryEncoding="iso15511" scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceStatus value="new"/>
  <maintenanceAgency>[...]</maintenanceAgency>
  <maintenanceHistory>[...] >/maintenanceHistory>
 </control>
</eac>
```

**Comment by kerstarno** [comment]
Following conversations in the context of https://github.com/SAA-SDT/eas-schemas/issues/23, I think this attribute should be name `@languageencoding` instead of `@langencoding`.

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 31 July 2020:

IANA-codes to be used and to be available as one option for @languageEncoding defining which codes are used in a specific XML file.

**Comment by SJagodzinski** [comment]
Change value _otherLangEncoding_ to _otherLanguageEncoding_ ?

**Comment by kerstarno** [comment]
@fordmadox - while this issue is not yet part of our Schema milestone, I've came across the following during my test for `<control>`: there is not option yet in the XSD nor in the RNG to select "iana" as a value for `@languageEncoding`.

**Comment by fordmadox** [comment]
@kerstarno :  thanks!  for the testing period, I've just added a new option for "ietf-bcp-47", which sort of follows the format of the other options in that list (e.g. iso639-2b).  

As for potential validation options, I just noticed this really cool service, https://schneegans.de/lv/.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@languageEncoding` is an optional attribute in `<control>`
- It can have the values "iso639-1" (two-letter code), "iso639-2b" (three-letter code), "iso639-3" (essentially the same as ISO 639-2, but excluding the collective languages), "ietf-bcp-47" (for a possible combination of the ISO 639-1 two-letter language code with an ISO 15924 script code, an ISO 3166-1 country code, and the United Nations' Standard Country or Area Codes for Statistical Use, UN M49) or "otherLanguageEncoding"
- It has the data type _token_ as in EAD3

The above applies for both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox With regard to Schematron: I'm assuming, the EAD3 Schematron currently only includes checks for ISO 639 variants, as we wouldn't know what other language encoding people might want to use instead of this. But I was wondering, if Schematron documentation could include something about what to do when using "otherLanguageEncoding" as the value here? Not necessarily for Schematron only, but also in terms of e.g. a recommendation as to where to define such other language codes (e.g. `<localControl>`?) next to mentioning the standard itself in `<conventionDeclaration>`.
