### ISSUE TITLE
@repositoryEncoding

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#122]
## Repository Encoding
Add optional attribute `@repositoryEncoding` with closed lists of predefined values to `<control>.`

Availability: optional
Values: iso15511, otherRepositoryEncoding
May occur within: `<control>`

- use schematron to validate ISO code

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit#)
`<control>` #81

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
The authoritative source or rules for values supplied in `<agencycode>` and repositorycode in `<unitid>.` If the value "otherrepositoryencoding" is selected an alternate code list should be specified in `<conventiondeclaration>.` Available only in `<control>.`

**Values:** iso15511, otherrepositoryencoding

## Context
EAD3 specific attribute.

## Solution documentation
- Topic for Best Practise Guide: Schematron validation

**Summary:** The authoritative source or rules for values supplied in `<agencycode>`. If the value "otherRepositoryEncoding" is selected an alternate code list should be specified in `<conventionDeclaration>.` Available only in `<control>.`

**Values:** iso15511, otherrepositoryencoding

**May occur within**: `<control>`

## Encoding example
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" **repositoryEncoding="iso15511"** scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceStatus value="new"/>
  <maintenanceAgency>[...]</maintenanceAgency>
  <maintenanceHistory>[...] >/maintenanceHistory>
 </control>
</eac>

```

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@repositoryEncoding` is an optional attribute in `<control>`
- It can have the values "iso15511" or "otherRepositoryEncoding"
- It has the data type _token_ as in EAD3

The above applies for both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox With regard to Schematron: I'm assuming, the EAD3 Schematron currently only includes checks for ISO 15511, as we wouldn't know what other repository encoding people might want to use instead of this. But I was wondering, if Schematron documentation could include something about what to do when using "otherRepositoryEncoding" as the value here? Not necessarily for Schematron only, but also in terms of e.g. a recommendation as to where to define such other repository codes (e.g. `<localControl>`?) next to mentioning the standard itself in `<conventionDeclaration>`.
