### ISSUE TITLE
@dateEncoding

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#124]
## Date Encoding
Add optional attribute `@dateEncoding` with closed lists of predefined values to `<control>.`

Availability: optional
Values: iso8601, otherDateEncoding
May occur within: `<control>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)
`<control>` #81 

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
The authoritative source or rules for values provided in normal in `<date>` and `<unitdate>.` If the value "otherdateencoding" is selected an alternate code list should be specified in `<conventiondeclaration>.`

**Values:** iso8601, otherdateencoding 

## Context
EAD3 specific attribute.

## Solution documentation
**Summary:** The authoritative source or rules for values provided in `@standardDate` in `<date>`, `<fromDate>` and `<toDate>`. If the value "otherDateEncoding" is selected an alternate code list should be specified in `<conventionDeclaration>.`

**Values:** iso8601, otherDateEncoding 

**May occur within**: `<control>`

## Example encoding
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" repositoryEncoding="iso15511" scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceStatus value="new"/>
  <maintenanceAgency>[...]</maintenanceAgency>
  <maintenanceHistory>[...] >/maintenanceHistory>
 </control>
</eac>
```

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@dateEncoding` is an optional attribute in `<control>`
- It can have the values "iso8601" or "otherDateEncoding"
- It has the data type _token_ as in EAD3

The above applies for both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox With regard to Schematron: I'm assuming, the EAD3 Schematron currently only includes checks for ISO 8601, as we wouldn't know what other date encoding people might want to use instead of this. But I was wondering, if Schematron documentation could include something about what to do when using "otherDateEncoding" as the value here? Not necessarily for Schematron only, but also in terms of e.g. a recommendation as to where to define such other date codes (e.g. `<localControl>`?) next to mentioning the standard itself in `<conventionDeclaration>`.

**Comment by fordmadox** [comment]
Just a note that I do not think that "iso8601" is sufficient as a controlled value option.  Version 2019 of ISO-8601 is very different from version 2014, etc.

**Comment by karinbredenberg** [comment]
In the EAC-CPF meeting on the (2021-08-06) we concluded that this fall into the [Design principles](https://github.com/SAA-SDT/TS-EAS-subteam-notes/wiki/Design-Principles) (principle 7) an suggest that the principle gets an addition of links to the used versions and with this hands this over to the Schema team, @fordmadox .
