### ISSUE TITLE
@scriptEncoding

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#126]
## Script Encoding
Add optional attribute `@scriptEncoding` with closed lists of predefined values to `<control>.`

Availability: optional
Values: iso15924, otherScriptEncoding
May occur within: `<control>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)
`<control>` #81 

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
The authoritative source or rules for values supplied in script and scriptcode. If the value "otherscriptencoding" is selected an alternate code list should be specified in `<conventiondeclaration>.` Available only in `<control>.`

**Values:** iso15924, otherscriptencoding

## Context
EAD3 specific attribute.

## Solution documentation
- Rephrasing _Summary_ needed ?
- example needed
- Topic for Best Practise Guide?

**Summary:** The authoritative source or rules for values supplied in `@scriptOfElement` and `@scriptCode.` If the value _otherscriptencoding_ is selected an alternate code list should be specified in `<conventionDeclaration>.` Available only in `<control>.`

**Values:** iso15924, otherScriptEncoding

**May occur within**: `<control>`

## Example encoding
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" repositoryEncoding="iso15511" scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceStatus value="new"/>
  <maintenanceAgency>[...]</maintenanceAgency>
  <maintenanceHistory>[...] >/maintenanceHistory>
 </control>
</eac>
```

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@scriptEncoding` is an optional attribute in `<control>`
- It can have the values "iso15924" or "otherScriptEncoding"
- It has the data type _token_ as in EAD3

The above applies for both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@fordmadox With regard to Schematron: I'm assuming, the EAD3 Schematron currently only includes checks for ISO 15924, as we wouldn't know what other script encoding people might want to use instead of this. But I was wondering, if Schematron documentation could include something about what to do when using "otherScriptEncoding" as the value here? Not necessarily for Schematron only, but also in terms of e.g. a recommendation as to where to define such other script codes (e.g. `<localControl>`?) next to mentioning the standard itself in `<conventionDeclaration>`.
