### ISSUE TITLE
@listtype

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#127]
## List Type
Add optional attribute `@listType` with closed lists of predefined values to `<list>`.

Availability: optional
Values: ordered, unordered
May occur within: `<list>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
Specifies the type of list: a definition list pairs a `<label>` with a corresponding `<item>` containing text that describes the term; an ordered list is a numbered or lettered list; an unordered list is one in which sequence is not critical (e.g., a bulleted list). Available only on `<list>.`

**Values:** deflist, ordered, unordered

## Context
EAD3 specific attribute.
## Solution documentation

**Summary**: Specifies the type of list: an ordered list is a numbered or lettered list; an unordered list is one in which sequence is not critical (e.g., a bulleted list). Available only on `<list>.`

**Values**: ordered, unordered

**May occur within**: `<list>`

## Encoding example
```
<generalContext>
 <list listType="unordered" mark="circle">
  <item>list item, unordered with circle</item>
  <item>list item, unorded with circle</item>
 </list>
 <list listType="ordered" numeration="decimal">
  <item>first list item, numbered with decimal 1</item>
  <item>second list item, numbered with decimal 2</item>
 </list>
</generalContext>
```

**Comment by ailie-s** [comment]
Tag Library Text

**Summary:** Specifies the type of list: an ordered list is a numbered or lettered list; an unordered list is one in which sequence is not critical (e.g., a bulleted list). Available only on `<list>`.

**Values:** ordered, unordered

**Comment by fordmadox** [comment]
Note:  having value = "deflist" isn't very useful.  EAD3 has another element, named `defitem`, which _can_ be used in this case (but it can also be used if the list type is set to something else), but the schema does not enforce that.  If we want definition lists (which would require label-item pairs, if keeping with definition lists from HTML), then I'd suggest having a definitionList element, rather than gesturing to what might appear in a list based on an attribute value.  

With EAC, though, I'd suggest just removing "deflist" as an option from `@listType`.  

What do others think?

**Comment by kerstarno** [comment]
See my comment in #171: definition lists are one of those EAD approaches, for which I'd like to get an understanding if it is used and how it is used and to which extent it is used in the community as part of the EAD revision. For EAC-CPF, I would hence agree with the suggestion to leave out the "deflist" value.

**Comment by fordmadox** [comment]
Just removed "deflist" for the time being from EAC, since it really doesn't make sense (but can adjust if needed after the next EAC meeting).  See https://github.com/SAA-SDT/eac-cpf-schema/commit/1444b8ba8ecab3ac0f7194b526c3667a56db8ee1

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@listType` is an optional attribute in `<list>`
- It can have the values "ordered" or "unordered"
  - Note: the use of definition lists will be evaluated as part of the EAD revision
- It has the data type _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
