### ISSUE TITLE
@mark

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#128]
## Mark

After a discussion around `<list>` #171 , it was decided to use `@style` #242 to encode the character to be used in marking each list entry in an undorded list. Hence `@mark` won't be introduced in EAC-CPF.

--- obsolete ---
Add optional attribute `@mark` with closed lists of predefined values to `<list>`.

Availability: optional
Values: disc, circle, inherit, none, square
May occur within: `<list>`

--- obsolete ---

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
For lists with a listtype value "unordered," mark may be used to indicate the character to be used in marking each list entry. Values are drawn from the CSS "list-style-type" property list.

**Values:** disc, circle, inherit, none, square

## Context
EAD3 specific attribute.

## Solution documentation

**Summary:** For lists with a listtype value "unordered", mark may be used to indicate the character to be used in marking each list entry. Values are drawn from the CSS "list-style-type" property list.

**Values:** disc, circle, inherit, none, square

**May occur within**: `<list>`

## Encoding example
```
<generalContext>
 <list listType="unordered" mark="circle">
  <item>list item, unordered with circle</item>
  <item>list item, unorded with circle</item>
 </list>
</generalContext>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** For lists with a `@listType `value "unordered", mark may be used to indicate the character to be used in marking each list entry. Values are drawn from the CSS "list-style-type" property list.
**Values:** disc, circle, inherit, none, square

**Comment by kerstarno** [comment]
Decision not to adopt `@mark`, but to introduce `@style` instead (see #171). Will have to be made part of EAD during revision.

Ran a quick check with both schemas, RNG and XSD, to confirm that `@mark` is not available (anymore).
