### ISSUE TITLE
@numeration

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#129]
## Numeration

After a discussion around `<list>` #171 , it was decided to use `@style` #242 to encode the type of numeration marking each list entry in an orded list. Hence `@numeration` won't be introduced in EAC-CPF.

------ obsolete ---------
Add optional attribute `@numeration` with closed lists of predefined values to `<list>`.

Availability: optional
Values: armenian, decimal, decimal-leading-zero, georgian, inherit, lower-alpha, lower-greek, lower-latin, lower-roman, upper-alpha, upper-latin, upper-roman
May occur within: `<list>`

-- obsolete ----

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[20200128_SharedSchemaOverview](https://docs.google.com/document/d/1o9mtdzEzNTize7EGvEfKCsFR4ZY_OCVIXZdLDzOJnrY/edit)

## EAD3 Reconciliation
Decision from EAC-EAD-Schema joint meeting, 28 Jan 2020, due to alignment of in both standards.

**Summary:**
For lists with a listtype value of "ordered," numeration specifies the type of numeration.

**Values:** armenian, decimal, decimal-leading-zero, georgian, inherit, lower-alpha, lower-greek, lower-latin, lower-roman, upper-alpha, upper-latin, upper-roman

## Context
EAD3 specific attribute.

## Solution documentation

**Summary**: For lists with a listtype value of "ordered", numeration specifies the type of numeration. Values are drawn from the CSS "list-style-type" property list.

**Values:** armenian, decimal, decimal-leading-zero, georgian, inherit, lower-alpha, lower-greek, lower-latin, lower-roman, upper-alpha, upper-latin, upper-roman

**May occur within**: `<list>`

## Encoding example
```
<generalContext>
 <list listType="ordered" numeration="decimal">
  <item>first list item, numbered with decimal 1</item>
  <item>second list item, numbered with decimal 2</item>
 </list>
</generalContext>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** For lists with a `@listType` value of "ordered", numeration specifies the type of numeration. Values are drawn from the CSS "list-style-type" property list.
**Values:** armenian, decimal, decimal-leading-zero, georgian, inherit, lower-alpha, lower-greek, lower-latin, lower-roman, upper-alpha, upper-latin, upper-roman

**Comment by kerstarno** [comment]
Decision not to adopt `@numeration`, but to introduce `@style` instead (see #171). Will have to be made part of EAD during revision.

Ran a quick check with both schemas, RNG and XSD, to confirm that `@numeration` is not available (anymore).
