### ISSUE TITLE
<sourceEntry>: should be repeatable

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#13]
Make `<sourceEntry>` within `<source>` repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<sourceEntry>` within `<source>` should be repeatable

## Context
Following EAD 3 schema.

> to support multi-language description

 [@rockivist]

**Comment by karinbredenberg** [comment]
Agreed!

**Comment by SJagodzinski** [comment]
EAD 3 has `<sourceEntry>` optional and repeatable within `<source>`.
Adapt schema and tag library accordingly.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
