### ISSUE TITLE
<useDates>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#134]
## Date of Use
- keep name and scope
- **change parent element name** `<nameEntrySet>`
- **add optional attributes**
`@audience`
`@conventationDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 
- change **availability** to optional and repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
The dates when the name or names were used for or by the CPF entity being described.

**May contain**: `<date>`, `<dateRange>`, `<dateSet>`
**May occur within**: `<nameEntry>`, `<nameEntryParallel>`
**Attributes:** `@xml:id`, `@xml:lang`
**Availability:** Optional, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<date>` or `<dateRange>` or `<dateSet>`
**May occur within**: `<nameEntry>`, `<nameEntrySet>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, repeatable

- New or other example needed?

## Example encoding
```
<nameEntry>
 <part>name part</part>
 <useDates audience="external" conventionDeclarationReference="conventiondeclaration1" id="useDates" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
  <dateSet>
   <dateRange>
     <fromDate standardDate="1947">1947</fromDate>
     <toDate standardDate="1949">1949</toDate>
   </dateRange>
   <date notAfter="2019" notBefore="1900" standardDate="1950">use date of name</date>
  </dateSet>
 </useDates>
</nameEntry>
```

**Comment by ailie-s** [comment]
For the Tag Library, I'm looking for suggestions of how to create a technical description of the availability of child elements in cases such as this. `<useDates>` must contain one of `<date>`, `<dateRange>` or `<dateSet>`. Possible description below, alternative suggestions welcome!

**May contain:** (`<date>`, `<dateRange>`, `<dateSet>` (1..1))

This relates to: https://github.com/SAA-SDT/EAS-TagLibraries/issues/57

**Comment by kerstarno** [comment]
The suggestion makes sense to me and seems to be straight forward.

**Comment by ailie-s** [comment]
Two other suggestions for describing child element where there is a choice of element, from EAC-CPF meeting 2 October 2020:
 
**May contain:** (`<date>` or `<dateRange>` or `<dateSet>` (1..1))
**May contain:** (`<date>` | `<dateRange>` | `<dateSet>` (1..1))

**Comment by SJagodzinski** [comment]
I think, opion 1 is more clear and distinct for non-technical users. Technical users can read the schema.

 May contain: `(<date>` or `<dateRange>` or `<dateSet>` (1..1))

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 6 November 2020:

Agreed to repeat `<useDates>` within `<nameEntry>`.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<nameEntry>` and `<nameEntrySet>` that provides the dates when the name or names were used for or by the CPF entity being described.
**May contain:** date or dateRange or dateSet (1..1)
**May occur within:** nameEntry, nameEntrySet
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:** Within `<nameEntry>`, `<useDates>` provides the dates during which the name was used for or by the CPF entity. For parallel names (e.g. official forms of the name in different languages and/or scripts), `<useDates>` may occur in `<nameEntrySet>` rather than in the individual `<nameEntry>` elements contained in `<nameEntrySet>`.
**Availability:** Optional, repeatable

**Comment by kerstarno** [comment]
@fordmadox - as a note, as I just came across this while looking at the elements order question: `<useDates>` is currently not repeatable, neither as sub-element of `<nameEntry>` nor `<nameEntrySet>` and neither in the RNG nor the XSD.

**Comment by fordmadox** [comment]
@kerstarno thanks!  I forgot to update the availability.  I'll do that later today and let you know once it's fixed.

**Comment by fordmadox** [comment]
Just fixed with https://github.com/SAA-SDT/eac-cpf-schema/commit/59d0c6e8476a6818ae6754a62fcb40b7c555516c

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `<useDates>` is an optional sub-element of `<nameEntry>` and `<nameEntrySet>`
- `<useDates>` can be repeated in both contexts
- `<useDates>` requires one of the following to be present: `<date>`, `<dateRange>`, or `<dateSet>`
- `<useDates>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`
- `<useDates>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD. 

The element is ready. 

@ailie-s - the TL draft above is currently missing `@target`.
