### ISSUE TITLE
<alternativeForm>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#136]
## Alternative Form
- remove the element from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Names control #26
New attribute @status #70
[Topic_names_20200130.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/names/Topic_names_20200130.pdf)

## EAD3 Reconciliation
EAC-CPF specific element

## Context
Qualifies the name contained in `<nameEntry>` or set of names contained in `<nameEntryParallel>` as alternative or variant forms.

Revising EAC-CPF and names control, the element will be removed and an attribute `<nameEntry @status>` will indicate if a name is authorised or alternative. The according rule is encoded in `<conventionDeclaration>`, where `<nameEntry>` is referring to via attributes.

## Solution documentation
- remove from Tag Library

**Comment by kerstarno** [comment]
I think, this still needs to go through schema testing, too, even if only to confirm that the element is not in the schema anymore. Will do that check later on today or early tomorrow and will the change the milestone again as agreed.

**Comment by kerstarno** [comment]
I was thinking, this still needs to go through schema testing, too, even if only to confirm that the element is not in the schema anymore. So, tested as part of the schema team's schema testing. 

I can confirm, that `<alternativeForm>` is not available anymore, neither with `<nameEntry>`, nor with `<nameEntrySet>`. This is the case for both, RNG and XSD.
