### ISSUE TITLE
<preferredForm>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#137]
## Preferred Form of Name
- remove the element from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<preferredForm>:` turn into attribute #71
[Topic_names_20200130.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/names/Topic_names_20200130.pdf)

## EAD3 Reconciliation
EAC-CPF specific element

## Context
An element used to indicate which of the parallel names recorded within `<nameEntryParallel>,` is the preferred one for display purposes in a given context.

Revising EAC-CPF and names control, the element will be removed and an attribute <nameEntry @preferredFrom> will indicate if a name is the preferred form for display.

## Solution documentation: agreed solution for TL and guidelines
- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:
`<preferredForm>` is not available anymore as a sub-element of `<nameEntry>` within `<nameEntrySet>`, neither in RNG, nor in XSD.

Test successful.
