### ISSUE TITLE
Proposal to deprecate or remove <sourceEntry> and use <citation> instead

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eac-cpf-schema#139]
## Creator of issue

1. EAC-CPF team
2. TS-EAS
3. @kerstarno @fordmadox 
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: In the context of dealing with assertion description (see #43 as well as the paper on the topic at https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/assertion/Topic_assertions_20200327.pdf), the proposal was made to remove `<sourceEntry>` from `<source>` and to use `<citation>` instead, possibly including a revision of the conceptual model of `<citation>`.  If approved, the change would also apply to EAD3 and result in according updates to the respective tag libraries.

## Reporting a bug

* Text:

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
`<sourceEntry>` is currently optional and only used in this very specific context, while `<citation>` seems to fulfil a similar purpose at least. 

**For reference** 
- The EAC-CPF tag library summarise `<sourceEntry>` as "textual identification, such as a title, for a particular source of evidence" and describes the element as "identif[ying] a source directly rather than using other content in <objectBinWrap> or <objectXMLWrap>" and as "generally contain[ing] free text".
- The EAD3 tag library summarise `<sourceEntry>` as "identif[ying] a specific source" and describes the element as being "used for brief citation information" - so, maybe as a short version of what would be encoded in `<citation>`? - and states that "any additional information should be provided in `<descriptivenote>`".

- With regard to `<citation>`, which is available in various contexts within EAC-CPF, the tag library summarises that the element "cites an external resource" and specifies that it "points to a resource that provides descriptive data which is not otherwise given" and "should not be confused with the <source> element which is used to declare a particular resource used in the composition of the EAC-CPF instance".
- In EAD3, `<citation>` is only used with the elements `<conventiondeclaration>`,`<localtypedeclaration>`,  and `<rightsdeclaration>` and is hence summarised as "identif[ying] any rules and conventions" and described as "cit[ing] an external resource in human and/or machine-processable form".
  - For "provid[ing] a link to content that may be internal or external to the finding aid" in any other contexts, EAD3 uses `<ref>`.


 



Decisions in this issue need to be reflected in #108 as well.

**Comment by kerstarno** [comment]
**Aspects to consider:**
- Based on the exmaples used in both tag libraries, `<sourceEntry>` seems to be meant to mainly capture the title/name of a source, while `<citation>` - especially in EAC-CPF - seems to aim ate to encoding more complete bibliographic information of a cited resource.
- The content model for `<sourceEntry>` in both EAS is more closely related. In both EAS, `<sourceEntry>` can only have [text], while `<citation>` can have [text] and `<span>` in EAC-CPF, but `<abbr>`, `<emph>`, `<expan>`, `<foreign>`, `<lb>`, `<ptr>`, and `<ref>` in EAD3, which might have an impact with regard to reconciliation.
- `<citation>` can be used with linking attributes, while `<sourceEntry>` does not provide this option. The parent element in this case, `<source>`, also comes with the same linking attributes. If we did replace `<sourceEntry>` with `<citation>`, where would we then expect users to include information for online resources?

**Comment by fordmadox** [comment]
Agreed with all of the above points that need to be considered. Just a quick note for now, though, regarding an upcoming / related change in SNAC.  See https://portal.snaccooperative.org/node/486. 

> The "Source Name" field is being removed in favor of the "Citation" field, and editors will be able to search and select Citations directly instead of needing to search by Source Names from the Cite button on specific SNAC elements.

**Comment by SJagodzinski** [comment]
The proposal to replace `<sourceEntry>` by `<citation>` in the[ topic paper on Assertion description](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/assertion/Topic_assertions_20200327.pdf) was accepted during the [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf) on 9 March 2020.

Later on, it was decided to change the elements name from `<citation>` into `<reference>`, cf #102

**Comment by kerstarno** [comment]
Not that I'd argue for keeping `<sourceEntry>` at any costs, especially after the general question about this being an "entry" element discussed during the last EAC team meeting, but wasn't this still a pending question according to the Berlin minutes? Maybe good to reconfirm during the next EAC team meeting?
