### ISSUE TITLE
<agencyCode>: change or remove regex pattern

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#14]
The content for the element`<agencyCode>` within `<maintenanceAgency>` is defined as xs:token with a regex pattern that corresponds ISIL code. Change or remove the regex pattern.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
There are 2 different proposals for the content of `<agencyCode>`:

1.  `<agencyCode>` will now be required to be a token, though it will be quite lenient in what it will accept: any character except a whitespace character [used by SNAC, contributed by @dpitti]

2. following EAD 3 without any restriction for the element content of `<agencyCode>`

## Context

* Text: 

> Being idealistic, wishful, the `<agencyCode>` value is restricted to an ISIL compliant value, and `<otherAgencyCode>` is restricted to NMTOKEN.
> In reality the ISIL codes are not strictly compliant with ISIL, which is to say, they frequently contain characters that are not allowed.

  [@dpitti]

> For possible types: type="ISO15511" for a code being compliant and type="ISIL" for an officially registered code. Just to accommodate the case, when an institution would use an identifier compliant with ISO 15511, but not (yet) registered as ISIL code might not be that uncommon (although of course not ideal...).

 [Kerstin Arnold]

see also #15

**Comment by karinbredenberg** [comment]
align with EAD3 and the other issues of the same sort.

**Comment by karinbredenberg** [comment]
In EAD3 it is checked when the EAD/@repository encoding is set to the value iso15511 when it uses the value otherrepositoryencoding no check is preformed. It might need more work here so this checks done in EAD3 also are made in EAC-CPF which means this is partly a Phase-2 issue where attributes and checks in Schematron is added in the same way as EAD3 for attributes describing repositoryencoding and some other attributes to be found in the EAD-element.
Perhaps the way is to at this point in phase-1 not remove the regex instead to update it so its corrrect compared to the iso and do the change in phase-2 since you can use otheragencycode for your own value.

**Comment by SJagodzinski** [comment]
- agency code pattern in eac.xsd: (([A-Z]{2})|([a-zA-Z]{1})|([a-zA-Z]{3,4}))(-[a-zA-Z0-9:/\-]{1,11})

- agency  code pattern in ead3.xsd: '(^([A-Z]{2})|([a-zA-Z]{1})|([a-zA-Z]{3,4}))(-[a-zA-Z0-9:/\-]{1,11})$' 
--> taken from ead3_rules.xsl: iso15511Pattern

Following Karins proposal, adapt schema with the ead3 pattern and use `<otherAgencyCode>` if you want to use a non-ISIL code. Add schematron solution for phase 2, as part of EAD3-Reconciliation.

**Comment by wisserk** [comment]
The issue I see is twofold: 

1) Are we committed to compliance with EAD3; and if so, does that mean only changes on the EAC-CPF end of things or would we make recommendations for adjustments to EAD3 as well? 

2) If we are committed to compliance with EAD3, is that solely at phase 2 effort, or can we make interim adjustments identified (such as this one) in phase 1?

**Comment by wisserk** [comment]
Results of team discussion: 

Prescriptive patters in schema takes away autonomy of the system. Instead the implementation/use of data value standards should be enforced locally. Therefore:

a) leave agencyCode open
b) Add @type to identify the data value standard: ISSUE #15  
c) In documentation recommend the use of data value standards and use ISO 15511 as an example. Additional language about "good reasons" for use of a data value standard.

Discussion points: 
* Role of documentation versus the role of the schema
* Inclusion of best practice recommendations in documentation
* Distinction between @type and @localType (there are two different functions here). 
* Standards within and outside of the archival context: EAC-CPF has applications outside of the archival community, EAD is primarily an archival standard; in reconciliation does this create conflict?
* Reconciliation should account for distinctions between definitions and labels. (e.g., @type needs to mean the same thing in both standards, @localType needs to mean the same thing in both standards, etc.); a discussion for phase 2.

**Comment by SJagodzinski** [comment]
### Result of team discussion:

Discussing #14, removing regex pattern requires adding an attribute in order to identify the data value standard. `@type`  is not suitable.  

Introducing a new attribute with a wide scope like identifying data value standards seems to be a comprehensive issue, that should be carefully discussed and is scheduled for eac-cpf revision (phase).
Ergo, both issue #14 and #15 aren't solved with the update and are forwarded to phase 2.

**Comment by SJagodzinski** [comment]
Comment by G. Müller (via email, 26 Apr 2019):

I‘d very much like to keep the regex. It simplifies validating files for both data and service providers. However, there are good arguments for excluding regex from the Schema, too. I thus support Daniels approach. If it is possible for data providers to encode a controlled statement about the quality of the agencyCode (registered, ...), it will be sufficient for service providers to deal with the data. I have no preferences on attributes or elements but I want to avoid a simple plain text approach for the code.

**Comment by SJagodzinski** [comment]
As noted in #15, the EAC-CPF team already [agreed](https://github.com/SAA-SDT/eac-cpf-schema/issues/15#issuecomment-379280587) to remove regex pattern for `<agencyCode>`, and to use attributes to encode information about a standard the agency code complies with and to qualify the agency code.
