### ISSUE TITLE
<representation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#140]
## Representation
- add as new optional, repeatable child element to `<control>`
- add attributes:
`@audience`
`@href`
`@id`
`@languageOfElement`
`@lastDateTimeVerified`
`@localTypeDeclarationReference`
`@linkRole`
`@linkTitle` 
`@scriptOfElement`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<control>:` add child element `<representation>` #9 

## EAD3 Reconciliation
use the same [definition as EAD 3](https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-representation)

## Context
new element

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text]
**May occur within**: `<control>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@href` - optional 
`@id` - optional
`@languageOfElement` - optional
`@lastDateTimeVerified` - optional
`@linkRole` - optional
`@linkTitle` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional
**Availability:** Optional, Repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example ecoding
```
<control >
 <recordId>records identifier</recordId>
 <maintenanceAgency>
  [...]
 </maintenanceAgency>
 <maintenanceHistory>
   [...]
 </maintenanceHistory>
 <representation audience="external" id="representation1" href="link to representation" languageOfElement="en" lastDateTimeVerified="20209-11-09" localType="localRepresentation" localTypeDeclarationReference="localTypeDeclaration1" linkRole="roleOfLink" linkTitle="linktext" scriptOfElement="lat">text about representation; use case: https://snaccooperative.org/view/44995506</representation>
</control>
```

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 6 November 2020:

- keep optional `@localType` and add optional `@localTypeDeclarationReference` in `<representation>`
- add optional `@lastDateTimeVerified` in `<representation>`

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<control>` for recording a link to a deliverable version of the EAC-CPF instance.
**May contain:** [text]
**May occur within:** `<control>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@href` - optional
`@id `- optional
`@languageOfElement` - optional
`@lastDateTimeVerified` - optional
`@linkRole` - optional
`@linkTitle` - optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional
**Description and Usage:**
Use `<representation>` to record a link to a deliverable version of an EAC-CPF instance, for example an XML, HTML or PDF version.
**Attribute Usage:**
Use `@href` to specify a link to a deliverable version of the EAC-CPF instance.
The optional `@localType` attribute can be used to differentiate between multiple `<representation>` elements.
**See Also:**
Use `<otherRecordId>` to provide any local identifier for the EAD instance that does not link to a deliverable version.
**Availability:** Optional, Repeatable

**Comment by SJagodzinski** [comment]
@ailie-s : Sorry, my fault. @instanceURL was rejected and we suggest to use `//representation @href` to link to the instance URL, cf https://github.com/SAA-SDT/eac-cpf-schema/issues/130

**Comment by karinbredenberg** [comment]
Test of element representation:
May contain: [text] **Ok in both schemas**
May occur within: <control> 0..n **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@href - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@lastDateTimeVerified - optional **Ok in both schemas**
@linkRole - optional **Ok in both schemas**
@linkTitle - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**

**Result**: element ready.
