### ISSUE TITLE
<otherEntityTypes>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#141]
## Other Entity Types
- add as new optional, non-repeatable child element to `<identity>`, serves as plural wrapper for `<otherEntityType>` elements
- add attributes:
`@audience`
`@conventationDeclarationReference`
`@id`
`@languageOfElement` 
`@maintenanceEventReference` 
`@scriptOfElement`
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Add new content for `<entityType>` #44

## EAD3 Reconciliation
EAC-CPF specific element

## Context
new element

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: `<descriptiveNote>`, `<otherEntityType>` 
**May occur within**: `<identity>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, non repeatable
- Example needed
- Topic for Best Practise Guide

## Example ecoding
```
<identity>
 <entityType value="family"/>
 <otherEntityTypes audience="external" conventionDeclarationReference="conventiondeclaration1" id="otherentitytypes1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
  <otherEntityType>
   <term>term for other entity type</term>
  </otherEntityType>
  <otherEntityType>
   <term>another term for other entity type</term>
  </otherEntityType>
  <descriptiveNote>
   <p>descriptive note for other entity types</p>
  </descriptiveNote>
 </otherEntityTypes>
 <nameEntry> [...] </nameEntry>
</identity>
```

**Comment by fordmadox** [comment]
Is ```otherEntityTypes``` (plural) really meant to be repeatable (as described above)?

**Comment by fordmadox** [comment]
Okay, I think that the TL description above is a typo (i.e. "Availability: Optional, Repeatable"), but this part, "non-repeatable child element to ```<identity>```", is what is actually intended.  Keeping it as non-repeatable.

**Comment by kerstarno** [comment]
@fordmadox - yes, I think we intended `<otherEntityTypes>` to be done in the same way as other plural elements, i.e. being optional  and not being repeatable.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<identity>` used as a wrapper for one or more `<otherEntityType>` elements.
**May contain:** descriptiveNote (0..1), otherEntityType (1..n)
**May occur within:** identity
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Description and Usage:**
An optional child element of `<identity>` used as a wrapper for one or more `<otherEntityType>` elements. These elements are used to encode any additional or alternative entity types used for the CPF instance in addition to the required `<entityType>` element with values of corporateBody, person or family. 
`<otherEntityTypes>` must include at least one `<otherEntityType>` element.
`<descriptiveNote>` can be used to add any additional descriptive information to the `<otherEntityTypes>`.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element otherEntityTypes:
May occur within: identity 0..1 **Ok in both schemas**
May contain: descriptiveNote (0..1), otherEntityType (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Missing in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result:** addition of the two language attributes needed, @target has been added.

**Comment by karinbredenberg** [comment]
Retest of element:
@languageOfElement - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**

**Result**: element ready

**Comment by SJagodzinski** [comment]
This issue was labelled for _Comments period_ in relation with #271.

Solution for #271 works in the instant case, as well, c.f. https://github.com/SAA-SDT/eac-cpf-schema/issues/271#issuecomment-913154524

No need to change encoding, schema or Tag Library description. Changes in PBG and examples needed.
