### ISSUE TITLE
<biogHist>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#143]
## Biography or History
* add optional attributes:
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference`
* keep the short element name _biogHist_ as it is well introduced in both EAS
* add new optional, non repeatable child element `<head>`
* remove child element: `<outline>`, `<reference>` (fka `<citation>)`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<biogHist/>:` please allow `<head/>` #51 
Child elements of singular/plural elements #61 
[2020-08-06_Topic_BiogHist_TS_EAS_Meeting.pdf ](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/TS-EAS-Notes/SAA20/TS%20EAS%20Meetings/2020-08-06_Topic_BiogHist_TS_EAS_Meeting.pdf)

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

**Additional parent elements in EAD 3**
`<archdesc>`, `<bioghist>`, `<c>`, `<c01>`  - `<c12>`

**Additional child elements in EAD 3**
`<bioghist>`, `<blockquote>`, `<chronlist>`, `<head>`, `<list>`, `<p>`, `<table>`

## Context
A concise essay and/or chronology that provides biographical or historical information about the EAC-CPF entity.

**May contain**: `<abstract>`, `<chronList>`, `<citation>`, `<list>`, `<outline>`, `<p>`
**May occur within**: `<description>`
**Attributes**:
`@localType` - Optional
`@xml:id` - Optional
`@xml:lang` - Optional
**Availability**: Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<abstract>` (0..1), `<chronList>` (0..n), `<head>` (0..1), `<list>` (0..n), `<p>` (0..n)
**May occur within**: `<description>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Optional, repeatable

## Example encoding
```
<description>
 <biogHist audience="external" conventionDeclarationReference="conventiondeclaration1" id="biogHist1" languageOfElement="en" localType="localBiogHist" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
  <head>header of a biography or history</head>
  <abstract>brief <span>summary</span> of the information contained within the <reference href="https://biography.com">biography</reference> or history as a whole</abstract>
  <chronList>
   <chronItem>
    <date>date of a list item</date>
    <chronItemSet>
     <event>event of the list item</event>
     <event>another event of the list item</event>
     <place>
      <placeName>place of the event or list item</placeName>
     </place>
    </chronItemSet>
   </chronItem>
   <chronItem>
    <dateRange>
     <fromDate>start date for a list item</fromDate>
     <toDate>end date for a list item</toDate>
    </dateRange>
    <event>event of this chronology list item</event>
    <place>
     <placeName>place of the event or list item</placeName>
    </place>
   </chronItem>
   <chronItem>
    <dateSet> 
     <date>single date of the list item</date> 
     <dateRange>
      <fromDate>start date for a list item</fromDate>
      <toDate>end date for a list item</toDate>
     </dateRange>
    </dateSet>
    <event>event of the list item</event>
   </chronItem>
  </chronList>
  <list>
   <item>list item</item> 
  </list>
  <p><span style="font-style:bold">Header</span>extended desription of biography or history</p>
  <p>text with <reference href="https:externalLink.com">link to reference</reference> in text</p>
  <p><reference href="https:externalLink.com">link to reference</reference></p>
 </biogHist>
</description>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A concise essay and/or chronology that provides biographical or historical information about the EAC-CPF entity.
**May contain:** abstract (0..1), chronList (0..n), head (0..1), list (0..n), p (0..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement `- optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<biogHist>` includes significant details about the life of an individual or family, or the administrative history of a corporate body.
The `<biogHist>` element may contain just text in a series of paragraphs `<p>`, and/or a chronology list `<chronList>` that matches dates and date ranges with associated events and/or places. The `<abstract>` element is intended to provide a very brief synopsis of the full `<biogHist>` content that could be extracted for inclusion in a remote source, such as a MARC record.
The optional `<list>` element is used to accommodate greater complexity in expressing or representing the biography or history of the CPF entity being described. A simpler discursive expression of the information may be encoded as one or more `<p>` elements. The optional `<head>` element can be used to add a title or caption to the text.
**Availability:** Optional, repeatable

**Comment by kerstarno** [comment]
@fordmadox - just as a note as I've came across this in the context of looking at the elements order question: resulting from the December meeting of the EAC team, `<biogHist>` should NOT contain `<reference>` as a separate sub-element anymore. It's currently still available in both RNG and XSD.

@ailie-s - the same for the above TL draft (where `<reference>` is already highlighted with question marks).

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<biogHist>` is an optional sub-element of `<description>`
- `<biogHist>` can be repeated
- `<biogHist>` cannot have content directly, but with all its sub-elements being optional, it could (in theory) be left empty
- `<biogHist>` allows for the optional sub-elements `<head>` and `<abstract>`, which cannot be repeated, and for the optional sub-elements `<chronList>`, `<list>`, and `<p>`, which can be repeated and can be used in any order and combination
  - in case `<head>` is used within `<biogHist>`, it always has to appear first
  - in case `<abstract>` is used within `<biogHist>`, it always has to appear before any `<chronList>`, `<list>`, or `<p>` that might be used in addition; i.e. either `<abstract>` appears first (in case there is no `<head>`) or second (in case there is a `<head>`)
- `<biogHist>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<biogHist>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready (thanks, @fordmadox, for removing `<reference>` as a separate sub-element).

@ailie-s - `<reference>` can be removed as separate sub-element in the TL draft
