### ISSUE TITLE
<existDates>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#144]
## Dates of Existence
- **add attributes**:
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement`
`@sourceReference`
- change availability to repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CFP specific element

## Context
The dates of existence of the entity being described, such as dates of establishment and dissolution for corporate bodies and dates of birth and death or floruit for persons.

**May contain:** `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>`
**May occur within**: `<description>`
**Attributes:**
`@localType` - Optional
`@xml:id` - Optional
`@xml:lang` - Optional
**Availability:** Optional, Non-repeatable

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain:** `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>`
**May occur within**: `<description>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Optional, repeatable

- New or other example needed in relation with assertions

## Example encoding
```
<description">
 <existDates audience="external" conventionDeclarationReference="conventiondeclaration1" id="existDates1" languageOfElement="en" localType="existDates" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
   <dateRange>
    <fromDate>start date of existence</fromDate>
     <toDate>end date of existence</toDate>
    </dateRange>
    <descriptiveNote>
     <p>descriptive Note for dates of existence</p>
    </descriptiveNote>
 </existDates>
```

**Comment by SJagodzinski** [comment]
@fordmadox : Please add //descriptiveNote as child element in xsd and rng

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional element within `<description>` encoding the dates of existence of the CPF entity being described, such as dates of establishment and dissolution for corporate bodies and dates of birth and death or floruit for persons.
**May contain:** (date or dateRange or dateSet (1..1)), descriptiveNote (0..1)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Description and usage:** 
The dates of existence of the CPF entity being described, such as dates of establishment and dissolution for corporate bodies and dates of birth and death or floruit for persons.
`<existDates>` must contain one of `<date>`, `<dateRange>`, or `<dateSet>`. These child elements may contain actual or approximate dates. A `<descriptiveNote>` may be included if a fuller explanation of the dates of existence is needed.
Use the `<date>` element to record the date of a single event, such as a date of birth or date of incorporation. Use `<dateRange>` to encode a pair of inclusive dates. Use `<dateSet>` to encode more complex date expressions that intermix `<date>` and `<dateRange>` elements.
**See Also:** Do not confuse with `<useDates>`, which is a child element of `<nameEntry>` or `<nameEntryParallel>` and represents the dates of use for a particular name or set of names.
**Availability:** Optional, repeatable

**Comment by karinbredenberg** [comment]
@ailie-s in issue #138 the cardinality for existDates is 0..1 and here its 0..n which one is the correct one?

**Comment by karinbredenberg** [comment]
Element exitDates tested:
May occur within: description **Currently cardinality 0..n**
date or dateRange or dateSet (1..1)), **ok in both schemas**
descriptiveNote (0..1) **Missing in both schemas**
@audience - optional (values limited to: external, internal) **ok in both schemas**
@conventationDeclarationReference - optional **ok in both schemas**
@id - optional **ok in both schemas**
@languageOfElement - optional **ok in both schemas**
@localType - optional **ok in both schemas**
@localTypeDeclarationReference - optional **ok in both schemas**
@maintenanceEventReference - optional **ok in both schemas**
@scriptOfElement - optional **ok in both schemas**
@sourceReference - optional **ok in both schemas**

**Result**: Cardinality of the element itself needs to be checked and element descriptiveNote added in both.

**Comment by fordmadox** [comment]
@karinbredenberg My mistake regarding descriptiveNote. Just patched that with this commit: https://github.com/SAA-SDT/eac-cpf-schema/commit/563d54a305743f46d1c1d0283950b7071da58ef3

**Comment by ailie-s** [comment]
@karinbredenberg cardinality should be 0..n - tag library has now been updated for description (#138 )

**Comment by karinbredenberg** [comment]
Retested, cardinality and descriptiveNote ok!

**Comment by fordmadox** [comment]
Just noting that the APEX fork of the EAC schema makes existDates a required element.  Not sure if we ever discussed that, but I like the approach that any element that's forced to show up first should also be required (with the one exception in the EAC draft schema currently being the "head" element, although in that case, I'd prefer that that element to be repeatable and to appear in any order, like h1-h6 in HTML, if it's needed at all).  Granted, if `existDates` were required, then the migration path would need to create this element when it doesn't exist, but this would be an opportunity to demonstrate a preferred method for including "unknown" as a value.

**Comment by SJagodzinski** [comment]
We never discussed having <existDates> mandatory and I prefer to keep it optional.

**Comment by fordmadox** [comment]
In that case, I might suggest that we consider moving `existDates` so that it is paired with the other repeatable elements (e.g. biogHist, etc.) rather than being the first element within the description section, but we don't have a schema-based principle for ordering of elements, and the order doesn't really matter, ultimately.
