### ISSUE TITLE
@vocabularySource

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#147]
## Vocabulary Source

Add optional attribute `@vocabularySource` to all elements that could come from a vocabulary.
Text or literal, where the element content (term, name, ID) comes from.

- define data type: token

List of elements: `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_relations_20200327.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/relations/Topic_relations_20200327.pdf)
`@vocabularySourceURI` #148

## EAD3 Reconciliation
new attribute

## Context
New attribute in EAS.

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed?

- New or other example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional attribute for identifying a vocabulary that is the source of the element's value.
**Data Type:** token

**Comment by fordmadox** [comment]
In the development version of the schema, this attribute is currently defined as `token`, though I can change this to `NMTOKEN` if preferred (e.g. we definitely don't want someone to have a space in the attribute).  However, we have an unwritten principle that we don't use "string" for attributes, so that's not an option :)  

In general, I'd like not to use NMTOKEN either, since we are not providing a DTD of EAC-CPF (and have decided not to continue doing that with EAD3, at least), but we do have a lot of attributes that use NMTOKEN now, so I'm fine with changing vocabularySource to that datatype.

Just let me know what you'd prefer to have in place for the call for comments, @SJagodzinski and @ailie-s.

**Comment by kerstarno** [comment]
FWIW, I'd argue that `@vocabularySource`, which can be the name/title of any kind of vocabulary, thesaurus, ontology - including local ones where there might not be an accompanying `@vocabularySourceURI` for, is more in the range of `@localType` (which is _token_) than in the range of this attributes that are currently defined as _NMTOKEN_ (i.e. `@languageOfElement`, `@scriptOfElement`, `@languageCode`, `@scriptCode`, `@countryCode`, `@calendar`, `@era`, and `@certainty`).

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@vocabularySource` is an optional attribute for the 27 elements listed in the issue description above, i.e. `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`
- Its data type is (currently) _token_
- It's always available together with the attributes `@vocabularySourceURI` and `@valueURI`

The above applies to both schemas, RNG and XSD.

**Comment by SJagodzinski** [comment]
> In the development version of the schema, this attribute is currently defined as `token`, though I can change this to `NMTOKEN` if preferred (e.g. we definitely don't want someone to have a space in the attribute). However, we have an unwritten principle that we don't use "string" for attributes, so that's not an option :)
> 
> In general, I'd like not to use NMTOKEN either, since we are not providing a DTD of EAC-CPF (and have decided not to continue doing that with EAD3, at least), but we do have a lot of attributes that use NMTOKEN now, so I'm fine with changing vocabularySource to that datatype.
> 
> Just let me know what you'd prefer to have in place for the call for comments, @SJagodzinski and @ailie-s.

@fordmadox , @ailie-s : I think there is no need to restrict the value to NMTOKEN as might have a space or comma. I agree to use _token_ instead.

**Comment by kerstarno** [comment]
With the confirmation of the data type _token_, this attribute is ready.
