### ISSUE TITLE
@vocabularySourceURI

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#148]
## Vocabluary Source URI

Add optional attribute `@vocabularySourceURI` with data type anyURI to all elements that could come from a vocabulary.
URI of the vocabulary source.

List of elements: `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_relations_20200327.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/relations/Topic_relations_20200327.pdf)
`@vocabularySource` #147 

## EAD3 Reconciliation
New attribute

## Context
New attribute in EAS.

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed?

- New or other example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional attribute for including a URI identifying the vocabulary source for the element's value.
**Data Type:** anyURI

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@vocabularySourceURI` is an optional attribute for the 27 elements listed in the issue description above, i.e. `<agencyCode>`, `<agencyName>`, `<agent>`, `<componentEntry>`, `<conventionDeclaration>`, `<event>`, `<function>`, `<identityId>`, `<legalStatus>`, `<localControl>`, `<localDescription>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<mandate>`, `<nameEntry>`, `<occupation>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<place>`, `<placeName>`, `<placeRole>`, `<relationType>`, `<rightsDeclaration>`, `<source>`, `<targetEntity>`, `<targetRole>`
- Its data type is _anyURI_ (and the initial restriction has been lifted)
- It's always available together with the attributes `@vocabularySource` and `@valueURI`

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
