### ISSUE TITLE
@xml:base

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#149]
## Base

Replace `xml:base` with optional attribute `@base` with data type anyURI. Use `@base` in all elements thats used `@xml:base`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Remove xml ns to align with EAD 3 #27](https://github.com/SAA-SDT/eac-cpf-schema/issues/27)

## EAD3 Reconciliation
Summary: Used to specify a base URI that is different than the base URI of the EAD instance. This allows any relative URIs provided on attributes of a specific element or its descendants to be resolved using the URI provided in that element’s base. Available on `<archdesc>`, `<c>`, `<c01>`, `<c02>`, `<c03>`, `<c04>`, `<c05>`, `<c06>`, `<c07>`, `<c08>`, `<c09>`, `<c10>`, `<c11>`, `<c12>`, `<control>`, `<daoset>`, `<ead>`, `<relations>`, `<sources>`.

Data Type: anyURI

## Context
@xml:base 

Summary: Used to specify a base URI other than the base URI of the EAC-CPF instance.

Description and Usage: xml:base is used to specify the base URI other than the base URI of the EAC-CPF instance, for the purpose of resolving any relative URIs used with elements that contain one or more descendants that use an attribute of type anyURI. xml:base makes it possible to declare an absolute base URI to facilitate the use of relative URIs on the descendants.

Data Type: NMTOKEN

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**Summary:** Used to specify a base URI that is different than the base URI of the EAC-CPF instance. This allows any relative URIs provided on attributes of a specific element or its descendants to be resolved using the URI provided in that element’s base. Available on `<alternativeSet>`, `<control>`, `<cpfDescription>`, `<description>`, `<eac>`, `<identity>`, `<multipleIdentities>`, `<relations>`, and `<sources>`.

**Data Type**: anyURI

- Example needed

## Example encoding

**Comment by fordmadox** [comment]
Regarding the migration, and the semantics for `@base` moving forward:  this attribute was previously xml:base, in EAC 1.x, which is defined very specifically (see http://www.w3.org/TR/xmlbase/). I was assuming that it was now bound to the `@href` attribute only, similarly to HTML base. However, we now have `@valueURI`, `@vocabularlySourceURI`, and `@href`. I don't think that "base" can serve as the base URI for all three. Perhaps coming up with mappings will help here, especially for mapping to other formats, like JSON-LD, RDF/XML, etc.  If so, we should link those mappings to this issue.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@xml:base` does not exist anymore
- `@base` is an optional attribute in `<eac>`, `<control>`, `<sources>`, `<multipleIdentities>`, `<cpfDescription>`, `<identity>`, `<description>`, `<relations>`, and `<alternativeSet>` 
- It has the data type _anyURI_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
> Regarding the migration, and the semantics for `@base` moving forward: this attribute was previously xml:base, in EAC 1.x, which is defined very specifically (see http://www.w3.org/TR/xmlbase/). I was assuming that it was now bound to the `@href` attribute only, similarly to HTML base. However, we now have `@valueURI`, `@vocabularlySourceURI`, and `@href`. I don't think that "base" can serve as the base URI for all three. Perhaps coming up with mappings will help here, especially for mapping to other formats, like JSON-LD, RDF/XML, etc. If so, we should link those mappings to this issue.

Mappings and examples certainly would be great. As for the question of binding `@base` to `@href`, `@valueURI`, and `@vocabularySourceURI`: if I understand the way that `@base` works correctly, this very much comes down to what types of URI-s will be put in these attributes. Anything that is not an absolute link, i.e. does not start with _http://_ etc., will be using the URI provided within `@base` to "be complete". So, if I'd put relative links in any of `@href`, `@valueURI`, and `@vocabularySourceURI`, these will be completed using `@base`, but if I put absolute links in any of `@href`, `@valueURI`, and `@vocabularySourceURI`, these will remain as they are. And if I e.g. only put relative links in `@valueURI`, but use absolute links in `@href`, this should work next to each other even if `@base` applies to the whole section of the EAS instance in which `@valueURI` and `@href` both appear.
