### ISSUE TITLE
@scriptOfElement

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#152]
## Script of Element

Add optional attribute `@scriptOfElement` with data type NMTOKEN. Use `@scriptOfElement` in all non-empty elements.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Language codes: adopt EAD 3 solution #29](https://github.com/SAA-SDT/eac-cpf-schema/issues/29)

## EAD3 Reconciliation
Summary: Indicates the writing script of the content of an element (e.g., Cyrillic, Katakana). Content should be taken from ISO 15924 Codes for the Representation of Names of Scripts, or another controlled list, as specified in the scriptencoding attribute in `<control>.` May be used consistently in a multi-lingual finding aid to specify which elements are written in which script. Available on all non-empty elements.
Data Type: NMTOKEN

## Context
EAD3 specific attribute

## Solution documentation: agreed solution for TL and guidelines

**Summary:** Indicates the writing script of the content of an element (e.g., Cyrillic, Katakana). Content should be taken from ISO 15924 Codes for the Representation of Names of Scripts, or another controlled list, as specified in the scriptencoding attribute in `<control>.` May be used consistently in a multi-lingual finding aid to specify which elements are written in which script. Available on all non-empty elements.

**Data Type**: NMTOKEN

**May occur within**:  `<abstract>`, `<address>`, `<addressLine>`, `<agencyCode>`, `<agencyName>`, `<agent>`, `<alternativeSet>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<citedRange>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<conventionDeclaration>`, `<date>`, `<dateRange>`, `<dateSet>`, `<description>`, `<descriptiveNote>`, `<event>`, `<eventDateTime>`, `<eventDescription>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<geographicCoordinates>`, `<head>`, `<identityId>`, `<item>`, `<language>`, `<languageDeclaration>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<maintenanceEvent>`, `<maintenanceHistory>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherEntityTypes>`, `<otherRecordId>`, `<p>`, `<part>`, `<place>`, `<placeName>`, `<placeRole>`, `<places>`, `<recordId>`, `<reference>`, `<relation>`, `<relationType>`, `<relations>`, `<representation>`, `<rightsDeclaration>`, `<setComponent>`, `<shortCode>`, `<source>`, `<sources>`, `<span>`, `<targetEntity>`, `<targetRole>`, `<term>`, `<term>`, `<toDate>`, `<useDates>`, `<writingSystem>`

## Example encoding

**Comment by alexduryee** [comment]
Currently does not use NMTOKEN (`Lat n` is valid) and is not applied to all elements (ref. `citedRange`) in either schema.

**Comment by alexduryee** [comment]
Re-tested and works correctly in both schemas.

**Comment by kerstarno** [comment]
Additional note resulting from testing for `@languageOfElement`.

- `@scriptOfElement` is used with 86 out of 89 elements in the draft for EAC-CPF 2.0
  - This adds `<control>` (#81), `<cpfDescription>` (#79), `<eac>` (#78), `<identity>` (#114), and `<relations>` (#210) to the 81 elements listed above in the solution documentation - _to be confirmed_
- The three elements that do not have `@languageOfElement` are:
  - `<multipleIdentities>` - _to be confirmed_
  - `<entityType>` - as it does not have text
  - `<objectXMLWrap>` - as its sub-elements are not from the EAS namespace

Pending confirmation alongside #151.

**Comment by SJagodzinski** [comment]
@fordmadox , @kerstarno : Please keep the lang attributes as they are: not available in `<mulitpleIdentities>`, `<entityType>` and `<objectXMLWrap>`

List will be completed

**Comment by kerstarno** [comment]
@SJagodzinski thanks for the confirmation. 

With this, the attribute is ready.
