### ISSUE TITLE
EAC-CPF (versions 2010 and 2018): is @localType optional in localControl or not?

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eac-cpf-schema#153]
## Creator of issue

1.  Mark Custer.
2.
3.
4.

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Could be a bug in the schema or in the tag library.  The issue is that ```localControl``` requires @localType.  See https://github.com/SAA-SDT/eac-cpf-schema/blob/pre-revision-files/cpf.rng#L395 

The tag library, however, says that this attribute is optional in localControl (as it is in EAD3).  See https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAC-CPF-TL-eng.xml#L4398-L4399

## Suggested Solution

* Given this doesn't seem to be causing any issues, I'd ignore it.  However, we could also release a patch for the schema or the tag library, if desired.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
See my comment to #105 - personally, I would not make `@localType` mandatory in any context.

**Comment by fordmadox** [comment]
Right now, ```@localType``` is already required on ```localContext``` in the  2010/2018 versions of the EAC schema.  We could issue a minor revision (e.g. EAC-CPF 1.2) to address that discrepancy in the tag library (and align with EAD3), but unless there is a community request to change it, I'd suggest we ignore this discrepancy and only address it in EAC 2.0.

**Comment by SJagodzinski** [comment]
@fordmadox : Following my [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/105#issuecomment-703090135) in #105 I'd like to anlign the schema and TL with EAD3. So, `@localType` and `<term>` are both defined as optional.

**Comment by fordmadox** [comment]
Sounds good!  I am going to close this issue, but please re-open if needed.   I opened this issue for the current versions of EAC, but it sounds like there's no desire to issue a patch for those two versions.
