### ISSUE TITLE
@maintenanceStatus

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#155]
## Maintenance Status

Add new required attribute `@maintenanceStatus` with restricted values (cancelled, deleted, deletedMerged, deletedReplaced, deletedSplit, derived, new, revised) in `<control>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<mainteanceStatus>` #84 
`<control>` #81 

## EAD3 Reconciliation
Used as element //control/maintanceStatus in EAD.

## Context
New attribute in EAS.

## Solution documentation:

**Summary:** The current drafting status of the EAC-CPF instance.

**Description and Usage**: The maintenance status must occur on `<control>.` As an EAC-CPF instance is modified or other events happen to it (as recorded in the `<maintenanceHistory>` element), the maintenance status should also be updated to reflect the current drafting status.
On first creation the status would be "new", which on revision can be changed to "revised". Because it is important to be clear about what has happened to records particularly when sharing and making links between them, a number of status values are available for records that are no longer current. A record that is simply deleted from a system can be given the status "deleted", but in cases where a record is marked as not current (obsolete or rejected) but kept for reference then it should be given the status "cancelled". If a record is deleted because it has become superseded by two or more records then its status should be given as "deletedSplit", while if it has simply been replaced by a new record then "deletedReplaced" is the appropriate status value. If a record is deleted because it has been merged with another record, its status should be given as "deletedMerged."A "derived" status value is available to indicate that the record was derived from another descriptive system.

**Data Type:** "cancelled" or "deleted" or "deletedMerged" or "deletedReplaced" or "deletedSplit" or "derived" or "new" or "revised"

**May occur within**: `<control>`

## Example encoding

**Comment by kerstarno** [comment]
@alexduryee - apologies for taking this one over, but I've essentially tested the attribute `@maintenanceStatus` as part of the test for the replaced element of the same name (see #84) and can confirm that after the merge of the pull request #163 this does now worked fine in both XSD and RNG.
