### ISSUE TITLE
@publicationStatus

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#156]
## Publication status

Add new optional attribute `@publicationStatus` with restricted values (approved, inProcess, published) in `<control>.`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<publicationStatus>` #85
`<control>` #81

## EAD3 Reconciliation
Used as element //control/publicationStatus in EAD.

## Context
New attribute in EAS.

## Solution documentation: 

**Summary:** The current publication status of the EAC-CPF instance.

**Description and Usage:** The current publication status of the EAC-CPF instance may be specified in the `@publicationStatus` attribute.

**Data Type:** "approved" or "inProcess" or "published"

**May occur within**: `<control>`

## Example encoding

**Comment by kerstarno** [comment]
@alexduryee - apologies for taking this one over, but I've essentially tested the attribute `@publicationStatus` as part of the test for the replaced element of the same name (see #85) and can confirm that this works fine in both XSD and RNG.
