### ISSUE TITLE
@maintenanceEventType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#157]
## Maintenance Event Type

Add new mandatory attribute `@maintenanceEventType` with restricted values (cancelled, created, deleted, derived, revised, unknown, updated) in `<maintenanceEvent>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<eventType>` #92 
`<maintenanceEvent>` #91 

## EAD3 Reconciliation

Used as element //maintenancehistory/maintenanceevent/eventtype in EAD.

## Context
New attribute in EAS.

## Solution documentation: 
**Summary:** A required attribute of `<maintenanceEvent>` that provides a controlled list of values for recording the type of maintenance activity.

**Description and Usage**: 
- cancelled: marks an instance as not current (obsolete or rejected), but retained for reference
- created: the initial creation of the EAC-CPF instance
- deleted: indication that the instance has been deleted from the system
- derived: indicates that the instance was derived from another descriptive system
- revised: any type of general modification to the EAD instance
- unknown: when the type of event is not known
- updated: when an instance has been brought up to date with significant changes to the materials being described or to the version of EAC-CPF used

Data Type: "cancelled" or "created" or "deleted" or "derived" or "revised" or "unknown" or "updated"

**May occur within**: `<maintenanceEvent>`

## Example encoding

**Comment by karinbredenberg** [comment]
Checked in both rng and xsd schema and is having the correct value list.
