### ISSUE TITLE
@agentType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#158]
## Agent Type

Add new mandatory attribute `@agentType` with restricted values (human, machine, unknown) in `<agent>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<agentType>` #94 
`<maintenanceEvent>` #91 

## EAD3 Reconciliation
Used as element //maintenancehistory/maintenanceevent/agenttype in EAD.

## Context
New attribute in EAS.

## Solution documentation: 
**Summary:** A required attribute of `<agent>` that indicates the type of agent responsible for the creation, modification, or deletion of an EAC-CPF instance.

**Description and Usage:** The attributes value must be set to "human," "machine," or "unknown," and should correspond to the information recorded in `<agent>`. For example, if the `<agent>` is Jane Marshall, the value of `@agentType` should be set to "human." If the `<agent>` is a database, style sheet, or other system, the value of `@agentType` should be set to "machine." The value of `@agentType` may also be set to "unknown" if the agent and/or type of agent cannot be determined.

**Data Type**: "human" or "machine" or "unknown"

**May occur within**: `<agent>`

## Example encoding

`<agent agentType="human">fordmadox</agent>`

**Comment by kerstarno** [comment]
I know we said, we'd move the elements to being attributes with their parent elements, but wouldn't it make more sense to have `@agentType` with `<agent>` instead of having it with `<maintenanceEvent>`?

**Comment by karinbredenberg** [comment]
Tested in both xsd and rng. attribute have the value list.

**Comment by SJagodzinski** [comment]
@fordmadox : Element for this attribute changed from `<maintenanceEvent>` to `<agent>`, cf https://github.com/SAA-SDT/eac-cpf-schema/issues/158#issuecomment-698555156

Please retest, if necessary.

**Comment by SJagodzinski** [comment]
Available in [85f90b0](https://github.com/SAA-SDT/eac-cpf-schema/commit/85f90b037a59063d7bc56a6efb4a02e2577adab9)
