### ISSUE TITLE
@countryCode

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#159]
## Country Code

- change data type to NMTOKEN
- remove regex pattern
- keep name and scope

Availability: optional
Data TYpe: NMTOKEN 

May occur within: `<maintenanceAgency>`, `<placeName>`, `<address>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary:** A unique code for the country in which the materials being described are held. Content of the attribute should be a code taken from ISO 3166-1 Codes for the Representation of Names of Countries and their Subdivisions, column A2, or another controlled list, as specified in the countryencoding attribute in `<control>.` Available in `<maintenanceagency>` and `<unitid>.`

Data Type: NMTOKEN

## Context
**Summary:** Two letter ISO 3166-1 standard code representing a country.

**Description and Usage**: The countryCode may occur on `<placeEntry>` or `<address>.` The countryCode attribute may be used to provide the ISO 3166-1 standard code designating a country. The values are to be taken from the list of ISO 3166-1 Codes for the Representation of Names of Countries, which can be downloaded from the website of ISO 3166 Maintenance Agency http://www.iso.org/iso/country_codes/iso_3166_code_lists.htm

Data Type: ISO 3166-1 Codes for the Representation of Names of Countries, column A2.

## Solution documentation
- Topic for Best Practise Guide: Schematron validation

**Summary:** [...] 
Content of the attribute should be a code taken from ISO 3166-1 Codes for the Representation of Names of Countries and their Subdivisions, column A2, or another controlled list, as specified in the countryencoding attribute in `<control>.` Available in `<maintenanceagency>`, `<placeName>` and `<address>`.

Data Type: NMTOKEN

May occur within: `<maintenanceAgency>`, `<placeName>`, `<address>`

## Example encoding
```
<eac>
<control audience="external" countryEncoding="iso3166-1" dateEncoding="iso8601" id="control1" languageEncoding="iso639-1" languageOfElement="en" maintanceStatus="new" publicationStatus="inProcess" repositoryEncoding="iso15511" scriptEncoding="iso15924" scriptOfElement="lat">
  <recordId>records identifier</recordId>
  <maintenanceAgency audience="external" countryCode="DE" id="maintenanceagency1" languageOfElement="eng" scriptOfElement="lat" vocabularySource="ISIL_Agency" vocabularySourceURI="http://ld.zdb-services.de/resource/organisations/" valueURI="http://ld.zdb-services.de/resource/organisations/XYZ">
  <agencyCode>agency code</agencyCode>
  <agencyName audience="external" id="agencyName1" languageOfElement="eng" scriptOfElement="lat">agency name</agencyName>
  </maintenanceAgency>
 </control>
</eac>
```

**Comment by kerstarno** [comment]
@alexduryee - just as a note: I've looked at `@countryCode` in the context of checking `<maintenanceAgency>` and found that currently it's not possible to e.g. use the ISO 3166-1 two-letter country codes without getting a validation error (I've tested with "DE"). Both, XSD and RNG, still use a regular expression to define the data type instead of NMTOKEN (as in EAD3), but I'm not sure if this is only a precursor for working with Schematron.

**Comment by fordmadox** [comment]
I think this will be a good to add as part of the Schematron, but my first pass was meant to make sure that two to three character country codes would validate.  I messed up the regular expression at some point, though, so I'll fix that now (or revert to NMTOKEN, but that leaves things really wide open, unless folks also use the Schematron).

**Comment by alexduryee** [comment]
Thanks @kerstarno and @fordmadox - tested and passes now in both schemas
