### ISSUE TITLE
<otherAgencyCode>: relax restriction xs:NMTOKEN

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#16]
The content for the element `<otherAgencyCode>` within `<maintenanceAgency>` is defined as xs:NMTOKEN. Relax the restriction to text.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Relax value of `<otherAgencyCode>` from NMTOKEN to text. [@dpitti]

## Context
Following EAD 3

**Comment by karinbredenberg** [comment]
Ok. Check so its aligned with EAD3.

**Comment by karinbredenberg** [comment]
Its text in EAD3.

**Comment by SJagodzinski** [comment]
Adapt schema and tag library accordingly.

**Comment by SJagodzinski** [comment]
Example for TL:

```
<maintenanceAgency>
<agencyCode>GB-Uk</agencyCode>
<otherAgencyCode>GB-058</otherAgencyCode>
<agencyName>The British Library: Manuscript
Collections</agencyName>
</maintenanceAgency>

```

GB-Uk is the official ISIL for The British Library. Does it fit here?

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
