### ISSUE TITLE
@languageCode

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#160]
## Language Code

- change data type to NMTOKEN
- remove regex pattern
- keep name and scope

Availability: optional
Data Type: NMTOKEN 
May occur within: `<language>`, `<languageDeclaration>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary:** The code for the language of the EAD instance and the language of the materials provided as text in `<language>.` Content of the attribute should be a code taken from ISO 639-1, ISO 639-2b, ISO 639-3, or another controlled list, as specified in the langencoding attribute in `<control>` .

Data Type: NMTOKEN

## Context
**Summary:** Three-letter ISO 639-2 language code. Must occur on `<language>.`

**Description and Usage:** The languageCode must occur on `<language>.` The Language Code is used to provide the ISO 639-2 standard code representing the language of the EAC-CPF instance. The values are to be taken from the list of ISO 639-2 Codes for the representation of Names of Languages, which can be downloaded from the website of the Library of Congress which is the registration agency of the standard (http://www.loc.gov/standards/iso639-2/langhome.html).

Data Type: ISO 639-2 Codes for the Representation of Names of Languages

May occur within: `<language>`, `<languageDeclaration>`

## Solution documentation
- Topic for Best Practise Guide: Schematron validation

**Summary:** The code for the language used in the EAC-CPF instance or in the creative work of the CPF entity being described. Content of the attribute should be a code taken from ISO 639-1, ISO 639-2b, ISO 639-3, or another controlled list, as specified in the `@languageEncoding` attribute in `<control>` . Mandatory in `<languageDeclaration>` and optional available in `<language>`.

Data Type: NMTOKEN

## Example encoding

Example for `<language>` to follow.

**Comment by alexduryee** [comment]
Tested in XSD and RNG and both versions don't adhere to NMTOKEN - spaces are valid when used within the attribute value.

**Comment by fordmadox** [comment]
@alexduryee I just updated with https://github.com/SAA-SDT/eac-cpf-schema/commit/2099a5c0bd7a979074dcef0488e0c761c5c7b4b8 per our meeting today.

**Comment by kerstarno** [comment]
Re-tested as part of Schema Team's schema testing:

- `@languageCode` is a mandatory attribute in `<languageDeclaration>` and an optional attribute in `<language>`
- It has the data type _NMTOKEN_, i.e. accepts values such as `languageCode="a2b4e6g8i-jkl_mno.pqr"`

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
