### ISSUE TITLE
@scriptCode

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#161]
## Script Code

- change data type to NMTOKEN
- remove regex pattern
- keep name and scope

Availability: optional
Data TYpe: NMTOKEN 
May occur within: `<writingSystem>`, `<languageDeclaration>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary:** The code for the writing script used with a given language. Content should be taken from ISO 15924 Codse for the Representation of Names of Scripts, or another controlled list, as specified in the scriptencoding attribute in `<control>.` Available in `<script>.`

Data Type: NMTOKEN

## Context
**Summary:** The ISO 15924 four-letter code for the writing script used.

**Description and Usage:** A standard four-letter code for the writing script used with a given language. The scriptCode attribute is required for the `<script>` element, and is available on other elements where language designations may be used.

Data Type: ISO 15924 Code for the Representation of Names and Scripts

## Solution documentation
- Topic for Best Practise Guide: Schematron validation

**Summary:** The code for the writing script for a language used in the EAC-CPF instance or in which the CPF entity being described was creative or productive. Content of the attribute should be a code taken from ISO 639-1, ISO 639-2b, ISO 639-3, or another controlled list, as specified in the `@scriptEncoding` attribute in `<control>`. Available in `<languageDeclaration>` and `<writingSystem>`.

Data Type: NMTOKEN

May occur within: `<writingSystem>`, `<languageDeclaration>`

## Example encoding

Example for `<writingSystem>` to follow.

**Comment by alexduryee** [comment]
Tested XSD, and it still uses the regex for validation instead of accepting any NMTOKEN.

**Comment by kerstarno** [comment]
Re-tested as part of Schema Team's schema testing:

- `@scriptCode` is an optional attribute in `<languageDeclaration>` and in `<writingSystem>`
- It has the data type _NMTOKEN_, i.e. accepts values such as `scriptCode="1b3d5f7h9-stu_vwx.yz"`

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
