### ISSUE TITLE
<citedRange>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#162]
## Cited range

- add as new optional, repeatable child element to `<source>`
- add optional attributes:
`@audience`
`@id`
`@languageOfElement`
`@scriptOfElement` 
`@unit`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic: Assertion description in EAS](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/assertion)

## EAD3 Reconciliation
New element in EAS

## Context
New element in EAS

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

> This element would be available to provide a location from within a source to indicate precisely where supporting evidence for the corresponding assertion was found (e.g. pages 88-92). 

**May contain**:  [text]
**May occur within**: `<source>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
`@unit` - optional

- example needed
- Topic for Best Practise Guide

## Example encoding
```
<source>
 <reference>internal or external reference to a source</reference>
 <citedRange audience="external" id="citedRang1" languageOfElement="eng" scriptOfElement="lat" target="element1" unit="pagenumber">p. 1</citedRange>
</source>
```

**Comment by ailie-s** [comment]
Draft Tag Library Text:

**Summary:** An optional child element of `<source>` that provide a location from within a source to indicate precisely where supporting evidence was found.
**May contain:** [text]
**May occur within:** source
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement `- optional
`@target` - optional
`@unit `- optional
**Description and Usage:** The `<citedRange>` element can be used to refer to a location within a source where supporting evidence can be found. It may refer to a specific location such as a single page, or a broader location such as a range of pages.
**Attribute Usage:** Use the optional `@unit` attribute to specify the format that the `<citedRange>` refers to, for example a page number or a volume number.
**Availability:** Optional, repeatable

**Comment by alexduryee** [comment]
Can be extant but empty in both schemas - dunno if this is intended behavior or not.

Neither `languageOfElement` nor `scriptOfElement` are supported in RNG and XSD.

**Comment by fordmadox** [comment]
Thanks, @alexduryee!  I just added the lang attributes to citedRange.  

As for the potential emptiness, that goes for all of our elements that can contain text right now.  Should be the same as previous versions of EAC and EAD, I think, but we could look into ensuring that the element is always non-empty.

**Comment by fordmadox** [comment]
fwiw, I added two new data types that we could use to force content in textual elements.  see https://github.com/SAA-SDT/eac-cpf-schema/blob/development/source/modules/datatypes.rng#L28-L38. right now, I only added the first one to "recordId".  that element is completely open in EAD3, but in EAC it has a very strict data type of NMTOKEN, which I'd say is only suitable for attributes.

**Comment by kerstarno** [comment]
Re-tested:

- `<citedRange>` is an optional sub-element of `<source>`
- `<citedRange>` can be repeated
- `<citedRange>` can contain content
- `<citedRange>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, and `@unit`
- `<citedRange>` also allows for optional attributes from other namespaces (tested with XLink) 

The above applies for both schemas, RNG and XSD. 

The element is ready.

**Comment by fordmadox** [comment]
As long as we have "localType" around, we might want to consider adding the localType attributes to `<citedRange>`.

Use case:  if we want to specify a URI for something like `citedRange/@unit` (e.g. https://www.wikidata.org/wiki/Q21995230), there'd be no way to do that right now without using a locally-namespace attribute.  That's probably fine, but if localType is going to be available, then it seems like that EAS attribute should be a possibility within this element.

**Comment by fordmadox** [comment]
I was going to add, I'm still not sure if this should be done or not, but if we want to consider the request (which just came out of me trying to model a Wikidata statement in EAC 2.0), then I can submit a new issue so that it can be discussed separately from this issue.  I just wanted to get the thought down before I forgot it 😃

**Comment by SJagodzinski** [comment]
EAC-CPF meeting 3 September 2021:

- discussion of @fordmadox [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/162#issuecomment-789089098) above
- **Decision**: No need for `@localType` here (as the original request was more specific to the unit attribute); no changes necessary
