### ISSUE TITLE
<placeEntry>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#166]
## Place Name
- rename to `<placeName>`
- keep scope
- add optional attributes
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySourceURI`
- remove attributes for geographic coordinates `@accuracy`, `@altitude`, `@latitude`, `@longitude`, because a new sibling element `<geographicCoordinates>` will be added within `<place>`
- remove `<placeName>` from parent element `<chronItem>` and relation element(s)
- keep <placeName> as optional, repeatable child element in `<function>` , `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<otherEntityTypes>`, and `<place>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<placeEntry>:` should be mandatory #4

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary:** An element used to encode information about the place or jurisdiction where the CPF entity described in the EAC-CPF instance was based, lived, or with which it had some other significant connection.
**May contain**: [text]
**May occur within**: chronItem, cpfRelation, function, functionRelation, legalStatus, localDescription, mandate, occupation, place, resourceRelation
**Attributes:** `@accuracy`, `@altitude`, `@countryCode`, `@latitude`, `@localType`, `@longitude`, `@scriptCode`, `@transliteration`, `@vocabularySource`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: 

**May contain**: [text]
**May occur within**:  `<function>` , `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<otherEntityTypes>`, `<place>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@countryCode` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional

**Availability:** Optional, Repeatable

- New or other example needed

## Example encoding
```
<place> 
 <placeName audience="external" conventionDeclarationReference="conventiondeclaration1" countryCode="DE" id="placename1" languageOfElement="en" localType="localPlaceName" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://www.geonames.org/7303381/rosslyn-chapel.html"vocabularySource="GeoNames" vocabularySourceURI="http://www.geonames.org">name of the place</placeName>
</place>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<place>` used to encode the name of a place that is related to the CPF entity described in the EAC-CPF instance.
**May contain:** [text]
**May occur within**: function, legalStatus, localDescription, mandate, occupation, otherEntityType, place
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference `- optional
`@countryCode` - optional
`@id` - optional
`@languageOfElement `- optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:**
`<placeName>` should be identified by the proper noun that commonly designates the place, natural feature, or political jurisdiction. It is recommended that place names be taken from authorized vocabularies. Within `<place>`, a companion `<placeRole>` is strongly recommended to describe the nature of the association of the `<placeName>` to the entity.
The `<placeName>` element is repeatable. It is strongly recommended that within` <place>`, the `<placeName>` element be repeated only to represent the same place name in various languages, with an accompanying `@languageOfElement` attribute.
**Attribute Usage:**
The `@vocabularySource` attribute may be used to indicate the controlled vocabulary from which the `<placeName>` term is derived.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<placeName>` is an optional sub-element of `<otherEntityType>`, `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, and `<occupation>`
- `<placeName>` in the context of `<place>` is optional as well, but one of `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, or `<contact>` has to be present
- `<placeName>` can be repeated in all its contexts
- `<placeName>` can contain text
- `<placeName>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, `@vocabularySourceURI`, and `@countryCode`
- `<placeName>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.

@ailie-s - the TL draft above says "otherEntityType**s**", while it should be the singular form "otherEntityType". It is also missing the attribute `@target` at the moment.
