### ISSUE TITLE
<abstract>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#167]
## Abstract  
- add optional attributes:
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
- add optional child element `<reference>`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 child elements**
[text], abbr, corpname, date, emph, expan, famname, footnote, foreign, function, genreform, geogname, lb, name, num, occupation, persname, quote, ptr, ref, subject, title

**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@label` - Optional
`@script` - Optional

## Context
**Summary:** An element that contains a brief summary of the information contained within the <biogHist> as a whole.
**May contain**: [text], span
**May occur within**: `<biogHist>`
**Attributes:** localType, xml:id, xml:lang - all optional
**Availability:** Optional, Non-repeatable

## Solution documentation: 

**May contain**: [text], `<reference>`, `<span>`
**May occur within**: `<biogHist>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

- New or other example needed

## Example encoding
```
<biogHist>
 <abstract audience="external" conventionDeclarationReference="conventiondeclaration1" id="abstract1" languageOfElement="en" localType="localAbstract" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="localTypeDeclaration1" scriptOfElement="lat" sourceReference="source1" target="element1">brief <span>summary</span> of the information contained within the <reference href="https://biography.com">biography</reference> or history as a whole</abstract>
</biogHist>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional element within `<biogHist>` that contains a brief summary of the information contained within the `<biogHist>` as a whole.
**May contain:** [text], reference (0..n), span (0..n)
**May occur within:** biogHist
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference `- optional
`@target` - optional
**Description and Usage:**
The `<abstract>` is a brief synopsis of the identity's biography or history that is often based on the longer descriptions found in `<biogHist>`. Its purpose is to help readers quickly identify the identity described in the EAC-CPF instance. The content within this element may also be harvested by other systems to provide explanatory context for the `<nameEntry>` data when it appears in a set of search results.
`<abstract>` may include one or more `<reference>` elements to point to external resources that provide additional descriptive data.
**Availability:** Optional, not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<abstract>` is an optional sub-element of `<biogHist>`
- `<abstract>` cannot be repeated
- `<abstract>` can contain content
- `<abstract>` allows for the optional and repeatable sub-elements `<span>` and `<reference>`
- `<citedRange>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<citedRange>` also allows for optional attributes from other namespaces (tested with XLink) 

The above applies for both schemas, RNG and XSD. 

The element is ready.

@ailie-s - the TL draft above is currently missing `@target`
