### ISSUE TITLE
<chronList>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#168]
## Chronology List
- add optional attributes
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
- keep the short element name _chronList_ as it is well introduced in both EAS
- keep scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
**Summary:** A structured chronological list of events, dates, and (optionally) places that may be used within the `<biogHist>` element.
**May contain**: chronItem
**May occur within**: biogHist
Attributes:
`@localType` - Optional
`@xml:id` - Optional
`@xml:lang` - Optional
**Availability:** Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines
**May contain**: `<chronItem>`
**May occur within**: `<biogHist>`
Attributes:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Optional, Repeatable

## Example encoding
```
<biogHist>
 <chronList audience="external" conventionDeclarationReference="cd1" id="chronlist1" languageOfElement="en" localType="localChronList" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" target="element1" scriptOfElement="lat" sourceReference="source1">
  <chronItem>
   <date>date of a list item</date>
   <chronItemSet>
    <event>event of the list item</event>
    <event>another event of the list item</event>
    <place>
     <placeName>place of the event or list item</placeName>
    </place>
   </chronItemSet>
   <reference href="http://www.eventoflistitem.org">reference to list item event</reference>
  </chronItem>
  <chronItem>
   <dateRange>
    <fromDate>start date for a list item</fromDate>
    <toDate>end date for a list item</toDate>
   </dateRange>
   <event>event of this chronology list item</event>
   <place>
    <placeName>place of the event or list item</placeName>
   </place>
  </chronItem>
  <chronItem>
   <dateSet>
    <date>single date of the list item</date>
    <dateRange>
     <fromDate>start date for a list item</fromDate>
     <toDate>end date for a list item</toDate>
    </dateRange>
   </dateSet>
   <event>event of the list item</event>
  </chronItem>
 </chronList>
</biogHist>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<biogHist>` used to document a structured chronological list of events, dates, and (optionally) places.
**May contain:** chronItem (1..n)
**May occur within:** biogHist
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<chronList>` comprises a sequentially structured list of significant events in the life of the person or during the existence of the family or corporate body described in the EAC-CPF instance. Such events are associated with the date of occurrence and optionally with the name of a place.
Each `<chronList>` contains one or more `<chronItem>` elements, each associating a `<date>`, `<dateRange>` or `<dateSet>` with an `<event>` and an optional `<place>`.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<chronList>` is a sub-element of `<biogHist>`
- `<chronList>` is optional and can be repeated
- `<chronList>` itself requires the sub-element `<chronItem>`, which can be repeated
- `<chronList>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<chronList>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.

@ailie-s - the TL draft above currently is missing `@target`.
