### ISSUE TITLE
<chronItem>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#169]
## Chronology List Item
- add new optional child elements `<chronItemSet>`, `<dateSet>`, `<reference>`
- change child element `<placeName>` to `<place>`
- add new optional attributes
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 child elements**
chronitemset, dateset, datesingle, geogname

**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@script` - Optional

## Context
**Summary:** A container element that keeps a date or a date range paired with an associated event and an optional place within a Chronology List `<chronList>.`
**May contain**: date, dateRange, event, placeEntry
**May occur within**: chronList
**Attributes:** localType, xml:id, xml:lang - all optional
**Availability:** Mandatory, Repeatable

## Solution documentation: 

**May contain**: `<chronItemSet>`, `<date>`, `<dateRange>`, `<dateSet>`, `<event>`, `<place>`, `<reference>`
**May occur within**: `<chronList>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Mandatory, Repeatable

- Topic for Best Practise Guide: cf [TS_EAS_SAA_2020_Meeting_notes.md](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/TS-EAS-Notes/SAA20/TS%20EAS%20Meetings/TS_EAS_SAA_2020_Meeting_notes.md)

> [...] in EAC-CPF it's not possible to say that the date given is for the wedding day. In EAD on the other hand it's possible to create a list in `<chronitemset>` (Chronology Item Set) where you can give this kind of event based lists.
`<chronitemset>` is a short solution for connecting a date with an event. EAC-CPF gives guidance on how to encode events such as the wedding date.

## Example encoding
```
<chronList> 
 <chronItem audience="external" conventionDeclarationReference="conventiondeclaration1" id="chronItem1" languageOfElement="en" localType="localChronItem" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
   <date>date of a list item</date>
   <chronItemSet>
    <placeName>place of the event or list item</placeName>
    <event>event of the list item</event>
    <event>another event of the list item</event>
   </chronItemSet>
   <reference href="http://www.eventoflistitem.org">reference to list item event</reference>
  </chronItem>
  <chronItem>
   <dateRange>
    <fromDate>start date for a list item</fromDate>
    <toDate>end date for a list item</toDate>
   </dateRange>
   <placeName>place of the event or list item</placeName>
   <event>event of the list item</event>
  </chronItem>
  <chronItem>
   <dateSet>
    <date>single date of the list item</date>
    <dateRange>
     <fromDate>start date for a list item</fromDate>
     <toDate>end date for a list item</toDate>
    </dateRange>
   </dateSet>
   <event>event of the list item</event>
  </chronItem>
 </chronList>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required element within `<chronList>` that pairs a date with one or more events and zero or more place names within a chronology list.
**May contain:** chronItemSet (0..n), date or dateRange or dateSet (1..1), event (1..1), place (0..1), reference (0..n)
**May occur within:** chronList
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
A required element within a chronology list, `<chronItem>` must contain `<date>`, `<dateRange>`, or `<dateSet>` followed by an `<event>` or `<chronitemSet>`. Use `<dateRange>` to record an inclusive pair of dates or `<dateSet>` to record multiple dates or date ranges.
An optional `<place>` element may be used alongside `<event>` to detail a place that is relevant to the chronology item.
`<chronItemSet>` can be used to record multiple events or place names within a single `<chronItem>`.
**Availability:** Required, Repeatable

**Comment by karinbredenberg** [comment]
Test of element chronItem:
May occur within: chronList 1..n **Ok in both schemas**
May contain: chronItemSet (0..1), **Ok in both schemas but is repeatable**
(date or dateRange or dateSet (1..1)),  **Ok in both schemas**
event (1..1), **Ok in both schemas**
placeName (0..1) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: Element passes. @ailie-s chronItemSet is 0..n see #170 , the eventSet is that now considered part of chronItemSet? Its not present in the schema as eventSet and its not in the list of may contain so perhaps some rewording needed in description and usage?

**Comment by fordmadox** [comment]
It was my understanding that it should be `chronItemSet (0..n)`, following how chronItem is defined in EAD3.

**Comment by fordmadox** [comment]
Example from EAD3 tag library:

```
<chronitem>
    <datesingle>March 1957</datesingle>
    <chronitemset>
        <geogname>
            <part encodinganalog="651" localtype="a">Biwabik, Minnesota</part>
        </geogname>
        <event>Dies</event>
    </chronitemset>
    <chronitemset>
        <geogname>
            <part encodinganalog="651" localtype="a">Minneapolis, Minnesota</part>
        </geogname>
        <event>Buried in Lakewood Cemetery</event>
    </chronitemset>
</chronitem>
```

(albeit a morbid example, with too much MARC)

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 6 November 2020:

Change child element in `<chronItem>` from `<placeName>` to `<place>`.

**Comment by karinbredenberg** [comment]
@fordmadox and @ailie-s just so you two see the element  change for placeName to place.

**Comment by fordmadox** [comment]
@karinbredenberg Thanks, I switched placeName to place in the development branch, here and in #170

**Comment by karinbredenberg** [comment]
Retested element chronItem:
Element placeName now replaced with element place.

**Result**: element ready.
