### ISSUE TITLE
<placeEntry>: should be repeatable

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#17]
Make `<placeEntry>` within `<cpfRelation>`, `<recourceRelatio>`, `<functionRelation>` repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<placeEntry>` within `<cpfRelation>`, `<recourceRelatio>`, `<functionRelation>` should be repeatable

## Context

> `<placeEntry>` within `<cpfRelation>`, `<recourceRelation>`, and `<functionRelation>` [m.relationBody] is repeatable according to the TL but not in the schema. Please correct the schema. 

[APEx project, May 2013]

**Comment by karinbredenberg** [comment]
Agreed!

**Comment by SJagodzinski** [comment]
Adapt schema for repeatable `<placeEntry>` within `m.relationBody`.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
