### ISSUE TITLE
<chronItemSet>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#170]
## Chronology Item Set
- add as new optional, repeatable child element to `<chronItem>`
- add optional attributes:
`@audience`
`@conventationDeclarationReference` 
`@id` 
`@languageOfElement` 
`@localType` 
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<chronList>:` adopt EAD 3 solution with additional elements #18

## EAD3 Reconciliation
**Additional EAD 3 attributes**: `@altrender`
**May contain**: `<event>`, `<geogname>`
**May occur within**: `<chronitem>`

## Context
new element in EAC-CPF

## Solution documentation: agreed solution for TL and guidelines

**May contain**: `<event>` , `<place>`, `<reference>`
**May occur within**: `<chronItem>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, repeatable

- Example needed
- Topic for Best Practise Guide: cf [TS_EAS_SAA_2020_Meeting_notes.md](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/TS-EAS-Notes/SAA20/TS%20EAS%20Meetings/TS_EAS_SAA_2020_Meeting_notes.md)

> [...] in EAC-CPF it's not possible to say that the date given is for the wedding day. In EAD on the other hand it's possible to create a list in `<chronitemset>` (Chronology Item Set) where you can give this kind of event based lists.
`<chronitemset>` is a short solution for connecting a date with an event. EAC-CPF gives guidance on how to encode events such as the wedding date.

## Example encoding
```
<chronItem audience="external" conventionDeclarationReference="cd1" id="chronitem1" languageOfElement="en" localType="localChronItem" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" target="element1" sourceReference="source1" scriptOfElement="lat">
 <date>date of a list item</date> 
 <chronItemSet audience="external" conventionDeclarationReference="cd1" id="cis1" languageOfElement="en" localType="localChronItemSet" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" target="element1" sourceReference="source1" scriptOfElement="lat">
  <event>event of the list item</event>
  <event>another event of the list item</event>
  <place>
   <placeName>place of the event or list item</placeName>
  </place>
  <reference href="">reference to chronology item set</reference>
 </chronItemSet>
</chronItem>
```

**Comment by karinbredenberg** [comment]
Tested element chronItemSet:
May occur within: chronItem 0..n **Ok in both schemas**
May contain: event , placeName **Ok in both schemas with placeName 0..n and event 1..n**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: Element passed test. @ailie-s perhaps in the explanation say that it occurs together with a date?

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 6 November 2020:

Add `@localType` & `@localTypeDeclarationReference` to `<chronItemSet>` as it is available in all parent elements: //biogHist/chronList/chronItem

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An element for binding together  one or more `<event>` elements and zero or more `<place>` elements within `<chronItem>`.
May contain: event (1..n), place (0..n), reference (0..n)
**May occur within:** chronItem
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement `- optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:** 
Use `<chronItemSet>` within `<chronItem>` when it is necessary to associate multiple `<event>` elements or multiple `<place>` elements. Possible combinations include multiple events, a single event associated with multiple locations, multiple events associated with a single location, or multiple events associated with multiple locations. `<chronItemSet>` may be repeated within `<chronItem>` when necessary to associate multiple instances of such combinations with the date or dates recorded within `<chronItem>`.
**Availability:** Optional, repeatable

**Comment by SJagodzinski** [comment]
> 
> 
> EAC-CPF meeting, 6 November 2020:
> 
> Add `@localType` & `@localTypeDeclarationReference` to `<chronItemSet>` as it is available in all parent elements: //biogHist/chronList/chronItem

**Addition**: Change child element `<placeName>` to `<place>.`

**Comment by fordmadox** [comment]
Switched placeName to place in the development branch.

Still a general question about whether we want to enforce the order of elements, but I believe I have things set up the same way as EAD3, where you have to have an optional place *before* the event, even though the event is what's required.

**Comment by karinbredenberg** [comment]
Retest of element chronItemSet changes:
Element placeName changed to element place **Ok in both schemas**
@localType **Missing in both schemas**
@localTypeDeclarationReference **Missing in both schemas**

**Result**: Addition of the two attributes @localType and @localTypeDeclarationReference needed.

**Comment by fordmadox** [comment]
@karinbredenberg I just updated chronItemSet with https://github.com/SAA-SDT/eac-cpf-schema/commit/3e178b180464ff6a5a3f94a382694e570a24408a.  Should be ready to re-test.  

When I added chronItemSet, I followed the model in EAD3, which does not include the localType attribute.  Sorry about that.

**Comment by karinbredenberg** [comment]
Retest of element chronItemSet changes:
@localType **Ok in both schemas**
@localTypeDeclarationReference **Ok in both schemas**

**Result**: Element ready

**Comment by kerstarno** [comment]
During their meeting on 23 July, the EAD team reviewed elements with `@localType` to ensure that this was used in the same way for shared elements of both EAS. With regard to `<chronItemSet>`, which currently does not have `@localType`, we would like to suggest removing the attribute (along with `@localTypeDeclarationReference`) as we feel like the local typing is better used individually on the sub-elements of `<chronItemSet>` or on the parent element `<chronItem>`.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 3 September 2021:

**Decision**: follow EAD3 and remove these two attributes from EAC-CPF 2.0

**Comment by SJagodzinski** [comment]
@fordmadox : seems `@localtype` and `@localTypeDeclarationReference` hasn't removed from the [schema](https://github.com/SAA-SDT/eac-cpf-schema/blob/development/xml-schemas/eac-cpf/eac.xsd), yet.

see also https://github.com/SAA-SDT/eac-cpf-schema/issues/170#issuecomment-913153405

**Comment by SJagodzinski** [comment]
@ailie-s : seems `@localtype` and `@localTypeDeclarationReference` hasn't removed from the [TL](https://github.com/ailie-s/EAS-TagLibraries/blob/master/tei/eac.pdf), yet.

see also #170 (comment)

**Comment by fordmadox** [comment]
@SJagodzinski :  I just removed this attribute set from chronItemSet in the development branch.  Should be good to go now.

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that neither schema includes `@localType` nor `@localTypeDeclarationReference` for `<chronItemSet>` anymore. Neither attribute is offered as an option for `<chronItemSet>` and trying to add either of the attributes to this element results in a validation error.
