### ISSUE TITLE
@sourceReference

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#172]
## Source Reference

Add new optional attribute `@sourceReference` with data type IDREF in all non-empty elements in `<cpfDescription>`. 

With `@sourceReference` a direct link to a source element within cpf/control/sources can be provided. Hence any detailled information about the described entity can be referenced with a source. 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic: Assertion Description in EAS](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/assertion/Topic_assertions_20200327.pdf)
Assertion Description (or Assertion Control) #43 

## EAD3 Reconciliation
New EAS attributes

## Context
New EAS attributes

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**Data Type**: IDREF

**May occur within**: `<abstract>`, `<address>`, `<addressLine>`, `<agencyCode>`, `<agencyName>`, `<agent>`, `<alternativeSet>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<citedRange>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<conventionDeclaration>`, `<date>`, `<dateRange>`, `<dateSet>`, `<description>`, `<descriptiveNote>`, `<event>`, `<eventDateTime>`, `<eventDescription>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<geographicCoordinates>`, `<head>`, `<identityId>`, `<item>`, `<language>`, `<languageDeclaration>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<localTypeDeclaration>`, `<maintenanceAgency>`, `<maintenanceEvent>`, `<maintenanceHistory>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherEntityTypes>`, `<otherRecordId>`, `<p>`, `<part>`, `<place>`, `<placeName>`, `<placeRole>`, `<places>`, `<recordId>`, `<reference>`, `<relation>`, `<relationType>`, `<representation>`, `<rightsDeclaration>`, `<setComponent>`, `<shortCode>`, `<source>`, `<sources>`, `<span>`, `<structureOrGenealogy>`, `<targetEntity>`, `<targetRole>`, `<term>`, `<toDate>`, `<useDates>`, `<writingSystem>`

- Example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Use `@sourceReference` to provide a direct link to a `<source>` element within control/sources from an element within the EAC-CPF instance that uses the source. Thus any detailed information about the described entity can be referenced with a source.
**Data Type:** IDREFS

**Comment by kerstarno** [comment]
See `@conventionDeclarationReferenc` (#174) with regard to pending confirmation of availability for `@sourceReference` and its two sibling elements.

Apart from that:

- `@sourceReference` has the data type _IDREFS_
- It is always available alongside `@ conventionDeclarationReference`
- It is always available alongside `@maintenanceEventReference`

The above applies to both schemas, RNG and XSD.

@ailie-s the data type has recently changed to IDREFS in order to allow for several IDs to be pointed to within one attribute.

**Comment by SJagodzinski** [comment]
Schema version [85f90b0](https://github.com/SAA-SDT/eac-cpf-schema/commit/85f90b037a59063d7bc56a6efb4a02e2577adab9) uses reference attributes correctly, no need to change. 

Documentation will be updated.

**Comment by kerstarno** [comment]
@SJagodzinski thanks for the confirmation. 

With this, the attribute is ready.
