### ISSUE TITLE
<item>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#176]
## Item

- add new optional attributes
`@audience` 
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
- keep name and scope
- change availability to optional, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 child elements**: abbr, corpname, date, emph, expan, famname, footnote, foreign, function, genreform, geogname, lb, list, name, num, occupation, persname, ptr, quote, ref, subject, title

**Additional EAD 3 attributes**: `@altrender`, `@audience`, `@script` - all optional

## Context
**Summary**: A formatting element that encodes the individual entries in a `<list>.`
**May contain**: [text], `<span>`
**May occur within**: `<level>`, `<list>`
**Attributes**: `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability:**
Within level: Mandatory, Non-repeatable
Within list: Mandatory, Repeatable

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text], `<span>` (0..n), `<reference>` (0..n)
**May occur within**: `<list>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** optional, repeatable

- New example needed: examples for encoding in a hierarchy

## Example encoding
```
<list listType="unordered"  style="circle">
 <item audience="external" conventionDeclarationReference="cd1" id="i1" languageOfElement="en" localType="localitem" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" target="element1">list item, unordered with circle</item>
 <item>list item, unorded with circle</item>
</list>
<list listType="ordered">
 <item>first list item</item>
 <item>second list item</item>
</list>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A child element of `<list>` that encodes the individual items in a list.
**May contain:** [text], reference (0..n), span (0..n)
**May occur within:** list
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
The `<item>` element is used for general lists within descriptive elements.
**See Also:**
Do not confuse with `<chronItem>`, which encodes entries within a structured chronology, `<chronList>`.
**Availability:** Optional, repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team schema testing:

- `<item>` is optional within `<list>` and can be repeated
  - @ailie-s - the TL draft still says "required" for availability. 
- `<item>` can contain text
- `<item>` can be used with the optional sub-element `<span>` and `<reference>`, both of which can be repeated
- `<item>` can be used with the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, and any attribute from other namespaces (tested with XLink)

The above applies to both, RNG and XSD schemas.

Element is ready.
