### ISSUE TITLE
<outline>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#177]
## Outline
- remove the element from EAC-CPF
- remove `<outline>` from `<biogHist>`, `<functions>`, `<generalContext>`, `<legalStatuses>`, `<localDescriptions>`, `<mandates>`, `<occupations>`, `<places>`, `<structureOrGenealogy>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[TS_EAS_SAA_2020_Meeting_notes.md ](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/TS-EAS-Notes/SAA20/TS%20EAS%20Meetings/TS_EAS_SAA_2020_Meeting_notes.md)

## EAD3 Reconciliation
EAC-CPF specific element

## Context
An element used within other elements of `<description>` to encode information in an outline format and/or in a hierarchical fashion.

In context of EAD 3 Reconciliation the element will be removed and the existing element `<list>` with sub element `<item>` will be able to encode an outline format or a hierarchy.

## Solution documentation: 
remove from Tag Library

**Comment by kerstarno** [comment]
Tested in the context of Schema Team schema testing:

`<outline>` is not available anymore in neither the RNG, nor the XSD schema. 
It cannot be added anymore to any of the plural elements (i.e. `<functions>`, `<legalStatuses>`, `<localDescriptions>`, `<mandates>`, `<occupations>`, `<places>`), nor the informal descriptive elements (i.e. `<biogHist>`, `<generalContext>`, `<structureOrGenealogy>`).
