### ISSUE TITLE
<level>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#178]
## Level

- remove the element from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<outline>` #177 

## EAD3 Reconciliation
EAC-CPF specific element

## Context
A required element within `<outline>` that delineates the outline format.

In context of EAD 3 Reconciliation the parent element `<outline>` will be removed and the existing element `<list>` with sub element `<item>` will be able to encode an outline format or a hierarchy.

## Solution documentation: 
- remove from Tag Library

**Comment by kerstarno** [comment]
Tested in the context of Schema Team schema testing:

With the parent element `<outline>` having been removed (see #177), `<level>` also is not available anymore in neither the RNG, nor the XSD schema.
