### ISSUE TITLE
<chronList>: adopt EAD 3 solution with additional elements

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#18]
Make `<chronList>` more flexible by adding elements `<head>`, `<listHead>` as child element and `<chronItemSet>` as child of `<chronItem>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
To align with EAD 3 schema, add following elements as child elements to `<chronlist>`:
`<head>`, `<listHead>` as optional and not repeatable

To make the chronologial more flexible and to align with EAD 3 add following element as child to `<chronItem>`: `<chronItemSet>` as optional and repeatable

Define `<chronItemSet>` as follows: child element `<placeEntry>` as optional and repeatable and child element `<event>`as required and repeatable

## Context
Allows to bound multiple places and events to a date.

> Herewith the possible structures that I think the chronological list needs to support. The proposed model is flexible. The key is that following a date, one needs to be able to bind together 0 or more places with one or more events.

[@dpitti]

**Comment by karinbredenberg** [comment]
Align with EAD3.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1548633886&range=C97)

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 29 July 2020:

Add `<chronitemset>` as child element of `<chronItem>`.

No decision on `<head>` and `<listhead>` so far.
