### ISSUE TITLE
<toDate>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#182]
## To Date

- add optional attributes
`@audience`
`@calendar`
`@certainty`
`@conventationDeclarationReference`
`@era`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@status`
`@sourceReference`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_dates_20200911.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)
`<dateRange>:` best practice #32
New attribute `@status` #70

## EAD3 Reconciliation
**Additional EAD 3 attributes**:
`@altrender`
`@audience`
`@script`

## Context
**Summary:** The ending date in a date range.
**May contain**: [text]
**May occur within**: dateRange
**Attributes:** `@localType`, `@notAfter`, `@notBefore`, `@standardDate`, `@xml:id`, `@xml:lang`
**Availability:** Optional, Non-repeatable

## Solution documentation: 
**May contain**: [text]
**May occur within**: `<dateRange>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@calendar` - optional
`@certainty` - optional
`@conventationDeclarationReference` - optional
`@era` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@notAfter` - optional
`@notBefore` - optional
`@scriptOfElement` - optional
`@standardDate` - optional
`@status` - optional (values limited to: unknown, ongoing)
`@sourceReference` - optional

**Availability:** Optional, not repeatable

- Topic for Best Practise Guide

## Example encoding
```
<dateRange> 
 <fromDate>start date of existence</fromDate>
 <toDate audience="external" certainty="circa" conventionDeclarationReference="conventiondeclaration1" id="toDate1" languageOfElement="en" localType="localToDate" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" notAfter="2019" notBefore="1900" scriptOfElement="lat" sourceReference="source1" standardDate="2010-12-31" status="ongoing">end date of existence</toDate>
</dateRange>>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A child element of `<dateRange>` that records the end point in a range of dates.
**May contain:** [text]
**May occur within:** `<dateRange>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@calendar` - optional
`@certainty` - optional
`@conventationDeclarationReference` - optional
`@era` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@notAfter` - optional
`@notBefore` - optional
`@scriptOfElement` - optional
`@standardDate` - optional
`@status` - optional (values limited to: unknown, ongoing)
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
Use `<toDate>` to record the end date in a range of dates, whether they be known or approximate. The content of the element is intended to be a human-readable, natural language expression of the date. If, however, indexing or other machine process of dates is desired, the `@standardDate` should be used to record the date in machine-processable form as well. `<toDate>` may be omitted from `<dateRange>`, or the `@status` attribute used, if the date span is ongoing or the `<toDate>` is unknown.
**Attribute Usage:**
Use `@certainty` to indicate the degree of precision in the dating, for example, "circa," "approximately," or "after."
Use `@localType` to supply a more specific characterization of the start date.
Use `@notAfter` and `@notBefore` to capture the earliest and latest possible dates in machine-processable form in cases when the date is uncertain.
Use `@standardDate` to provide a machine-processable form of the date.
Use `@status` with the values "unknown" or "ongoing" to indicate where part of a date range is unknown, or the date range is ongoing.
**See Also:**
Use `<fromDate>` to record the starting point of a date range.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element toDate:
May occur within: dateRange 0..1**Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@certainty - optional **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@notAfter - optional **Wrong name in both schemas**
@notBefore - optional **Wrong name in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@standardDate - optional **Ok in both schemas**
@status - optional (values limited to: unknown, ongoing) **Missing in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: @fromDate to become @notBefore, @toDate to become @notAfter, addition of @status with value list "unknown, ongoing".

**Comment by fordmadox** [comment]
Sorry about that!  Fixed now with https://github.com/SAA-SDT/eac-cpf-schema/commit/94f81e114e13101d377334652a7b7284c7d00920 (for the attribute names) and https://github.com/SAA-SDT/eac-cpf-schema/commit/b7a6968e02fcb1b55b14abe7ac100be646e8aa7d (to add another status attribute)

**Comment by karinbredenberg** [comment]
Retested element toDate:
@fromDate to become @notBefore, **Ok in both schemas**
@Todate to become @notAfter, **Ok in both schemas**
addition of @status with value list "unknown, ongoing". **Ok in both schemas**

**Result**: Element ready.
