### ISSUE TITLE
<dateSet>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#183]
## Date Set

- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@id` 
`@languageOfElement` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**:
`@altrender`, `@audience`, `@script`

## Context
**Summary:** A grouping element that facilitates complex date expressions by being able to combine single dates and date ranges, multiple single dates, or multiple date ranges.
**May contain**: date, dateRange
**May occur within**: cpfRelation, existDates, function, functionRelation, legalStatus, localDescription, mandate, occupation, place, resourceRelation, useDates
**Attributes**: `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: 
**May contain**: `<date>`, `<dateRange>`
**May occur within**: `<existDates>`, `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<place>`, `<relation>`, `<useDates>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Optional, Repeatable

## Example encoding
```
<dateSet audience="external" conventionDeclarationReference="conventiondeclaration1" id="dateSet1" languageOfElement="en" localType="localDateSet" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <dateRange>
  <fromDate standardDate="1947">1947</fromDate>
  <toDate standardDate="1949">1949</toDate>
 </dateRange>
 <date>1951</date>
</dateSet>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A wrapper element for encoding complex dates that cannot be adequately represented in one `<date>` or `<dateRange>`
**May contain:** date or dateRange (2..n)
**May occur within:** chronItem, existDates, function, legalStatus, localDescription, mandate, occupation, otherEntityType, place, relation, useDates
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:** `<dateSet>` binds together single dates and date ranges, multiple single dates, or multiple date ranges. `<dateSet>` is used in situations where complex date information needs to be conveyed and requires at least two child elements. These can be a combination of `<date>` and `<dateRange>`.
**Availability:** 
Within `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<otherEntityType>`, `<place>`, `<relation>`: one of `<date>`, `<dateRange>` or `<dateSet>` optional, not repeatable
Within `<chronItem>`, `<existDates>`, `<useDates>`: one of `<date>`, `<dateRange>` or `<dateSet>` required, not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `<dateSet>` is a sub-element of `<useDates>`, `<otherEntityType>`, `<function>`, `<legalStatus>`, `<localDescription>`, `<mandate>`, `<occupation>`, `<place>`, `<existDates>`, `<chronItem>`, and `<relation>`
- `<dateSet>` in itself is optional in all its contexts, but one of `<date>`, `<dateRange>` or `<dateSet>` is required in the contexts of `<useDates>`, `<existDates>`, and `<chronItem>`
- `<dateSet>` is not repeatable
  - @ailie-s this needs updating in the TL draft above with regard to `<place>`; for `<place>` the same applies as for the other singular elements, i.e. `<dateSet>` (as an alternative to either `<date>` or `<dateRange>`) is optional, not repeatable
- `<dateSet>` requires at least two iterations of its sub-elements `<date>` and `<dateRange>` to be present, i.e. ad minimum either two `<date>`-s or two `<dateRange>`-s or one `<date>` plus one `<dateRange>`
- `<dateSet>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<dateSet>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.
