### ISSUE TITLE
<places>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#184]
## Places

- keep name and scope
- remove child elements `<citation>`, `<list>`, `<outline>`, `<p>`
- change availability from 0..n to 0..1
- add optional attributes:
`@audience` 
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61
`<placeEntry>:` should be mandatory #4

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary:** A grouping element used to bundle together individual <place> elements.
**May contain**: citation, descriptiveNote, list, outline, p, place
**May occur within**: description
**Attributes:** `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: 

**May contain**: `<descriptiveNote>`, `<place>`
**May occur within**: `<description>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability:** Optional, not repeatable

## Example encoding
```
<places audience="external" conventionDeclarationReference="conventiondeclaration1" id="places1" languageOfElement="en" localType="localPlaces" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <place>
  <placeName>name of the place</placeName>
 </place>
 <descriptiveNote>
  <p>note for all places</p>
 </descriptiveNote>
</places>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<description>` used for grouping together one or more `<place>` elements.
**May contain:** descriptiveNote (0..1), place (1..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Description and Usage:**
Use the optional `<places>` element to group together one or more occurrences of `<place>`. `<places>` must include at least one `<place>` element. A `<descriptiveNote>` element may be included if fuller textual explanation is needed.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element places:
May occur within: description 0..1   **Ok in rng schemas, xsd gets 0..n in carinality**
May contain: descriptiveNote (0..1),   **Missing in both schemas**
place (1..n)  **Ok in both schemas**
@audience - optional (values limited to: external, internal)  **Ok in both schemas**
@conventationDeclarationReference - optional  **Ok in both schemas**
@id - optional  **Ok in both schemas**
@languageOfElement - optional  **Ok in both schemas**
@localType - optional  **Missing in both schemas**
@localTypeDeclarationReference - optional  **Missing in both schemas**
@maintenanceEventReference - optional  **Ok in both schemas**
@scriptOfElement - optional  **Ok in both schemas**
@sourceReference - optional  **Ok in both schemas**

**Result**: Addition of element descriptiveNote and localType attributes, Cardinality in xsd needs to be changed to 0..1.

**Comment by karinbredenberg** [comment]
Retest of element:
May occur within: description 0..1 **Ok in both schemas**
May contain: descriptiveNote (0..1),   **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional  **Ok in both schemas**
@target - optional **Ok in both schemas**

**Result**: Element ready.
