### ISSUE TITLE
<place>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#185]
## Place

- keep name and scope
- add new optional child elements `<contact>` and `<geographicCoordinates>`
- one of the optional child elements `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, or `<contact>` must appear as child element of `<place>`
- add optional attribues:
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference` 
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`
- add `<place>` as optional child element to  `<chronItem>`, `<chronItemSet>`, and `<relation>`
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
- elements name : `<geogname>`
- child elements: geographiccoordinates, part
- additional attributes: altrender, audience, encodinganalog, identifier, normal, relator, rules, script, source

## Context
**Summary:** An element that provides information about a place or jurisdiction where the CPF entity was based, lived, or with which it had some other significant connection.
**May contain**: address, citation, date, dateRange, dateSet, descriptiveNote, placeEntry, placeRole
**May occur within**: description, places
**Attributes:** `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability:** Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: `<address>`, `<contact>`, `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>`, `<geographicCoordinates>`, `<placeName>`, `<placeRole>`
**May occur within**:  `<chronItem>`, `<chronItemSet>`, `<places>`, `<relation>`
**Attributes:** 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability:** required, repeatable

- New examples needed

## Example encoding
```
<places> 
 <place audience="external" conventionDeclarationReference="conventiondeclaration1" id="place1" languageOfElement="en" localType="localplace" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://www.geonames.org/2950159/berlin.html" vocabularySource="GeoNames" vocabularySourceURI="http://www.geonames.org">
  <placeName>name of the place</placeName>
  <placeRole>example place</placeRole>
  <geographicCoordinates>N 52° 31' 27'', E 13° 24' 37''</geographicCoordinates>
  <address>
   <addressLine>distinct address information</addressLine>
  </address>
  <contact>
   <contactLine>distinct contact information</contactLine>
  </contact>
  <dateSet>
   <date>1950</date>
   <dateRange>
    <fromDate>1970</fromDate>
    <toDate status="ongoing"/>
   </dateRange>
  </dateSet>
  <reference>external reference for the place</reference>
  <descriptiveNote>
    <p>note for this place</p>
   </descriptiveNote>
 </place>
</places>
```

**Comment by ailie-s** [comment]
Draft Tag Library Text:

**Summary:** An element that provides information about a place or jurisdiction, including places where the CPF entity was based, lived, or with which it had some other significant connection.
**May contain:** address (0..n), contact (0..n), date or dateRange or dateSet (0..1), descriptiveNote (0..1), geographicCoordinates (0..n), placeName (0..n), placeRole (0..n)
**May occur within:** chronItem, chronItemSet, places, relation
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI `- optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
A `<place>` element is a wrapper element used to encode information about a place or jurisdiction. This includes identifying the places or jurisdictions where the CPF entity was based, lived, or with which it had some other significant connection. It can also be used to encode address and contact information.
`<place>` must include at least one of `<address>`, `<contact>`, `<geographicCoordinates>`, `<placeName>` or `<placeRole>`.
`<placeName>` may be used to encode the name of a place that is related to the CPF entity described. The `<placeRole>` element is available to specify the nature of the connection of the place with the CPF entity being described, and its use is strongly recommended. Terms in `<placeName>` and `<placeRole>` may be drawn from controlled vocabularies or may be natural language terms. These controlled vocabularies can be identified with the <att>vocabularySource</att> attribute.
The `<address>` element is available for specifying a postal or other address. The `<contact>` element is available for specifying a digital address or other contact information.
Associated date or date range (`<date>`, `<dateRange>` or `<dateSet>`) information may be included to further constrain the term's meaning. A `<descriptiveNote>` may be included if a fuller explanation of the relation between the values is needed.
**Availability:** 
Within `<chronItem>`, `<chronItemSet>`, `<relation>`: optional, repeatable
Within `<places>`: required, repeatable.

_Review 'may contain' availability information_

**Comment by kerstarno** [comment]
Not sure, but I think `<date>`, `<dateRange>` and `<dateSet>` would be used with `<place>` in the same way as with other single elements, i.e. "date or dateRange or dateSet (0..1)". Just wanted to clarify as I'm just doing an update for `<place>` with regard to `<reference>`(see #102).

**Comment by SJagodzinski** [comment]
True, @ailie-s this will need an update for the TL description.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<place>` is a required sub-element of `<places>`
- `<place>` is an optional sub-element of `<chronItem>`, `<chronItemSet>`, and `<relation>`
- `<place>` can be repeated in `<places>`, `<chronItemSet>`, and `<relation>`
- `<place>` cannot be repeated in `<chronItem>`
  - @ailie-s the TL draft currently states that `<place>` would be repeatable in `<chronItem>`, which would need to be updated; repeatability of `<place>` and `<event>` only comes with `<chronItemSet>` 
- `<place>` requires one of `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, or `<contact>` to be present; all of these can be repeated
  - @ailie-s I was wondering, if the TL would in this case rather say something like "address or contact or geographicCoordinates or placeName or placeRole (1..n)", but wasn't quite sure if that fits the current format of indicating the cardinality. I had a look at `<dateSet>`(#183), which is similar as it also cannot be empty (as in having no sub-elements). Here we currently say "date or dateRange (2..n)".
- `<place>` furthermore allows for the date elements (`<date>` or `<dateRange>` or `<dateSet>`) and `<descriptiveNote>` as optional sub-elements that cannot be repeated
- `<place>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`
- `<place>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.
