### ISSUE TITLE
<geographicCoordinates>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#187]
## Geographic Coordinates

- add new optional, repeatable text element <geographicCoordinates> to <place>
- follow EAD approach for encoding geographic coordinates 
- add mandatory attribute:
`@coordinateSystem` 
- add optional attributes
`@audience` 
`@conventationDeclarationReference`
`@id` 
`@languageOfElement` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary**: A child element of `<geogname>` that encodes a set of geographic coordinates.
**Attribute usage**: Use `@coordinatesystem` to provide a commonly used code for the system used to express the coordinates. Examples include WGS84, OSGB36, ED50.
**May contain**: [text]
**May occur within**: geogname
**Description and Usage**: Use `<geographiccoordinates>` to express a set of geographic coordinates such as latitude, longitude, and altitude representing a point, line, or area on the surface of the earth.
**Attributes**:
altrender - Optional
audience - Optional (values limited to: external, internal)
coordinatesystem - Required
id - Optional
lang - Optional
script - Optional
**Availability**: Optional, repeatable

## Context
new EAC-CPF element

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text]
**May occur within**: `<place>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@coordinateSystem` - required
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Optional, repeatable

- example needed

## Example encoding
```
<place>
 <placeName>name of the place</placeName> 
 <geographicCoordinates audience="external" conventionDeclarationReference="conventiondeclaration1" coordinateSystem="WGS84" id="geoco1" languageOfElement="lat" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">N 52° 31' 27'', E 13° 24' 37''</geographicCoordinates>
</place>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<place>` that encodes a set of geographic coordinates.
**May contain:** [text]
**May occur within:** place
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@coordinateSystem` - required
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
Use `<geographicCoordinates>` to express a set of geographic coordinates such as latitude, longitude, and altitude representing a point, line, or area on the surface of the earth.
**Attribute Usage:**
Use the required `@coordinateSysten` attribute to provide a commonly used code for the system used to express the coordinates. Examples include WGS84, OSGB36, ED50.
**Availability:** Optional, repeatable

(Include example encoding altitude)

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<geographicCoordinates>` is an optional sub-element of `<place>`, however, one of `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, or `<contact>` has to be present
- `<geographicCoordinates>` can be repeated
- `<geographicCoordinates>` can contain text
- `<geographicCoordinates>` does currently not require the attribute `@coordinateSystem`(@fordmadox, this would need updating in the schemas) 
- `<geographicCoordinates>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`, 
- `<geographicCoordinates>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

@ailie-s - the TL draft currently is missing `@target`.

**Comment by fordmadox** [comment]
Thanks, @kerstarno !  Just patched with https://github.com/SAA-SDT/eac-cpf-schema/commit/03c0b48ac173501c0ccdb6c57a8234af9a67917f

**Comment by kerstarno** [comment]
Thanks, @fordmadox. Re-tested and can confirm that `@coordinateSystem` is now a required attribute of `<geographicCoordinates>`.

This applies to both schemas, RNG and XSD.

Element is ready.
