### ISSUE TITLE
@coordinateSystem

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#188]
## Coordinate System

Add new mandatory attribute `@coordinateSystem` with data type _token_ to the new element `<geographicCoordinates>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary:** A code for a system used to express geographic coordinates, for example WGS84, (World Geodetic System), OSGB36 (Ordnance Survey Great Britain), or ED50 (European Datum). Required in `<geographiccoordinates>.`
**Data Type**: token

## Context
new EAC-CPF attribute

## Solution documentation: agreed solution for TL and guidelines
_Summary_ needed

**Data Type**: token

**May occur within**: `<geographicCoordinates>`

- example needed

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A code for a system used to express geographic coordinates, for example WGS84, (World Geodetic System), OSGB36 (Ordnance Survey Great Britain), or ED50 (European Datum). Required in `<geographicCoordinates>`.
**Data Type:** token

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@coordinateSystem` is a required attribute in `<geographicCoordinates>` 
- It has the data type _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
