### ISSUE TITLE
<address>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#189]
## Address

- keep name and scope
- add optional attributes
`@audience`
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**: 
altrender - Optional
audience - Optional (values limited to: external, internal)
script - optional

## Context
**Summary**: A postal or other address.
**May contain**: addressLine
**May occur within**: place
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation: 

**May contain**: `<addressLine>`
**May occur within**: `<place>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Optional, Repeatable

- `<address>` is ideally bundled with `<placeName>`
- use `<address>` to encode a physical or analog address vs. `<contact>` to encode digital addresses and contact information

## Example encoding
```
<place> 
 <placeName>name of the place</placeName>
 <address audience="external" conventionDeclarationReference="conventiondeclaration1" id="address1" languageOfElement="en" localType="localAdress" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" target="element>
  <addressLine>distinct address information</addressLine>
  <addressLine>distinct address information</addressLine>
 </address>
</place>
```

**Comment by ailie-s** [comment]
Tag library Text:

**Summary:** An optional child element of `<place>` that binds together one or more `<addressLine>` elements to encode a postal or other address.
**May contain:** addressLine (1..n)
**May occur within:** place
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<address>` is an optional wrapper element within `<place>` used to encode a physical or analog address.
Ideally `<address>` should be bundled with a `<placeName>` element within `<place>` to provide both the name and address of a location.
`<address>` must include one or more `<addressLine>` element(s) that provide full or sufficient information identifying a postal or other physical address related to the entity being described.
**See Also:**
Use `<contact> `to encode digital addresses and contact information.
**Availability:** Optional, Repeatable

**Comment by karinbredenberg** [comment]
Test of element address:
May occur within: place 0..n **Ok in both schemas**
May contain: addressLine (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: Element ready
