### ISSUE TITLE
<preferredForm>: relax restriction xs:NMTOKEN

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#19]
The content for the element `<preferredForm>` within `<nameEntry>` is defined as xs:NMTOKEN. Relax the restriction.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
There are 2 different proposals for the content of <preferredForm>:

1. `<preferredForm>` changed from NMTOKEN to token: [\S]+ to correspond with `<agencyCode>` [used by SNAC, contributed by @dpitti ]

2. following EAD 3 without any restriction for the element content of `<preferredForm>` 

see also #14 

## Context

> The <preferredForm> element contains an abbreviation of the relevant national, international or other convention or rule applied by a given agency and according to which the name thus qualified is deemed as preferred to the others.

[Tag Library](http://eac.staatsbibliothek-berlin.de/fileadmin/user_upload/schema/cpfTagLibrary.html#preferredForm)

**Comment by karinbredenberg** [comment]
1. would be valid if done as 2. So align with EAD3.

**Comment by SJagodzinski** [comment]
As EAD3 has no `<preferredForm>`. At a glimpse, I can't see a similar element in EAD 3. Element `<abbr>` is defined a text.
Adapt schema and tag library: define <preferredForm> as text.

**Comment by SJagodzinski** [comment]
> The `<preferredForm>` element contains an abbreviation of the relevant national, international or other convention or rule applied by a given agency and according to which the name thus qualified is deemed as preferred to the others. 

There are parallels to #14 and #15. Again an attribute to identify the used data value standard would be useful here, too. But, TL says

> The abbreviations expressed in `<preferredForm>` must be declared within the `<conventionDeclaration>` element in `<control>`. 

Fazit: Adapt schema and tag library: define as text.

**Comment by SJagodzinski** [comment]
Example for TL :

```
<nameEntryParallel>
<nameEntry lang="fr" scriptCode="Latn">
<part>Institut international des droits de l'homme</part>
<preferredForm>AFNOR_Z44-060</preferredForm>
</nameEntry>
</nameEntryParallel>
```

Taken from `<nameEntryParallel>` example.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
