### ISSUE TITLE
<addressLine>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#190]
## Address Line

- keep name and scope
- add optional attributes
`@addressLineType`
`@audience` 
`@conventationDeclarationReference`
`@id` 
`@languageOfElement` 
`@localType` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**: 
altrender - Optional
audience - Optional (values limited to: external, internal)
script - Optional

## Context
**Summary**: One line of a postal or other address
**May contain**: [text]
**May occur within**: address
**Attributes**: `@localType`, `@xml:id`, `@xml:lang`
**Availability**: Mandatory, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: [text]
**May occur within**: `<address>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@addressLineType` - optional (values limited to: county, country, district, municipality, postBox, postalCode, region, street)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Mandatory, Repeatable

## Example encoding
```
<place>
 <placeName>name of the place</placeName>
 <address> 
  <addressLine audience="external" addressLineType="street" conventionDeclarationReference="conventiondeclaration1" languageOfElement="en" localType="localadressline" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" id="adressline1" scriptOfElement="lat" sourceReference="source1" target="element1">distinct address information</addressLine>
 </address>
</place>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<address>` used for recording one line of an address, whether postal or other.
**May contain:** [text]
**May occur within:** address
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@addressLineType` - optional (values limited to: county, country, district, municipality, postBox, postalCode, region, street)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<addressLine>` is used to encode parts or lines of a physical address within a parent `<address>` element.
`<addressLine>` may be repeated as many times as necessary to enter all parts of an address.
**Attribute Usage:**
Use one of the set values in the optional `@adressLineType` attribute to encode the part of the address that the `@addressLine `refers to, for example "street".
**Availability:** Required, Repeatable

**Comment by karinbredenberg** [comment]
Test of element addressLine:
May occur within: address 1..n **Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@addressLineType - optional (values limited to: city, county, country, district, municipality, postBox, postalCode, region, street) **In both schemas, values needs to be added, camelcasing**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: @addressLineType lacks values city and postalBox. Camelcasing of all the values?

**Comment by fordmadox** [comment]
Updated value lists with the new restricted values: https://github.com/SAA-SDT/eac-cpf-schema/blob/be3c14af5730fdf64ca3c505211b290b9924d63d/source/modules/attributes.rng#L15-L27

**Comment by karinbredenberg** [comment]
Retest of element addressLine:
@addressLineType - optional (values limited to: city, county, country, district, municipality, postBox, postalCode, region, street) **Ok in both schemas**

**Result**: Element ready
