### ISSUE TITLE
<contact>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#192]
## Contact

Add new optional element `<contact>` with child element `<contactLine>` to `<place>` to encode digital addresses or contact information. 
- add optional attributes:
`@audience` 
`@conventationDeclarationReference`
`@id`
`@languageOfElement` 
`@localType` 
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
new EAC-CPF element

## Context
new EAC-CPF element

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: `<contactLine>`
**May occur within**: `<place>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Optional, Repeatable

- use `<contact>` to encode digital addresses and contact information vs. `<address>` to encode a physical or analog address 

## Example encoding
```
<place>
 <contact audience="external" conventionDeclarationReference="cd1" languageOfElement="en" localType="localcontact" localTypeDeclarationReference="ltd1" id="contact1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" target="element1">
  <contactLine>distinct contact information</contactLine>
 </contact>
</place>
```

**Comment by ailie-s** [comment]
Tag Library Text:

*Summary:** An optional child element of `<place>` that binds together one or more `<contactLine>` elements to encode contact details or digital addresses.
**May contain:** contactLine (1..n)
**May occur within:** place
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement `- optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<contact> `is an optional wrapper element within `<place>` used to encode digital addresses and contact information.
`<contact>` must include one or more `<contactLine>` element(s) that provide relevant contact details for the entity being described.
**See Also:**
Use `<address>` to encode a physical or analog address.
**Availability:** Optional, Repeatable

**Comment by karinbredenberg** [comment]
Test of element contact:
May occur within: place 0..n  **Ok in both schemas**
May contain: contactLine (1..n)  **Ok in both schemas**
@audience - optional (values limited to: external, internal)  **Ok in both schemas**
@conventationDeclarationReference - optional  **Ok in both schemas**
@id - optional  **Ok in both schemas**
@languageOfElement - optional  **Ok in both schemas**
@localType - optional  **Ok in both schemas**
@localTypeDeclarationReference - optional  **Ok in both schemas**
@maintenanceEventReference - optional  **Ok in both schemas**
@scriptOfElement - optional  **Ok in both schemas**
@sourceReference - optional  **Ok in both schemas**

**Result**: Element ready.
