### ISSUE TITLE
<contactLine>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#193]
## Contact Line

Add new optional text element `<contactLine>` in `<contact>` to encode digital addresses or contact information.

- add optional attributes:
`@audience` 
`@contactLineType` 
`@conventationDeclarationReference` 
`@href`
`@id`
`@languageOfElement` 
`@linkRole`
`@linkTitle`
`@localType` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@target`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
new EAC-CPF element

## Context
new EAC-CPF element

## Solution documentation: agreed solution for TL and guidelines
 _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text]
**May occur within**: `<contact>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@contactLineType` - optional (values limited to: email, fax, homepage, mobileNumber, phoneNumber)
`@conventationDeclarationReference` - optional
`@href` - optional
`@id` - optional
`@linkRole` - optional
`@linkTitle` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional

**Availability**: Mandatory, Repeatable

## Example encoding
```
<contact>  
 <contactLine audience="internal" contactLineType="fax" conventionDeclarationReference="cd1" id="contactLine1" languageOfElement="en" localType="localcontactline" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" href="www.fax.com" linkRole="fax" linkTitle="Fax" target="element1">distinct contact information</contactLine>
 <contactLine contactLineType="email">email contact information</contactLine>
</contact>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<contact>` used for recording one line of contact details or digital addresses.
**May contain:** [text]
**May occur within:** contact
**Attributes:**
`@audience `- optional (values limited to: external, internal)
`@contactLineType` - optional (values limited to: email, fax, homepage, mobileNumber, phoneNumber)
`@conventationDeclarationReference` - optional
`@href` - optional
`@id `- optional
`@languageOfElement` - optional
`@lastDateTimeVerified` - optional
`@linkRole` - optional
`@linkTitle `- optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<contactLine>` is used to encode separate details or lines of contact details or digital addresses within a parent `<contact>` element.
`<contactLine>` may be repeated as many times as necessary to enter all relevant contact details.
**Attribute Usage:**
Use one of the set values in the optional `@contactLineType` attribute to encode the type of contact detail that the `<contactLine>` refers to, for example "phoneNumber".
**Availability:** Required, Repeatable

**Comment by karinbredenberg** [comment]
Test of element contactLine:
May occur within: contact 1..n **Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@contactLineType - optional (values limited to: email, fax, homepage, mobileNumber, phoneNumber)  **In both schemas the valuelist needs to be remade**
@conventationDeclarationReference - optional **Ok in both schemas**
@href - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@lastDateTimeVerified - optional **Ok in both schemas**
@linkRole - optional **Ok in both schemas**
@linkTitle - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: The attribute contactLineType's value list needs to be changed in both schemas.

**Comment by fordmadox** [comment]
Updated value lists with the new restricted values: https://github.com/SAA-SDT/eac-cpf-schema/blob/be3c14af5730fdf64ca3c505211b290b9924d63d/source/modules/attributes.rng#L44-L52

**Comment by karinbredenberg** [comment]
Retest of element contactLine:
@contactLineType - optional (values limited to: email, fax, homepage, mobileNumber, phoneNumber) **Ok in both schemas**

**Result**: Element ready
