### ISSUE TITLE
@contactLineType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#194]
## Contact Line Type

Add the new optional attribute `@contactLineType` with limited values in `<contactLine>` to specify the type of the contact line. 

Values: email, fax, homepage, mobileNumber, phoneNumber, directions

Use the attribute `@localType` in order to encode a local type of a contact line.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
new EAC-CPF attribute

## Context
new EAC-CPF attribute

## Solution documentation: agreed solution for TL and guidelines
_Summary_ needed

Data Type: "email" or "fax" or "homepage" or "mobileNumber" or "phoneNumber" or "directions"

May occur within: `<contactLine>`

- use the attribute `@localType` in order to encode a local type of a contact line.
- example needed

## Example encoding
`<contactLine contactLineType="fax">+1 (312) 606 0728</contactLine>`

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Used to specify the type of contact line encoded in `<contactLine>`.
**Description:** Use one of the set values to specify the type of contact line encoded in `<contactLine>`. Use the attribute `@localType` in order to encode a local type of a contact line.
**Data values:** email, fax, homepage, mobileNumber, phoneNumber

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@contactLineType` is an optional attribute in `<contactLine>`
- It can have the values "email", "fax", "homepage", "mobileNumber", and "phoneNumber"
- It has the data type _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
Apologies for the late addition, but the following came up during the July meeting of the Working Group on Standards (WGoS) of Archives Portal Europe and in the current major revision of EAG that WGoS is running at the moment:

- WGoS aims at adopting the place encoding approach suggested in the draft of EAC-CPF 2.0 and most of the place encoding elements available in EAG at the moment can be mapped easily for this. 
- There is, however, one element that we'd like to map, but can't sufficiently at the moment: [`<directions>`](http://www.archivesportaleuropefoundation.eu/images/docs/EAG2012_TagLibrary.html#e65), which can include textual directions as well as a link e.g. to public transport recommendations or a map. 
- We would hence like to suggest adding the new value "directions" to `@contacLineType`, which would allow EAG to adopt the `<contact><contactLine>` approach for this piece of information, as `<contactLine>` also caters for linking options. 
- While having directions information might not always be required or obvious in the EAC-CPF context, it might still be useful to have this option, especially when describing CPF entities that are still alive/in operation. 
- Furthermore, having directions information as part of the place encoding could be of use in the EAD context, where the new place encoding approach will be adopted as well (e.g. as part of the publisher's or holding institution's information).

**Comment by MicheleCombs** [comment]
This seems like it makes sense to me.

Michele

**Comment by SJagodzinski** [comment]
EAC-CPF meeting 15 October 2021:

Agreement to add the new attribute value “directions”.
As @contactLineType is an optional attribute, there will be no value “other”. The Tag Library explains that other values are supposed to appear in @localType.

**Comment by kerstarno** [comment]
@fordmadox - this is another issue for the Schema team (update to the schema and testing). Just noting this here, as it's got the Tag Library milestone at the moment and hence did not yet appear in the list we discussed during the last Schema team meeting.

**Comment by SJagodzinski** [comment]
@fordmadox : Seems `@contactLineType` is still missing the new value "directions"

see also [#194 (comment)](https://github.com/SAA-SDT/eac-cpf-schema/issues/194#issuecomment-952182479 )

**Comment by fordmadox** [comment]
Thanks for the reminder, @SJagodzinski !  I still haven't done my final review of the updates still needed, but I hope to do that next week.  In the meantime, I've added "directions" as a valid option of `@contactLineType`.  See https://github.com/SAA-SDT/eac-cpf-schema/commit/3d4b5604c1bc32527dbf9cec27d0b5fc7b33206f

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that the value "directions" is now available for `@contactLineType` in both schemas as an additional option. 

With regard to an example encoding, here's one which I have just adapted to the upcoming EAG 3.0, which will follow EAC-CPF 2.0 in terms of encoding places and contact information:

```
<contact>
  <contactLine contactLineType="directions" languageOfElement="ger"
  href="https://www.bundesarchiv.de/DE/Content/Downloads/Foeve_Rastatt/2020-10-07_naturfreundehaus.pdf?
  __blob=publicationFile">
  Wegbeschreibung zum Naturfreundehaus in Rastatt
  </contactLine>
</contact>
```
