### ISSUE TITLE
<functions>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#195]
## Functions

- keep name and scope
- remove child elements `<citation>`, `<list>`, `<outline>`, `<p>`
- change availability from 0..n to 0..1
- add optional attributes:
`@audience` 
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: A grouping element used to bundle together individual `<function>` elements.
**May contain**: citation, descriptiveNote, function, list, outline, p
**May occur within**: description
**Attributes**: `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: `<descriptiveNote>`, `<function>`
**May occur within**: `<description>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, not repeatable

## Example encoding
```
<functions audience="external" conventionDeclarationReference="conventiondeclaration1" id="functions1" languageOfElement="en" localType="localfunctions" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <function>
  <term>function term</term>
 </function>
 <descriptiveNote>
  <p>note for all functions</p>
 </descriptiveNote>
</functions>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<description>` used for grouping together one or more `<function>` elements.
**May contain:** descriptiveNote (0..1), function (1..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference `- optional
**Description and Usage:**
Use the optional `<functions>` element to group together one or more occurrences of `<function>`. `<functions>` must include at least one `<function>` element.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element functions:
May occur within: description 0..1 **Ok in rng, Error in xsd 0..n**
May contain: descriptiveNote (0..1), **Ok in both schemas**
function (0..n) (description says 1..n though and the may contain 0..1) **In both schemas 1..n** 
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional  **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: @ailie-s change needed in May contain so it follows the description and usage. @fordmadox  In both schemas addition of the localType attributes, cardinality for the element in xsd needs to be changed.

**Comment by karinbredenberg** [comment]
Retest of element:
May occur within: description 0..1 **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional  **Ok in both schemas**
@target - optional **Ok in both schemas**

**Result**: Element ready.
