### ISSUE TITLE
<function>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#196]
## Function

- keep name and scope
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
**May contain**: part
**Additional EAD3 attributes**: altrender, audience, encodinganalog, identifier, normal, relator, rules, script, source

## Context
**Summary**: An element that provides information about a function, activity, role, or purpose performed or manifested by the CPF entity being described.
**May contain**: citation, date, dateRange, dateSet, descriptiveNote, placeEntry, term
**May occur within**: description, functions
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation:

**May contain**: `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>` (0..1), `<placeName>` (0..n), `<term>` (0..n)
**May occur within**: `<functions>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: required, repeatable

## Example encoding
```
<functions>
 <function audience="external" conventionDeclarationReference="cd1" id="f1" languageOfElement="en" localType="localfunction" localTypeDeclarationReference="ltd1" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" valueURI="http://functionvalue.org" vocabularySource="functionVocabulary" vocabularySourceURI="http://functionVocabulary.org" target="element1">
  <term>function term</term>
  <date>1950</date>
  <descriptiveNote>
   <p>descriptive note for this function</p>
  </descriptiveNote>
 </function>
</functions>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<functions>` that provides information about a function, activity, role, or purpose performed by the CPF entity being described.
**May contain**: date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), term (1..n)
**May occur within:** functions
**Attributes:**
`@audience `- optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference `- optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
A `<function>` element is a wrapper element used to encode an index term, using the child element `<term>`. Terms are used to identify the functions, processes, activities, tasks, or transactions performed by the CPF entity described in the EAC-CPF instance. They may be drawn from controlled vocabularies or may be natural language terms.
`<function>` must include at least one `<term>` element. `<term>` can be repeated within `<function>` to include translations of the same function. Use the `@languageOfElement` attribute to identify the language used in each `<term>`.
Associated date(s) (`<date>`, `<dateRange>` or `<dateSet>`) and place(s) (`<placeEntry>`) may be included to further constrain the term's meaning. A `<descriptiveNote>` may be included if a textual explanation is needed.
**Availability:** required, repeatable

**Comment by karinbredenberg** [comment]
Test of element function:
May occur within: functions 1..n  **Ok in both schemas**
May contain: date or dateRange or dateSet (0..1),  **Ok in both schemas**
descriptiveNote (0..1),  **Ok in both schemas**
placeName (0..n),  **Ok in both schemas**
reference (0..1),  **Ok in both schemas**
term (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: In both schemas is the localType attributes needed to be added. @ailie-s a note that the valueURI and vocabularySourceURI are of a type demanding a uri like value so that is explained in the attribute description in the TL.

**Comment by fordmadox** [comment]
Adding the localType attributes with https://github.com/SAA-SDT/eac-cpf-schema/commit/c957b09990e4a31d69a331339f5b573552359cf2#diff-be2fd24ee88d6a4affb100d9c7905d7805b06f3e9baaa13a097d7eea4a5c07d5R444

**Comment by karinbredenberg** [comment]
Retest of function:
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**

**Result**: element ready

**Comment by kerstarno** [comment]
Note: Following the EAC Team meeting on 8 January, `<function>` will not have `<reference>` as direct sub-element anymore. It's not listed for the TL draft, but the schema test confirms its availability. Needs to be rechecked.

**Comment by kerstarno** [comment]
Updated the schema (models-and-shared-elements.rng) and removed `<reference>` from the single elements model therein. 

Retested.

- `<function>` does not allow for `<reference>` anymore as a direct sub-element in neither the RNG, nor the XSD

Element ready (again).
