### ISSUE TITLE
<legalStatuses>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#197]
## Legal Statuses

- keep name and scope
- remove child elements `<citation>`, `<list>`, `<outline>`, `<p>`
- change availability from 0..n to 0..1
- add optional attributes:
`@audience` 
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: A grouping element used to bundle together individual `<legalStatus>` elements.
**May contain**: citation, descriptiveNote, legalStatus, list, outline, p
**May occur within**: description
**Attributes**: `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: `<descriptiveNote>`, `<legalStatus>`
**May occur within**: `<description>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, not repeatable

## Example encoding
```
<legalStatuses audience="external" conventionDeclarationReference="conventiondeclaration1" id="legalStatuses1" languageOfElement="en" localType="locallegalstatuses" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <legalStatus>
  <term>legal status term</term>
 </legalStatus>
 <descriptiveNote>
  <p>note for all legal statuses</p>
 </descriptiveNote>
</legalStatuses>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<description>` used to bundle together one or more `<legalStatus>` element.
**May contain:** descriptiveNote (0..1), legalStatus (1..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement `- optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Description and Usage:**
`<legalStatuses>` groups together one or more occurrences of `<legalStatus>`. `<legalStatuses>` must include at least one `<legalStatus>` element.
**Availability:** Optional, not repeatable

**Comment by karinbredenberg** [comment]
Test of element legalStatuses:
May occur within: description 0..1**Ok in rng schema, in xsd 0..n**
May contain: descriptiveNote (0..1), legalStatus (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**

**Result**: Addition of the localType attributes. Cardinality in xsd needs to be changed to 0..1.

**Comment by karinbredenberg** [comment]
Retest of element:
May occur within: description 0..1 **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional  **Ok in both schemas**
@target - optional **Ok in both schemas**

**Result**: Element ready.
