### ISSUE TITLE
<legalStatus>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#198]
## Legal Status

- keep name and scope
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
**May contain**: blockquote, chronlist, head, legalstatus, list, p, table
**Additional EAD3 attributes**: altrender, audience, encodinganalog, script

## Context
**Summary**: An element used to encode information about the legal status of a corporate body.
**May contain**: citation, date, dateRange, dateSet, descriptiveNote, placeEntry, term
**May occur within**: description, functions
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation:

**May contain**: `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>` (0..1), `<placeName>` (0..n), `<term>` (0..n)
**May occur within**: `<legalStatuses>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: required, repeatable

## Example encoding
```
<legalStatuses>
 <legalStatus audience="external" conventionDeclarationReference="conventiondeclaration1" id="legalStatus1" languageOfElement="en" localType="locallegalstatus" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://legalstatusterm.org" vocabularySource="legalstatusvocaburlary" vocabularySourceURI="http://legalstatusvocaburlary.org">
  <term>legal status term</term>
  <placeName>place related to a legal status</placeName>
  <date>1960</date>
  <reference>external reference for a legal status</reference>
  <descriptiveNote>
   <p>note for this legal status</p>
  </descriptiveNote>
 </legalStatus>
</legalStatuses>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<legalStatuses>` used to encode information about the legal status of a corporate body.
**May contain:** date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), term (1..n)
**May occur within:** legalStatuses
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource `- optional
`@vocabularySourceURI` - optional
**Description and Usage:** 
The legal status of a corporate body is typically defined and granted by authorities or through authorized agencies. Enter terms in accordance with provisions of the controlling legislation. Terms may be drawn from controlled vocabularies or may be natural language terms.
`<legalStatus>` must include at least one `<term>` element, where the legal status of the corporate body is encoded. `<term>` can be repeated within `<legalStatus>` to include translations of the same term. Use the `@languageOfElement` attribute to identify the language used in each `<term>`.
Associated date(s) (`<date>`, `<dateRange>` or `<dateSet>`) and place(s) (`<placeName>`) may be included to further constrain the term's meaning. A `<descriptiveNote>` element may be included if fuller textual explanation is needed.
Multiple `<legalStatus>` elements may be grouped within a `<legalStatuses>` element.
**Availability:** required, repeatable

**Comment by karinbredenberg** [comment]
Test of element legalStatus:
May occur within: legalStatuses 1..n **Ok in both schemas**
May contain: date or dateRange or dateSet (0..1),  **Ok in both schemas**
descriptiveNote (0..1),  **Ok in both schemas**
placeName (0..n),  **Ok in both schemas**
reference (0..1),  **Ok in both schemas**
term (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: element ready.

**Comment by kerstarno** [comment]
Note: Following the EAC Team meeting on 8 January, `<legalStatus>` will not have `<reference>` as direct sub-element anymore. It's not listed for the TL draft, but the schema test confirms its availability. Needs to be rechecked.

**Comment by kerstarno** [comment]
Updated the schema (models-and-shared-elements.rng) and removed `<reference>` from the single elements model therein. 

Retested.

- `<legalStatus>` does not allow for `<reference>` anymore as a direct sub-element in neither the RNG, nor the XSD

Element ready (again).
