### ISSUE TITLE
<citation>

### ISSUE THREAD

**Issue by wisserk** [SAA-SDT/eac-cpf-schema#2]
The <citation> element is specified as being repeatable within the tag library but not within the schema.

**Comment by SJagodzinski** [comment]
Make `<citation>` repeatable or revise the tag library

## The issue relates to
- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<citation>` should be repeatable in the schema or the availability in the tag library should be changed to non-repeatable
in EAD 3 `<citation>` is not repeatable

## Context

> Within `<conventionDeclaration>`, `<localTypeDeclaration>`, `<localDescription>`, `<legalStatus>`, `<occupation>`, `<function>` and `<mandate>` [= m.simpleDescription] it is repeatable according to the Tag Library but not in the schema.

reported by APEx projekt, May 2013

**Comment by karinbredenberg** [comment]
Align with EAD3.

**Comment by SJagodzinski** [comment]
So, change TL to non-repeatable

**Comment by SJagodzinski** [comment]
Usage/availability according the updated schema (2010_Revised):

**element**
biogHist - optional, repeatable
conventionDeclaration - mandatory, non-repeatable
localTypeDeclaration - mandatory, non-repeatable
place - optional, non-repeatable
rightsDeclaration - mandatory, non-repeatable

**m.discursiveSet**
functions - optional, repeatable
legalStatuses - optional, repeatable
localDescriptions - optional, repeatable
mandates - optional, repeatable
occupations - optional, repeatable
places - optional, repeatable

**m.simpleDescription**
function - optional, non-repeatable
legalStatus - optional, non-repeatable
localDescription - optional, non-repeatable
mandate - optional, non-repeatable
occupation - optional, non-repeatable

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
