### ISSUE TITLE
Availability information in the tag library is confusing

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#20]
Confusion in the case of an element that may occur within many parents, with different conditions,  information found in the section Availability of the TL might be misleading. 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> Within `<descriptiveNote>` the child element `<p>` is mandatory according to the schema not in TL. Please correct the TL.

 [APEx, May 2013]

## Suggested Solution

> While the description of the element correctly reads: “The `<p>` element is an important textual feature, which must be used as part of any general description within a `<descriptiveNote>` element and may be used inside many of the descriptive elements within `<description>`." After the revision of the TL the statement is "Optional", which only partially reflects what is said in the textual description of the element!

[Anila Anjeli]

> - Consider that information on Occurrence and Repeatable/Non Repeatable is specified only by the schema and so, remove it from the Tag Library
> 
> - Use the info contained in the schema to feed programmatically the Tag Library (by XSLT programming). For each of the parent element (in case of multiple parents) process the information on the occurrence to get a human readable form in the TL

[Anila Anjeli]

## Context
The issue has largely been discussed within the revision group of the Tag Library. 

- Confusion in the case of an element that may occur within many parents, with different conditions
Information about the occurrence of each element is meaningful only contextually, i.e. in relation to each of the parent elements. If an element has multiple possible parents, the Tag Library should address accurately each and every situation of this element. A global declaration at the level of the child element should be true for the occurrence of the element within each and every possible parent.
In the revised version we have included an item in the Glossary:
“The section “Availability informs about the conditions of the occurrence of an element within its parent element."
Apparently this is not enough, as people do consult punctually the definition of each element in an isolated way without making reference to the introductory apparatus of the Tag Library.

In addition the statements “May contain” and “May be contained” are confusing, especially for cases where a child element is mandatory within a parent element (the statement “may contain” conflicts with a mandatory presence). 
Most of the comments, distributed in different sections of this document highlight problems with understanding and interpretation of these information.

**Comment by karinbredenberg** [comment]
Align with TL for EAD3 and do as its done in the TL for EAD3. Both TL's use the same transformations.

**Comment by ailie-s** [comment]
The EAD3 Tag Library uses 'Description and Usage' to include a statement about elements that must be contained, eg `<descriptiveNote>` "must contain one or more `<p>` elements".
For elements that must occur within other elements, this is stated under 'Availability', eg `<p>`
Within `<descriptivenote>`: Required, repeatable
Within all other parents: Optional, repeatable

**Comment by ailie-s** [comment]
There are differences in the language describing availability between EAC-CPF and EAD, eg mandatory(EAC-CPF)/required(EAD) and non-repeatable/not repeatable.
It would be good to make this consistent across both tag libraries.

**Comment by ailie-s** [comment]
At the meeting in Berlin in March 2020 it was decided to adopt the EAD terminology for describing availability: Required/Optional, Repeatable/Not Repeatable.

It was also decided to use more complete availability statements, eg:
> `<nameEntry>`
> Within `<identity>`: one of `<nameEntry>` or `<nameEntrySet>` required, repeatable
> Within `<nameEntrySet>`: `<nameEntry>` is required, repeatable

It was also decided to investigate including technical information of the availability of child elements within an element, eg:
> `<nameEntry>`
> May contain: `<part>` (1..n), `<useDates>` (0..1)

**Comment by SJagodzinski** [comment]
The EAC-CPF 2.0 Tag Library was aligned with EAD3 Tag Library by using the same terminology for availability. 

Availability information for **elements** is differentiated by their parent elements, if needed. The occurance of child elements is given by technical information within _May contain_.

Availability information for **attributes** is given next whithin the elements description and within the text description of the attribute.
