### ISSUE TITLE
<mandate>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#202]
## Mandate

- keep name and scope
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: The source of authority or mandate for the corporate body in terms of its powers, functions, responsibilities or sphere of activities, such as a law, directive, or charter.
**May contain**: citation, date, dateRange, dateSet, descriptiveNote, placeEntry, term
**May occur within**: description, functions
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation:

**May contain**: `<date>`, `<dateRange>`, `<dateSet>`, `<descriptiveNote>` (0..1), `<placeName>` (0..n), `<term>` (0..n)
**May occur within**: `<mandates>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional

**Availability**: required, repeatable

## Example encoding
```
<mandates> 
 <mandate audience="external" conventionDeclarationReference="conventiondeclaration1" id="mandate1" languageOfElement="en" localType="localmandate" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://mandateterm.org" vocabularySource="mandatetermsource" vocabularySourceURI="http://mandatetermsource.org">
  <term>term of a mandate</term>
  <placeName>place related to this mandate</placeName>
  <date>1980</date>
  <reference>external reference for a mandate</reference>
  <descriptiveNote>
   <p>note for this mandate</p>
  </descriptiveNote>
 </mandate>
</mandates>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<mandates>` used for identifying the source of authority or mandate for the corporate body in terms of its powers, functions, responsibilities or activities, such as a law, directive or charter.
**May contain:** date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), term (1..n)
**May occur within:** mandates
**Attributes:**
`@audience `- optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
`<mandate>` is used to identify the source of authority or mandate for the corporate body in terms of its powers, functions, responsibilities or sphere of activities, such as a law, directive or charter. Terms may be drawn from controlled vocabularies or may be natural language terms.
`<mandate>` must include at least one `<term>` element. `<term>` can be repeated within `<mandate>` to include translations of the same mandate. Use the `@languageOfElement` attribute to identify the language used in each `<term>`.
Associated date or date range (`<date>`, `<dateRange>` or `<dateSet>`) and place(s) (`<placeName>`) may be included to further constrain the term's meaning. A <descriptiveNote> element may be included if a fuller explanation is needed.
Multiple `<mandate>` elements may be grouped within a `<mandates>` element.
**Availability:** required, repeatable

**Comment by karinbredenberg** [comment]
Test of element mandate:
May occur within: mandates 1..n **Ok in both schemas**
May contain: date or dateRange or dateSet (0..1),  **Ok in both schemas**
descriptiveNote (0..1),  **Ok in both schemas**
placeName (0..n),  **Ok in both schemas**
reference (0..1),  **Ok in both schemas**
term (1..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: element ready.

**Comment by kerstarno** [comment]
Note: Following the EAC Team meeting on 8 January, `<mandate>` will not have `<reference>` as direct sub-element anymore. It's not listed for the TL draft, but the schema test confirms its availability. Needs to be rechecked.

**Comment by kerstarno** [comment]
Updated the schema (models-and-shared-elements.rng) and removed `<reference>` from the single elements model therein. 

Retested.

- `<mandate>` does not allow for `<reference>` anymore as a direct sub-element in neither the RNG, nor the XSD

Element ready (again).
