### ISSUE TITLE
<generalContext>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#206]
## General Context 
- keep name and scope
- add new optional, non repeatable child element `<head>`
- remove child element: `<outline>`, `<reference>` (fka `<citation>`)
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: An element that encodes information about the general social and cultural context of the CPF entity being described.
**May contain**: citation, list, outline, p
**May occur within**: description
**Attributes**: `@localType`, `@xml:id`, `@xml:lang`
**Availability**: Optional, Repeatable

## Solution documentation: 

**May contain**: `<head>` (0..1), `<list>` (0..n), `<p>` (0..n)
**May occur within**: `<description>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, Repeatable

## Example encoding
```
<generalContext audience="external" conventionDeclarationReference="conventiondeclaration1" id="generalcontext1" languageOfElement="en" localType="localcontext" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <p>Description of the general social and cultural context of the CPF entity being described.</p>
 <p>A discursive expression of the general context may be encoded as one or more paragraph elements.</p>
  <list>
  <item>list or tree for the general context information</item>
 </list>
</generalContext>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<description>` that encodes information about the general social and cultural context of the CPF entity being described.
**May contain:** head (0..1), list (0..n), p (0..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<generalContext>` encodes information about the social, cultural, economic, political, and/or historical context in which the CPF entity being described existed. The general context provides wide latitude to record contextual information not specifically accommodated by other elements contained in `<description>`.
The optional `<list>` element may be used to accommodate greater complexity in expressing or representing the general context being described.  The optional `<head>` element may be used to encode a title or caption. A simpler discursive expression of the general context may be encoded as one or more `<p>` elements.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
@fordmadox - just as a note as I've came across this in the context of looking at the elements order question: resulting from the December meeting of the EAC team, `<generalContext>` should NOT contain `<reference>` as a separate sub-element anymore. Neither should `<chronList>` be included. Both are currently still available in both RNG and XSD.

@ailie-s - the same for the above TL draft with regard to `<reference>`. Instead, `<head>` will need to be added.

**Comment by fordmadox** [comment]
Got it, thanks.  Finally had to remove my comment about chronList (https://github.com/SAA-SDT/eac-cpf-schema/commit/f11e2cd3d97cc4cb3888d9367f97328653585052#diff-9c8e7d14f008e33f16049b8bce31b9eb4a7caf3ae00d2bec2ae901a48a0e39aaL388), since I was hoping to make those 3 elements the same 😄

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<generalContext>` is an optional sub-element of `<description>`
- `<generalContext>` can be repeated
- `<generalContext>` allows for the optional sub-elements `<head>` (which has to come first, if used), `<p>`, and `<list>`; the two latter can be repeated
- `<generalContext>` furthermore allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<generalContext>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.

@ailie-s thanks for adding `<head>` and removing `<reference>` in the TL draft for "May contain". The "Description and usage", however, still includes a sentence with regard to `<reference>`, but doesn't mention `<head>`.
