### ISSUE TITLE
<structureOrGenealogy>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#207]
## Structure or Genealogy
- keep name and scope
- add new optional, non repeatable child element `<head>`
- remove child element: `<outline>`, `<reference>` (fka `<citation>`)
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: A description of the internal administrative structure(s) of a corporate body or the genealogy of a family.
**May contain**: citation, list, outline, p
**May occur within**: description
**Attributes**: `@localType`, `@xml:id`, `@xml:lang`
**Availability**: Optional, Repeatable

## Solution documentation: 

**May contain**: `<head>` (0..1), `<list>` (0..n), `<p>` (0..1)
**May occur within**: `<description>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, Repeatable

## Example encoding
```
<structureOrGenealogy audience="external" conventionDeclarationReference="conventiondeclaration1" id="structure1" languageOfElement="en" localType="localgenealogy" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <p>Description of the internal administrative structure(s) of a corporate body or the genealogy of a family.</p>
 <list>
  <item>item for a structure</item>
 </list>
</structureOrGenealogy>
```

**Comment by ailie-s** [comment]
Tag Library Text: 

**Summary:** An optional child element of `<description>` used to describe internal administrative structure(s) of a corporate body or the genealogy of a family.
**May contain:** head (0..1), list (0..n), p (0..n)
**May occur within:** description
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<structureOrGenealogy>` encodes information expressing the internal administrative structure(s) of a corporate body and the dates of any changes to that structure that are significant to understanding the way that corporate body conducted affairs (such as dated organization charts), or the genealogy of a family (such as a family tree) in a way that demonstrates the interrelationships of its members with relevant dates.
The optional `<list>` element may be used to accommodate greater complexity in expressing or representing the structure(s) or genealogy being described. `<head>` may be used to encode a title or caption. A simpler discursive expression of the structure(s) or genealogy may be encoded as one or more `<p>` elements.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
@fordmadox - just as a note as I've came across this in the context of looking at the elements order question: resulting from the December meeting of the EAC team, `<structureOrGenealogy>` should NOT contain `<reference>` as a separate sub-element anymore. Neither should `<chronList>` be included. Both are currently still available in both RNG and XSD.

@ailie-s - the same for the above TL draft with regard to `<reference>`. Instead, `<head>` will need to be added.

**Comment by karinbredenberg** [comment]
Test of element structureOrGeneallogy:
May contain: list (0..n),  **Ok in both schemas**
p (0..n),  **Ok in both schemas**
reference (0..n)  **Ok in both schemas as removed**
head (0..1) **Ok in both schemas, added in comnparision to the current TL entry**
May occur within: description 0..n **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@target - optional  **Ok in both schemas, added**

**Result**: element ready. @ailie-s just a reminder of the changes needed in the TL text.
