### ISSUE TITLE
<languageUsed>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#209]
## Language Used

- keep name and scope
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
- change availability to mandatory, repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
Role and function of singular/plural elements is confusing #21
Child elements of singular/plural elements #61

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: The language and script used by the CPF entity being described.
**May contain**: descriptiveNote, language, script
**May occur within**: description, languagesUsed
**Attributes**: localType, xml:id, xml:lang - all optional
**Availability**: Optional, Repeatable

## Solution documentation:

**May contain**: `<descriptiveNote>` (0..1), `<language>` (0..n), `<writingSystem>` (0..n)
**May occur within**: `<languagesUsed>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: required, repeatable

## Example encoding
```
<languagesUsed>
 <languageUsed audience="external" conventionDeclarationReference="conventiondeclaration1" id="languageused1" languageOfElement="en" localType="locallanguage" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
  <language languageCode="en">English</language>
  <writingSystem scriptCode="lat">Latin</writingSystem>
  <descriptiveNote>
   <p>note for this information on used language and script</p>
  </descriptiveNote>
 </languageUsed>
</languagesUsed>
```

**Comment by SJagodzinski** [comment]
EAC-CPF December 2020 meeting:

`<languagesUsed>` and `<languageUsed>` is not designed like other singular/plural elements and contains only the defined lanuage and descriptive note elements.

**Comment by fordmadox** [comment]
I think that's a very good point about those two elements being different than the rest of the singular/plural elements.  Additionally, I worry that there will be even more potential typos with this pair since the plural "s" occurs in the middle of the element name, whereas the rest are at the end.  Given that, I wonder if we couldn't rename one of those two elements to something else entirely?  Since I don't have a good suggestion I'll take a look at other schemas, like how this is handled in TEI when describing people, but just throwing that out there for now.  

But one idea would be to scrap languge**s**Used altogether and let languageUsed repeat just like biogHist can now, without a pluralized wrapper.

Total aside, but I also wonder if it would ever be useful to permit the languageUsed wrapper as an optional child of relation?

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<languagesUsed>` describing the language and writing system used by the CPF entity being described.
**May contain:** descriptiveNote (0..1), language (0..n), writingSystem (0..n)
**May occur within:** languagesUsed
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType `- optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference `- optional
`@target` - optional
**Description and Usage:**
`<languageUsed>` is an element used to indicate the language and writing system, or script, in which the CPF entity being described was creative or productive. Use the `<language>` element to specify the language and a corresponding `<writingSystem>` element for the writing system.
**See Also:**
Do not confuse with `<languageDeclaration>` which refers to the language and script of the EAC-CPF instance.
**Availability**: required, repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<languageUsed>` is a required sub-element of `<languagesUsed>`
- `<languageUsed>` can be repeated
- `<languageUsed>` allows for the optional sub-elements `<language>`, `<writingSystem>`, and `<descriptiveNote>`;  the first two can be repeated
- `<languageUsed>` furthermore allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
- `<languageUsed>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.
