### ISSUE TITLE
Role and function of singular/plural elements is confusing

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#21]
Confusion on the role and function of singular/plural elements

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

Wouldn’t it be suitable to state the occurrence of all the elements, that could be used in singular and plural forms, as "0...∞ or 1...∞" for their singular forms? 
It seems to be kind of a similar situation as with `<cpfDescription>` as standalone resp. as subelement of `<multipleIdentities>` – either I use e.g. `<function>` in its singular form, such as
   `<function/>`
   ` <function/>`
    `<function/>`
[etc.]
or I bundle several `<function>` elements with the plural form `<functions>`, such as
    `<functions>`
         `<function/>`
         `<function/>`
        `<function/>`
         [etc.]
    `</functions>`
where I would at least need to have one `<function>` as subelement, because otherwise "bundling" would not make that much sense, wouldn’t it?

[ Kerstin Arnold, July 2012]

## Context
See also #20

**Comment by karinbredenberg** [comment]
Align with TL for EAD3 and do as its done in the TL for EAD3. Both TL's use the same transformations.

**Comment by fordmadox** [comment]
From the EAC tag library:  

> Descriptive elements generally have a singular and plural form, the
> latter being used for those cases of multiple instances of a descriptive category or less
> formal prose description. For example, \<function> would be used for a single function
> term, \<functions> will bundle more than one function descriptor or alternatively, it will
> allow a discursive description. Most elements within \<description> include an optional
> \<descriptiveNote> element to provide explanatory text.

I've never understood this distinction in EAC, though, so at first blush I am 100% in support of Kerstin's suggestion, especially within the prospect of the major revision.  It would make working with the standard much more enjoyable, as well, I think.  HTML does not have ul and uls, h1 and h1s (even though those can repeat), p and ps, etc. :)

**Comment by karinbredenberg** [comment]
I would take a bolder action and always having the bundling to make it easier to write import/export. So not having function unless its in functions.

**Comment by cannedit** [comment]
I agree with Karin on this.

**Comment by kerstarno** [comment]
For what it's worth, 7 years after initially having asked this question: in the Archives Portal Europe the exact same approach that Karin mentioned has been taken when defining the apeEAC-CPF profile. There you'll always have the plural/bundling elements, even if they only contain one of their singular "siblings".

**Comment by fordmadox** [comment]
Right now, EAC allows two options when using the pluralized versions for a few of those pluralized elements.  Option one allows you to have the singular element (1 or more) and a descriptive note (0 or 1).  Option two allows you to have the discursive set (e.g. citation, list, outline, p).  If we can get rid of having two options, I'm all for using the pluralized versions. 

There's also the issue of the singular elements that can repeat but *cannot* be grouped the same way, though:   generalContext, structureOrGenealogy, biogHist.

I'm perfectly fine with just grouping by element names while processing, however.  

That said, if we force "function" to be a child of "functions", why not "generalContext" as a child of "generalContexts", etc.  However, I'd still probably be in favor of just letting singular elements repeat without forcing them in a grouping element.   

Regardless, I think that this needs to be addressed, since I don't see any reason to keep the singular/plural distinction as it exists now in EAC.

**Comment by SJagodzinski** [comment]
Team discussion: see also [meeting minutes](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2019/20190301_EAC-CPF_minutes.pdf)
In EAC-CPF 2010 there are formal and informal descriptive elements within `<description>`. Formal descriptive elements can be bundled within their plural element and they can also be repeated as singular elements, e.g. `<places>` and `<place>`. The informal descriptive elements are `<structureOrGenealogy>`, `<generalContext>`, `<biogHist>`. They are repeatable but can't be bundled in a plural element.

This solution brings a problem to process the schema, because there are multiple options to process these (repeated) elements. 

**Option 1**: Use only singular elements and make them repeatable, get rid of plural elements.
This solution would enforce users to use a specific order in the encoding.

**Option 2**: Use singular elements only in plural elements and make only the singular elements repeatable. 
Bundling elements makes it easier for processing: having one bundling element signalises that one or more can be existing at this point.

**Solution**: `<functions>` (0..1) – `<function>` (1..n) – `<term>` (1..n) with @lang and other child elements of `<term>`

**Documentation**: Repeat child elements if you describe the same function in different languages.

Distinction btw formal and informal descriptive elements will be part of documentation but not included in the schema.

**Comment by SJagodzinski** [comment]
Following elements are singular elements and also available as repeatable elements in a wrapper:

- `<cpfDesription>` within `<mulitpleIdentities>`
- `<cpfRelation>` within `<relations>`
- `<resourceRelation>` within `<relations>`
- `<funtionRelation>` within `<relations>`

These elements are not affected by this solution.

**Comment by SJagodzinski** [comment]
Adopt the solution for these elements:
//places/place
//localDescriptions/localDescription
//legalStatuses/legalStatus
//functions/function
//languagesUsed/languageUsed
//occupations/occupation
//mandates/mandate

**Comment by SJagodzinski** [comment]
Btw: EAD 3 is using //bibliography/bibliograpy whereas the "plural" element //bibliography = 0..1 and the "singular" element  //bibliography/bibliograpy = 0..n

**Comment by SJagodzinski** [comment]
See solution in #61
