### ISSUE TITLE
<relations>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#210]
## Relations 

- keep name and scope
- keep availability with 0..1
- remove child elements: `<cpfRelation>`, `<functionRelation>`, `<resourceRelation>`
- add mandatory, repeatable child element `<relation>`
- add optional, not-repeatable child element `<descriptiveNote>`
- add optional attributes
`@audience` 
`@conventationDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
- remove xml namespace

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
**Additional EAD 3 attributes**: `@altrender`, `@audience`, `@encodinganalog`, `@localtype`, @script - all optional
**May occur within:** archdesc, c, c01, c02, c03, c04, c05, c06, c07, c08, c09, c10, c11, c12
**May contain**: relation (0..n)

## Context
**Summary**: A wrapper element for grouping one or more specific relations, each of them expressed by `<cpfRelation>,` `<resourceRelation>,` or `<functionRelation>.`
**May contain**: cpfRelation, functionRelation, resourceRelation
**May occur within**: cpfDescription
**Attributes**: `@xml:base`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Optional, Non-repeatable

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: `<descriptiveNote>` (0..1), `<relation>` (1..n)
**May occur within**: `<cpfDescription>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
**Availability**: Optional, Non-repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<relations audience="external" base="baseURI" conventionDeclarationReference="conventiondeclaration1" id="relations1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
 <relation>
  <targetEntity targetType="person">
   <part>name or part of the name or term of the related entity</part>
  </targetEntity>
  <relationType>Family</relationType>
  <targetRole>Parent</targetRole>
  <dateSet>
   <date>1800</date>
   <dateRange>
    <fromDate>1900</fromDate>
    <toDate>1950</toDate>
   </dateRange>
  </dateSet>
 <place>
  <placeName>place of the relation</placeName>
  <placeRole>residence</placeRole>
  <date>1930</date>
  <descriptiveNote>
   <p>descriptive note to a place related with the target entity</p>
  </descriptiveNote>
  </place>
  <descriptiveNote>
   <p>note for this relation</p>
  </descriptiveNote>
  <objectXMLWrap>
   <anyelementofanynamespace/>
  </objectXMLWrap>
 </relation>
 <descriptiveNote>
  <p>note for all relations</p>
 </descriptiveNote>
</relations>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<cpfDescription>` that groups one or more `<relation>` elements, which identify external entities and characterize the nature of their relationships to the entity being described.
**May contain:** descriptiveNote (0..1), relation (1..n)
**May occur within:** cpfDescription
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement `- optional
`@maintenanceEventReference `- optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
A wrapper element that groups together one or more `<relation>` elements, each of which encodes a specific relationship.
**Availability:** Optional, Non-repeatable

**Comment by karinbredenberg** [comment]
Test of element relations:
May contain: descriptiveNote (0..1),  **Ok in both schemas**
relation (1..n) **Ok in both schemas**
May occur within: cpfDescription 0..1 **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@base - optional **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@target - optional **Ok in both schemas**

**Result**: element ready.
