### ISSUE TITLE
<resourceRelation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#212]
## Resource Relation

- remove the element from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations

## EAD3 Reconciliation
EAC-CPF specific element

## Context
An element for encoding a relation between a resource and the CPF entity.

Revising EAC-CPF and relations encoding, the element will be removed and a new elements //relation/targetEntity with the mandatory attribute `@targettype` (limited values: corporatebody | person | family | resource | function) will indicate what kind of relation is given.

## Solution documentation:

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

`<resourceRelation>` is not available anymore as sub-element of `<relations>`. Neither in RNG, nor in XSD. 

Test successful.
