### ISSUE TITLE
<functionRelation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#213]
## Function Relation

- remove the element from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
EAC-CPF specific element

## Context
An element designed to encode a relationship between a function and the CPF entity described in the EAC-CPF instance.

Revising EAC-CPF and relations encoding, the element will be removed and a new elements //relation/targetEntity with the mandatory attribute `@targettype` (limited values: corporatebody | person | family | resource | function) will indicate what kind of relation is given.

## Solution documentation:

- remove from Tag Library

**Comment by karinbredenberg** [comment]
Test of element functionRelation:

**Result**: The element can't be found.
