### ISSUE TITLE
<targetEntity>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#215]
## Relation Target Entity

- add new mandatory, not repeatable element `<targetEntity>` as child element of `<relation>`
- add mandatory and repeatable child element `<part>` to add the name or term of the related entity
- add **mandatory attribute**
`@targetType` (limited values: corporateBody, person, family, resource, function)
- add **optional attributes**
`@audience` 
`@conventationDeclarationReference` 
`@id` 
`@languageOfElement` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
EAC-CPF specific element

## Context
new EAC-CPF element
- was `<relationEntry>` before

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: `<part>` (1..n)
**May occur within**: `<relation>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@targettype` - mandatory (values limited to: corporateBody, person, family, resource, function)
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: mandatory, not repeatable

- New or other example needed
- Topic for Best Practise Guide

## Example encoding
```
<relation>
 <targetEntity audience="external" conventionDeclarationReference="conventiondeclaration1" id="targetEntity1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://entity.uri" vocabularySource="sourceofentityvoc" vocabularySourceURI="http://sourceofentityvoc.org">7
  <part>name or part of the name or term of the related entity</part>
 </targetEntity>
</relation>
```

**Comment by fordmadox** [comment]
Just a note that though I've now made @target a global attribute as per our most recent discussion, I think we should revisit that decision. The "reference" element should be able to point internally if it can be used to point externally, but where could elements like "eac" and "multipleIdentities" need to link internally?  

I'm adding this comment to "targetEntity", since this element is going to be difficult to explain with the multiple "target" attribute options:

`targetEntity/@target`
`targetEntity/@targetType`

There's also the issue that the HTML target attribute means something else entirely, but I assume that EAD inherited the name target from TEI (see https://www.tei-c.org/release/doc/tei-p5-doc/en/html/REF-ATTS.html#target).  In TEI, though, target can only be used on specific elements, and certainly not like `TEI/@target`

**Comment by ailie-s** [comment]
Draft Tag Library Text:

**Summary:** A required child element of `<relation>` used to identify the entity that is being targeted by the relation.
**May contain:** part (1..n)
**May occur within:** relation
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference `- optional
`@id` - optional
`@languageOfElement `- optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference `- optional
`@target` - optional
`@targetType` - required (values limited to: agent, corporateBody, person, family, resource, function)
`@valueURI `- optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:**
`<targetEntity>` is used within `<relation>` to identify an entity that is related to the subject of the EAC-CPF instance.
`<targetEntity>` must include at least one `<part>` element, encoding the name or term for the related entity.
**Attribute Usage:**
Use the required `@targetType`, to identity the type of entity related to in `<targetEntity>`, using one of the following values: corporateBody, person, family, resource, function.
**Availability:** required, not repeatable

**Comment by MicheleCombs** [comment]
> I think we should revisit that decision.

I agree.  I’m sorry I missed the earlier discussion, as I would have raised the same reservations as Ford does here – it simply doesn’t make sense for most elements.  What was the rationale for adding it to everything?

Michele

**Comment by SJagodzinski** [comment]
@MicheleCombs , @fordmadox : On the agenda for our January meeting.

**Comment by SJagodzinski** [comment]
@ailie-s, @fordmadox : I think we need to change availability from optional to mandatory. Otherwise, a relation might be encoded without the information what kind of entity is related given in //relation/targetEntity@targetType.

A relation without related entity wouldn't be useful and desired, I guess.

**Comment by fordmadox** [comment]
Also see https://github.com/SAA-SDT/eac-cpf-schema/issues/253

**Comment by karinbredenberg** [comment]
Test of element targetEntity:
May contain: part (1..n)  **Ok in both schemas**
May occur within: relation 1..1  **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@target - optional **Ok in both schemas**
@targettype - required (values limited to: corporateBody, person, family, resource, function) **Ok in both schemas (observe the addition of agent as value**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: elemnt ready. @ailie-s just a reminder so you dont miss the value agent in the targetType attribute and its capital T in Type.
