### ISSUE TITLE
<head>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#217]
## Heading

- add new optional, not repeatable element `<head>` as child element to `<biogHist>`, `<generalContext>`, `<list>`,  `<structureOrGenealogy>`
- add optional, repeatable child element `<span>` to `<head>` as formatting element and allow text
- add optional attributes:
`@audience` 
`@conventationDeclarationReference` 
`@id`
`@languageOfElement`
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<biogHist/>:` please allow `<head/>` #51

## EAD3 Reconciliation
**May contain**: [text], abbr, emph, expan, foreign, lb, ptr, ref
**Additional EAD 3 attributes**: `@althead`, `@altrender` - all optional

## Context
new EAC-CPF element

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed?

**Summary**: An element that encodes a title or caption for a section of text.
**May contain**: [text], `<span>` (0..n)
**May occur within**:  `<biogHist>`, `<generalContext>`, `<list>`,  `<structureOrGenealogy>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Optional, not repeatable

- example needed

## Example encoding
```
<biogHist>
    <head audience="external" conventionDeclarationReference="cd1" id="h1" languageOfElement="en" maintenanceEventReference="me1" scriptOfElement="lat" sourceReference="source1" target="element1">header of a biography or history</head>
    <abstract>brief summary of the information contained within the <reference href="https://biography.com">biography</reference> or history as a whole</abstract>
</biogHist>
```

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

- `<head>` is now available as an optional sub-element of `<biogHist>`, `<generalContext>`, `<list>`, and `<structureOrGenealogy>`
- `<head>` is not repeatable in any of these contexts
- `<head>`, when used, is expected to be the first element in each of these contexts
- `<head>` can include the optional and repeatable sub-element `<span>`
- `<head>` can be used with the optional attributes `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement` and `@target`
- `<head>` can also be used with optional attributes from other namespaces (tested with XLink)

The above is true for both, RNG and XSD.

In both, RNG and XSD, `<head>` was missing the optional attributes `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`. I've updated this in the source models-and-shared-elements.rng (as well as in the RNG and XSD).

Retested after update:
- `<head>` can now also be used with the optional attributes`@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`


Test successful.

**Comment by kerstarno** [comment]
@fordmadox - I'm adding this as a note here, as I couldn't find an issue for `<span>` yet: at the moment, `<span>` does not include `@localType`. Needs to be added.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An element that encodes a title or caption for a section of text.
**May contain:** [text], span (0..n)
**May occur within:** biogHist, generalContext, list, structureOrGenealogy
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
**Description and Usage:**
`<head>` is used for supplying title-like statements to a section of text or a list. When `<head>` is used, it must be the first child element, followed by one or more other elements.
**Availability:** Optional, not repeatable
