### ISSUE TITLE
<relationType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#219]
## Relation Type

- add new optional, repeatable text element `<relationType>` as child element of `<relation>` 
- add **optional attributes**
`@audience` 
`@conventationDeclarationReference` 
`@id`
`@languageOfElement` 
`@localType`
`@localTypeDeclarationReference` 
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
new EAC element

## Context
new EAC element

Type of relation, replaces omitted attributes `@cpfRelationType`, `@functionRelationType`, `@resourceRelationType` with their fixed values. The type of a relation can be descriped with text or defined via URI.

CPF Relation Types: "identity" or "hierarchical" or "hierarchical-parent" or "hierarchical-child" or "temporal" or "temporal-earlier" or "temporal-later" or "family" or "associative"

Function Relation Types: "controls" or "owns" or "performs"

Resource Relation Types: "creatorOf" or "subjectOf" or "other"
 
## Solution documentation:
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May contain**: [text]
**May occur within**: `<relation>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: optional, repeatable

## Example encoding
```
<relation>
 <targetEntity targetType="person">
  <part>persons name</part>
 </targetEntity>
 <relationType audience="external" conventionDeclarationReference="conventiondeclaration1" id="relationtype1" languageOfElement="en" localType="localrelationtye" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" voabularySource="GND" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd#" valueURI="https://d-nb.info/standards/elementset/gnd#Family">Family</relationType>
</relation>
```

**Comment by ailie-s** [comment]
@SJagodzinski  and @fordmadox can we confirm the availability of `<relationType>`?

The solution documentation says optional, repeatable, #214 says relationType (0..n), but the schema says it's required.

**Comment by SJagodzinski** [comment]
@ailie-s : Trust the issue ;-) 
We discussed this question in our December meeting and Gerhard confirmed this approach. Multiple `<relationTypes>` might be useful for translation or detailled description next to authorized vocabulary.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A child element of `<relation>` used to specify the type of relation that the `<targetEntity>` has to the entity being described.
**May contain:** [text]
**May occur within:** relation
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:** 
Use <relationType> within `<relation>` to specify the type of relation that the `<targetEntity>` has to the entity being described.
The `<relationType>`element contains a textual description of the relation. Examples of relations between the entity being described and a corporate body, person or family include "identity", "hierarchical", "temporal", "family" or "associative". Relations between the entity being described and a resource could be "creatorOf", "subjectOf" or "other". Relations between the entity being described and a function could be "controls", "owns" or "performs".
**Availability:** optional, repeatable

**Comment by fordmadox** [comment]
My bad!  I just updated the development schemas so that relationType is indeed optional.  I still have a question about how the relation element in general is meant to be modeled now, but I've added a question about that here:  https://github.com/SAA-SDT/eac-cpf-schema/issues/214#issuecomment-753535235

**Comment by karinbredenberg** [comment]
Test of element relationType:
May contain: [text]  **Ok in both schemas**
May occur within: relation 0..n  **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal)  **Ok in both schemas**
@conventationDeclarationReference - optional  **Ok in both schemas**
@id - optional  **Ok in both schemas**
@languageOfElement - optional  **Ok in both schemas**
@localType - optional  **Missing in both schemas**
@localTypeDeclarationReference - optional  **Missing in both schemas**
@maintenanceEventReference - optional  **Ok in both schemas**
@scriptOfElement - optional  **Ok in both schemas**
@sourceReference - optional  **Ok in both schemas**
@target - optional  **Ok in both schemas**
@valueURI - optional  **Ok in both schemas**
@vocabularySource - optional  **Ok in both schemas**
@vocabularySourceURI - optional  **Ok in both schemas**

**Result**: Addiotn of the two localType attributes needed.

**Comment by karinbredenberg** [comment]
Retested element:
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**

**Result**: element ready.

**Comment by SJagodzinski** [comment]
During EAC-CPF team meeting in Sep, Oct and Nov 2021 the topic of converting EAC-CPF 2010 relation tyes within `@cpfRelationType` (#230), `@resourceRelationType` (#239), @functionRelationType (#231) to the new encoding was discussed and decided: Topic [relationType](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/relations/Topic_relationTypes_20211203.pdf)

**Comment by SJagodzinski** [comment]
No comment from Call for Comments.
