### ISSUE TITLE
Description of the attributes @longitude, @altitude in the tag library is incorrect

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#22]
Attributes `@longitude` and `@altitude` are described to be used with `<place>`, but they are used within `<placeEntry>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Correct description of the attributes `@longitude` and `@altitude` in the tag library. Replace the element `<place>` with `<placeEntry>`.

## Context
The same issue was obviously solved for the attribute `@latitude`.

**Comment by karinbredenberg** [comment]
Agreed!

**Comment by SJagodzinski** [comment]
Change tag library accordingly.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
