### ISSUE TITLE
<targetRole>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#220]
## Relation Target Role

- add new optional, repeatable text element `<targetRole>` as child element of `<relation>`
- add optional attributes
`@audience` 
`@conventationDeclarationReference`
`@id`
`@languageOfElement` 
`@localType` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
new EAC element

## Context
new EAC element

Role of the related entity, similiar to `<placeRole>`

## Solution documentation: agreed solution for TL and guidelines
_Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<relation>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: optional, repeatable

## Example encoding
```
<relation>
 <targetEntity targetType="person">
  <part>persons name</part>
 </targetEntity>
 <relationType>Family</relationType>
 <targetRole audience="external" conventionDeclarationReference="conventiondeclaration1" id="targetRole1" languageOfElement="lat" localType="localtargetrole" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" vocabularySource="schema.org" vocabularySourceURI="http://schema.org" valueURI="http://schema.org/parent">Parent</targetRole>
</relation>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:**  An optional child element of `<relation>` used to specify the role of a related entity.
**May contain:** [text]
**May occur within:** relation
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Description and Usage:**
`<targetRole>` is used with `<relation>` to specify the role of a related entity.
The `<targetRole>` element contains a textual description of the relation.
**Availability:** optional, repeatable

**Comment by karinbredenberg** [comment]
Test of element targetRole:
May contain: [text]  **Ok in both schemas**
May occur within: relation 0..n  **Ok in both schemas**
Attributes:
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@conventationDeclarationReference - optional **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional **Missing in both schemas**
@maintenanceEventReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@sourceReference - optional **Ok in both schemas**
@target - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: addition of @localType and @localTypeDeclarationReference needed.

**Comment by karinbredenberg** [comment]
Retested element:
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**

**Result**: element ready.
