### ISSUE TITLE
<componentEntry>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#224]
## Component Entry

- review scope and usage: use cases from National Library of Australia - keep the element
- add optional attributes:
`@audience`
`@conventationDeclarationReference`
`@localTypeDeclarationReference` 
`@maintenanceEventReference` 
`@scriptOfElement` 
`@sourceReference` 
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
alternativeSet / setComponent / componentEntry #154

## EAD3 Reconciliation
EAC-CPF specific element

## Context
**Summary**: A caption that can be used to provide identification and access to a linked resource.
**May contain**: [text]
**May occur within**: setComponent
**Attributes**: `@localType`, `@scriptCode`, `@transliteration`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: [text]
**May occur within**: `<setComponent>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: Optional, Repeatable

## Example encoding
```
<setComponent>
 <componentEntry audience="external" conventionDeclarationReference="convention1" id="ce1" languageOfElement="eng" localType="localEntry" localTypeDeclarationReference="local1" maintenanceEventReference="maintanance1" scriptOfElement="lat" sourceReference="source1" target="control1" valueURI="http://entity.uri" vocabularySource="sourceofentityvoc" vocabularySourceURI="http://sourceofentityvoc.org">textual note about the EAC-CPF encoding for one entire authority record</componentEntry>
</setComponent>
```

**Comment by kerstarno** [comment]
Tested as part of schema testing:

- `<componentEntry>` is an optional sub-element of `<setComponent>`
- `<componentEntry>` can be repeated
- `<componentEntry>` can have text
- `<componentEntry>` can be used with the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeReference`, `@valueURI`, `@vocabularySource` and `@vocabularySourceURI` 
- `<componentEntry>` also allows for optional attributes of any other namespace (tested with XLink)

The above applies to both schemas, RNG and XSD. 

The element is ready.

**Comment by ailie-s** [comment]
Draft Tag Library Text:

**Summary:** A child element of `<setComponent>` that can be used to provide identification and access to a linked resource.
**May contain:** [text]
**May occur within:** setComponent
**Attributes:** 
`@audience `- Optional (values limited to: external, internal)
`@conventionDeclarationReference `- Optional
`@id `- Optional
`@languageOfElement `- Optional
`@localType `- Optional
`@localTypeDeclarationReference `- Optional
`@maintenanceEventReference  `-Optional
`@scriptOfElement `- Optional
`@sourceReference `- Optional
`@target `- Optional
`@valueURI `- Optional
`@vocabularySource `- Optional
`@vocabularySourceURI `- Optional
**Description and Usage:** `<componentEntry>` is used within `<setComponent>` to provide a textual note about the EAC-CPF instance that is being bundled together with other authority records for the same entity within an `<alternativeSet>` wrapper. The bundled alternative records for a given EAC-CPF entity may be in difference languages or come from different authority
systems. The bundling allows them to be transmitted or stored together. The `<componentEntry>` element provides a place where a particular alternative record can be described or explained in relation to the other authority records.
**Availability:** Optional, repeatable
