### ISSUE TITLE
<event>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#225]
## Event

- keep name and scope
- add optional child elements `<reference>` and `<span>`
- add optional attributes
`@audience` 
`@conventationDeclarationReference`
`@localTypeDeclarationReference`
`@maintenanceEventReference` 
`@scriptOfElement`
`@sourceReference` 
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**May contain**: [text], abbr, corpname, date, emph, expan, famname, footnote, foreign, function, genreform, geogname, lb, list, name, num, occupation, persname, ptr, quote, ref, subject, title
**May occur within**: chronitem, chronitemset
**Attributes**: altrender, audience, id, lang, localtype, script - all optional
**Availability:**
Within <chronitem>: Optional, not repeatable
Within <chronitemset>: Required, repeatable

## Context
**Summary**: An element used to encode an event associated with a date and, optionally, a place within a structured chronology.
**May contain**: [text]
**May occur within**: chronItem
**Attributes**: `@localType`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Mandatory, Non-repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: [text], `<reference>` (0..n), `<span>` (0..n)
**May occur within**: `<chronItem>`, `<chronItemSet>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: Mandatory, Non-repeatable

## Example encoding
```
<chronItem>
 <dateRange>
  <fromDate>start date for a list item</fromDate>
   <toDate>end date for a list item</toDate>
  </dateRange>
  <event audience="external" conventionDeclarationReference="conventiondeclaration1" id="event1" languageOfElement="en" localType="localevent1" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" valueURI="http://eventsvocabulary/event" vocabularySource="EV" vocabularySourceURI="http://eventsvocabulary/">event of this chronology list item</event>
</chronItem>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A child element of `<chronItem>` or `<chronItemSet>` that is used to encode an event associated with a date, and optionally a place, within a structured chronology.
**May contain:** [text], reference (0..n), span (0..n)
**May occur within:** chronItem, chronItemSet
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
`@target` - optional
**Description and Usage:**
`<event>` contains discursive text identifying the event described by the `<chronItem>` or `<chronItemSet>`. `<chronItem>` must include one of either `<event>` or `<chronItemSet>`. `<chronItemSet>` must include one or more `<event>`.
Every `<event>` must have date(s) (`<date>`, `<dateRange>` or `<dateSet>`) associated with it. It may also have optional `<placeName>` element associated with it.
**Availability:** 
Within `<chronItem>`: One of `<chronItemSet>` or `<event>` required, not repeatable.
Within `<chronItemSet>`: required, repeatable.

**Comment by fordmadox** [comment]
If we add "reference" here (and "item", etc.), should we also add "span"?  In principle, I'd think that span should be available in all of the same mixed-content locations that reference is available.

**Comment by kerstarno** [comment]
It's not specifically put down in the minutes, but I made this suggestion (adding `<span>` to `<event`)  as part of my general suggestion of having `<reference>` with `<event>`. This is not only to align the same mixed-content locations that make `<reference>` available within the EAC-CPF context, but will also make alignment with EAD easier in the long run.

**Comment by fordmadox** [comment]
Wherever "reference" is allowed in mixed content, I should say, then "span" should be allowed too :smile:

**Comment by SJagodzinski** [comment]
Confirmed, I added `<span>` together with `<reference>` in the issue above.

**Comment by kerstarno** [comment]
Tested as part of the Schema Team's schema testing:

- `<event>` is a sub-element of `<chronItem>` and `<chronItemSet>`
- `<event>` is required and repeatable as sub-element of `<chronItemSet>`
- As sub-element of `<chronItem>`, either `<event>` or `<chronItemSet>` has to be there; in this context, `<event>` is not repeatable
- `<event>` can contain text
- `<event>` allows for the optional sub-elements `<span>` and `<reference>`, which both can be repeated
- `<event>` allows for the optional attributes `@audience`, `@id`,  `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventationDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`
- `<event>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD. 

The element is ready.
