### ISSUE TITLE
Why not make "level of detail" an authorized attribute again? 

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eac-cpf-schema#226]
I'm assuming that `<term>` isn't required in `<localControl>` as it to a certain extent is modelled after the singular elements, where `<term>` is not required either, but one could simply use a date element, `<placeEntry>`, `<citation>`, or `<descriptiveNote>` instead at the moment. 

I'd agree that it would make sense to require `<term>` (though I'd also tend to require `<term>` with the singular elements, come to think about it), but I would not make `@localType` mandatory. This, for me, seems to be counterintuitive with regard to what this attribute is meant to be. 

If we keep `<localControl>` we might want to consider highly recommending the use of `@localType` with it. Looking at the example values from your dataset, @fordmadox, it seems that those are referring back to the attribute `@detaillevel`, which existed in EAC beta:
```
<xs:attribute name="detaillevel">
  <xs:simpleType>
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="minimal"/>
      <xs:enumeration value="partial"/>
      <xs:enumeration value="full"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
```
Do we know, why this was removed respectively not taken up by values used with either `<maintenanceStatus>` or `<publicationStatus>`? If this really is the only use case for `<localControl>` it might make more sense to consider a dedicated element/attribute for the detail level of an EAS description?

_Originally posted by @kerstarno in https://github.com/SAA-SDT/eac-cpf-schema/issues/105#issuecomment-671237127_

**Comment by fordmadox** [comment]
Just posting this as a new issue so that I can link a branch to it later on.  I'd assume that control/@levelOfDetail would work?  

If so, we'd be aligned with ISAAR-CPF 5.4.5, and we could also let any applications of that standard, e.g. https://github.com/saa-ts-dacs/dacs/blob/master/08_part_II/06_chapter_13/05_level_of_detail.md, know that there is a better mapping available.

**Comment by SJagodzinski** [comment]
`<term>` is defined as required and repeatable, cf #110 and https://github.com/SAA-SDT/eac-cpf-schema/issues/105#issuecomment-705769932

**Comment by kerstarno** [comment]
Just as a note that we decided to keep `<localControl>` as is in the EAC-CPF 2.0 draft for now, but have a closer look at how it is used in EAD3 at the moment. E.g. is anyone using the examples for `<localControl>` given in the EAD3 TL or has anyone added their own terms to `<localControl>` and if so, for which pieces of information.

**Comment by SJagodzinski** [comment]
EAC-CPF team meeting, 6 Aug 2021:

- add new optional attribute `@detailLevel` in `<control>` with values _minimal_, _basic_, _extended_
- keep `<localControl>`
