### ISSUE TITLE
<span>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#227]
## Span

- keep name and scope
- add optional attributes
`@audience`
`@conventationDeclarationReference` 
`@localTypeDeclarationReference` 
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 
- review parent elements, cf `<citation>` #102 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element, analogous EAD element is `<emph>`

## Context
**Summary**: Specifies the beginning and the end of a span of text.
**May contain**: [text]
**May occur within**: abstract, citation, item, p
**Attributes**: `@localType`, `@style`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Optional, Repeatable

## Solution documentation: agreed solution for TL and guidelines

**May contain**: [text]
**May occur within**: `<abstract>`, `<item>`, `<p>`, `<reference>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@style` - optional
**Availability**: Optional, Repeatable

## Example encoding
```
<biogHist>
 <abstract>brief <span audience="external" conventionDeclarationReference="conventiondeclaration1" id="span1" languageOfElement="en" localType="localspan" localTypeDeclarationReference="localTypeDeclaration1" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1" style="bold">summary</span> of the information contained within the <reference href="https://biography.com">biography</reference> or history as a whole</abstract>
</biogHist>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Specifies the beginning and the end of a span of text.
**May contain:** [text]
**May occur within:** abstract, event, eventDescription, head, item, reference, p
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional
`@style `- optional
`@target` - optional
**Description and Usage:**
`<span>` is an optional formatting element for distinguishing words or phrases that are intentionally stressed or emphasized for linguistic effect or identifying some qualities of the words or phrases.
**Attribute Usage:**
Use the optional `@style` attribute to affect an arbitrary stylistic difference.
**Availability:** Optional, Repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `<span>` is an optional sub-element of `<eventDescription>`, `<p>`, `<head>`, `<abstract>`, `<item>`, `<event>`, and `<reference>`
- `<span>` can be repeated in all these contexts
- `<span>` can contain text
- `<span>` allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, and `@style`
- `<span>` also allows for optional attributes from other namespaces (tested with XLink)

The above applies to both schemas, RNG and XSD.

The element is ready.
