### ISSUE TITLE
@accuracy

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#228]
## Accuracy

Remove optional attribute `@accuracy` from `<placeName>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from EAC-CPF November 2020 meeting to remove `@accuracy` from place encoding. No known use case.

**Summary**: The accuracy specification for a place statement.
**Description and Usage**: Within the `<placeEntry>` element, this attribute allows for an accuracy specification.
**Data Type**: string

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@accuracy` does not exist anymore

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
