### ISSUE TITLE
@altitude

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#229]
## Altitude

Remove optional attribute `@altitude` from `<placeName>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from EAC-CPF November 2020 meeting to remove `@altitude` from place encoding. No known use case.

**Summary**: The altitude or elevation of the geographic place.
**Description and Usage**: The altitude may occur on `<placeEntry>`. The value of the attribute is the altitude or elevation of the geographic place named. altitude should be used in conjunction with longitude and latitude.
**Data Type**: NMTOKEN

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@altitude` is not available anymore as an attribute for `<placeName>` (or in general in EAC-CPF 2.0)

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
