### ISSUE TITLE
<control>: express more adequately 

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#23]
There is a need to express the `<control>` more adequately – we suggest the use or inclusion of similar fields within `<eadheader>` such a `<descrules>`.

[K. Cox]

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> There is a need to express the `<control>` more adequately – we suggest the use or inclusion of similar fields within `<eadheader>` such a `<descrules>`.

[K. Cox]

## Context
This comment was part of the feedback from the staff in the Arrangement & Description Team at Alexander Turnbull Library (National Library of New Zealand) sent by Kirsty Cox.

**Comment by karinbredenberg** [comment]
Consolidation with EAD

**Comment by ailie-s** [comment]
Not sure whether this is a request to better describe the `<control>` element or to include more elements within `<control>`. Both `<eadheader>` and `<descrules>` have been omitted from EAD3, and `<conventiondeclaration>` (which is already in EAC-CPF) has replaced `<descrules>`. 
We can certainly improve the description of `<control>` in the Tag Library based on EAD's description. More detailed examples of usage could be included in best practice guidelines.

**Comment by SJagodzinski** [comment]
See solution in #81
