### ISSUE TITLE
 @cpfRelationType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#230]
## Corporate Body, Person, or Family Relation Type

Remove optional attribute `@cpfRelationType`. 
The attribute was inherited in `<cpfRelation>` element that was also removed from EAC and replaced by //targetEntity@targetType with limited values. 
`@cpfRelationType` is replaced by new element `<relationType>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Paper on Relation](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/relations)

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from Berlin 2020 meeting to change the relation encoding.

**Summary**: The type of relation that the corporate body, person, or family has to the entity being described.
**Description and Usage**: The cpfRelationType may occur on `<cpfRelation>`. The value designates the type of relation that a corporate body, person, or family has to the entity being described in the EAC-CPF instance. If the nature of the relation is more specific than one of the values given below, the Xlink attributes can be used in addition to cpfRelationType.
**Data Type**: "identity" or "hierarchical" or "hierarchical-parent" or "hierarchical-child" or "temporal" or "temporal-earlier" or "temporal-later" or "family" or "associative"

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@cpfRelationType` is not available anymore in the draft schema for EAC-CPF 2.0

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@SJagodzinski, @fordmadox, @ailie-s, @gerhardmueller 

Looking at conversion routes from the current values ("identity" or "hierarchical" or "hierarchical-parent" or "hierarchical-child" or "temporal" or "temporal-earlier" or "temporal-later" or "family" or "associative") and wondering whether this all would end up in `<relationType>` (#219) now, which currently concentrates on the more general examples of "identity" or  "hierarchical" or "temporal" or "family" or "associative", or if some (namely "hierarchical-parent" or "hierarchical-child" or "temporal-earlier" or "temporal-later") could actually also fit into `<targetRole>` (#220). The relations paper uses "family" for `<relationType>` and "parents" for the more specific `<targetRole>`. 

Any thoughts?

**Comment by SJagodzinski** [comment]
See https://github.com/SAA-SDT/eac-cpf-schema/issues/219#issuecomment-985367445
