### ISSUE TITLE
@identityType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#232]
## Identity Type 

- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context 
**Summary**: Indicates whether the identity is given or acquired. May be useful for processing when multiple identities are described in the same instance.

**Description and Usage**: The identityType may occur on `<identity>`. Though optional, it is recommended that it be used when multiple identities are described in the same EAC-CPF instance using `<multipleIdentities>`. It will enable processors to distinguish between the description of a person and one or more personae.

**Data Type**: "given" or "acquired"

## Solution documentation: 
Rephrasing _Summary_ and _Description_ needed?

## Example encoding
```
<identity identityType="given">
 <entityType value="family"/>
 <nameEntry>
  <part localType="surname">Lemoyne</part>
  <part localType="forename">Francois</part>
 </nameEntry>
</identity>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Indicates whether the identity is given or acquired. May be useful for processing when multiple identities are described in the same instance.
**Description and Usage:**
The `@identityType `may occur on `<identity>`. Though optional, it is recommended that it be used when multiple identities are described in the same EAC-CPF instance using `<multipleIdentities>`. It will enable processors to distinguish between the description of a person and one or more personae.
**Values:** given, acquired

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@identityType` is an optional attribute in `<identity>`
- It can have the values "given" or "acquired"
- Its data type is _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
