### ISSUE TITLE
@latitude

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#234]
## Latitude

Remove optional attribute `@latitude` from `<placeName>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from EAC-CPF November 2020 meeting to remove `@latitude` from place encoding, replaced by new element `<geographicCoordinates>`.

**Summary**: The geographic latitude of the place.
**Description and Usage**: The latitude may occur on `<placeEntry>`. The value of the attribute is the geographic latitude of the place named. latitude should be used in conjunction with longitude and altitude.
**Data Type**: NMTOKEN

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@latitude` is not available anymore as an attribute for `<placeName>` (or in general in EAC-CPF 2.0)

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
