### ISSUE TITLE
@longitude

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#235]
## Longitude

Remove optional attribute `@@longitude` from `<placeName>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific attribute

## Context
Decision from EAC-CPF November 2020 meeting to remove `@longitude` from place encoding, replaced by new element `<geographicCoordinates>`.

**Summary**: The longitude of the place.
**Description and Usage**: The longitude may occur on `<placeEntry>`. The value of the attribute is the geographic longitude of the place named. longitude should be used in conjunction with latitude and altitude.
**Data Type**: NMTOKEN

## Solution documentation

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@longitude` is not available anymore as an attribute for `<placeName>` (or in general in EAC-CPF 2.0)

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
