### ISSUE TITLE
@localType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#236]
## Local Type

- keep name and scope
- use `@localType` with `@localTypeDeclarationReference` 
- aligned with EAD shared elements in `<cpfDescription>` 
- avoid `@localType` in `<control>`, esp. in `<localTypeDeclaration>` itself
- **review data type**

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary**: This optional attribute provides a means to narrow the semantics of an element, or provide semantics for elements that are primarily structural or semantically weak. The value of localtype may be from a local or generally used external vocabulary. While the value of localtype may be any string, to facilitate exchange of data, it is recommended that the value be either the URI or the preferred label for a term defined in a formal vocabulary (e.g., SKOS), which is identified by an absolute URI, and is resolvable to a web resource that describes the semantic scope and use of the value. Local conventions or controlled vocabularies used in localtype may be declared in `<localtypedeclaration>` within `<control>`.

**Data Type**: token

## Context

**Summary**: Used to make the semantics of the element more specific or to provide semantic specificity to elements that are semantically weak. Value should be an absolute URI.

**Description and Usage**: The localType is broadly available on many descriptive and a few control elements. It is intended to provide a means to narrow the semantics of some elements or provide semantics for elements that are primarily structural or that are semantically weak. The value of the localType must conform to W3C Schema Part 2: Datatypes, anyURI. To facilitate exchange of EAC-CPF instances, it is highly recommend that the URI be absolute and resolvable to a local resource that describes the semantic scope and use of the value.

**Data Type**: anyURI

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<abstract>`, `<address>`, `<addressLine>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<date>`, `<dateRange>`, `<dateSet>`, `<event>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<identityId>`, `<item>`, `<languageUsed>`, `<languagesUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<part>`, `<place>`, `<placeName>`, `<places>`, `<relationType>`, `<representation>`, `<span>`, `<targetRole>`, `<toDate>`

## Example encoding

**Comment by SJagodzinski** [comment]
@fordmadox : I recommend to relax the data type accordingly EAD from anyURI to token. Do you agree?

**Comment by ailie-s** [comment]
Is there agreement on the data type for `@localType`? Relaxing it to token makes sense to me @SJagodzinski

**Comment by SJagodzinski** [comment]
@ailie-s : No feedback from @fordmadox so far, but let's use _token_ as data type for `@localType`.

Might be changed during the Call for Comments period, if necessary.

**Comment by fordmadox** [comment]
@SJagodzinski Sorry, didn't see this previously.  In EAC 1.x, I believe that localType is defined as "anyURI".  Same in EAD3 (update:  sorry, it is "token" in EAD3... I'll go back to look and see what the rationale is for that).  What's the impetus behind changing it to "token"?  

FWIW, values like `localtype="a"` are valid with anyURI :smile: 

Anyhow, I will update this momentarily so that it uses "token".

**Comment by fordmadox** [comment]
Changed the datatype to "token" with https://github.com/SAA-SDT/eac-cpf-schema/commit/43d9e856c93bcf298a7553a4f27d79f639bf0dd2

**Comment by fordmadox** [comment]
I don't think that there should any impact on the migration process, but I'm not sure the exact differences between those two datatypes.

**Comment by SJagodzinski** [comment]
> What's the impetus behind changing it to "token"?

@fordmadox : Due to alignment with EAD3. I assume that EAD revision team had an idea behind this data type. 

We can discuss these details during the Call for Comments period, but to finalise the draft for the Call for Comments, I try to freeze a status. No time and need to discuss the attribute data types at this moment, I think.

**Comment by ailie-s** [comment]
Tag Library Text

**Summary:** This optional attribute provides a means to narrow the semantics of an element, or provide semantics for elements that are primarily structural or semantically weak. 
**Description and Usage:**
The value of `@localType` may be from a local or generally used external vocabulary. While the value of `@localType` may be any string, to facilitate exchange of data, it is recommended that the value be either the URI or the preferred label for a term defined in a formal vocabulary (e.g., SKOS), which is identified by an absolute URI, and is resolvable to a web resource that describes the semantic scope and use of the value. 
Local conventions or controlled vocabularies used in `@localType` may be declared in `<localTypeDeclaration>` within `<control>`. `@localTypeDeclarationReference` should always be used alongside `@localType` to provide a direct link to the `<localTypeDeclaration>`.
**Data Type:** token

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@localType` is an optional attribute for (currently) 49 elements (`<abstract>`, `<address>`, `<addressLine>`, `<biogHist>`, `<chronItem>`, `<chronItemSet>`, `<chronList>`, `<componentEntry>`, `<contact>`, `<contactLine>`, `<date>`, `<dateRange>`, `<dateSet>`, `<event>`, `<existDates>`, `<fromDate>`, `<function>`, `<functions>`, `<generalContext>`, `<identity>`, `<identityId>`, `<item>`, `<languagesUsed>`, `<languageUsed>`, `<legalStatus>`, `<legalStatuses>`, `<list>`, `<localControl>`, `<localDescription>`, `<localDescriptions>`, `<mandate>`, `<mandates>`, `<nameEntry>`, `<nameEntrySet>`, `<occupation>`, `<occupations>`, `<otherAgencyCode>`, `<otherEntityType>`, `<otherRecordId>`, `<part>`, `<place>`, `<placeName>`, `<places>`, `<relationType>`, `<representation>`, `<span>`, `<structureOrGenealogy>`, `<targetRole>`, `<toDate>`)
  - That adds `<identity>` and `<structureOrGenealogy>` to the elements listed in the solution documentation above. @SJagodzinski seeing that these two have `@localType` in EAC-CPF 1.0 and we decided to keep `@localType` where available outside of `<control>`, I'm assuming this is correct. Could you please confirm? 
- Its data type is _token_
- It's always available together with the attribute `@localTypeDeclarationReference`.

The above applies to both schemas, RNG and XSD. 

@fordmadox with regard to the transformation, there are two elements that currently allow for `@localType`, but won't have it available anymore in EAC-CPF 2.0: `<rightsDeclaration>` (as per the EAC Team's decision on 6 November) and `<relationEntry>` when becoming `<targetEntity>`. 

Deleted following decision in #218 to migrate `@localType` with `<relationEntry>` to `@localType` with `<targetEntity><part>` <del>@SJagodzinski could you please confirm that `<targetEntity>` will not retain the `@localType` from `<relationEntry>`?</del>

**Comment by kerstarno** [comment]
With the confirmation in #175 for `@localTypeDeclarationReference`, the attribute `@localType` is ready, too.
