### ISSUE TITLE
@notAfter

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#237]
## Not After

- keep name and scope
- change data type to _token_

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_dates_20200911.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)
New attribute `@status` #70

## EAD3 Reconciliation
**Summary**: A standard numerical form of an approximate date for which a latest possible date is known. Available in `<datesingle>`, `<fromdate>`, and `<todate>`. It is recommened that notafter values follow ISO 8601 or another standard date format as specified in dateencoding.

**Data Type**: token

## Context
**Summary**: The latest date possible for an uncertain date.

**Description and Usage**: The notAfter may occur on `<date>`, `<fromDate>`, and `<toDate>`. For uncertain dates, used in conjunction with standardDate, the value of notAfter is the latest date possible. See also notBefore.

**Data Type**: Union of the XML Schema Datatypes date, gYear, and gYearMonth. The following are all valid patterns: 2009-12-31, 2009, 2009-12.

## Solution documentation: agreed solution for TL and guidelines
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<date>`, `<fromDate>`, `<toDate>`
**Data type**: token

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:
**Summary:** A standard numerical form of an approximate date for which a latest possible date is known. Available in `<date>`, `<fromDate>`, and `<toDate>`. It is recommended that `@notAfter` values follow ISO 8601 or another standard date format as specified in `@dateEncoding`.
**Data type:** token

**Comment by SJagodzinski** [comment]
@ailie-s : attribute is not ready, yet. We'll discuss data type in our January meeting.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@notAfter` is an optional attribute in `<date>`, `<fromDate>`, and `<toDate>`
- Its data type is _token_, i.e. it allows for textual values including blanks and most special characters rather than being constrained to ISO 8601 dates only (which is necessary for the "otherDateEncoding" option)

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
