### ISSUE TITLE
@standardDate

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#240]
## Standard Date

- keep name and scope
- change data type to _token_

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
@standardDate, @standardDateTime: remove regex pattern #33

## EAD3 Reconciliation

**Summary**: The standardized form of date expressed in `<datesingle>`, `<fromdate>`, or `<todate>`. It is recommened that standarddate values follow ISO 8601, for example, 2011-07-22, 1963, or 1912-11, or another standard date format as specified in dateencoding.

**Data Type**: token

## Context

**Summary**: The date represented in a standard form for computer processing.

**Description and Usage**: The standardDate may occur on `<date>`, `<fromDate>`, and `<toDate>`. The value of standardDate provides a standard form of the date expressed in `<date>`, `<fromDate>`, or `<toDate>` that can be used in computer processing, such as searching.

Data Type: Union of the XML Schema Datatypes date, gYear, and gYearMonth. The following are all valid patterns: 2009-12-31, 2009, 2009-12.

## Solution documentation:
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<date>`, `<fromDate>`, `<toDate>`
**Data type**: token

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** The standardized form of date expressed in `<date>`, `<fromDate>`, and `<toDate>`. It is recommended that `@standardDate` values follow ISO 8601, for example, 2011-07-22, 1963, or 1912-11, or another standard date format as specified in `@dateEncoding`.
**Data type:** token

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@standardDate` is an optional attribute in `<date>`, `<fromDate>`, and `<toDate>`
- Its data type is _token_, i.e. it allows for textual values including blanks and most special characters rather than being constrained to ISO 8601 dates only (which is necessary for the "otherDateEncoding" option)

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
