### ISSUE TITLE
@standardDateTime

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#241]
## Standard Date and Time

- keep name and scope
- change data type to EAD pattern

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
@standardDate, @standardDateTime: remove regex pattern #33

## EAD3 Reconciliation

**Summary**: An ISO 8601-compliant form of the date or date and time of a specific maintenance event expressed in `<eventdatetime>`. For example, 2009-12-31, 2009, 2009-12, 2009-12-31T23:59:59. Available only in `<eventdatetime>`.

**Data Type**: Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

## Context

**Summary**: The date or date and time represented in a standard form for computer processing.

**Description and Usage**: The standardDateTime may occur on `<eventDateTime>`. The value of standardDateTime provides a standard form of the date or date and time expressed in the `<eventDateTime>` that can be used in computer processing. For example, using both the value in `<eventType>` and standardDateTime, all EAC-CPF instances "revised" on a particular date can be identified.

Data Type: Union of the XML Schema Datatypes date, gYear, gYearMonth, and dateTime. The following are all valid patterns: 2009-12-31, 2009, 2009-12, 2009-12-31T23:59:59.

## Solution documentation:
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<eventDateTime>`
**Data Type**: Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An ISO 8601-compliant form of the date or date and time of a specific maintenance event expressed in `<eventDateTime>`. For example, 2009-12-31, 2009, 2009-12, 2009-12-31T23:59:59. Available only in `<eventDateTime>`
**Data Type:** Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@standardDateTime` is (currently) an optional attribute in `<eventDateTime>`
- Its data type is constrained to the options YYYY, YYYY-MM, YYYY-MM-DD, YYYY-MM-DDThh:mm:ss, YYYY-MM-DDThh:mm:ssZ, YYYY-MM-DDThh:mm:ss+hh:mm, YYYY-MM-DDThh:mm:ss-hh:mm 

The above applies to both schemas, RNG and XSD.

**Comment by kerstarno** [comment]
Reviewing elements that are currently mandatory in order to create a minimal EAC-CPF instance, the Schema Team suggested to make `@standardDateTime` mandatory along with restricting `<eventDateTime>` from having text (see #93). This decision is currently pending.

**Comment by SJagodzinski** [comment]
No, this solution forces users for automatic creation of EAC-CPF files or at least of the `@standardDateTime` value. This produces new hurdles which we want to avoid by simplifying the schema.

**Comment by kerstarno** [comment]
With the decision on `<eventDateTime>` (#93) with regard to keeping the element mandatory and allowing for text, but leaving the attribute optional, the attribute `@standardDateTime` is ready.
