### ISSUE TITLE
@transliteration

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#243]
## Transliteration

Remove attribute `@transliteration`.

Information about a transliteration scheme can be provided within `<conventionDeclaration>` element that can be referred via `@conventionDeclarationReference` attribute, cf #174.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary**: A value designating the transliteration scheme used in converting one script into another script. For example, the ISO 15919 Transliteration of Devanagari and related Indic scripts into Latin characters.

**Data Type**: NMTOKEN

## Context
**Summary**: A value designating the transliteration scheme used in representing converting one script into another script.

**Description and Usage**: The conventions or rules that prescribe a method for converting one script into another script.

**Data Type**: NMTOKEN

## Solution documentation: agreed solution for TL and guidelines

- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@transliteration` is not available anymore in the draft schema for EAC-CPF 2.0

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
