### ISSUE TITLE
@xlink:actuate

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#244]
## Xlink: Actuate

Remove xlink namespace and attribute `@xlink:actuate.` 
Do not replace with `@actuate`.

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf):

> Use `@linkrole`, `@linktitle`, and `@href`, from former XLink attributes and drop `@actuate`, `@arcrole`, `@show`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
Corresponding attribute in EAD: `@actuate`

**Summary**: A control that defines whether a rendering application should present an actionable link automatically (onload) or when requested by the user (onrequest). It is used in conjunction with show to determine link behavior.

**Values**: none, onload, onrequest, other

## Context
**Summary**: Used to signal intended behavior with respect to whether the remote resource link is resolved when the containing resource is rendered, or when the user requests the resource.

**Description and Usage**: The xlink:actuate should be used with the xlink:show to indicate intended behavior. The xlink:actuate is used to signal intended behavior with respect to when the remote resource is to appear. The values indicate whether the resource is to appear automatically when the containing resource is rendered ("onLoad"), or only after the user requests the resource ("onRequest"). "None" or "other" are also valid values.

**Data Type**: "onLoad" or "onRequest" or "other" or "none"

## Solution documentation: agreed solution for TL and guidelines
- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@xlink:actuate` is not available anymore in the draft schema for EAC-CPF 2.0, though with allowing attributes of any namespace one could of course still use `@xlink:actuate` along with other XLink attributes if wanted

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
