### ISSUE TITLE
@xlink:arcrole

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#245]
## Xlink: Arc role

Remove xlink namespace and attribute `@xlink:arcrole.` 
Do not replace with `@arcrole`.

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf):

> Use `@linkrole`, `@linktitle`, and `@href`, from former XLink attributes and drop `@actuate`, `@arcrole`, `@show`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
Corresponding attribute in EAD: `@arcrole`

**Summary**: A URI that describes the nature of the source of a link as relative to the target of the link.

**Data Type**: anyURI

## Context
**Summary**: URI defining the purpose of the link.

**Description and Usage**: An absolute URI that describes the nature of the relation between the entity being described in the EAC-CPF instance and a remote resource (`<cpfRelation>`, `<resourceRelation>`, or `<functionRelation>`) or the nature of the relation between the EAC-CPF instance description (or component of description) and the remote resource (`<citation>`, `<setComponent>`, and`<source>`). The value of the attribute should indicate the direction of the relation. It is recommended that the direction of the relation be from local resource to remote resource.

**Data Type**: string

## Solution documentation: agreed solution for TL and guidelines
- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@xlink:arcrole` is not available anymore in the draft schema for EAC-CPF 2.0, though with allowing attributes of any namespace one could of course still use `@xlink:arcrole` along with other XLink attributes if wanted

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
