### ISSUE TITLE
@xlink:show

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#246]
## Xlink: Show

Remove xlink namespace and attribute `@xlink:show`. 
Do not replace with `@show`.

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf):

> Use `@linkrole`, `@linktitle`, and `@href`, from former XLink attributes and drop `@actuate`, `@arcrole`, `@show`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
Corresponding attribute in EAD: `@show`

**Summary**: A control that defines whether a remote resource that is the target of a link appears in a new window, replaces the local resource that initiated the link, appears at the point of the link (embed), initiates some other action, or causes no target resource to display. It is used in conjunction with actuate to determine link behavior.

**Values**: new, replace, embed, other, none

## Context
**Summary**: Used to signal intended behavior with respect to where the remote resource is to appear when the link is resolved.

**Description and Usage**: The xlink:show should be used with the xlink:actuate to indicate intended behavior. The xlink:show is used to signal intended behavior with respect to where the remote resource is to appear when the link is resolved. The values indicate whether the resource is to appear embedded at the point of the link ("embed"), replace the resource in which it appears ("replace"), or in a new window ("new"). "None" or "other" are also valid values.

**Data Type**: "embed" or "new" or "replace" or "none" or "other"

## Solution documentation: agreed solution for TL and guidelines
- remove from Tag Library

**Comment by SJagodzinski** [comment]
Comments on `@xlink:show` in our [Berlin meeting notes](https://docs.google.com/document/d/1BsPEpKtbS40-EcAtYhNH7GC1UveJ7_0rAPJacb2vxxg/edit?usp=sharing):

@fordmadox : 
> could be handled another way, but just a note that EAD's dao element heavily relies on @show to determine whether a digital object is a thumbnail or not.

@kerstarno :

> 
> While I can see, why `@show` could be used as a work-around with regard to showing a thumbnail as "embed" and a digital object as "new" or "replace", I'm not sure I would agree that that's the actual question behind this.
> 
> What we'd want to have would be a way to say "this digital object is a thumbnail" and "this digital object is a high-resolution version of the image". But that's more about typing the digitial object than about defining how the link is supposed to act when shown.
> 
> In Archives Portal Europe, by the way, we use `@xlink:title` (EAD 2002) to differentiate between thumbnails and a higher resolution version. The high-res `<dao>` would have an actual title of the linked image, which could be shown as alternative text for accessibility reasons, while the thumbnail <dao> only has the title "thumbnail".
> 
> It's a work-around as well, I know; just wante to add it as an example that doesn't use `@(xlink:)show` for this purpose.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@xlink:show` is not available anymore in the draft schema for EAC-CPF 2.0, though with allowing attributes of any namespace one could of course still use `@xlink:show` along with other XLink attributes if wanted

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
