### ISSUE TITLE
@xlink:role

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#248]
## Xlink: Role

- remove xlink namespace and rename to `@linkRole`
- change data type from _string_ to _anyURI_
- accomponied by `@href`, `@lastDateTimeVerified`, `@linkTitle`

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf):

> Use `@linkrole`, `@linktitle`, and `@href`, from former XLink attributes and drop `@actuate`, `@arcrole`, `@show`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation

**Summary**: A URI that characterizes the nature of the remote resource to which a linking element refers.

**Data Type**: anyURI

## Context
**Summary**: Identifies the type or nature of the remote resource with an absolute URI.

**Description and Usage**: Identifies the type or nature of the remote resource with an absolute URI. 

**Data Type**: string

## Solution documentation: 
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<contactLine>`, `<reference>`, `<representation>`, `<source>`

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An ISO 8601-compliant form of the date or date and time of a specific maintenance event expressed in `<eventDateTime>`. For example, 2009-12-31, 2009, 2009-12, 2009-12-31T23:59:59. Available only in `<eventDateTime>`
**Data Type:** Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

**Comment by ailie-s** [comment]
What is the data type for `@linkRole`? EAD3 uses anyURI and EAC-CPF uses string.

**Comment by kerstarno** [comment]
I've had a look through the EAD3 repository to see if I could find anything with regard to the data type decision for EAD3, but there isn't anything specific there that would be an argument for using anyURI over string. Most of the comments point back to the origins in XLink and to XLink not being particularly precise respectively sending mixed messages with regard to especially `@xlink:arcrole` and `@xlink:role`.

Judging from the examples in the EAD3 TL, I would assume that the idea was to move the usage of `@linkrole` towards more of an L[O]D approach by defining its data type as "anyURI" (see examples such as "http://purl.org/archival/vocab/arch#Collection" or "http://xmlns.com/foaf/0.1/Person" or even "application/PDF"). 

Seeing that this would fit to what we are trying to achieve by the introduction of `@valueURI` and `@vocabularySourceURI`, using the data type anyURI for `@linkRole` seems to make sense in my opinion. Plus, it's still relatively open if someone wanted to use general text as its value. E.g. the following is valid for `@href` (which currently is also defined as anyURI in the draft for EAC-CPF 2.0):

```
<reference 
  href="This is some general text with a selection of special characters and punctation marks such as 
  , ; . - _ # ' + * ´ ` ß ? = ) ( / $ § ! ° ^ « ∑ € ® † Ω ¨ ⁄ ø π • ü ± ‘ ' ≠ } { | ] [ ¢ ¶ “ ¡ å ‚ ∂ ƒ © ª º ∆ @ œ ö æ ä ≤ ¥ ≈ ç √ ∫ ~ µ ∞ … 
  –"/> 
<!-- The only punctuation marks that I came across in this quick test that do throw a validation error are : and % -->
```

**Comment by SJagodzinski** [comment]
As we adopted `@linkRole` from EAD, we are going to use data type _anyURI_.

Might be changed during the Call for Comments period, if necessary.

**Comment by ailie-s** [comment]
Tag Library Text

**Summary:** A URI that characterizes the nature of the remote resource to which a linking element refers.
**Data type:** anyURI

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@xlink:role` does not exist anymore in the draft schema for EAC-CPF 2.0
- `@linkRole` is an optional attribute in `<representation>`, `<source>`, `<reference>`, `<contactLine>` and `<setComponent>`
  - @ailie-s Not sure, if you wanted to list the potential parent elements for `@linkRole`. If yes, and depending on the decision of keeping or removing `<alternativeSet>` and its sub-elements, `<setComponent>` would need to be included next to `<contactLine>`, `<reference>`, `<representation>`, and `<source>`
- It is available with all elements that also allow for `@href` 
- Its data type is _anyURI_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
