### ISSUE TITLE
@xlink:title

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#249]
## Xlink: Title

- remove xlink namespace and rename to `@linkTitle`
- change data type from _string_ to _token_
- accomponied by `@href`, `@lastDateTimeVerified`, `@linkRole`

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf):

> Use `@linkrole`, `@linktitle`, and `@href`, from former XLink attributes and drop `@actuate`, `@arcrole`, `@show`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation

**Summary**: Information that serves as a viewable caption which explains to users the part that a resource plays in a link. May be useful for meeting accessibility requirements when rendering finding aids in a web browser.

**Data Type**: token

## Context
**Summary**: Information that may be used as a viewable caption for the remote resource.

**Description and Usage**: Information that serves as a viewable caption that indicates the name or type of the linked remote source.

**Data Type**: string

## Solution documentation: 
Rephrasing _Summary_ and _Description and Usage_ needed

**May occur within**: `<contactLine>`, `<reference>`, `<representation>`, `<source>`

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Information that serves as a viewable caption which explains to users the part that a resource plays in a link. May be useful for meeting accessibility requirements when rendering finding aids in a web browser. Available in `<contactLine>`, `<reference>`, `<representation>`, and `<source>`.
**Data Type:** token

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@xlink:title` does not exist anymore in the draft schema for EAC-CPF 2.0
- `@linkTitle` is an optional attribute in `<representation>`, `<source>`, `<reference>`, `<contactLine>` and `<setComponent>`
  - @ailie-s Depending on the decision of keeping or removing `<alternativeSet>` and its sub-elements, `<setComponent>` would need to be included next to `<contactLine>`, `<reference>`, `<representation>`, and `<source>`
- It is available with all elements that also allow for `@href` 
- Its data type is _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
