### ISSUE TITLE
Identifiers

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#25]
Topic of identifiers is discussed esp. concerning the elements `<otherRecordId>` and `<entityId>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

1. `<recordId>`: should not be changed.

2. `<otherRecordId>`: 

> Widen the scope for this element (cf. usages of this element in projects like SNAC, ARDC Party Infrastructure, etc.)
> Two different uses for this element:
> 
> - alternative record identifiers for the same EAC-CPF instance as stated in the description of `<otherRecordId>` “These might include the identifiers of merged EAC-CPF instances representing the same entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance.”
> 
> - different IDs, each identifying each of the authority records aggregated within the EAC-CPF instance, in case of aggregation. 

[French Archivists]

Comments (unknown) so far:

- Needs to be addressed. 
Create an appropriate attribute/element the provenance (source repository/system) of the otherRecordId? All identifier related comments should be considered in relation to one another. 
- Element or attribute that would allow us to include the identifier of the institution
- `<otherRecordId>` represent recordIds that are considered (potentially outside of the system the record exists) 
- Tag Library: the connection is not reflected between this record and another record that describes the same entity in another system.

- FURTHER DISCUSSION: further clarification on what the issues are and some use case scenarios (otherRecordId).

3. `<entityId>`: change to `<identityId>`

Comments by TS-EAC so far:

- Agreement that `<entityId>` should be renamed `<identityId>` (but still some issues/questions to address in documentation, etc.) identityID is determined to make more sense. Mostly

## Context

`<otherRecordID>`: The `@localType` attribute of `<otherRecordId>` can be used to identify the kind of institution or service responsible for each associated record identifier. The `@xml:id` attribute of `<otherRecordId>` serves to name specific elements in an EAC-CPF instance. 
[APEx, May 2013]

The issue of the IDs is a complex one and needs to be reconsidered in the schema for more consistency and to accommodate for all the possible uses. In a networking environment the IDs are becoming crucial in accurately identifying and linking resources (“resource” in the web meaning of the term). EAC-CPF schema distinguishes between different types of identifiers according to the object of identification and the functionalities of each one, however some changes are probably needed.
If we list the uses of the identifiers:

**`<recordId>`** - the current EAC-CPF instance ID, which is unique as it identifies the record.
Required and unique

**`<otherRecordId>`** – two different uses for this element

1. alternative record identifiers for the same EAC-CPF instance as stated in the description of `<otherRecordId>` 
“These might include the identifiers of merged EAC-CPF instances representing the same entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance.”

2. different IDs, each identifying each of the authority records aggregated within the EAC-CPF instance, in case of aggregation. 

**`<entityId>`** 
here again the object of identification is arguable. EAC-CPF accommodates for multiple identities of a “real world entity” (to keep it simple). If the different identities of the “entity” – typically known by its eventual different names, such as pseudonyms under which the entity makes itself publicly known – get discrete identifiers, does the design and semantics of the element `<entityId>` address that distinction? 
In cases of EAC-CPF instances containing `<multipleIdentities>`, each of the “identities” recorded in the same EAC-CPF instance may be likely to have its own (and even multiple) identifiers.
ISNI (International Standard Name Identifier http://www.isni.org/, which aims at identifying the public identity of a party) and eventually other IDs that respond to the visions and needs of various communities and/or projects, as is the case of ORCID http://orcid.org/, are or are likely to explore those differences and sooner or later they will need to be appropriately accounted for. 

Shouldn’t `<entityId>` become `<identityId>`? At the final end, what identifies `<entityId>`? As this element is contained within `<identity>` it would be more consistent to change its name into `<identityId>`. In case of multiple identities in the same EAC-CPF instance, each handled in a separate `<identity>` element, it should be possible to record a separate ID for each of the identities described

[French Archivists]

**Comment by karinbredenberg** [comment]
The name change might be a challenge in regard to existing implementations, but would make it easier to understand the name. Clear use cases of/for all the different ID's is a good thing to have.

**Comment by SJagodzinski** [comment]
Results of team [discussion]( TS-EAS-subteam-notes/eaccpf-subteam/meeting-minutes-2017/20180914_EAC-CPF_minutes.pdf ):

This issues will be splitted between the elements `<redordId>`, `<otherRecordId>` and `<entityId>`.  There is probably no need for an umbrella issue for identifiers, so the issue will be closed and might be reopened, if needed.
