### ISSUE TITLE
@xlink:type

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#250]
## Xlink: Type

Remove xlink namespace and attribute `@xlink:type`. 

Agreed in EAC-CPF and in EAD team to remove this attribute to simplify the schema, cf [Berlin meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200309-12_EAC-CPF_minutes.pdf).

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
No corresponding attribute in EAD

## Context
**Summary**: A fixed value that identifies an XLINK compliant element of a particular type.

**Description and Usage**: A fixed value that identifies an XLINK compliant element of a particular type. Only one XLINK type is used in EAC-CPF, "simple." While the attribute is optional in instances validated against the W3C Schema version of EAC-CPF, the Relax NG version of EAC-CPF requires it. To support exchange of EAC-CPF instances, it is recommended that the xlink:type be present in the instance whenever any of the other XLINK attributes are used.

**Data Type**: Fixed value: "simple"

## Solution documentation: agreed solution for TL and guidelines
- remove from Tag Library

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing: 

- `@xlink:type` is not available anymore in the draft schema for EAC-CPF 2.0, though with allowing attributes of any namespace one could of course still use `@xlink:type` along with other XLink attributes if wanted

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
