### ISSUE TITLE
@certainty

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#251]
## Certainty 

- add new optional attribute `@certainty` to `<date>`, `<fromDate>`, and `<toDate>` with data type NMTOKEN

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic_dates_20200911.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)

## EAD3 Reconciliation
**Summary**: The level of confidence for the information given in `<date>`, `<unitdate>`, or `<unitdatestructured>`, e.g., approximate or circa.

**Data Type**: NMTOKEN

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

**May occur within**: `<date>`, `<fromDate>`, `<toDate>`
**Data Type**: NMTOKEN

- Topic for Best Practise Guide

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** The level of confidence for the information given in `<date>`, `<fromDate>`, or `<toDate>`, e.g., approximate or circa.
**Data Type:** NMTOKEN

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@certainty` is an optional attribute in `<date>`, `<fromDate>`, and `<toDate>`
- Its data type is _NMTOKEN_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
