### ISSUE TITLE
@preferredForm

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#252]
## Preferred Form of Name 

- add new optional attribute `@preferredForm` to `<nameEntry>` to indicate if a name entry is the preferred form for display
- values limited to: true, false

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<preferredForm>:` turn into attribute #71
[Topic_names_20200130.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/names/Topic_names_20200130.pdf)

## EAD3 Reconciliation
new EAC attribute

## Context
new EAC attribute, was element `<preferredForm>` before

## Solution documentation: 
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May occur within**: `<nameEntry>`
**Values**: false, true

- example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by fordmadox** [comment]
Just a note:  do we want to add a test to the Schematron to ensure that there is only 1 "true" preferredForm, or are multiple values okay?

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Attribute that specifies whether or not a `<nameEntry>` provides the preferred form of the name of the EAC-CPF entity.
**Values:** false, true

**Comment by SJagodzinski** [comment]
> 
> 
> Just a note: do we want to add a test to the Schematron to ensure that there is only 1 "true" preferredForm, or are multiple values okay?

I guess, multiple values would be ok in several name entries that are not bundled in a name entry set or if you have several name entry sets, eg one for each language, and have to declare the preferred form per set.

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@preferredForm` is an optional attribute in `<nameEntry>`
- It can have the values "false" or "true"
- Its data type is _boolean_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by SJagodzinski** [comment]
> 
> 
> Tag Library Text:
> 
> **Summary:** Attribute that specifies whether or not a `<nameEntry>` provides the preferred form of the name of the EAC-CPF entity.
> **Values:** false, true

@ailie-s : Could we add information that the preferred form of a name is meant for display purposed, cf https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-preferredForm
