### ISSUE TITLE
@targetType

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eac-cpf-schema#253]
## Relation Target Type

- add new mandatory attribute `@targetType` to `<targetEntity>` with limited values agent, corporateBody, person, family, resource, function

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
`<targetEntity>` #215 

## EAD3 Reconciliation
new EAC attribute

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

-  information what kind of entity is related 

**Mandatory within**: `<targetEntity>`
**Values**: agent, corporateBody, person, family, resource, function

Use value _agent_ only for migration from EAC-CPF 2010 to EAC 2.x

## Example encoding
```
<relation>
 <targetEntity targetType="person">
  <part>name or part of the name or term of the related entity</part>
 </targetEntity>
</relation>
```

**Comment by fordmadox** [comment]
Just a note that I have a few questions about how to handle the migration for this.  Consider this valid EAC 1.0 example:

```
            <cpfRelation>
                <relationEntry>Incognito</relationEntry>
            </cpfRelation>
```

Since we have no idea if the target is a person, corporate body, etc., what could we do in this case?  Would it possible to add other valid values to the current list of targetType values?

**Comment by SJagodzinski** [comment]
> Since we have no idea if the target is a person, corporate body, etc., what could we do in this case? Would it possible to add other valid values to the current list of targetType values?

What kind of value would that be? Maybe _cpf_ as value only for transformation or migration purposes?
What about to define eg _person_ as kind of default value for transformation or migration and communicate this one. Can we provide these values as parameter for xslt?

**Comment by kerstarno** [comment]
I'd prefer Silke's second suggestion , i.e. using _person_ as the default for transformation or migration and communicating this accordingly in a conversion report. Especially seeing that we've got a few other changes that we might need to communicate as a result of the conversion, this could be a good option. 

I'd rather not add a fourth value only for transformation or migration purposes. However, if we have to add one, I'd support the suggestion of using _cpf_ rather than using e.g. _other_ which would only open a can of worms... ;-)

**Comment by fordmadox** [comment]
Right, I think that something generic, like "cpfType", or even "agent" could work.  Similar to how EAD has `<name/>`, which can function as a generic option when it is unknown whether an entity is a person, a corporate body, work, etc., I'd suggest adding "**agent**" to the targetType list rather than defaulting to "person" in the conversion script when the type cannot be inferred.  This would also keep the terminology aligned with RiC, and might also open up possibilities, in the future, for having other targetTypes, like "instantiation" (although I still need to look at the ontology to understand why that is distinct from "record resource").

**Comment by fordmadox** [comment]
I'll go with a parameterized option for now in the transformation, but I still vote for adding a new option like "agent"... I think 😄

**Comment by SJagodzinski** [comment]
EAC-CPF January 2021 meeting outcome:

Confirmed to add value “agent” to `@targetType`.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Required attribute within `<targetEntity>` which identifies the type of entity that is related to the CPF entity being described. Use value "agent" only for migration from EAC-CPF 2010 to EAC 2.x
**Values:** agent, corporateBody, family, function, person, resource

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@targetType` is a required attribute in `<targetEntity>`
- It can have the values "agent", "corporateBody", "family", "function", "person", or "resource"
- Its data type is _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
