### ISSUE TITLE
@status

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#254]
## Status

- add new optional attribute `@status` to `<agencyCode>`, `<date>`, `<fromDate>`, `<nameEntry>`, `<otherAgencyCode>`, `<toDate>` to indicate if an element contains the authorized or alternative form of a code or a name or to indicate unknown and ongoing dates
- values in limited to: authorized, alternative | unknown, ongoing 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
New attribute `@status` #70
[Topic_names_20200130.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/names/Topic_names_20200130.pdf)
[Topic_dates_20200911.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)

## EAD3 Reconciliation
new EAC attribute

## Context
new EAC attribute

## Solution documentation: 
_Summary_, _Description and Usage_ and _Attribute usage_ needed

**May occur within**:  `<agencyCode>`, `<fromDate>`, `<nameEntry>`, `<otherAgencyCode>`, `<toDate>` 
**Values**: 
-  `<agencyCode>`, `<nameEntry>`, `<otherAgencyCode>`: authorized, alternative
- `<fromDate>` : unknown
- `<toDate>` : unknown, ongoing
- `<date>`: unknown

see also: [Kerstins comment in #70](https://github.com/SAA-SDT/eac-cpf-schema/issues/70#issuecomment-567085520):
> `@status` on the other hand, qualifies - or categorises - the content of the according element.

- example needed
- Topic for Best Practise Guide

## Example encoding

**Comment by SJagodzinski** [comment]
@ailie-s : Is `<fromDate status="ongoing"/>` useful?

**Comment by ailie-s** [comment]
@SJagodzinski : I don't think `<fromDate status="ongoing"/>` is useful.

**Comment by kerstarno** [comment]
Might be constructed, but in theory the following encoding would be valid, if we wanted to say that something has a timespan and that we know it's still active, but we are not sure about the actual start date:
```
<dateRange>
    <fromDate status="ongoing"/>
</dateRange>
```
Question might be - do we instead want to "enforce" an encoding such as:
```
<dateRange>
    <fromDate status="unknown"/>
    <toDate status="ongoing"/>
</dateRange>
```
by restricting the values for `@status` when used with `<fromDate>`?

**Comment by fordmadox** [comment]
We didn't discuss during today's meeting, did we?  Anyhow, just let me know if I need to make any changes in the schemas.

**Comment by SJagodzinski** [comment]
Let's keep it simple:

**Values:**
- `<agencyCode>`, `<nameEntry>`, `<otherAgencyCode>`: authorized, alternative
- `<fromDate>` : unknown
- `<toDate>` : unknown, ongoing

**Comment by kerstarno** [comment]
I.e. @fordmadox - please remove "ongoing" as a possible value for `@status` with `<fromDate>`.

**Comment by fordmadox** [comment]
Update made (and this change does remove 'status' from the 'date' element, since those previously all got the same attribute definitions before..., see #179, so if we need to add that attribute back to 'date', let me know). See https://github.com/SAA-SDT/eac-cpf-schema/commit/8a9adea4a70b3f05632943865481df31bc53ec47

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Attribute that provides controlled terminology detailing the status of elements. Available in `<agencyCode>`, `<fromDate>`, `<nameEntry>`, `<otherAgencyCode>` and `<toDate>`. The terms available for `@status` are defined in closed lists that vary by element.
**Values:**
Values in `<fromDate>`:  unknown
Values in `<agencyCode>`, `<nameEntry>`, `<otherAgencyCode>`: alternative, authorized
Values in `<toDate>`: ongoing, unknown

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@status` is an optional attribute in (currently) `<agencyCode>`, `<otherAgencyCode>`, `<nameEntry>`, `<fromDate>`, and `<toDate>`
  - @ailie-s the TL draft above is missing `<agencyCode>` and `<otherAgencyCode>` 
- Depending on its context, it can have the values "authorized" or "alternative" (`<agencyCode>`, `<otherAgencyCode>`, `<nameEntry>`), "unknown" (`<fromDate>`), and "unknown" or "oingoing" (`<toDate>`)
- Its data type is _token_

The above applies to both schemas, RNG and XSD.

**Comment by kerstarno** [comment]
There is currently a pending question if at least `@status="unknown"` should be re-instated with `<date>` in the same way as it's available with `<fromDate>`(see #179).

**Comment by SJagodzinski** [comment]
> There is currently a pending question if at least `@status="unknown"` should be re-instated with `<date>` in the same way as it's available with `<fromDate>`(see #179).

Is it, cf [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/254#issuecomment-758841237) and [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/247#issuecomment-763046789) ?

**Comment by kerstarno** [comment]
Well, the question in #179 was pending.

Anyway, note taken for feedback on the call for comments. :-)

**Comment by kerstarno** [comment]
With the decision to not have `@status="unknown"` for `<date>`, this attribute is ready.

**Comment by kerstarno** [comment]
Following their meeting on 18 June, the EAD team would like to suggest that `@status` is added to `<date>` as well allowing the value "unknown" (i.e. the same as `<fromDate>`. The main use case behind this is the use of `<date>` as one of the possible sub-elements of `<unitDateStructured>`, where having an "unknown" status could help clarify cases of "no date"/"n.d." etc. which are relatively common when describing archival material.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting 3 September 2021:

**Decision**:  add the optional `@status` attribute to `<date>`, with a single option:  “unknown”

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that `@status` with the (only) value "unknown" is now also available for `<date>` in both schemas.
