### ISSUE TITLE
@unit

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#255]
## Unit 

- add new optional attribute `@unit` to `<citedRange>` with data type _token_

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Topic: Assertion description in EAS](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/assertion)

## EAD3 Reconciliation

**Summary**: The type of measurement used to calculate the value provided in `<dimensions>`.
**Data Type**: token

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

- can be used to specify where the cited range of materials represents a page number, volume number, etc. 

**May occur within**: `<citedRange>`
**Data tpye**: token

## Example encoding
```
<citedRange unit="pagenumber">p. 1</citedRange>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Use `@unit` to document the format or unit that is specified in `<citedRange>`, for example page number ("pagenumber") or volume number ("volumenumber)".
**Data Type:** token

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@unit` is an optional attribute in `<citedRange>`
- Its data type is _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment]
@ailie-s Wondering, if example values that we provide with the TL should also follow the camelCase approach, i.e. "pageNumber" and "volumeNumber"? Especially here, where "page number" and "volume number" would be equally valid.

**Comment by fordmadox** [comment]
I'd suggest just using values like "page" or "volume".  

Here are the examples from the TEI documentation, although we do not have the ability to use those "from" and "to" attributes:

```
<citedRange>pp 12–13</citedRange>
<citedRange unit="page" from="12" to="13"/>
<citedRange unit="volume">II</citedRange>
<citedRange unit="page">12</citedRange>
```
