### ISSUE TITLE
@calendar

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#258]
## Calendar 

- add new optional attribute `@calendar` to `<date>`, `<fromDate>`, `<toDate>` with data type NMTOKEN

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation

**Summary**: System of reckoning time, such as the Gregorian calendar or Julian calendar. Suggested values include but are not limited to "gregorian" and "julian." Available in `<date>`, `<unitdate>`, and `<unitdatestructured>`.

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

**May occur within**: `<date>`, `<fromDate>`, `<toDate>`
**Data type**:  NMTOKEN

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** System of reckoning time, such as the Gregorian calendar or Julian calendar. Suggested values include, but are not limited to, "gregorian" and "julian." Available in `<date>`, `<fromDate>` and `<toDate>`.
**Data Type:** NMTOKEN

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@calendar` is an optional attribute in `<date>`, `<fromDate>`, and `<toDate>`
- Its data type is _NMTOKEN_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
