### ISSUE TITLE
@era

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#259]
## Era

- add new optional attribute `@era` to `<date>`, `<fromDate>`, `<toDate>` with data type NMTOKEN

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation

**Summary**: Period during which years are numbered and dates reckoned, such as CE (Common Era) or BCE (Before Common Era). Suggested values include "ce" and "bce". Available in `<date>`, `<unitdate>`, and `<unitdatestructured>`.

## Context
new EAC attribute

## Solution documentation: 
_Summary_ needed

**May occur within**: `<date>`, `<fromDate>`, `<toDate>`
**Data type**:  NMTOKEN

## Example encoding

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** Period during which years are numbered and dates reckoned, such as CE (Common Era) or BCE (Before Common Era). Suggested values include "ce" and "bce". Available in `<date>`, `<fromDate>` and `<toDate>`.
**Data Type:** NMTOKEN

**Comment by kerstarno** [comment]
Tested as part of Schema Team's schema testing:

- `@era` is an optional attribute in `<date>`, `<fromDate>`, and `<toDate>`
- Its data type is _NMTOKEN_

The above applies to both schemas, RNG and XSD. 

The attribute is ready.
