### ISSUE TITLE
Names control

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#26]
Topic of names control is discussed concerning the elements `<authorizedForm>` and `<alternativeForm>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> `<authorizedForm>`, `<alternativeForm>` are designed to qualify the forms of the name  contained in a `<nameEntry>` or the set of names contained in `<nameEntryParallel>`. This qualification currently obliges to indicate the rule according to which a name is qualified as authorized, parallel, or alternative. "Authorized" and "Alternative" should qualify in a straightforward way each name, and not in combination with rules. It should also be made possible, in a separate statement, to indicate the Institution responsible for the construction of each form of the name. 

[APEx, May 2013]

Comment by Anila Anjeli:
This highlights a persisting confusion among users on the meaning and use of these elements, with the need for a better control of names (in short: a clear distinction between 1) the source of the name, that is, the indication of the institution the form of the name comes from, 2) the rules applied for the construction of the name, and 3) the “status” authorized/alternative.)

Comment unknown: 
BETTER CONTROL of NAMES; source, form of the name comes from, rules, and the institution that formed the name. Proposed model, may apply more broadly to factual aspect.

Comment by TS-EAC so far: 
Names Control issue: all agreed about the need to revise how this is done; Daniel recommends that whatever solution is employed is extended to all of aspects of EAC that encode “factual description” (example of another, related problem:  right now, EAC-CPF doesn’t permit the encoding of competing existence dates, but scholars need to be able to encode this information, along with citation and provenance metadata regarding the statements).
name forms, people should look into a method for identifying multiple versions of names. Citation is proposed as another form for the dates.

## Context
see also #24

**Comment by karinbredenberg** [comment]
Yes, this is confusing when trying to explain. Not sure on a solution though.

**Comment by wisserk** [comment]
I think there are two issues here that may warrant separation: 

1) The use of authorizedForm and alternativeForm and the ability to identify the institution who has applied the rules that are identified in those elements. 
>>An attribute could be added to these elements that would allow for the identification of the institution establishing the name and its "status" as authorized or alternative. I believe that by identifying the rules, you are providing the justification for the determination of authorized or alternative (noting of course that the application of rules is subjective). 

2) The ability to provide a citation or assertion for any data field in order to track where that information has come from and based on what source to attribute the information. 
>>I'm not sure that this latter point needs to be limited to "factual description" only, but I do think that this is an important addition for us to consider.

**Comment by gerhardmueller** [comment]
I agree with Kathy. This should be separated. With regard to the first issue, I consider the identification of the rules as sufficient justification (RDA, etc.).

**Comment by gerhardmueller** [comment]
The tracking of modifications on element or attribute level seems to be very challenging. I do not sufficiently understand this matter.

**Comment by SJagodzinski** [comment]
Depending on our next team meeting discussion, I can separate no 2 from this ticket.

Anyway, as it seems to be confusing to use the elements `<alternativeForm>` and `<authorizedForm>`, how to go on?

To repeat Anilas comment above, we need to encode:
* name
* status (authorized/alternative)
* source of the name/institution where the name comes from
* rules for the names construction

Remembering my first contact with EAC-CPF, I would, at a first intention, nest the `<nameEntry>` and it's `<part>` elements within `<authorizedForm>`/`<alternativeForm>` (//nameEntryParallel/authorizedForm/nameEntry/part).

But having a `@status` attribute within `<nameEntry>` (//nameEntry @status) seems more useful at this time.

Encoding the rules might be more distinct by introducing a `"<rule>"` element within `<nameEntry>` (//nameEntry/rule), that might be named in a more proper way. 

Is the point about the source of the name linked or the same as #43?

**Comment by SJagodzinski** [comment]
This issue is mainly discussed in [Topic: Names](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/names).

**Comment by GuillaumeLestringant** [comment]
If I may offer an outside opinion, I am a bit wary about the whole notion of “authorized name”. Let me take an insightful example.

The southeasternmost region of continental France is called `Provence-Alpes-Côte d'Azur`. It is the legal name of the entity, as mentioned in the [décret n° 2016-1689](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033553530) of December 8th, 2016.

On the other hand, the region itself decided by the [deliberation 17-1166](https://deliberation.maregionsud.fr/docs/ASSEMBLEEPLENIERE/2017/12/15/DELIBERATION/D0V0Q.pdf) of December 15th, 2017, to rename itself `Région Sud Provence-Alpes-Côte d'Azur`.
This name is authorized, as it is extensively used in official material, including the website of the region, booths at events, etc. regularly even reducing it to `Région Sud` as in [this communiqué](https://www.maregionsud.fr/actualites/detail/savonniers-et-parfumeurs-solidaires-face-au-covid-19).
It is however forbidden to use it in legal documents, the only allowed name being the former.

Lastly, the National Commission for Toponymy [advocates](http://cnig.gouv.fr/wp-content/uploads/2015/03/CNT-site-collectivit%C3%A9s-fran%C3%A7aises.pdf) the name of the region to be `Provence-Alpes-Côte-d'Azur` (notice the hyphen between the two last words), following general rules of French typography. This name is authorized too, but absolutely nobody uses it: even the CNT itself uses the first form in part of its website.

So here is my point: a name can be “authorized”, but only in certain contexts, e. g. general public communication, while not in others, e. g. legal documents, or be authorized, but never actually used.

So my proposal would be to have a list of names (`nameEntrySet`), each name optionally pointing to one or several `conventionDeclaration` (or some other name) that contain which source documents the given name, and only one of the name entries may have the `preferredForm` attribute.
That way, it is up to the reader to determine whether a name is authoritative in a certain context or not, without the writer of the description assuming what authority is the most authoritative.

**Comment by kerstarno** [comment]
Hi @GuillaumeLestringant, 

thanks very much for your input. I think, we have something in mind, which will address your main concerns and also picks up on your point about `<conventionDeclaration>`. The TS-EAS EAC Team spoke about this during a meeting we had during the second week of March in Berlin. 

We are currently in the process of finalising the notes from this meeting and will - in due course - update GitHub accordingly. Please bear with us for a little longer.

**Comment by SJagodzinski** [comment]
@GuillaumeLestringant 
See our final solution in issue  #118. There will be the option to refer to a source, to a convention and to a maintenance event from each `<nameEntry>.` There is also the option ot refer to external vocabularies. The usage of `@localType` attribute provides more option to encode more detailled information.
