### ISSUE TITLE
Change data type NMTOKEN to token

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#266]
Change data type for all attributes from _NMTOKEN_ to _token_ in all EAS standards. 

## Creator of issue
1. @fordmadox 

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [x] Schema issue
- [ ] Tag Library issue
- [x] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
In general, I'd like not to use NMTOKEN either, since we are not providing a DTD of EAC-CPF (and have decided not to continue doing that with EAD3, at least), but we do have a lot of attributes that use NMTOKEN now, so I'm fine with changing vocabularySource to that datatype.

## Suggested Solution
Attributes with data type NMTOKEN: 
`@calendar` #258
`@certainty` #251
`@era` #259 
`@countryCode` #159
`@languageCode` #160 
`@languageOfElement` #151 
`@scriptCode` #161 
`@scriptOfElement` #152 

## Context
[NMTOKEN](https://www.w3.org/TR/xmlschema11-2/#NMTOKEN): any of the allowed characters can be the first character; NMTOKEN values can’t contain any whitespace
[token](https://www.w3.org/TR/xmlschema11-2/#token): sets of all strings after whitespace replacement

- derived from #147 [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/147#issuecomment-763188021)

**Comment by karinbredenberg** [comment]
@fordmadox  in the EAC-CPF meeting (2021-08-06) we concluded that we support this suggestion but its a need for the Schema team to decide and state that token is used in attributes with text. Also check the opinion with the EAD Team. When this decision is made its ok to implement in EAC-CPF and the EAC-CPF team needs to be informed so updates in the TL can be made.

**Comment by fordmadox** [comment]
Just noting this for discussion: https://lists.oasis-open.org/archives/ubl/200906/msg00012.html.

**Comment by SJagodzinski** [comment]
Token is used in attributes with text, implemented in EAC-CPF 2.0 schema and Tag Library.
