### ISSUE TITLE
Encode terms of a place role in multiple languages

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#268]
`<placeRole>`: It should be possible to encode terms of a placeRole in multiple languages (e.g. analog to otherEntityType).

## Creator of issue
1. Gerhard Müller
2. Staatsbibliothek zu Berlin

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add child element //placeRole/term (//placeRole = Wrapper Element)

### example:
```
<placeRole vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#placeOfActivity">
    <term languageOfElement="de">Wirkungsort</term>
    <term languageOfElement="en">Place of activity</term>
</placeRole>
```

## Context
It should be possible to encode terms of a placeRole in multiple languages (e.g. analog to otherEntityType).

#186

**Comment by kerstarno** [comment]
`<placeRole>` is repeatable to enable the use of multilingual terms. In my opinion, introducing `<term>` as a sub-element of `<placeRole>` would be overload.

```
<placeRole vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#placeOfActivity" languageOfElement="de">Wirkungsort</placeRole>
<placeRole vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#placeOfActivity" languageOfElement="en">Place of activity</placeRole>
```

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 4 Nov 2021: 

No change – use the repeatable <placeRole> element to encode in different languages.
