### ISSUE TITLE
Structure content of <descriptiveNote>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#269]
It should be possible to structure content of <descriptiveNote> with `<p>` or `<term>`.

## Creator of issue
1. Gerhard Müller
2. Staatsbibliothek zu Berlin

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add optional child element `<term>` as sibling of `<p>` to `<descriptiveNote>`.

### example:

```
<descriptiveNote vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson">
    <term languageOfElement="en">Earlier name of the person</term>
    <term languageOfElement="de">Früherer Name der Person</term>
</descriptiveNote>
```

## Context
Using vocabularies of an ontology to specify (in this case) the type of a name.

#109 , #110

**Comment by kerstarno** [comment]
If we were to enable such possibility, and I admit that I am not sure that `<descriptiveNote>` in its current definition is meant to do this, I think we need to consider this in the more general context of mixed content - especially in relation to EAD3 where one could do something like this with the following encoding (adapted to using the vocabulary attributes as introduced by EAC-CPF 2.0): 
```
<descriptiveNote>
  <p>
    <persName vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson">
      <part languageOfElement="en">Earlier name of the person</part>
    </persName>
    <persName vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson">
      <part languageOfElement="de">Früherer Name der Person</part>
    </persName>
  </p>
</descriptiveNote>
```
I don't mean to say that we should do it the EAD-way, I mainly want to point to the circumstance that this is a question of broader context. In EAC-CPF words, a similar encoding could also be reached by:
```
<descriptiveNote>
  <p>
    <span vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson" localType="persName" languageOfElement="en">Earlier name of the person</span>
    <span vocabularySource="GND Ontology" vocabularySourceURI="https://d-nb.info/standards/elementset/gnd" valueURI="https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson" localType="persName" languageOfElement="de">Früherer Name der Person</span>
  </p>
</descriptiveNote>
```
Provided, of course, we would acknowledge this use of `<span>` with `@localType` for " identifying some qualities of the words or phrases" (see TL definition in #227) and provided we would enable the vocabulary attributes with `<span>`.

**Comment by fordmadox** [comment]
I do not think this should be added to descriptiveNote.  Looking at the other examples, like this one:  

```
      <relation sourceReference="DE-611-29">
                <targetEntity targetType="corporateBody" vocabularySource="GND"
                    vocabularySourceURI="https://d-nb.info/gnd/"
                    valueURI="https://d-nb.info/gnd/1038776023">
                    <part>Jewish Cultural Reconstruction Inc.</part>
                </targetEntity>
                <dateRange>
                    <fromDate standardDate="1949">1949</fromDate>
                    <toDate standardDate="1952">1952</toDate>
                </dateRange>
                <targetRole vocabularySource="GND Ontology"
                    vocabularySourceURI="https://d-nb.info/standards/elementset/gnd"
                    valueURI="https://d-nb.info/standards/elementset/gnd#affiliation"
                    languageOfElement="de">Affiliation</targetRole>
                <targetRole vocabularySource="GND Ontology"
                    vocabularySourceURI="https://d-nb.info/standards/elementset/gnd"
                    valueURI="https://d-nb.info/standards/elementset/gnd#affiliation"
                    languageOfElement="en">Affiliation</targetRole>
                <descriptiveNote>
                    <p>Geschäftsführerin</p>
                </descriptiveNote>
     </relation>
```

It seems to me that we are missing a way to associate the term "Geschäftsführerin" with the targetRole.  If that's right, then I do not think that a note field is the way to do it.  I think this also relates to a few of the issues I had with creating the transformations from EAC 1 to 2, since not all of the "xlink" attributes could be mapped as is.  Nevertheless, I think we can adjust the current model slightly to work this out, without having to use descriptiveNote since, as a note field, it is semi-structured at best.

**Comment by fordmadox** [comment]
As for the https://d-nb.info/standards/elementset/gnd#EarlierNameOfThePerson example above, it would be helpful to know where exactly this is proposed to be utilized (I would assume nameEntry, but the example is not complete).  I do not think that we should put that type of controlled information into a note, but if it cannot be utilized as needed right now, then we should find a place to map those types of class names.

**Comment by kerstarno** [comment]
Associating the term "Geschäftsführerin" with `<targetRole>` as indicated in [one of the previous comments](https://github.com/SAA-SDT/eac-cpf-schema/issues/269#issuecomment-816714517) should be fairly simple:

```
<targetRole>Geschäftsführerin</targetRole>
```
Just because `<targetRole>` allows for the vocabulary attributes doesn't mean they HAVE to be there. One could also just use `<targetRole>` with straightforward text.

Apart from this, there actually is an according entry in the GND for "Geschäftsführerin", i.e. 
```
<targetRole vocabularySource="GND" vocabularySourceURI="https://d-nb.info/gnd/" valueURI="https://d-nb.info/gnd/7664670-1" languageOfElement="de">Geschäftsführerin</targetRole>
```
would also be possible.

**Comment by kerstarno** [comment]
As a follow-up to my [comment from April this year](https://github.com/SAA-SDT/eac-cpf-schema/issues/269#issuecomment-813844914), I'd like to add that the EAD team has decided to suggest removing the mixed content from elements such as `<abstract>`, `<p>`, etc. (in EAD) and to follow the EAC approach of only using `<reference>` and `<span>` with the latter being used with `@style` for formatting and with `@localType` for any other qualities of a word or phrase.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 4 Nov 2021:

No change. Highlight in Tag Library that `<descriptiveNote>` is to be used for descriptive, not structured, content.
