### ISSUE TITLE
Renaming elements

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#272]
Comments from the Archives and Records Association Section for Archives and Technology

Concerns:
`<placeEntry>` #166 
`<abbreviation>` #101 
`<script>` #99 

## Creator of issue
1. Archives and Records Association Section for Archives and Technology, UK

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Rename  new element names `<shortCode>` and `<writingSystem>`.

## Context
I was pleased to see that attention had been given to renaming elements to be clearer and more distinct, though the results were mixed, in my opinion. For example, I liked the renaming of `<placeEntry>` to `<placeNAME>.` Others I wasn’t so sure of, however. I didn’t like the change to `<shortCode>` from `<abbreviation>` - a poor replacement, I think. I wasn’t sure about `<writingSystem>` replacing `<script>` either. I realise these points may seem pedantic, but then data modelling is always going to raise semantic quibbles!

**Comment by kerstarno** [comment]
Can we go back to Archives and Records Association Section for Archives and Technology and ask for alternative terms, please? 

I find it tricky to restart the discussion on how to name things based on the feedback of 1 person without any suggestions for an alternative, when - as is the case here - two sub-teams of TS-EAS have previously discussed variations of names to end up with the ones that have now been suggested.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 4 Nov 2021:

Keep element names <shortCode> and <abbreviation> as they are. As there are no proposals or recommendations for other or better terms we keep the element names.
