### ISSUE TITLE
Better for corporate creators than individuals?

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#273]
Comments from the Archives and Records Association Section for Archives and Technology

Concerns: persons

## Creator of issue
1. Archives and Records Association Section for Archives and Technology, UK

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Context
It struck me that corporate bodies and places had fared better than individuals in terms of attention to attributes, linked data etc. I may be missing something here, but I did think that the concept of identity and the individual (specifically gender and identity) had not been addressed as it could have been.

**Comment by kerstarno** [comment]
As a note:

EAC beta included an element `<sex>` that had a required `@type` with the values "m" (for male), "f" (for female), and "u" (for unknown). We probably would want to consider the name of the element and especially the values, if we wanted to stick with a predefined value list, but maybe this could be a starting point. 

Possibly interesting to look at in this context: 
- https://eige.europa.eu/thesaurus/browse 
- https://www.hrc.org/resources/glossary-of-terms
- https://thesafezoneproject.com/resources/vocabulary/
or similar

**Comment by SJagodzinski** [comment]
EAC-CPF meeting 3 September 2021:

- `<legalStatuses>`/`<legalStatus>` is actually the only specific element due to the entity type corporate body; all other elements are general element that fit to all entity types
- `<localDescriptions>`/`<localDescription>` was meant to enter further information like nationality, and gender, religious or ethnic affiliation
- some of these information are not allowed to capture for data protection and there might be also cultural differences in the archival description
- **Decision**:  Add a new demographic element grouping, which will have term, descriptiveNote, etc.  Need to name the new plural/singular grouping.  Keep `<localDescriptions>`.
