### ISSUE TITLE
@detailLevel

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#274]
## Level of detail

- add new optional attribute `@detailLevel` to `<control>` with limited values minimal, basic, extended

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
 Why not make "level of detail" an authorized attribute again? #226 

## EAD3 Reconciliation
new EAC attribute

## Context
- new EAC attribute
- has been an attribute in EAC beta, cf [TL](https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2004v01.html#a.detaillevel)

## Solution documentation: 
_Summary_ needed

-  information about the level of detail of the entitys description 

**Optional within**: `<control>`
**Values**: minimal, basic, extented

## Example encoding

**Comment by fordmadox** [comment]
The new branch is ready for testing:  https://github.com/SAA-SDT/eac-cpf-schema/tree/issue/226

**Comment by fordmadox** [comment]
This can also be tested in our regular development branch, as well.

**Comment by kerstarno** [comment]
As a note: 
The EAD team discussed this during their meeting on 17 September and the general feedback has been that we need to make sure we can describe and explain the use cases for the attribute and its three possible values sufficiently and clearly. There especially were concerns with regard to the question whether the level of detail refers to the descriptive data provided in the EAS file or to the way the information is encoded. 

Furthermore, the EAD team will check against DACS and MARC to review the terms used there and to potentially come up with mappings for these terms (https://saa-ts-dacs.github.io/dacs/08_part_II/06_chapter_13/05_level_of_detail.html and https://www.loc.gov/marc/bibliographic/bdleader.html (17 - Encoding level)). This will be picked up again during the next EAD team meeting on 15 October. Should this have any impact on the terms used as values for this new attribute, the EAD team will provide according feedback in this issue.

**Comment by kerstarno** [comment]
Following up from my previous comment:
The EAD team discussed the addition of `@detailLevel` again during their meeting on 15 October and also looked at values uses in DACS and MARC. Reviewing the options available, the EAD team agrees with the suggested values "minimal", "basic", and "extended" and will work on a mapping suggestion towards the values of DACS and MARC, which could become part of the Best Practices Guide.

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that `@detailLevel` is now available as optional attribute of `<control>` in both schemas and can have the values "minimal", "basic", or "extended".
