### ISSUE TITLE
@xml:lang: adopt EAD 3 solution

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#28]
Adopt EAD 3 solution for the attribute `@xml:lang`: remove xml namespace, add `@lang` to every non-empty element, make all elements with `@lang` repeatable

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
1. remove xml namespace, see also #27
2. add `@lang` to every non-empty element (= elements containing text) to encode the language of the elements content
3. remove `@lang` from wrapper elements and elements not containing text
4. make elements with `@lang` repeatable

## Context

> All text elements with xml:lang should be repeatable due to multilingualism of EAC-CPF files and to state different languages. Please change following elements to repeatable elements:
> `<placeRole>`
> `<term> `
> `<event>` in `<chronItem> `

[APEx, May 2013]

Comment Anila Anjeli:
Needs careful consideration. However there is a problem of schema design, namely with regard to `<term>`. A solution might be to make `<term>` and `<placeRole>` repeatable only in case when multiple xml:lang are needed.

Comment unknown: 
ENDORSE the principle here; exact mechanism. Someone needs to do a comparison; needs further research.

Comment TS-EAC so far: 
The principle is endorsed, but the implementation may need to be reviewed.  Already added in EAD3?
`@xml:lang` containing elements should be repeatable? EAD3 did a review on the subject to address this. In things such as place name... Daniel notes that this is good in theory but should looked at. Maybe look at EAD3.

> Why is `@xml:lang` used with elements that – themselves – are not PCDATA, ie do not contain any content for which the language would need to be specified? It seems to be sufficient to have `@xml:lang` with their subelements, that actually would contain text. Furthermore, it also could be technically troublesome if there (by chance) would be different values e.g. for `@xml:lang` with `<descriptiveNote>` and for `@xml:lang` with the `<p>` tags wrapped within.

 [Kerstin Arnold, July 2012]

Comment unknown: 
POSSIBLY an issue of best practice guidelines; using `@xml:lang`, xml namespace, W3C provides guidance; bring in alignment with EAD3, move away from xml namespace to provide more flexibility. If we give a recommendation in the tag library, these should be inline with what is expressed. Revisit this in light of EAD3.

Comment TS-EAC so far: 
Possibly an issue for best practices.  Recommendation to investigate this issue further and report back.

**Comment by karinbredenberg** [comment]
All these reltated issues needs to be checked and one solution aligned with EAD3 suggested.

**Comment by karinbredenberg** [comment]
This is two issues. One is the xml:lang attribute the other one is the repability of elements having the attribute and which eleemnts should have it. Would make it a principal discussion first and then phase-2.

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
Reworking language and script attributes touchs different issues, eg namespace.
Will be moved to phase 2, revision, because it is not suitable for a technical update.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=347935402&range=B26)

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020 resp. comment in the notes document:

@regineheberlein wrote:
> For accessibility purposes (screen readers), we should use the 2-letter codes from the IANA registry wherever possible (see WCAG)

@fordmadox wrote:
> Can you say more about that, and/or point to further documentation? I'm not very familiar with IANA (which looks to reuse ISO 639 codes, but preferences the two-letter ones when those are available). I just had to check how this is handled in the EAD3 schematron, and it's set up so that you have the choice of using ISO 639-1, 639-2b, or 639-3 (with a default of 639-2b). I believe that IANA / IETF is a combo of those, though... but that that standards also combine language codes with script codes, and other codes, for even further specificity. e.g. sr-Cyrl-BA but right now in EAD3, you could only specify those first two codes.

> Need to investigate more, but it seems to me that using IANA as the default (as EAC tag library suggests that it already does) would be the better way to go than using only one ISO-639 at a time as per EAD3.

@karinbredenberg wrote:
> I have a feeling there is no available file of any kind to use to get the same sort of checking as there are with the iso ones. But needs investigation.

@regineheberlein answered:
> Sorry, just catching up with this after returning to work. https://www.w3.org/International/questions/qa-choosing-language-tags
> https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by SJagodzinski** [comment]
**TS-EAS Chicago meeting, 4 August 2020:**

Remove xml namespace but keep the attributes needed.

`@xml:lang` becomes `@languageOfElement` with data type NMTOKEN.

**EAC-CPF Chicago meeting, 27 July 2020:**

Allow `@languageofElement` [...] on all non-empty elements (the EAD 3 way).

**EAC-CPF-EAD Joint meeting, 8 June 2020:**

Rename `@lang` and `@script` to `@languageofelement` and `@scriptofelement` to make it clearer what they refer to.
