### ISSUE TITLE
Language codes: adopt EAD 3 solution

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#29]
Adopt EAD 3 solution for usage of language codes in the attribute `@xml:lang`/`@lang`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Adopt EAD 3 solution  for usage of language codes in the attribute `@xml:lang`/`@lang`:

> Content of the attribute should be a code taken from ISO 639-1, ISO 639-2b, ISO 639-3, or another controlled list, as specified in the langencoding attribute in `<control>`. 

Without further adaptions in EAC-CPF, the controlled list can be defined within `<conventionDeclaration>`.

## Context
> The new TL recommends two different language codes for xml:lang (IANA) and languageCode (ISO 639-2). EAD (current & revised) and EAG 2012 use ISO 639-2b for language attributes. 

[APEx, May 2013]

Comment Anila Anjeli:
As having been for a long time a member of the international committee for language coding (JAC ISO 639), I could say that what IANA recommends is perfectly compliant with ISO 639-2. In this respect one might say that for IANA there are not two different codes. But ISO 639-2 – and others -1, -3 are the basis of the W3C recommendation as supported by IANA. (In other terms ISO 639-2b might be one possible component part of a IANA language subtags, which also contains ISO 639-1 and ISO 639-3, as well as those for scripts and regions). 
Anyway this issue is a bit complicated and it will necessarily be re-discussed within the framework of the revision of EAD. And EAC-CPF will surely adopt the same policy.

Comment TS-EAC so far:
proposal accepted

**Comment by karinbredenberg** [comment]
Agreed!

**Comment by karinbredenberg** [comment]
For me this is a Phase-2 and needs to be dealt with the same way as Issue #14

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
Reworking language and script attributes touchs different issues, eg namespace.
Will be moved to phase 2, revision, because it is not suitable for a technical update.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=347935402&range=C26)

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Following the conversation in Berlin, the EAC team confirmed to keep `@transliteration` and have it along with `@lang` and `@script.`

**Comment by SJagodzinski** [comment]
See solution in #28
