### ISSUE TITLE
<eac-cpf>: Remove XLink namespace

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#3]
Remove the XLink namespace from EAC-CPF

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Remove the XLink namespace from EAC-CPF. 

## Context
Following EAD 3 schema.
> This was one of the least noticeable but most important changes we made in EAD3. Using the xlink namespace brings no functionality and lots of validation headache. Important to remove it from EAC to support interoperability and reducing needless complexity.

 [@rockivist ]

**Comment by karinbredenberg** [comment]
Agreed! Align with EAD3!

**Comment by karinbredenberg** [comment]
Phase-2

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
Changing the namespace has a huge impact on the schema.
Will be moved to phase 2, revision, because it is not suitable for a technical update.

**Comment by SJagodzinski** [comment]
related to #27

**Comment by kerstarno** [comment]
Just as a note - the Shared Schema subteam has been discussing a common approach to XLink (and XML) namespace as well. You can find our thoughts here: [SAA-SDT/SharedSchema#1](https://github.com/SAA-SDT/SharedSchema/issues/1).

**Comment by SJagodzinski** [comment]
List of xlink-Attributes:
- xlink:type
- xlink:href
- xlink:role
- xlink:arcrole
- xlink:title
- xlink:show
- xlink:actuate

**Comment by SJagodzinski** [comment]
Team discussion: 
Removing the namespace simplifies the schema and xml handling.
There is no specific EAC-CPF requirement in respect with linking. The team agrees on removing the namespace.
There is a need to define linking attributes the same way, with same functionality, but not using the same attribute names. The language needs to be consistent trhough the schemas (TS-EAS).

**Comment by SJagodzinski** [comment]
EAC-EAD-Schema joint meeting, 28 Jan 2020:

Fully agreed to **remove xlink namespace.**
