### ISSUE TITLE
@scriptCode: remove and adjust tag library for @xml:lang/@lang

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#30]
Remove attribute `@scriptCode` and adjust the Tag Library description of `@xml:lang` 

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> Remove `@scriptCode `and adjust the Tag Library description of `@xml:lang` to reflect that it is to be constructed using values from  http://www.iana.org/assignments/language-subtag-registry 
> And the syntax is specified here: http://www.w3.org/International/articles/language-tags/ 

[@dpitti , August 2012, on the list]

Comment Silke Jagodzinski:
This proposal does not correspond to the EAD 3 solution. 
Here we have 2 attributes `@script` and `@scriptcode` within the element `<script>`, also `@scriptencoding` within the element `<control>`.

## Context
The current encoding of languages in `@xml:lang` is from the ISO 639-2 (alpha three codes). Daniel says that the two alpha codes should be used as the W3C specification specifically specifies that the values must come from the [IANA list](http://www.iana.org/assignments/language-subtag-registry).
 
That in itself is not a problem, simply use the IANA registry for language codes. But the problem goes beyond this in the `@xml:lang` also accommodates script and country codes (e.g., French as spoken is Canada). The reason this is a problem is that EAC-CPF also has a `@scriptCode` used in the same context as `@xml:lang`, based on the misunderstanding of `@xml:lang`. 

Comment Anila Anjeli:
Given the information on IANA registry for the assignment of language subtags that you refer to http://www.iana.org/assignments/language-subtag-registry, there is a significant development adopted by W3C on this issue http://www.w3.org/International/articles/language-tags/, the consequence of which is:

- applying alpha-2 codes for languages for which such a code exists on behalf of alpha-3 codes (e.g. 'en' rather than 'eng')

- bringing together in `@xml:lang` information about language, script, region (rather than country), and other language variant information or locally applied code (e.g. 'zh-Hant-HK' (Traditional Chinese as used in Hong Kong)), explained in the above W3C cited  document in the section language-extlang-script-region-variant-extension-privateuse 
However, I do not think the `@scriptCode` in EAC-CPF was created on a basis of misunderstanding of `@xml:lang`. It intentionally separated language from script as do other schemas. As EAC-CPF is not the only XML schema implementing separately language tags (using the ISO 639-2 Alpha three codes, or ISO 632-1 Alpha-2 codes) and script tags (using the ISO 15924 four-letter script codes). I just had a look at MADS and it has the `@script` attribute separately from `@xml:lang`. 
Of course we might shift to the most advanced technological stage of tagging languages and scripts. I do not contest the validity and ingenuity of the system, but however, I wonder whether this information is broadly known by all who build W3C compliant XML implementations. What about legacy data?

see also #29 , #28

**Comment by karinbredenberg** [comment]
Consolidation with EAD3 needs to be taken into account.

**Comment by karinbredenberg** [comment]
Phase-2 and in cojunction with Issiues #14 and #29

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
Reworking language and script attributes touchs different issues, eg namespace. 
Will be moved to phase 2, revision, because it is not suitable for a technical update.

**Comment by SJagodzinski** [comment]
Decision of [EAC meeting, 24 April 2020](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/20200424_EAC-CPF_minutes.pdf):

1. Confirmation to rename `<script>` to `<writingSystem>.`
2. Keep both attributes `@scriptCode` and `@script` as optional attributes. Change occurance of `@scriptCode` from required to optional.
3. Rename language and script attributes `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement.`
4. Change occurance of `<writingSystem>` within `<languageUsed>` from required to optional.

So, request to remove `@scriptCode` is not accepted.
