### ISSUE TITLE
<fromDate>, <toDate>: add @localType

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#31]
Add attribute `@localType` to the elements `<fromDate>` and `<toDate>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add attribute `@localType` to the elements `<fromDate>` and `<toDate>` to specify dates

## Context
Both TS-EAD and TS-EAC will want to give some thought to the typing of dates and think about the feasibility of having a specific attribute to address this. 

Example encountered in processing records for SNAC:

> 1836- fl. 1867. In other words, the date of birth is known, but not the date of death, and in lieu of the date of death, the last date the person was known to be active is given. For processing purposes (date searching in particular), we need to be able to specify that the first date is a date of birth and the second an active date.

 [@dpitti ]

`@localType` is available on `<existDates>`, `<dateRange>`, and `<date>`, but not `<fromDate>` and `<toDate>`. 

Comment TS-EAC so far:
`@localType` in `<fromDate>`/`<toDate>` approved. One of them should be required. But modeling date stuff may be an issue.

**Comment by karinbredenberg** [comment]
Follow EAD3.

**Comment by SJagodzinski** [comment]
EAD 3 has an optional `@localtype` in `<fromdate>` and `<todate>`.
Adapt schema and tag library accordingly.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
