### ISSUE TITLE
@standardDate, @standardDateTime: remove regex pattern

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#33]
The attribute `@standardDate` [m.data.standardDate] is defined with a maximum year 2099. Remove regex pattern and follow EAD 3, also allows other values.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Remove regex pattern from `@standardDate` and `@standardDateTime`, allow for different date normalization schemes.

## Context
The attribute @standardDate [m.data.standardDate] is defined with a maximum year 2099. To add unknown or still existing years it could be helpful to use 2199.
See also #32

**Comment by karinbredenberg** [comment]
And then maximum becomes 2199. Isnt it another way to write the regex if its really needed?

**Comment by SJagodzinski** [comment]
So, our question is, if we need a maximum year at all or if we just define 4-digit numbers and avoid '0000'.

**Comment by karinbredenberg** [comment]
Looking at it again, is a regex pattern really needed? We need to really check the date and datetime types in XML and see what is allowed.

**Comment by regineheberlein** [comment]
Discussion: Change to 9999 for phase 1, revisit fundamental considerations (alignment with best practices on other tags; prescriptive v. non-prescriptive approach to data values) for phase 2.

**Comment by fordmadox** [comment]
You can see how I've handed this in the schema for the first pass here:   https://github.com/SAA-SDT/eac-cpf-schema/commit/95ab39b43e972babdb1d007199022c88d3f58f30

Basically, this just means that  attribute values with years greater than 2999 will now be valid, but we don't lose the ability to restrict values like "300u" from the standardDate and standardDateTime attributes.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
