### ISSUE TITLE
<date>: best practice

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#34]
Find and describe best practice for uncertain dates in `<date>`, `<toDate>`, `<fromDate>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> I have been asked for a solution to put a textual date in a EAC-CPF record like: “ca. 1868” or: “beginning 19th century”. I assumed that EAC-CPF would have something like EAD for that: `@certainty`, but to my surprise this is not supported. 
> Do you know how to deal with this (other than adding a descriptive note to a datarange)? 

[@cannedit ]

**Comment by karinbredenberg** [comment]
Reconciliation with EAD needed.

**Comment by ailie-s** [comment]
Outcomes of discussion in Austin, August 2019:

1. Add optional `@certainty` attribute (from EAD3) to `<date>`, `<fromDate>` and `<toDate>` 
Example:
```
<dateRange>
    <fromDate standardDate="1762" certainty="circa">c.1762</fromDate>
    <toDate standardDate="1814" certainty="circa">c.1814</toDate>
</dateRange>
```

2. Allow for the optional use of EDTF (https://www.loc.gov/standards/datetime/edtf.html) integrated in ISO 8601-2019, to qualify a date as uncertain (?), approximate (~) and uncertain and approximate (%).
Example:
```
<dateRange>
    <fromDate standardDate="1762?">c.1762</fromDate>
    <toDate standardDate="1814?">c.1814</toDate>
</dateRange>

```
