### ISSUE TITLE
Consolidate relations part following EAD 3

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#35]
follow EAD 3 and consolidate `<cpfRelation>`, `<resourceRelation>`, and `<functionRelation>` into `<relation>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

> Others will disagree with me, but I think EAD 3 improves on `<relations>` in EAC-CPF by consolidated the three relation elements into one. 

[@rockivist ]

**Comment by karinbredenberg** [comment]
Consolidation needed! Right now working with swedish profiles of both EAD3 and EAC-CPF and the different availability of elements in EAC-CPF relations and if both looked they same it would make it easier to explain the two standards.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1548633886&range=C403)

**Comment by SJagodzinski** [comment]
Issue solved with our decision at the EAC-CPF Berlin meeting, 10 March 2020, cf [notes](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2020/f2f-meetings/Berlin/20200310_EAC-CPF_minutes.pdf).

See also the final [topic paper on relations](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/relations/Topic_relations_20200327.pdf).
