### ISSUE TITLE
value list for <agentType> align with EAD3

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/eac-cpf-schema#40]
## Creator of issue

1. Karin Bredenberg
2. TS EAS
3. karin.bredenberg@riksarkivet.se
4.

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: Valuelist for <agentType> is could also use EAD3 value unknown.

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by SJagodzinski** [comment]
The question for terms for the content/value list of the element is addressed in #7  . The value "unknown" is listed here.

I close this issue #40 because of redundancy with #7.
