### ISSUE TITLE
General overlook on value list for attributes align with EAD3

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/eac-cpf-schema#42]
## Creator of issue

1. Karin Bredenberg
2. TS EAS
3. karin.bredenberg@riksarkivet.se
4.

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Reconciliation for attribute value list towards EAD3 would be good.

## Reporting a bug

* Text:

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by karinbredenberg** [comment]
Working with Swedish adoptions I can see that at least I would benefit from having lists looking the same when explaining them since they are used for describing the same attributes.

**Comment by SJagodzinski** [comment]
Done within the process of EAC-CPF revision and solved with EAC-CPF 2.0
