### ISSUE TITLE
<rightsdeclaration>: add to control

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#46]
Add the element `<rightsdeclaration>` as child to `<control>` and following EAD 3 update.

## Creator of issue

1. Adrian Turner
2. OAC/Calisphere Data Services Manager
3. California Digital Library
4. adrian.turner@ucop.edu 

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
I'd like to suggest incorporating an additional element within <control>, for indicating a human- and machine-readable rights and/or licensing indicator pertaining to use and re-use of the EAC-CPF record itself.  The indicator could be a narrative statement and/or URI. 

It would be helpful for users or consumers of EAC-CPF records (particularly within large-scale aggregations such as SNAC) to have clear information as to what they can or can't do with the records.  This could parallel this particular revision to EAD3: https://github.com/SAA-SDT/EAD3/issues/506

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
This request is under development for EAD 3 update at the moment, vgl. https://github.com/SAA-SDT/EAD3/issues/506. EAC-CPF will watch EAD 3 development, comments and decision and is going to adapt this solution for the `<control>` area, if it is accepted for EAD 3.

**Comment by eboudreau** [comment]
I am creating this as a new optional, repeatable element within <control>. If we follow EAD3 the element can contain abbr, citation, and descriptiveNote. For attributes EAD3 allows audience, encodinganalog, id, lang, localtype, and script. EAC-CPF doesn't have audience or encodinganalog, but it does have xml:id, xml:lang, localType, and scriptCode. Should we include all four of these?

**Comment by SJagodzinski** [comment]
According to the current draft of the [updated [rng & xsd] files](https://github.com/SAA-SDT/eac-cpf-schema/tree/phase-1-revision-2018), the element `<rightsDeclaration>` is defined as follows:

May contain: `<abbreviation>`, `<citation>`, `<descriptiveNote>`
May occur within: `<ontrol>`
Attributes: `@xml:id`, `@xml:lang`, `@localType` - all Optional
Availability: Optional, Repeatable

So, no scriptCode needed.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
