### ISSUE TITLE
<publicationStatus>: add value for restricted content

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#49]
Add the new value "published" for the restricted content of the element.

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

Add the new value "published" for the restricted content of the element.

## Context

Derived from #6 . Issue #6  is split into 2 issues, whereas #6 remains for eac-cpf revision phase 2.

**Comment by eboudreau** [comment]
Should the Description of this element be updated to indicate when the new value "published" should be used, or should we remove existing guidance for when to use each value? Current language is: 

_The current publication status of the EAC-CPF instance may be specified in the publicationStatus element. If according to local practice the instance is still in the process of being approved for publication, the value should be "inProcess," while if approved for publication, the value should be "approved."_ 

We could simplify it to just:
_The current publication status of the EAC-CPF instance may be specified in the publicationStatus element._

**Comment by SJagodzinski** [comment]
I agree with the simplification:

_The current publication status of the EAC-CPF instance may be specified in the publicationStatus element._

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
