### ISSUE TITLE
<maintenanceStatus>: element content should become attribute value

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#5]
The restricted content for element `<maintenanceStatus>` should become restricted value for the new attribut `@value`. Add new value "deletedMerged".

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Create new attribute `@value`. 
The restricted content for element `<maintenanceStatus>` should become restricted value for the new attribut `@value`. The content for `<maintenanceStatus>` is defined: revised, deleted, new, deletedSplit, deletedReplaced, cancelled, derived.
In line with EAD 3 add new value for `@value`: deletedMerged.

## Context
Following EAD 3 schema.

> allows for element content to be in a different language

 [@rockivist]

**Comment by karinbredenberg** [comment]
Agreed! Align with EAD3.

**Comment by karinbredenberg** [comment]
For a Phase-1 I would add the new value and in phase-2 transform to align with EAD3.

**Comment by wisserk** [comment]
I wonder if this suggestion would open up the possibilities of contradictory or conflicting values in the same element (e.g., the value indicates one status, the content of the element presents another).

**Comment by SJagodzinski** [comment]
Meeting 3 May 2019 outcome:

The risk to get conflicting information within value and content is already existing in EAD3 and it seems to be acceptable for EAC-CPF, too. 

Defining optional text as data type for `<maintenanceStatus>` allows users to give extra information about the maintenance status or to add content in different languages

To follow EAD 3, add the required attribute `@value` with following values:
revised, deleted, new, deletedsplit, deletedmerged, deletedreplaced, cancelled, derived

**Comment by SJagodzinski** [comment]
Solved with #84 : element removed and new mandatory attribute `@maintenanceStatus` with restricted values (revised, deleted, new, deletedsplit, deletedmerged, deletedreplaced, cancelled, derived) added to `<control>` in EAC-CPF 2.0.
