### ISSUE TITLE
RNG version of schema does not define xml:id attributes properly

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eac-cpf-schema#52]
See:  https://github.com/SAA-SDT/eac-cpf-schema/blob/master/cpf.rng#L1890-L1898

In XML, attributes with an ID data type must be unique within the XML document.  However, if an EAC file is associated with the RNG schema (rather than the EAC XSD schema, which does use the correct data type), then the following is valid since the data type for the xml:id attribute is specified as NCName:

```
    <control>
        <recordId xml:id="testing-uniqueness-123">recordId</recordId>
        <otherRecordId xml:id="testing-uniqueness-123"/>
        ...
    </control>
```

I have a patch for this issue, which I will submit as a pull request later this week. 

Also, I think that this update should be considered for the 2018 minor revision.

**Comment by fordmadox** [comment]
Just a note that I've added a new branch to address this issue.  See https://github.com/SAA-SDT/eac-cpf-schema/commit/4bec3c9f36509fabb23ae4bcb003c47631b28108#diff-766fe0fc6ccf48a646fa57dd839dcd28 

Despite what I type previously, though, I'm not sure if this issue should be rolled into the 2018 minor revision, or perhaps be handled as part of a separate EAC/EAD "schema harmonization" process.

**Comment by SJagodzinski** [comment]
Added to the next virt. meeting agenda

**Comment by SJagodzinski** [comment]
Meeting 7 July 2018 outcome:

Changing RNG schema accordingly is bug fixing and is going to be included in the 2010_revised schema (minor update 2018).

Users and the community will be informed with the call for comments. If there is no feedback or feedback shows that nobody is using RNG schema for EAC-CPF, this bug should be fixed with the update.

**Comment by fordmadox** [comment]
I'll need to test my initial patch a bit more, but once I've had time to do that I will merge it with the rest of the updates.

**Comment by fordmadox** [comment]
Just to follow up:  my initial patch was not a satisfactory one.  I'll try to find some time to fix this correctly, but it's likely that we will need to revisit this issue with the next revision.

**Comment by fordmadox** [comment]
Just a note that I am closing this issue now that:

- the definition has changed (in EAC 2.0) to use the ID datatype:
- we will add a Schematron rule to enforce uniqueness of ID attributes, since that is not enforced by RNG in the same way as the XSD standard.
