### ISSUE TITLE
<otherRecordId>: definition

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#54]
(Re)define `<otherRecordId>` in context of the (re)definition of `<recordId>`  (#53) and `<entityId>` (#55) 

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
(Re)define `<otherRecordId>` in context of the (re)definition of `<recordId>` and `<entityId>`, if necessary

## Suggested Solution
Widen the scope for this element (cf. usages of this element in projects like SNAC, ARDC Party Infrastructure, etc.)

Two different uses for this element:
* alternative record identifiers for the same EAC-CPF instance as stated in the description of `<otherRecordId>` “These might include the identifiers of merged EAC-CPF instances representing the same entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance.”
* different IDs, each identifying each of the authority records aggregated within the EAC-CPF instance, in case of aggregation.

**Schema**: create an appropriate attribute/element for the provenance (source repository/system) of the `<otherRecordId>` = element or attribute that would allow to include the identifier of the institution.

**Tag Library**: the connection is not reflected between this record and another record that describes the same entity in another system.

## Context
Derived from #25. Issue #25 is split into 3 issues and is closed.

Tag Library: 
> Alternative record identifiers that may be associated with the EAC-CPF instance. 

> Description and Usage:
> An element in `<control>` used to encode record identifiers that are alternatives to the mandatory identifier in `<recordId>`. These might include the identifiers of merged EAC-CPF instances representing the same CPF entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance.
The localType attribute can be used to identify the kind of institution or service responsible for each associated record identifier if not the same as that given in the `<maintenanceAgency>` element for this EAC-CPF instance. 

Comments APEx, May 2013:
`<otherRecordID>`: The `@localType` attribute of `<otherRecordId>` can be used to identify the kind of institution or service responsible for each associated record identifier. The `@xml:id` attribute of `<otherRecordId>` serves to name specific elements in an EAC-CPF instance. 
Question: How to identify the archival institution that has created an alternative record?

**Comment by SJagodzinski** [comment]
The Archives Portal Europe is using the element `<otherRecordId>` in the following way:

>  In case, existing EAC-CPF instances are delivered to the Archives Portal Europe and are
converted to apeEAC-CPF, this conversion would ensure, that the original `<recordId>` in
the content provider’s system is kept by transforming it to `<otherRecordId>` with the
localType=”converted”. As `<otherRecordId>` is repeatable, it would in parallel be possible
to also include existing `<otherRecordId>` elements from the original files, which might be
useful for the question of re-directing to content providers’ systems.

> For files exported from local systems to the Archives Portal Europe, there’d be a check
on the `<recordId>` in these exports being unique and compliant to the identifiers’ format
as chosen for the Archives Portal Europe. When both these requirements are met, the
identifier as delivered in `<recordId>` would be kept. When the test on one of these
requirements should be failing, the same principle would apply to these files as to the
ones being converted – the original `<recordId>` would be moved to `<otherRecordId>` and
an identifier for the use in the Archives Portal Europe would be created as new content
for `<recordId>`.

See: [State of the art report on EAC-CPF and recommendations for implementation in Archives Portal Europe](http://www.apex-project.eu/images/docs/APEx_D4.4_SOTA_EAC-CPF_final_version_01.pdf), chap 4.1.2, p 54.

Examples for encoding of `<otherRecordId>` in APE:
* Belgium
```
<recordId>eac-BE-A0500_000024_DUT</recordId>
<otherRecordId>eac-BE-A0500_000024_FRE</otherRecordId>
```
File exported from a local system with unique `<recordId>`. `<otherRecordId>` is used for the ID of EAC-CPF intance with a French description of the same entity, which might be also ingested in the portal.

* France:
```
<recordId>eac_HU-00000001443_FRAD019_EAC001212</recordId>
<otherRecordId localType="localIDconverted">FRAD019_EAC001212</otherRecordId>
```
File exported from a local system using the `<recordId>` with prefix containing formats type and agency code. `<otherRecordId>` is used for the ID of EAc-CPF intance within the French system. Here the question rises, where to encode the institution responsible for the "alternative record".

**Comment by gerhardmueller** [comment]
To add to @SJagodzinski: for the Kalliope Union Catalog we have chosen a similar approach 
`<otherRecordId localType="DE-588">(DE-588)11850391X</otherRecordId>`
where localType is an identifier or name of the data provider/provenance, in this case localType="DE-588" is the ISIL of the Integrated Authority File (ex.: [http://kalliope-verbund.info/de/xmleac?eac.id=11850391X](http://kalliope-verbund.info/de/xmleac?eac.id=11850391X))

**Comment by fordmadox** [comment]
I checked the Connecting the Dots project, and the only examples of otherRecordId in that project mirror the examples in the EAD3 tag library (as well as one of the examples of how otherRecordId is used in the Kalliope Union Catalog).  

Here's one example, for the record about "Burney, Charles, 1726-1814":

`        <recordId>FHCL.HOUGH:8822109</recordId>`
`        <otherRecordId localType="url">http://nrs.harvard.edu/urn-3:FHCL.HOUGH:8822109</otherRecordId>`

The record also lists the LCNAF record as a "source," where the other record identifier URI can be accessed via the href attribute:

`            <source xlink:actuate="onRequest" xlink:href="http://lccn.loc.gov/n50032067"
                xlink:show="new" xlink:type="simple">
                <sourceEntry>Library of Congress Control Number: n 50032067</sourceEntry>
            </source>`

Were the LC authority record not used as a source, though, then I'm not sure how that project would have decided to record external record identifiers.   entityId (or identityId) could be the best place (if it's agreed that the authority record ID used by systems like VIAF represents the entity and not the authority record???), but right now there is not a good way to record a URI on any of those elements (entityId, recordId, or otherRecordId).  It can be done, as the examples prove, but I think that I'd prefer that the schema to enforce the use of attributes for storing URIs.

Last, were this record ingested into SNAC in order to enhance http://snaccooperative.org/view/75601210, then I think that's where more discussion would need to happen.  How is this handled in APE, Kalliope, etc.?  Not only is the record ID worth considering, but even more importantly, how would you handle the statements listed, how they're cited, etc.?  But citations and such are another matter altogether, albeit a crucial one for the major revision, I think.

**Comment by gerhardmueller** [comment]
To add to my previous and Marks comments:

For the Kalliope Union Catalog, we deal with various identifier from different systems, but especially authority records. However, there is in this context - at least from my current understanding - no difference between a local or authority record describing an entity.

`<recordId>300755-8</recordId>` (ex.: [Suhrkamp Verlag, http://kalliope-verbund.info/gnd/300755-8 ](http://kalliope-verbund.info/gnd/300755-8) ) 

This identifier is the primary identifier to identify the record describing the entity Suhrkamp Verlag in the Kalliope Union Catalog. 

There are, however, additional identifier from different systems:

```
<otherRecordId localType="PPN">003007553</otherRecordId>
<otherRecordId localType="DE-611_URI">http://kalliope-verbund.info/gnd/300755-8</otherRecordId>
<otherRecordId localType="DE-588_URI">http://d-nb.info/gnd/300755-8</otherRecordId>
<otherRecordId localType="DE-588">(DE-588)300755-8</otherRecordId>
<otherRecordId localType="DE-101">(DE-101)003007553</otherRecordId>
<otherRecordId localType="VIAF">150718921</otherRecordId>
<otherRecordId localType="WikiData">Q301609</otherRecordId>
<otherRecordId localType="LCAuth">n86825104</otherRecordId>
<otherRecordId localType="LCAuth_URI">http://id.loc.gov/authorities/names/n86825104</
<otherRecordId localType="GNDinvalidId">(DE-588)1086213432</otherRecordId>
<otherRecordId localType="GNDinvalidId">(DE-588)1086110498</otherRecordId>
<otherRecordId localType="GNDinvalidId">(DE-588)1072892618</otherRecordId>
<otherRecordId localType="GNDinvalidId">(DE-588)108523696X</otherRecordId>
<otherRecordId localType="GNDinvalidId">(DE-588)4058533-5</otherRecordId>
<otherRecordId localType="SWDInvalidId">(DE-588c)4058533-5</otherRecordId>
<otherRecordId localType="GKDInvalidId">(DE-588b)300755-8</otherRecordId>
```

The element `otherRecordId` is used for both additional identifier assigned by database systems of the Kalliope Union Catalog and external systems providing records about the same entity. At least by now, I did not considered record identifier from library or archival systems as identifier assigned to an entity which would be indeed encoded with entityId. As far as I understood the TL definition: "identifiers that are alternatives ... These might include the identifiers of merged EAC-CPF instances representing the same CPF entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance." I simply replaced EAC-CPF instances simply by records describing a CPF entity in any system for I consider EAC-CPF as an encoding schema mainly for data exchange purposes. 

Identifier I considered for being encoded with entityId would be any identifier "used to designate the entity" and "typically assigned by an authoritative agency" which would be - again at least from my perspective by now - any real world corporate body, e.g. tax office assigning a tax id, the district court assigning a company a commercial register id (in Germany, e.g. Suhrkamp HRB 163774 B), the vat registration number (USt-ID), etc.

```
<entityId localType="HRB">163774 B</entityId>
<entityType>corporateBody</entityType>
<nameEntry>
    <part>Suhrkamp Verlag</part>
</nameEntry>

```

Last but not least, by now I understood the element source to name the sources used to describe a CPF entity, like archival records, biographies, lexica or - also - records linked via otherRecordId (VIAF, GND, ...). 

It would be, however, a very good idea to go on with the discussion on this and in addition to that - and as already addressed yesterday in our call - if the elements and attributes are sufficient, e.g.

- it might be necessary to add an additional attribute to otherRecordId to make statements about a) the source (system) of an identifier, b) the type of an identifier (ID, URI), and c) the replacement of an identifier (e.g. replaced by record id).

- on closer examination - and presupposed we can agree on the general usage of various types of identifier (recordIds and entityIds) - entity id could become part of a CPF relation element to make clear by which a CPF entity got an ID assigned.

**Comment by SJagodzinski** [comment]
Gerhard pointed out, that also SNAC is using the element `<otherRecordId>` for non-EAC-CPF records, e.g. [Hannah Ahrendt](http://snaccooperative.org/download/5219366?type=eac-cpf). 

Kalliope is using `<recordId>` for their own ID, that also could be an authority file identifier (in case Kalliope creates this authority file as partner of the authority file agency). If so, the same ID would be repeated in `<otherRecordId>` and specified with `@localType` attribute, e.g. [Hannah Arendt](http://kalliope-verbund.info/de/xmleac?eac.id=11850391X). Again `<otherRecordId>` contains an non-EAC-CPF record ID. 

Hence, SNAC and Kalliope seem to use `<otherRecordId>` for any (record) identifier of a third system, specified by `@localType` and independently from the records format, i.e. EAC-CPF record or not.
