### ISSUE TITLE
<entityId>: definition

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#55]
Rename `<entityId>` in context of the (re)definition of `<recordId>`  (#53) and `<otherRecordId>` (#54)

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
`<entityId>` should be renamed `<identityId>`.

## Context
Derived from #25. Issue #25 is split into 3 issues and is closed.

Tag Library: 
> Any formal identifier used to designate the entity being described.

> Description and Usage:
> An optional element of `<identity>` that may be used to record any identifier associated with the CPF entity being described in the EAC-CPF instance. Identifiers such as legal identifiers, typically assigned by an authoritative agency, may be recorded in this element.
Do not confuse with `<recordId>` within `<control>`, which refers to an identifier for the EAC-CPF instance rather than the entity it describes. 

Comments French archivists:
Here again the object of identification is arguable. EAC-CPF accommodates for multiple identities of a “real world entity” (to keep it simple). If the different identities of the “entity” – typically known by its eventual different names, such as pseudonyms under which the entity makes itself publicly known – get discrete identifiers, does the design and semantics of the element `<entityId>` address that distinction?

In cases of EAC-CPF instances containing `<multipleIdentities>`, each of the “identities” recorded in the same EAC-CPF instance may be likely to have its own (and even multiple) identifiers.
ISNI ([International Standard Name Identifier](http://www.isni.org/), which aims at identifying the public identity of a party) and eventually other IDs that respond to the visions and needs of various communities and/or projects, as is the case of [ORCID](http://orcid.org/), are or are likely to explore those differences and sooner or later they will need to be appropriately accounted for.

Shouldn’t `<entityId>` become `<identityId>`? 
At the final end, what identifies `<entityId>`? As this element is contained within `<identity>` it would be more consistent to change its name into `<identityId>`. In case of multiple identities in the same EAC-CPF instance, each handled in a separate `<identity>` element, it should be possible to record a separate ID for each of the identities described.

**Comment by SJagodzinski** [comment]
The Archives Portal Europe is using the element `<entityId>` in the following way:

> [...]the optional element <entityId> will be used in apeEAC-CPF,
> where the attribute @localType would furthermore allow the content provider to specify
> the identifying system used. As <entityId> is defined as repeatable, it will also be possible
> to include identifiers for the entity coming from different identifying systems, eg the
> national authority file, plus international identifications.

See: [State of the art report on EAC-CPF and recommendations for implementation in Archives Portal Europe](http://www.apex-project.eu/images/docs/APEx_D4.4_SOTA_EAC-CPF_final_version_01.pdf), chap 4.1.3, p 55.

I have no examples for this encoding. Does someone else has any?

**Comment by SJagodzinski** [comment]
I got a nice example from Spain for this issue:

`<identity>`
`<entityId localType="PARES">44795</entityId>`
            `<entityId localType="VIAF">32057978</entityId>`
            `<entityId localType="BNE">XX1720002</entityId>`
            `<entityId localType="CGUIA">22122</entityId>`
            `<entityType>person</entityType>`
            `<nameEntry localType="preferred">`
                `<part xml:lang="spa">Alcalá-Zamora, Niceto (1877-1949)</part>`
                `<authorizedForm>NPA2</authorizedForm>`
            `</nameEntry>`
            `<nameEntry xml:lang="spa" localType="authorized">`
                `<part xml:lang="spa">Alcalá Zamora, Niceto (1877-1949)</part>`
               ` <authorizedForm>BNE</authorizedForm>`
            `</nameEntry>`
            `<nameEntry xml:lang="spa" localType="authorized">`
                `<part xml:lang="spa">Alcalá-Zamora y Torres, Niceto (1877-1949)</part>`
                <authorizedForm>LOC</authorizedForm>
            `</nameEntry>`
           ` <nameEntry xml:lang="spa" localType="other">`
                `<part xml:lang="spa">Alcalá-Zamora y Torres, Niceto (1877-1949)</part>`
                `<alternativeForm>NPA2</alternativeForm>`
            `</nameEntry>`
           ` <nameEntry xml:lang="spa" localType="other">`
             ` <part xml:lang="spa">El Botas</part>`
                <alternativeForm>NPA2</alternativeForm>
            `</nameEntry>`
        `</identity>``

**Comment by kerstarno** [comment]
Potential input to this issue from the subteam on Shared Schemas: https://github.com/SAA-SDT/SharedSchema/issues/7.

**Comment by SJagodzinski** [comment]
Decision during f2f meeting August 2019:

`<entityId>` = `<identityId>`.
Example of different descriptions of the same identity should be giveb in `<cpfRelation>` not in `<entityId>`.

Rename the element approved.

Result of the discussion on Topic: Assertion description during the f2f meeting 2019, see minutes.
