### ISSUE TITLE
Tag library update needed for the <span> element

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eac-cpf-schema#58]
See https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAC-CPF-eng/elem-span.xml#L26 

span is only available in abstract, citation, item, and p.  It is not available in componentEntry and sourceEntry.

**Comment by fordmadox** [comment]
Ditto for https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAC-CPF-ger/elem-span.xml#L20

**Comment by SJagodzinski** [comment]
As for the English version, we'll see, if we can delete both elements for 2010 Revised already.
The German version is not updated and not online. No need to change here.

**Comment by SJagodzinski** [comment]
Solved with 2010_revised
