### ISSUE TITLE
Child elements of singular/plural elements

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#61]
Define child elements for description for singular/plural elements

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Derived from #21 

Following elements:

//otherEntityTypes/otherEntityType
//places/place
//localDescriptions/localDescription
//legalStatuses/legalStatus
//functions/function
//languagesUsed/languageUsed
//occupations/occupation
//mandates/mandate

will be available as repeatable elements within their plural, wrapper element. Wrapper elements are not repeatable (any more).

## Suggested Solution
Decision about the child elements of the plural elements needed.

## Context
In EAC-CPF 2010_revised the plural elements contain following child elements for description:
- singular element (1..n)
- `<descriptiveNote>` (0..1)
- `<citation>` (0..n)
- `<p>` (0..n)
- `<list>` (0..n)
- `<outline>` (0..n)

In EAC-CPF 2010_revised the singular elements contain following child elements for description:
- `<term>` (0..1)
- `<placeEntry>` (0..n)
- `<date>`, `<dateSet>`, `<dateRange>` (0..1)
- `<citation>` (0..1)
- `<descriptiveNote>` (0..1)

**Comment by kerstarno** [comment]
Quick question: wouldn't at least `<term>` and potentially `<citation>`(if not all child elements of the singular elements) be repeatable? In order to e.g. do something like:
`<functions>`
   `<function>`
       `<term xml:lang="eng">`Developer `</term>`
       `<term xml:lang="ger">`Entwickler `</term>`
       `<placeEntry xml:lang="eng">`Munich`</placeEntry>`
       `<placeEntry xml:lang="ger">`München`</placeEntry>`
   `</function>`
   `<function>`
       `<term xml:lang="eng">`Teacher`</term>`
       `<term xml:lang="ger">`Lehrer `</term>`
       `<placeEntry xml:lang="eng">`London`</placeEntry>`
       `<placeEntry xml:lang="fre">`Londres`</placeEntry>`
   `</function>`
`</functions>`

Or am I misinterpreting the note on #21 on documentation: "Repeat child elements if you describe the same function in different languages."?

**Comment by SJagodzinski** [comment]
Yes, that the idea of #21 , having child elements of the singular elements repeatable, using exactly your example. 

What do you think? Does it work? Does it simplify eac encoding a bit?
Which child elements for the plural elements are needed?

**Comment by kerstarno** [comment]
Ok. Just wanted to check.

To start with: Personally I am not sure, whether it makes that much of a difference in terms of processing  to have e.g. repeated `<function>` elements in a wrapper or not, but I don't necessarily mind. 

Furthermore, there still might be the situation where you'd wanted to provide some contextual information for a group of functions, e.g. I might want to add the information to the example that I created in my previous comment, that these two functions were part of the same job or something like that. 

Hence, I'd get if people wanted to keep something like `<p>` or `<descriptiveNote>` for the plural elements, although there might be the question if these two don't actually fulfil the same purpose, especially seeing that `<descriptiveNote>` requires `<p>`as a sub-element anyway. I'd also tend to keeping `<citation>` for the plural elements. 

Not sure about `<list>`and `<outline>`. In my opinion, these do make more sense in the informal descriptive elements than in the formal ones.

**Comment by MicheleCombs** [comment]
Maybe this is too cumbersome, or not a good semantic match, but I wonder: Instead of having singular and plural, would it make sense to have all of these elements be singular and instead provide matching [*]set elements (e.g. functionset), similar to what we did for phydescset, chronitemset, dateset, languageset?

**Comment by SJagodzinski** [comment]
We see, that set elements bundle different information in an element, like `<languageset>` bundles languages and script whereas plural elements contain only the same information in its single element. That's why we agreed on having singular elements in a plural element.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 27 July 2020 (Chicago meeting):

Keep it simple the plural element just contains the singular (1..n) and descriptiveNote (0..1) where descriptiveNote will catch citation, p, list and outline in the transformation path. 

Make citation repeatable on singular elements.
