### ISSUE TITLE
Remove grouping documents

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/eac-cpf-schema#65]
As per discussion with Karin, the grouping documents (`grp.xsd` and `grp.rng`) have not been supported, and are no longer relevant to the schema.  These should be removed from the repository, as they aren't part of the supported schema.

## Creator of issue

1. Alexander Duryee
2. NYPL

## The issue relates to

- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove `grp.rng` and `grp.xsd` from the repository.

**Comment by fordmadox** [comment]
Just a note that these two flies have been removed from the "master" branch.  I'm going to close this ticket, but please let me know if there is anything else to follow up on.
