### ISSUE TITLE
<nameEntryParallel>: rename

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#66]
## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Rename elements name `<nameEntryParallel>` to `<nameentryset>`.

## Suggested Solution
Change elements name `<nameEntryParallel>` to `<nameentryset>` to bundle together sets of same name, identify one as authorised and rest as alternate. Could include `@localType=”parallel”` to reflect US usage.

## Context
Proposal as a result of the discussion on Topic: Names during the f2f meeting 2019, see minutes.
There is obviously a different interpretation according to this element in the different traditions of archival description in Europe and North America.
Proposal updated based on the EAC-CPF team meeting on 1 November 2019.

See also #56

**Comment by SJagodzinski** [comment]
See [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/61#issuecomment-487063806) for #61 

Other plural elements are bundled within a plural, wrapper element, like places/place etc.

Would this approach useful for name entries, too?

**Comment by kerstarno** [comment]
During their meeting on 1 November 2019, EAC-CPF team decided to use the new name `<nameentryset>` and have this element as optional and repeatable.

**Comment by SJagodzinski** [comment]
**Best Practise Guide**:

Use the optional attribute @localType to reflect the usage of parallel names in North America.

**Comment by SJagodzinski** [comment]
See solution for #117 .
