### ISSUE TITLE
<conventionDeclaration>: add sub-elements

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#67]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add `<agencyCode>` and `<agencyName>` to element `<conventionDeclaration>`.

## Suggested Solution
Re-use the existing elements `<agencyCode>` and `<agencyName>` within `<conventionDeclaration>` to describe and identify the rules source along with the description of the rule via `<abbreviation>`, `<descriptiveNote>` and `<citation>`. 
Use the existing optional attribute `@xml:id` (or `@id`) to provide an option for direct link between described rule and `@rules` attribute, cf #68. 

## Context
Proposal as a result of the discussion on Topic: Names during the f2f meeting 2019, see minutes.

Names need to be authorised by someone/a rule. Preference to use attributes for encoding rules, rather than elements to be more flexible. Might be useful for other information within an EAC-CPF file.

Proposal to solve #26

**Comment by kerstarno** [comment]
Once confirmed for EAC-CPF, this should also be considered for EAD3 as `<conventionDeclaration>` is one of the shared elements between the two standards.

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1548633886&range=C124)

**Comment by SJagodzinski** [comment]
During their meeting on 22 November 2019, EAC-CPF team decided to use the `@id` attribute to refer from a name entry to the rule in convention declaration, in order to encode the rule that formed a name.

**Comment by SJagodzinski** [comment]
During their meeting on 20 December 2019, EAC-CPF team was not able to decide on this issue. 

There will be a request for use cases, real life examples and encoding preferences to EAC-CPF users to support decision making.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting Berlin, 11 March 2020

A request for use cases was send to colleagues in France, Italy, Spain and USA. There is no feedback so far. 

**Decision**: No additional agency information in convention declaration as there is no use case available.
