### ISSUE TITLE
<nameEntry>: add @rules

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#68]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add EAD3 attribute @rule to element `<nameEntry>`.

## Suggested Solution
Use EAD3 attribute @rules within `<nameEntry>` to encode the rules. 
Use existing element `<conventionDeclaration>` to describe the rules. See also #67.

## Context
Proposal as a result of the discussion on Topic: Names during the f2f meeting 2019, see minutes.

Names need to be authorised by someone/a rule. Preference to use attributes for encoding rules, rather than elements to be more flexible. Might be useful for other information within an EAC-CPF file.

Proposal to solve #26

**Comment by SJagodzinski** [comment]
see also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=1662057578&range=C26)

**Comment by SJagodzinski** [comment]
During their meeting on 22 November 2019, EAC-CPF team decided to add the new attribute:

- `@rules`
- data type: IDREF
- May occur within: `<nameEntry>`
- availability: Optional

ATTENTION: EAD3 attribute `@rules` has data type NMTOKEN. Also EAD3 `@rules` differs in its definition:

> Name of the descriptive rules or conventions that govern the formulation of the content of the element.

**Comment by kerstarno** [comment]
Sorry to pick this up as someone who couldn't make the last meeting and hasn't got the overview of the conversation, but could we look into the difference of `@rules` in EAD3 and the intended use in EAC-CPF a little further? If we re-use an EAD3 attribute, we might want to aim at re-using it in the same way (keyword: shared schema approach) or might want to consider introducing another attribute instead. 

If this is to point from the name entry to the rule in `<conventionDeclaration>` why not re-use the EAD3 attribute `@target` instead? This attribute does exactly what we'd want to achieve here: "A pointer to the ID of another element. Used to create internal links within an XML instance." Its type is IDREF and it's optional in its current EAD3 context.

**Comment by karinbredenberg** [comment]
On meeting 20th of December we agreed upon the need of the attribute but the naming needs to be looked over taking into account showing what the attribute is, reconciliation with EAD3 and so on.

**Comment by SJagodzinski** [comment]
See solution in #118 

Use //control/conventionDeclaration to describe the rule that authorises or creates the name.
Use //nameEntry@conventionDeclarationReference to refer from the name to this rule.

No need to use `@rules` attributes for this purpose.
