### ISSUE TITLE
<nameEntry>: add @idref

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#69]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add @idref to `<nameEntry>` to link a name entry to a rules description.

## Suggested Solution
Add @idref to `<nameEntry>` to link a name entry to a rules description.
ATTENTION: Alternative to #68 ?

## Context
Proposal as a result of the discussion on Topic: Names during the f2f meeting 2019, see minutes.

Proposal to solve #26

**Comment by kerstarno** [comment]
I think, this should rather be "Add `@target`". IDREF is more about the data type of an attribute than an attribute's name. EAD3 uses `@target` in connection with `@id` in order to distinguish between document-internal links and document-external links, which would use `@href`.

**Comment by SJagodzinski** [comment]
During their meeting on 22 November 2019, EAC-CPF team decided to use the attribute `@rules` to link back to convention declaration, cf #68.

**Comment by SJagodzinski** [comment]
During their meeting on 22 November 2019, EAC-CPF team decided to keep an attribute with IDREF data type to link back to `<conventionDeclaration>`. The former decision to call this attribute `@rules` was discarded, as `@rules` has a different scope in EAD3. 

Nevertheless, the attributes name needs to be decided in context with shared schema and EAD3.

The object, how to link back from `<nameEntry>` to `<conventionDeclaration>` will be discussed in issue #68.

**Comment by SJagodzinski** [comment]
See solution in #118 

Use //control/conventionDeclaration to describe the rule that authorises or creates the name.
Use //nameEntry@conventionDeclarationReference to refer from the name to this rule.

No need to use `@rules` attributes for this purpose.
