### ISSUE TITLE
<nameEntry>: add @normal

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#72]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add the EAD3 attribute `@normal` to enter the authorized, normalized form of name in `<nameEntry>`.
Remove elements `<authorizedForm>` and `<alternativeForm>`.

## Suggested Solution
Add `@normal ` in the context of [EAD3](https://www.loc.gov/ead/EAD3taglib/EAD3.html#attr-normal) to enter the authorized, normalized form of name, eg
```
<nameEntry normal="[authorized version]">
 <part>IIDH</part>
</nameEntry>
``` 
An authorized form would not use `@normal` attribute.

## Context
Proposal as a result of the discussion on Topic: Names during the f2f meeting 2019, see minutes.

Proposal to solve #26

**Comment by kerstarno** [comment]
Attention: this would be an alternative proposal to what's mentioned for `<nameEntry>` in issue #70. Only one option should be implemented.

**Comment by kerstarno** [comment]
During their meeting on 1 November 2019, EAC-CPF team decided to decline this suggestion.

**Comment by SJagodzinski** [comment]
Needs final confirmation

**Comment by SJagodzinski** [comment]
There is no reason that the authorised name, which is to be inserted as value of `@normal`, shouldn’t be entered in an `<nameEntry>` element with status as authorized. Means, if the authorised, and with it the normalised, form of the name is known, it has to be encoded as name entry. 
An additional normalisation of the name is not necessary and does not show any advantages.
