### ISSUE TITLE
new element <evidence>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#73]
Add a new element `<evidence>` and a range of attributes for assertion description.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add a new element `<evidence>` to be connected with existing elements `<source>` and `<maintenanceEvent>`.

Add a new attribute `@fromSource` in `<evidence>` to link to the element `<source>`, ie this evidence is based on information in this source.

Add a new attribute `@supportsAssertion` in `<evidence>`  to specify the exact data element.

Add a new attribute `@associatedMaintenanceEvent`  in `<evidence>`  to associate an agent/date/note.

Add a new element`<citedRange>` to point to a specific part within the evidence along with an attribute `@unit` in `<evidence>` to specify if the cited range of materials represents a page number, volume number, etc. 

Add a new element `<foundData>` in `<evidence>` to provide a description of the new evidence data found.

## Suggested Solution
Maintenance event points to the source (its addition); source doesn't point to the maintenance event. Where the evidence is stated needs to be in the evidence. 

Simplify the model a little to be clear about what you pointing to where. Relate source to <maintenanceEvent>, don’t include <maintenanceEvent> in assertion.

Prefer not to name element `<evidence>` – we need to come up with less loaded term.
Use word “assertion” in tag library to refer to data which we might be providing evidence of assertions?

## Context
Proposal as a result of the discussion on Topic: Assertion description during the f2f meeting 2019, see minutes.

Proposal to solve #43

**Comment by kerstarno** [comment]
Addition:
- Rather than using the name `@supportsAssertion` for the new attribute in `<evidence>`, use @supports.
- Rather than using a new attribute `@associatedMaintenanceEvent`  in `<evidence>`, strengthen the use of the `<control>` elements `<maintenanceEvent>` and `<source>` and make the connection therein.

**Comment by SJagodzinski** [comment]
The topic assertion description was discussed for revision and is solved with a new element and a range of new attributes. Follow the discussion with our [topic papers](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/assertion) and see the following related issues:

`<citedRange>` #162 
`@conventionDeclarationReference` #174 
`@sourceReference` #172
`@maintenanceEventReference` #173 
`@unit` #255

The solution will be explained in our Best Practise Guide.

The element `<evidence>` will not be added.
