### ISSUE TITLE
new attribute @assertionRank

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#74]
Add new attribute `@assertionRank`, added to a parent element of `<evidence>`.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add new attribute `@assertionRank`, added to a parent element of `<evidence>`, cf #73, that can be used when assertions of the same type contradict.

## Suggested Solution
Add new attribute `@assertionRank`, added to a parent element of `<evidence>`, cf #73, that can be used when assertions of the same type contradict or use the new attribute `@status`, cf #70.

## Context
Proposal as a result of the discussion on Topic: Assertion description during the f2f meeting 2019, see minutes.

Proposal to solve #43

**Comment by fordmadox** [comment]
In my notes, I wrote down that we would prefer to use `@status` for this instead of creating yet another attribute. If `@status` is added, then I agree that it could/should also be used in this context (e.g. status='deprecated', etc.)

**Comment by SJagodzinski** [comment]
The topic assertion description was discussed for revision and is solved with a new element and a range of new attributes. Follow the discussion with our [topic papers](https://github.com/SAA-SDT/TS-EAS-subteam-notes/tree/master/eaccpf-subteam/working-documents/topics/assertion) and see the following related issues:

`<citedRange>` #162 
`@conventionDeclarationReference` #174 
`@sourceReference` #172
`@maintenanceEventReference` #173 
`@unit` #255

The solution will be explained in our Best Practise Guide.

The attribute `@assertionRank` will not be added.
