### ISSUE TITLE
<date>: add @certainty

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#75]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add @certainty to `<date>` to encode the level of confidence for the information and to align with EAD3.

## Suggested Solution
Add @certainty to `<date>` to encode the level of confidence for the information and to align with EAD3.

Datatype: NMTOKEN
Occurance: optional

## Context
Agreement as a result of the discussion on Topic: Dates during the f2f meeting 2019, see minutes.

Proposal to solve #34. See also [comparison report](https://docs.google.com/spreadsheets/d/13XT1lHfhEJiZ06KVeYtRu0f3ke20_9vZKoRuzKM-Ll0/edit#gid=2052825589&range=B18).

**Comment by kerstarno** [comment]
Going through the minutes and the paper on dates again, the suggestion is to add `@certainty` to `<date>`,  `<fromDate>` and `<toDate>`.

**Comment by kerstarno** [comment]
Trying to get my head around this once more, while going through the minutes from Berlin and seeing, what we might need to consider replicating in EAD. 

With the potential integration of EDTF in ISO 8601 and with having ISO 8601 as the recommended value for `@dateencoding` (see #124), would we still need `@certainty` as a separate attribute or would we look to include the certainty aspect within @standarddate instead? 

I.e. would we want people to encode
```
<daterange>
  <fromdate certainty="approximate" standarddate="20200309">9 March 2020</fromdate>
  <todate standarddate="20200312">12 March 2020</todate>
</daterange>
```
or rather
```
<daterange>
  <fromdate standarddate="2020-03-09~">9 March 2020</fromdate>
  <todate standarddate="2020-03-12">12 March 2020</todate>
</daterange>
```
Or would we keep `@certainty` with the recommendation of using the EDTF values "uncertain", "approximate", or "uncertain and approximate", but only if another date encoding scheme than ISO8601 is used?

**Comment by ailie-s** [comment]
My preference is the latter, that we keep `@certainty`, recommend using the EDTF values, if using another date encoding schema.

I haven't been able to get access to the 2019 edition of ISO 8601, which should include EDTF. Given that the standards are not always easily accessible, it would be good to include another option.

**Comment by kerstarno** [comment]
Thanks for the feedback, @ailie-s. I agree - mainly wanted to check and make sure.

**Comment by fordmadox** [comment]
Just a note that we will see about getting access, through SAA, to the 2019 editions of ISO 8601.
