### ISSUE TITLE
<eac-cpf>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#78]
## Root element: 

- rename to `<eac>`
- remove xlink namespace
- remove xml namespace

- add new optional attribute:
`@audience`
`@base`
`@languageOfElement`
`@scriptOfElement`

- no change request for element or availability

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<eac-cpf>`: Remove XLink namespace #3](https://github.com/SAA-SDT/eac-cpf-schema/issues/3)
[Remove xml ns to align with EAD 3 #27](https://github.com/SAA-SDT/eac-cpf-schema/issues/27)
[@xml:lang: adopt EAD 3 solution #28](https://github.com/SAA-SDT/eac-cpf-schema/issues/28)

[Common approach to XLink namespace #1](https://github.com/SAA-SDT/SharedSchema/issues/1)
[Common approach to XML namespace #2](https://github.com/SAA-SDT/SharedSchema/issues/2)

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - optional
`@audience`  - optional (values limited to: external, internal)
`@relatedencoding` - optional
`@script` - optional

[EAD3 Tag Library, Preface](https://www.loc.gov/ead/EAD3taglib/index.html#d0e115):
> The XLink model for linking attributes was preserved, but the XLink namespace, which had been added to the schema versions of EAD 2002, was removed due to the onerous and needless complexity that namespaces introduce when processing XML.

## Context
The `<eac-cpf>` is the root element and as such contains the entire EAC-CPF description of the person, corporate body, or family. It contains a required `<control>` followed by either a `<cpfDescription>` or a `<multipleIdentities>` element.

**May contain**: control, cpfDescription, multipleIdentities
**Attributes**: xml:base, xml:id, xml:lang
**Availability**: Mandatory, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<control>`, `<cpfDescription>`, `<multipleIdentities>`
**Attributes**: 
`@audience`  - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional
`@languageOfElement` - optional
 `@scriptOfElement` - optional

**Availability**: Required, not repeatable

## Example encoding
```
<eac xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" audience="internal" id="eaccpf1" languageOfElement="en" scriptOfElement="lat">
    <control>
        [...]
    </control>
    <cpfDescription>
       [...]
    </cpfDescription>
</eac-cpf>
```

**Comment by kerstarno** [comment]
Note with regard to one part of the Solution documentation: In the EAD3 tag library, we've just removed the "May occur within: ROOT" as this creates a link to an "element" called "ROOT", which leads into the void.

**Comment by fordmadox** [comment]
Just a note (regardless of the naming scheme, but especially if we keep camelCase):  I'd suggest changing the document element name to ```eac``` instead of the kebab-cased ```eac-cpf```.  A future version of EAC-F could then potentially use the same root element, swapping out ```cpfDescription``` for the ```eafDescription``` element name from the French schema (or something similar).

**Comment by MicheleCombs** [comment]
"kebab-case" lol

Michele

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

Agree to changing to `<eac>`, but with the intent to have distinct root elements for Activities & Functions, e.g. `<eaf>`.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** The required root element of an EAC-CPF instance.
**May contain:** `<control>` (1..1), (`<cpfDescription>`, `<multipleIdentities>` (1..1))
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Description and usage:** 
`<eac>` wraps all other elements in a particular instance of an archival authority record encoded with the EAC-CPF XML Schema.
`<eac>` must contain `<control>` and either a `<cpfDescription>` or a `<multipleIndentities>` element.
**Availability:** Required, not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema Team schema testing:

- The root element is now named `<eac>`
- `<eac>` requires `<control>` as sub-element
- `<eac>` requires either `<cpfDescription>` or `<multipleIdentities>` as sub-element
- `<eac>` can use the optional attributes `@audience`, `@id`, `@base`, `@languageOfElement`, `@scriptOfElement`
- `<eac>` can also use attributes from other namespaces (tested with XLink)
- `<eac>` does not have `@target` as decided during the most recent EAC Team meeting

The above applies to both, RNG and XSD schemas.

Element is ready.

**Comment by SJagodzinski** [comment]
Request from @fordmadox during schema creation:

Remove global attributes `@audience`, `@base`, `@id`, `@languageOfElement`, `@scriptOfElement` from root element.

**Comment by fordmadox** [comment]
Wait, what?  I don't recall making that request 😄.    Or is this a request _for_ me to change something?  If the latter, can we discuss sometime this week or early next week?

**Comment by SJagodzinski** [comment]
@fordmadox : No, sorry, my fault! I remember veguely a discussion about attributes in the root element. If it is not your or @karinbredenberg request, I'm going to delete these comments and the label.

**Comment by karinbredenberg** [comment]
Nope not me.
