### ISSUE TITLE
<cpfDescription>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#79]
## Corporate Body, Person, or Family Description
- add optional attribute:
`@audience`
`@base`
`@conventationDeclarationReference`
`@maintenanceEventReference`
`@scriptOfElement`
`@sourceReference`

- no change request for elements or availability

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
The `<cpfDescription>` contains the description of one identity. Commonly one CPF entity has one identity, but when it has more than one, use either `<multipleIdentities>` or multiple interrelated EAC-CPF instances.

**May contain**: `<alternativeSet>`, `<description>`, `<identity>`, `<relations>`
**May occur within**: `<eac-cpf>`, `<multipleIdentities>`
**Attributes**: `@xml:base`, `@xml:id`, `@xml:lang` - all optional
**Availability**: Within eac-cpf: Mandatory, Non-repeatable; Within multipleIdentities: Mandatory, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<alternativeSet>`, `<description>`, `<identity>`, `<relations>`
**May occur within**: `<eac>`, `<multipleIdentities>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability**: Within `<eac>`: Required, not repeatable; Within `<multipleIdentities>`: Required, repeatable

New or any _example_ needed?

## Example encoding
 ```
<eac>
    <control> [...]  </control>
    <cpfDescription audience="external" base="baseURI" conventionDeclarationReference="conventiondeclaration1" id="cpfDescription1" languageOfElement="eng" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">
        <identity>
            [...]
        </identity>
    </cpfDescription>
</eac>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A wrapper element that binds together the descriptive information of one CPF identity.
**May contain:** alternativeSet (0..1), description (0..1), identity (1..1), relations (0..1)
**May occur within:** eac, multipleIdentities
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageOfElement `- optional
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference `- optional
`@target` - optional
**Attribute Usage:**
The `@id` attribute allows individual `<cpfDescription>` elements to be individually identified when using the `<multipleIdentities>` structure.
**Description and Usage:**
`<cpfDescription>` contains the description of one identity.  
The `<cpfDescription>` includes a required `<identity>` element containing authorized or parallel name entries and optional `<description>` and `<relations>` to provide contextual information for the CPF entity being described, including the relations to other corporate bodies, persons, families, resources, and functions.
An optional `<alternativeSet>` element allows the incorporation of two or more authority records derived from two or more authority systems.
**Availability:** 
Within `<eac>`: one of `<cpfDescription>` or `<multipleIdentities>` required, not repeatable
Within `<multipleIdentities>`: two or more `<cpfDescription>` required, repeatable

**Comment by kerstarno** [comment]
Tested in the context of Schema Team schema testing:

- In the context of `<eac>`, `<cpfDescription>` is required in case `<multipleIdentities>` is not used instead; in this context, `<cpfDescription>` cannot be repeated
- In the context of `<multipleIdentifies>`, at least two `<cpfDescription>`-s have to be present and `<cpfDescription>` can be repeated
- `<cpfDescription>` itself requires `<identity>` as a sub-element; `<identity>` is not repeatable
- `<cpfDescription>` also allows for the optional sub-elements `<description>`, `<relations>`, and `<alternativeSet>`; none of these is not repeatable
- `<cpfDescription>` furthermore allows for the optional attributes `@audience`, `@id`, `@target`, and `@base` as well as optional attributes from another namespace (tested with XLink)
- `<cpfDescription>` does currently not include the optional attributes `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`
   - These **need to be added**

The above applies to the RNG and the XSD schema.

@ailie-s - the TL draft is currently missing `@target`.

**Comment by fordmadox** [comment]
Language and reference attributes should now be available here, as requested.  See https://github.com/SAA-SDT/eac-cpf-schema/commit/7cc64b0957a2858005319f22aa6a60e0e6521ddd

**Comment by kerstarno** [comment]
Retested.

- `<cpfDescription>` now also allows for the optional attributes `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`

This applies to RNG and XSD schemas.

Element is ready with regard schema testing.
