### ISSUE TITLE
<eventType>: element content should become attribute value

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#8]
The restricted content for element `<eventType>` should become restricted value for the new attribut `@value`. Add new value "unknown".

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Create new attribute `@value`.
The restricted content for element `<eventType>` should become restricted value for the new attribut `@value`. The content for `<eventType>` is defined: created, revised, deleted, cancelled, derived.
In line with EAD 3 add new value for `@value`: unknown.

## Context
Following EAD 3 schema.

> allows for element content to be in a different language

[@rockivist]

**Comment by karinbredenberg** [comment]
Agreed! Align with eAD3.

**Comment by karinbredenberg** [comment]
For a Phase-1 I would add the new value and in phase-2 transform to align with EAD3.

**Comment by SJagodzinski** [comment]
Meeting 18 Dec 2017 outcome:
We are going to follow Karin proposal. The issues will be split into 2 new issues, each for one phase.

**Comment by SJagodzinski** [comment]
Meeting 3 May 2019 outcome:

The risk to get conflicting information within value and content is already existing in EAD3 and it seems to be acceptable for EAC-CPF, too.

Defining optional text as data type for `<eventType>` allows users to give extra information about the event type or to add content in different languages

To follow EAD 3, add the required attribute `@value` with following values:
cancelled, created, deleted, derived, revised, unknown, updated

**Comment by SJagodzinski** [comment]
Solved with #92 : element removed and new mandatory attribute `@maintenanceEventType` with restricted values (cancelled, created, deleted, derived, revised, unknown, updated) added to <maintenanceEvent> instead in EAC-CPF 2.0
