### ISSUE TITLE
<multipleIdentities>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#80]
## Multiple Identities
- add optional attribute:
`@audience`
`@base`
- no change request for elements or availability

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
EAC-CPF specific element

## Context
A wrapper element used to group together more than one `<cpfDescription>` within a single EAC-CPF instance.

**May contain**: `<cpfDescription>`
**May occur within**: `<eac-cpf>`
**Attributes**: `@xml:base`, `@xml:id`, `@xml:lang` - all optional
`Availability`: Optional, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**:  `<cpfDescription>`
**May occur within**: `<eac-cpf>`

**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional

**Availability**: Optional, not repeatable

- New or other example needed?
- Topic for Best Practise Guide?

## Example encoding
```
<eac-cpf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" audience="internal" id="eaccpf1">
    <control>
        [...]
    </control>
    <multipleIdentities audience="external" id="multipleidentities1">
        <cpfDescription audience="external" id="cpfdescription1">
              [...]
        </cpfDescription>
        <cpfDescription audience="external" id="cpfdescription2">
              [...]
        </cpfDescription>
    </multipleIdentities>
   </eac-cpf>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A child element of `<eac>` used to group together more than one `<cpfDescription>` within a single EAC-CPF instance
**May contain:** `<cpfDescription>` (2..n)
**May occur within:** `<eac>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@base` - optional
`@id` - optional
**Description and Usage:**
A grouping element used to encode more than one `<cpfDescription>` in a single EAC-CPF instance.
The use of the `<multipleIdentities>` element can resolve two identity circumstances. Firstly, it can be used to represent more than one identity (including official identities) of the same CPF entity, each with a separate `<cpfDescription>`. Secondly, it can be used to represent a collaborative identity that includes multiple individuals operating under a shared identity (such as a shared pseudonym).
`<multipleIdentities>` must include two or more `<cpfDescription>` elements.
**Availability:** Within `<eac>`: one of `<cpfDescription>` or `<multipleIdentities>` required, not repeatable

**Comment by karinbredenberg** [comment]
Test of element multipleIdentities:
May occur within: eac **Ok in both schemas**
May contain: cpfDescription (2..n) **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@base - optional **Ok in both schemas**
@id - optional **Ok in both schemas**

**Result**: Element passes test.

**Comment by fordmadox** [comment]
Do we need the two language attributes here, as well?
