### ISSUE TITLE
<recordId>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#82]
## Record Identifier
- add optional attributes
`@audience`
 `@languageOfElement`
 `@scriptOfElement`

- change elements content definition from NMTOKEN to [text]

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<recordID>`: definition #53](https://github.com/SAA-SDT/eac-cpf-schema/issues/53)
[Topic_identifiers.pdf](https://github.com/SAA-SDT/eac-cpf-schema/issues/Topic_identifiers.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/identifiers/Topic_identifiers.pdf))
[Identifiers in EAC-CPF](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/identifiers/Identifiers%20in%20EAC-CPF.pdf))

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@instanceurl` - Optional
`@lang` - Optional
`@script `- Optional

**May contain**: [text]

## Context
The unique identifier for a particular instance.

**May contain**: [NMTOKEN]
**May occur within**: `<control>`
**Attributes**: `@xml:id` - Optional
**Availability**: Mandatory, Non-repeatable

## Solution documentation
Rephrasing **Summary**, **Description and Usage** and **Attribute usage** needed?

May contain: [text]
May occur within: `<control>`
Attributes:
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@instanceurl` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional

Availability: Required, not repeatable

- New or other example needed?
- Topic for Best Practise Guide

## Solution schema
```
<control>
 <recordId audience="external" id="recordid1" instanceUrl="http://url.of.eac-cpfinstance.int" languageOfElement="en" scriptOfElement="Latn">record identifier</recordId>
[...]
</control>
```

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Currently `<recordid>` is text in EAD3, but specifically NMTOKEN in EAC-CPF. Felt that there was no reason for these to be different, with a preference for moving this toward NMTOKEN. Will need to consult with the EAD Team about addressing this difference.

**Decision**: Discuss difference btw content resp. data type in <recordId> with EAD team.

**Comment by SJagodzinski** [comment]
EAD virt meeting, 8 June 2020:

Suggestion of EAD team to rather loosen the restrictions of NMTOKEN in EAC-CPF. There are examples to use additional special characters than hyphen (-), underscore (_) and full stop (.). 
Furthermore, some EAC elements `(<preferredForm>`, `<agencycode>`, `<otheragencycode>)` relaxed NMTOKEN restrictions in EAC-CPF.

**Comment by SJagodzinski** [comment]
EAC-CPF  virt meeting, 3 July 2020:

Change elements content definition from NMTOKEN to [text].

**Comment by ailie-s** [comment]
Tag Library Text: 

**Summary:** A required child element of `<control>` that designates a unique identifier for the EAC-CPF instance.
**May contain:** [text]
**May occur within:** control
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Description and Usage:** 
`<recordId>` is used for recording a unique identifier for the EAC-CPF instance. The institution assigning the identifier ensures uniqueness of the `<recordId>`  value within the archival descriptions under its control. A globally unique identifier may be constructed within `<recordId>`  according various external protocols (i.e. HTTP URI, DOI, PURL, or UUID), or in combination with `<agencyCode>`, which is an optional element within `<maintenanceAgency>`.
Any alternative or additional record identifiers may be recorded in `<otherRecordId>`.
**Availability:** Required, not repeatable

**Comment by ailie-s** [comment]
`@instanceURL` needs to be removed, as per outcome EAC-CPF September 2020 meeting (#130 )

**Comment by kerstarno** [comment]
I think, this still needs to go through schema testing, too. Will do that check later on today or early tomorrow and will the change the milestone again as agreed.

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

- `<recordId>` is mandatory within `<control>`
- `<recordId>` cannot be repeated
- `<recordId>` can be used with the optional attributes `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement`, and `@target`
- The attribute `@instanceURL` is not available with `<recordId>` 
- `<recordId>` can also be used with attributes from another namespace (tested with XLink)
- `<recordId>` can have any text (tested with a value that contains - / , and (blank))

This is true for both, RNG and XSD.

Test successful.

**Comment by fordmadox** [comment]
Just an FYI that this element received a custom data type to enforce that it had some value.  See https://github.com/SAA-SDT/eac-cpf-schema/blob/development/source/modules/datatypes.rng#L28-L32.   Otherwise, `<recordId/>` would also be valid. (as is true for agencyCode now). @SJagodzinski Do we want to employ this tactic elsewhere on any other required elements?

**Comment by SJagodzinski** [comment]
> Just an FYI that this element received a custom data type to enforce that it had some value. See https://github.com/SAA-SDT/eac-cpf-schema/blob/development/source/modules/datatypes.rng#L28-L32. Otherwise, `<recordId/>` would also be valid. (as is true for agencyCode now). 

Solution: Schema defines string with a given pattern as content for `<recordId>`.
