### ISSUE TITLE
<otherRecordId>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#83]
## Other Record Identifier

- add optional attributes
`@audience`
`@languageOfElement`
`@localType`
`@localTypeDeclarationReferencde`
`@scriptOfElement`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`
- review **Tag Library**
- use `@vocabularySource` to encode provenance of this record identifier

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<otherRecordId>`: definition #54](https://github.com/SAA-SDT/eac-cpf-schema/issues/54)
[Topic_identifiers.pdf](https://github.com/SAA-SDT/eac-cpf-schema/issues/Topic_identifiers.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/identifiers/Topic_identifiers.pdf))
[Identifiers in EAC-CPF](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/identifiers/Identifiers%20in%20EAC-CPF.pdf))

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@script` - Optional

## Context
Alternative record identifiers that may be associated with the EAC-CPF instance.

**May contain**: [text]
**May occur within**: `<control>`
**Attributes**: `@localType`, `@xml:id` - all optional
**Availability**: Optional, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<control>`
**Attributes**: 
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability**: Optional, repeatable

- New or other example needed?
- Topic for Best Practise Guide

## Example encoding
```
<control>
 <recordId>record identifier</recordId> 
 <otherRecordId audience="external" id="otherrecordid1" languageOfElement="en" localType="localRecordId" localTypeDeclarationReference="localTypeDeclaration1" scriptOfElement="lat" valueURI="recordURI" cocabularySource="recordVocabulary" vocabularySourceURI="recordVocabularyURI">other record identifier</otherRecordId>
 [...]
</control>
```

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Suggested that `@valueURI,` `@vocabularysource,` and `@vocabularysourceURI` be added, as optional attributes. Could also use MODS's `@authority` and `@authorityURI` - but preferable to reuse existing terms in our own standards.

For example: 
`<otherrecordid vocabularysource="[code value for repository]" vocabularysourceURI="[original instance repository URI]" valueURI="[URI of original instance]">`

**Comment by SJagodzinski** [comment]
EAC-CPF Chicago meeting, 28 and 31 August 2020:

Decision on elements for @valueURI, @vocabularysource, and @vocabularysourceURI was postponed to a virtual meeting, discussion via online document.

TS-EAS Chicago meeting, 6 August 2020:

Keeping `@localType,` looking over `<control>,` making sure it’s available where needed, and if adding declaration elements, where have `@localType` have a reference attribute `@localTypeDeclarationReference`.

**Comment by SJagodzinski** [comment]
TS-EAS meeting, 2 October 2020:

Add `@valueURI`, `@vocabularysource`, and `@vocabularysourceURI` to the identifier elements `agencyCode`, `identityId`, `otherAgencyCode` and `otherRecordId`.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<control>` that encodes any local identifier for the EAC-CPF instance.
**May contain:** [text]
**May occur within:** control
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id `- optional
`@languageOfElement` - optional
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional
`@target` - optional
`@valueURI `- optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Attribute Usage:**
Use `@localType` to identify the institution or service responsible for providing the associated record identifier, if not the same as that given in `<maintenanceAgency>`.
**Description and Usage:**
`<otherRecordId>` can be used to record an identifier that is an alternative to the mandatory identifier provided in `<recordId>`. These might include the identifiers of merged EAC-CPF instances representing the same CPF entity or those of records that are no longer current but had some part in the history and maintenance of the EAC-CPF instance.
**Availability:** Optional, repeatable

**Comment by SJagodzinski** [comment]
EAC-CPF Meeting, 6 November 2020:

Use `@vocabularySource` to encode provenance of this `<otherRecordId>`?

**Comment by karinbredenberg** [comment]
Test of element otherRecordId:
May occur within: control 0..n **Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: The element is ready and already have the @target.
