### ISSUE TITLE
<otherAgencyCode>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#89]
## Other Agency Code
- add optional attributes
`@audience` 
`@languageOfElement`
`@localTypeDeclarationReference` 
`@scriptOfElement` 
`@status`
`@valueURI` 
`@vocabularySource` 
`@vocabularySourceURI` 

- keep element name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@script` - Optional

## Context
Alternate code representing the institution or service responsible for the creation, maintenance, and/or dissemination of the EAC-CPF instance.

**May contain**: [text]
**May occur within**: `<maintenanceAgency>`
**Attributes**: `@localType`, `@xml:id` all optional
**Availability**: Optional, Repeatable

## Solution documentation
Rephrasing_Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<maintenanceAgency>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)  
`@id` - optional  
`@languageOfElement` - optional  
`@localType` - optional  
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional  
`@status` - optional (values limited to: authorized, alternative)  
`@valueURI` - optional  
`@vocabularySource` - optional  
`@vocabularySourceURI` - optional  
**Availability**: Optional, repeatable

- New or other example needed

## Example Encoding
```
<control >
 <recordId >records identifier</recordId>
 <maintenanceAgency>
  <agencyCode>agency code</agencyCode>
  <otherAgencyCode audience="external" id="otherAgencyCode1" languageOfElement="eng" localType="localAgencyCode" scriptOfElement="lat" status="alternative" valueURI="otherAgencyCodeURI" vocabularySource="VIAF" vocabularySourceURI="VIAFURI">other agency code</otherAgencyCode>
  <agencyName>agency name</agencyName>
 </maintenanceAgency>
 <maintenanceHistory>
  [...]
 </maintenanceHistory>
</control>
```

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<maintenanceAgency>` that provides an alternative code for the institution or service responsible for the EAC-CPF instance.
**May contain:** [text]
**May occur within:** maintenanceAgency
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional 
`@localType` - optional
`@localTypeDeclarationReference` - optional
`@scriptOfElement` - optional
`@status` - optional (values limited to: authorized, alternative)
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Attribute Usage:**
Use `@localType` to specify the type of code being provided.
Use `@status` to encode whether the `<otherAgencyCode>` is an authorized or alternative code.
**Description and Usage:**
Use <`otherAgencyCode>` to provide alternative and/or local institution code that represents the institution or service responsible for the creation, maintenance, and/or dissemination of the EAD instance. Any code other than that given in `<agencyCode>` may be provided in `<otherAgencyCode>`. The addition of an ISO 3166-1 alpha-2 country code as the prefix to a local code is recommended to ensure international uniqueness.
**Availability:** Optional, repeatable

**Comment by karinbredenberg** [comment]
Test of element otherAgencyCode:
May occur within: maintenanceAgency 0..n **Ok in both schemas**
May contain: [text] **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@localType - optional **Missing in both schemas**
@localTypeDeclarationReference - optional **Missing in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@status - optional (values limited to: authorized, alternative) **Missing in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

**Result**: Addition of @localType, @localTypeDeclaration and @status. Element already have @target in the schema.

**Comment by karinbredenberg** [comment]
Retest of element:
@localType - optional **Ok in both schemas**
@localTypeDeclarationReference - optional **Ok in both schemas**
@status - optional (values limited to: authorized, alternative) **Ok in both schemas**

**Result**: element ready.
