### ISSUE TITLE
<control>: add child element <representation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#9]
Add new element `<representation>` as child element of `<control>`

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. s.jagodzinski@bundesarchiv.de or silkejagodzinski@gmail.com

## The issue relates to
- [x] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Add new element `<representation>` as child element of `<control>`.
Define the occurrance optional and unbounded.

## Context
Following EAD 3 schema.
Description in [EAD 3 TL](http://www.loc.gov/ead/EAD3taglib/index.html#elem-representation):

> A child element of <control> for recording a link to a transformed and deliverable version of the EAD instance.
> Use <representation> to record a link to a transformed and deliverable version of an EAD instance, for example an HTML or PDF version. If desired, the localtype attribute can be used to differentiate multiple <representation> elements.

**Comment by karinbredenberg** [comment]
Agreed! Align with EAD3.

**Comment by SJagodzinski** [comment]
EAC-CPF Berlin meeting, 11 March 2020:

Add the element `<representation>` as it is used and defined in EAD3 for EAC-CPF within `<control>.`
