### ISSUE TITLE
<maintenanceHistory>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#90]
## Maintenance History
- add attributes
`@audience`
`@scriptOfElement`
- keep element name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
The history of the creation and maintenance of the EAC-CPF instance.

**May contain**: `<maintenanceEvent>`
**May occur within**: `<control>`
**Attributes**: `@xml:id`, `@xml:lang` - all optional
**Availability**: Mandatory, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<maintenanceEvent>`
**May occur within**: `<control>`
**Attributes**:
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Availability**: Required, not repeatable

## Example encoding
```
<control>
 <recordId>record identifier</recordId>
 <maintenanceStatus value="new"/>
 <publicationStatus value="inprocess"/>
 <maintenanceAgency>  [...] </maintenanceAgency> 
 <maintenanceHistory audience="external" id="maintenancehistory1" languageOfElement="en" scriptOfElement="lat">
  <maintenanceEvent>
   <eventType value="created"/>
   <eventDateTime standardDateTime="2020-07-01T13:01:48">01.07.2020</eventDateTime>
   <agentType value="human"/> 
   <agent>agent name</agent>
   <eventDescription>description of the maintenance event</eventDescription>
  </maintenanceEvent>
 </maintenanceHistory>
</control>
```

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

We will not have control type elements anymore; we will move them to attributes to their parent elements.

**Comment by ailie-s** [comment]
Tag Library Text: 

**Summary:** A required child element of `<control>` that captures the history of the creation and maintenance of the EAC-CPF instance.
**May contain:** `<maintenanceEvent>` (1..n)
**May occur within:** `<control>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Description and Usage:**
A required child element of `<control>`, `<maintenanceHistory>` is for recording the history of the creation, revisions, updates, and other modifications to the EAC-CPF instance.
There must be at least one child `<maintenanceEvent>` in `<maintenanceHistory>`, which usually will be a record of the creation of the instance. There may be many other `<maintenanceEvent>` elements documenting the milestone changes or activities in the maintenance of the instance.
**Availability:** Required, not repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

- `<maintenanceHistory>` in itself is required in `<control>`
- `<maintenanceHistory>` cannot be repeated
- `<maintenanceHistory>` requires at least one `<maintenanceEvent>` as sub-element
- `<maintenanceHistory>` can be used with the optional attributes `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement`, and `@target
- `<maintenanceHistory>` can also be used with optional attributes from other namespaces (tested with XLink and XML)

The above applies to the RNG and the XSD.

Test successful.
