### ISSUE TITLE
<maintenanceEvent>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#91]
## Maintenance Event
- add attributes
`@audience`
`@maintenanceEventType`
`@scriptOfElement`
- keep element name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[new element `<evidence>` #73](https://github.com/SAA-SDT/eac-cpf-schema/issues/73)
[Topic_assertion_control.pdf](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/assertion/Topic_assertion_control.pdf)
`<agentType>` #94 

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience `- Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
A maintenance event in the life of the EAC-CPF instance.

**May contain**: `<agent`, `<agentType>`, `<eventDateTime>`, `<eventDescription>`, `<eventType>`
**May occur within**: `<maintenanceHistory>`
**Attributes** : `@xml:id`, `@xml:lang` - all optional
**Availability**: Mandatory, Repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: `<agent>`, `<eventDateTime>`, `<eventDescription>`
**May occur within**: `<maintenanceHistory>`
**Attributes** :
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageOfElement` - optional
`@maintenanceEventType` - required (values limited to: cancelled, created, deleted, derived, revised, unknown, updated)
`@scriptOfElement` - optional
**Availability**: Required, repeatable

- New or other example needed?
- Topic for Best Practise Guide in the context of assertion description

## Example encoding
```
<control>
 <recordId>record identifier</recordId>
 <maintenanceAgency>  [...] </maintenanceAgency> 
 <maintenanceHistory>
  <maintenanceEvent audience="external" id="maintenancevent1" languageOfElement="de" maintenanceEventType="created" scriptOfElement="lat">
   <eventDateTime standardDateTime="2020-07-01T13:01:48">01.07.2020</eventDateTime>
   <agent>agent name</agent>
   <eventDescription>description of the maintenance event</eventDescription>
  </maintenanceEvent>
 </maintenanceHistory>
</control>
```

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

We will not have control type elements anymore; we will move them to attributes to their parent elements.

**Comment by SJagodzinski** [comment]
EAC-CPF meeting, 6 November 2020:

We will not use an attribute to refer to a source from `<maintenanceEvent>`.
This is not a requirement for assertions so far.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of <maintenanceHistory> used to record information about maintenance activities in the history of the EAC-CPF instance.
**May contain:** agent (1..1), eventDateTime (1..1), eventDescription (0..n)
**May occur within:** maintenanceHistory
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement `- optional
`@maintenanceEventType` - required (values limited to: cancelled, created, deleted, derived, revised, unknown, updated)
`@scriptOfElement` - optional
`@target` - optional
**Description and Usage:**
A required child element of `<maintenanceHistory>`, `<maintenanceEvent>` is used to record an activity in the creation and ongoing maintenance of an EAC-CPF instance, including revisions, updates, and deletions. There will always be at least one maintenance event for each instance, which will typically be its creation.
`<maintenanceEvent>` must include `<agent>` and `<eventDateTime>` child elements to record the agent that carried out the maintenance event, and the date and time the maintenance event occurred.
**Attribute Usage:**
Use the required `@maintenanceEventType` to document the type of maintenance activity that the `<maintenanceEvent>` is recording, using one of the values from the available controlled list.
**Availability:** Required, repeatable

**Comment by kerstarno** [comment]
Tested in the context of Schema team's schema testing:

- `<maintenanceEvent>` is required within `<maintenanceHistory>`
- `<maintenanceEvent>` can be repeated
- `<maintenanceEvent>` requires the sub-elements `<eventDateTime>` and `<agent>` (both of which cannot be repeated)
- `<maintenanceEvent>` furthermore allows for the optional and repeatable sub-element `<eventDescription>`
- `<maintenanceEvent>` requires the attribute `@maintenanceEventType`
- `<maintenanceEvent>` can be used with the optional attributes `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement`, and `@target`
- `<maintenanceEvent>` can also be used with optional attributes from other namespaces (tested with XLink and XML)

The above applies to both, RNG and XSD.

Test successful.

@ailie-s - the sub-elements for `<maintenanceEvent>` are currently missing the cardinality information in the TL draft.

**Comment by kerstarno** [comment]
> EAC-CPF meeting, 6 November 2020:
> 
> We will not use an attribute to refer to a source from `<maintenanceEvent>`.
> This is not a requirement for assertions so far.

Just as a note with regard to the reopened `@target` vs `<reference>` question: having `@target` with `<maintenanceEvent>` effectively makes it possible to refer to a source from here, even though it's not with the dedicated `@sourceReference` attribute.

**Comment by SJagodzinski** [comment]
@fordmadox : see https://github.com/SAA-SDT/eac-cpf-schema/issues/158#issuecomment-749656888
