### ISSUE TITLE
<eventType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#92]
## Maintenance Event Type

- remove the element from EAC-CPF
- add new mandatory attribute `@maintenanceEventType` with restricted values (cancelled, created, deleted, derived, revised, unknown, updated) to `<maintenanceEvent>` instead

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<eventType>`: element content should become attribute value #8](https://github.com/SAA-SDT/eac-cpf-schema/issues/8)
`<agentType>` #94 

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@script` - Optional

## Context
The type of maintenance event for the EAC-CPF instance.

Revising EAC-CPF, the element will be removed and an attribute `<maintenanceEvent @maintenanceEventType>` will state the type of maintenance event.

## Solution documentation:

- remove from Tag Library

**Comment by kerstarno** [comment]
EAC-CPF Berlin meeting, 12 March 2020:

Use `<eventtype>` as an empty element without text or other content with a required attribute `@value` with limited values and without language attributes. This element is mandatory and not repeatable.

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

We will not have control type elements anymore; we will move them to attributes to their parent elements.

**Comment by karinbredenberg** [comment]
Element is removed and replaced with attribute in both rng and xsd schema.
