### ISSUE TITLE
<agentType>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#94]
## Agent Type

- remove the element from EAC-CPF
- add new mandatory attribute `@agentType` with restricted values (human, machine, unknown) to `<agent>` instead

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`<agentType>`: element content should become attribute value #7](https://github.com/SAA-SDT/eac-cpf-schema/issues/7)

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@lang` - Optional
`@script` - Optional

## Context:
The type of agent responsible for a maintenance event of the EAC-CPF instance.

Revising EAC-CPF, the element will be removed and an attribute <maintenanceEvent @agentType> will state the type of the agent.

## Solution documentation:
- remove from Tag Library

**Comment by kerstarno** [comment]
EAC-CPF Berlin meeting, 12 March 2020:

Use `<agenttype>` as an empty element without text or other content with a required attribute `@value` with limited values and without language attributes. This element is mandatory and not repeatable.

**Comment by fordmadox** [comment]
Just a note that it seems very odd to me for all the empty elements that have ```@value```. It seems to me, based on our Design Principles, that those elements should be defined as attributes instead.  

e.g. what's the need for an agentType element, if we instead used ```@type``` or  ```@agentType``` on the agent element?  Ditto for the rest.  Given that attributes are all "key/value" pairs, it seems very odd to have these in the "value/value" format  😄.  Also, it would simplify control.  Not sure if EAD3 considered this or not.

**Comment by fordmadox** [comment]
E.g.

This looks complicated, with no extra benefits that I can think of:

```
<maintenanceEvent>
    <eventType value="derived"/>
    <eventDateTime standardDateTime="2018-12">Whenever that December</eventDateTime>
    <agentType value="human"/>
    <agent>Whomever</agent>
</maintenanceEvent>
```

Versus

```
<maintenanceEvent eventType="derived">
    <eventDateTime standardDateTime="2018-12">Whenever that December</eventDateTime>
    <agent agentType="human">Somebody</agent>
</maintenanceEvent>
```

And I'd think it could be further simplified with generic ```@type``` attributes, though I know that there are differing opinions about that point.

**Comment by kerstarno** [comment]
If I remember correctly, the idea of using `@value` for the pre-defined terms and still having a dedicated element in EAD3 was to allow users to use the element's content for analog terms in their own languages while still having standardised terms in the attribute for interoperability, e.g. `<eventType value="created" languageOfElement="ger">erstellt</eventType>`.

This option has now been removed (decision at Berlin meeting to have these elements not allow text anymore), so in general it could be an option to consider changing `@value` into context-specific `@...Type` attributes used with other elements. I think, this could work for a `@maintenanceEventType` and an `@agentType` as in the example above and maybe `@maintenanceStatus` and `@publicationStatus` could be attributes of either the root element or `<control>` (EAD2002 had `@findaidstatus` with `<eadheader>`) . 

I'm not sure, though, where we would put an attribute @entityType. To me, it would feel even more "out of place" if we added it as an attribute to `<identity>` than it already does with having it as a sub-element here (speaking towards the mix of "entity" and "identity"). Or would we use it with `<cpfDescription>`?

**Comment by SJagodzinski** [comment]
Outcome EAC-CPF September 2020 meeting:

We will not have control type elements anymore; we will move them to attributes to their parent elements. 
We have decided to put the elements `<maintenanceStatus>` and `<publicationStatus>` as attributes into `<control>.`

**Comment by karinbredenberg** [comment]
Tested in both xsd and rng and its removed and replaced with the attribute instead.
