### ISSUE TITLE
<agent>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#95]
## Agent
- add attributes
`@agentType`
`@audience`
`@scriptOfElement`
`@valueURI`
`@vocabularySource`
`@vocabularySourceURI`
- keep element name and definition

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@script` - Optional

## Context
The agent (human or machine) responsible for an event in the maintenance of the EAC instance.

**May contain**: [text]
**May occur within**: `maintenanceEvent`
**Attributes:** `@xml:id`, `@xml:lang` -optional
**Availability:** Mandatory, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<maintenanceEvent>`
**Attributes:**
`@agentType` - required (values limited to: human, machine, unknown)
`@audience` - optional (values limited to: external, internal)
`@id` - optional 
`@languageOfElement` - optional 
`@scriptOfElement` - optional 
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI` - optional
**Availability:** Required, not repeatable

## Example encoding
```
<maintenanceHistory>
 <maintenanceEvent>
  <eventDateTime>01.07.2020</eventDateTime>
  <agencyName audience="external" id="agencyName1" languageOfElement="eng" scriptOfElement="lat" valueURI="agencyNameURI" vocabularySource="VIAF" vocabularySourceURI="VIAFURI" target="agencycode1">agency name</agencyName>
 </maintenanceEvent>
</maintenanceHistory>
```

**Comment by karinbredenberg** [comment]
Element agent tested:
May occur within: <maintenanceEvent> 1..1 **Ok in both schemas**
Contains text  **Ok in both schemas**
@audience - optional (values limited to: external, internal) **Ok in both schemas**
@id - optional **Ok in both schemas**
@languageOfElement - optional **Ok in both schemas**
@scriptOfElement - optional **Ok in both schemas**
@valueURI - optional **Ok in both schemas**
@vocabularySource - optional **Ok in both schemas**
@vocabularySourceURI - optional **Ok in both schemas**

new @agentType - mandatory **Ok in both schemas**

**Result**: Element  ready.

**Comment by karinbredenberg** [comment]
@agentType missing in attribute list.

**Comment by ailie-s** [comment]
Can we confirm that `@agentType` will be included on `<agent>` and not `<maintenanceEvent>` #91 ?

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** A required child element of `<maintenanceEvent>` that provides the name of a person, institution, or system responsible for the creation, modification, or deletion of an EAC-CPF instance.
**May contain:** [text]
**May occur within:** maintenanceEvent
**Attributes:**
`@agentType` - Required (values limited to: human, machine, unknown)
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
`@target` - optional
`@valueURI` - optional
`@vocabularySource` - optional
`@vocabularySourceURI `- optional
**Description and Usage:**
Use `<agent>` to indicate the person, institution, or system responsible for a maintenance event. Examples include the name of the author or encoder, the database responsible for creating the EAC-CPF instance, and the style sheet used to update an instance to a new version of EAC-CPF.
Give the name of the agent for each maintenance event described in `<maintenanceEvent>`.
**Attribute Usage:**
Use the required `@agentType `attribute to specify whether the agent is 'human', 'machine', or 'unknown'.
**Availability:** Required, not repeatable

**Comment by SJagodzinski** [comment]
> 
> 
> Can we confirm that `@agentType` will be included on `<agent>` and not `<maintenanceEvent>` #91 ?

@ailie-s : confirmed

**Comment by SJagodzinski** [comment]
@fordmadox : see https://github.com/SAA-SDT/eac-cpf-schema/issues/158#issuecomment-749656888

**Comment by kerstarno** [comment]
@SJagodzinski and @fordmadox for information:

The most recent EAC Team meeting discussed the question of potentially requiring content for those elements that are currently mandatory for a minimum EAC instance. `<agent>` is one of these. The Schema Team followed up on this during their meeting today and suggest to make `<agent>` optional. Seeing that it currently does not require to have content, we do not foresee any issues with regard to moving from EAC-CPF 1.0 to EAC-CPF 2.0 in this context. 

For background see also: https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/working-documents/20210108_ContentRequirement_MandatoryElements.pdf

**Comment by kerstarno** [comment]
If we do not make `<agent>` optional (which - for now - has already been implemented in the draft schema), do we then require the element to have content? Do we do something similar as has now been implemented (for testing) with regard to `<part>` (see #133), i.e. requiring that at least one non-whitespace character must be present?

If we consider this element carrying essential information by telling us if the agent is "human" or a "machine" (via `@agentType`), it might make sense to transform the essential information into useful information by adding a nudge to also provide a name for this "human" or this "machine". If we don't think, this information would easily be available, we might want to ask ourselves if knowing that the agent is "human" or a "machine" already is useful enough to require this element in all cases.

**Comment by MicheleCombs** [comment]
If it’s not optional it needs to accept the value “unknown” and/or be permitted empty.  People won’t always know where their EAD comes from.

Michele

**Comment by SJagodzinski** [comment]
I agree with @MicheleCombs , give users the chance to leave the element empty for unknown agents.

`<agent>` is mandatory but can be an empty element. 

`<agent>` needs to be mandatory, because agent type (human, machine, unknown) is a crucial information for maintance information. As requested by @kerstarno this mandatory attributes changed from `<maintenanceEvent>` to `<agent>`.

**Comment by fordmadox** [comment]
Just so that I'm clear.  Is it okay if the following, at a minimum, is required:

```
          <agent agentType="unknown"/>
```

If so, then the element and attribute are ready in both schemas. 

If that is not correct, what should be changed in the schemas?

**Comment by SJagodzinski** [comment]
@fordmadox : Yes, thats ok and there no need to change the schemas.

**Comment by kerstarno** [comment]
Thanks for the clarification, @SJagodzinski.

I think, we'll have to agree to disagree on what is crucial information in this case :-) And on how it's easier to require an element but allow it to be empty, than to not require it at all, if we want cater for situation when the wanted information is not known.

**Comment by kerstarno** [comment]
@fordmadox During the most recent testing for #86 I found that `<agent>` seems to have become optional in both schemas. Could you please re-check and make sure that the schema reflects the final decision in this issue here: keeping `<agent>` and its attribute `@agentType` mandatory, but not requiring text in the element? Thanks very much in advance :-)

**Comment by fordmadox** [comment]
@kerstarno  It was switched to optional after the last Schema team meeting, ten days ago, when we decided to test only making recordId and a single nameEntry required.  I can add it back now based on the above discussion.  Given that eventDateTime and agent are required, should we change the order such that agent comes first?

**Comment by kerstarno** [comment]
> I agree with @MicheleCombs , give users the chance to leave the element empty for unknown agents.
> 
> `<agent>` is mandatory but can be an empty element.
> 
> `<agent>` needs to be mandatory, because agent type (human, machine, unknown) is a crucial information for maintenance information. 

Yes, but @SJagodzinski objected to this and asked for it to remain mandatory.

**Comment by kerstarno** [comment]
As for the order, sure, we could make it an alphabetical order for these two mandatory and not repeatable elements.

**Comment by fordmadox** [comment]
Seems like that is keeping it consistent with the rest of the schema: https://github.com/SAA-SDT/eac-cpf-schema/commit/a729cad014f22b0792c317824b14867328b50c3c  Updated here and can be tested now in the development branch.

**Comment by kerstarno** [comment]
Re-tested:
- `<maintenanceEvent>` now requires `<agent>` as its sub-element, next to `<eventDateTime>`
- `<agent>` requires the attribute `@agentType`, but can be left empty
- `<agent> is expected to appear before `<eventDateTime>`

The above applies to  both schemas, RNG and XSD.
