### ISSUE TITLE
<language>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#98]
## Language
- add **attributes:**
`@audience`
`@conventationDeclarationReference` 
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 
- change availability for //languageUsed/language from _required_ to _optional_
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[Child elements of singular/plural elements #61](https://github.com/SAA-SDT/eac-cpf-schema/issues/61)
[Role and function of singular/plural elements is confusing #21](https://github.com/SAA-SDT/eac-cpf-schema/issues/21)

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@label` - Optional
`@script` - Optional

**Similiar attribute** 
`@langcode` - Optional

**May occur within**: `<langmaterial>`,  `<languageset>`
**Availability:**
Within `<langmaterial>`:  One of `<language>` or `<languageset>` is required, repeatable
Within `<languageset>`: Required, repeatable

Same usage of `<language>` within `<languageDeclaration>`.
Different solutions to encode the entities used language resp. the language of the materials being described.

## Context
The specification of a particular language used in the EAC-CPF instance or in the creative work of the CPF entity being described.

**May contain**: [text]
**May occur within**: `<languageDeclaration>`, `<languageUsed>`
**Attributes:** 
`@languageCode` - Required
`@xml:id`, `@xml:lang` - all optional

**Availability:** Mandatory, Non-repeatable

## Solution documentation:
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<languageUsed>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageCode` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, repeatable

- New or other example needed
- Topic for Best Practise Guide

# Example encoding
```
<languageUsed>
 <language audience="external" conventionDeclarationReference="conventiondeclaration1" id="language1" languageCode="en" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptOfElement="lat" sourceReference="source1">English</language>
 <writingSystem scriptCode="lat">Latin</writingSystem>
</languageUsed>
```

**Comment by SJagodzinski** [comment]
Decision of EAC meeting, 24 April 2020:

1. Keept availability within `<languageused>`

**Comment by SJagodzinski** [comment]
Decision from EAC meeting, 24 April 2020 was to change availability of attribute `@scriptCode` within //languageUsed/writingSystem from required to optional, see [comment](https://github.com/SAA-SDT/eac-cpf-schema/issues/99#issuecomment-619027874) in #99  

Ergo, the attribute `@languageCode` within //languageUsed/language is supposed to be optional, too.

**Comment by ailie-s** [comment]
Tag Library Text:

**Summary:** An optional child element of `<languageUsed>` that identifies a particular language used in the creative work of the CPF entity being described.
**May contain:** [text]
**May occur within:** `<languageUsed>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageCode` - optional
`@languageOfElement` - optional
`@scriptOfElement` - optional
**Description and Usage:**
An optional element within `<languageUsed>` that gives the language or languages used by the CPF entity being described.
**Attribute Usage:**
The `@languageCode` attribute can be used to encode a valid code from ISO 639-2.
**Availability:** Optional, repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

- `<language>` is not available anymore in `<languageDeclaration>`
- `<language>` is optional in `<languageUsed>`
  - @SJagodzinski - I think, it would be good to revise this. It makes sense not to require a `@languageCode` with regard to languages that might not be covered by the ISO standards, as well as it makes sense not to require `<writingSystem>` seeing that certain languages will always be bound to a specific writing system anyway. But with `<language>` being optional, `<languageUsed>` can effectively be used as a completely empty element (i.e. `<languageUsed/>`), which doesn't seem to be particularly useful.
- `<language>` can be repeated in `<languageUsed>`
- `<language>` can contain text 
- `<language>` can be used to the optional attributes `@audience`, `@conventionDeclarationReference`, `@id`, `@languageCode`, `@languageOfElement`, `@maintenanceEventReference`, `@scriptOfElement`, `@sourceReference`, and `@target`
- `<language>` can also be used with optional attributes from other namespaces (tested with XLink)

The above applies to both, RNG and XSD. 

Test successful as it stands for now, pending the question raised above with regard to the cardinality of `<language>`.

@ailie-s - the `@...Reference` attributes are currently missing from the TL draft, as is `@target` (though the latter might be pending the January meeting).

**Comment by SJagodzinski** [comment]
@kerstarno : `<languageUsed>` with only `<descriptiveNote>` might be useful, eg 
```
<languageUsed>
 <descriptiveNote>
   <p>It is not known what language and script the entity used.</p>
 </descriptiveNote>
</languageUsed>
```
It might also be useful to have empty elements like <languageUsed/> as place holder for missing information or created by processing db data into xml but not having the language information available. 

@fordmadox, @karinbredenberg : Is there any design principle or rule to avoid empty elements so far? 

If it is a requirement to avoid empty elements the schema should use <xs:choice> to enforce one of the child elements, but I think there is no need to define a mandatory element here.

**Comment by fordmadox** [comment]
No principle for that issue currently, and I personally think it's fine to allow empty elements.  Also, the above example is a good one that we should add to the Best Practices guide. 

It would be good to review our wrapper elements at some point, though, and consider implementing a principle and then make sure that principle is applied consistently in the schema :smile:  For instance, we could have a stance on exactly how to indicate that something is unknown vs. something having no value and have guidance on how to test for that.  

In any event, if we do require language to be present (which I'd also be fine with), then the following encoding would be equivalent (and equally as valid):

```
                <languagesUsed>
                    <languageUsed>
                        <language/>
                        <descriptiveNote>
                            <p>It is not known what language and script the entity used.</p>
                        </descriptiveNote>
                    </languageUsed>
                </languagesUsed>
```

**Comment by kerstarno** [comment]
I'd support @fordmadox's point with regard to guidance - and maybe at some point even an according option in the schema - around indication of something being unknown vs. something not having a value. 

Looking at the example of exporting from a DB to XML, e.g. for sharing in an aggregation context, I personally would rather avoid empty elements, because as soon as the data is shared, there is no way for the person or system that it is shared with to know, if something is left empty by mistake, or because there was no value, or because there was a conscious decision to not share this piece of information, or because there was a conscious decision of leaving something without a value because it's unknown.  

But that might just be me :-)

**Comment by kerstarno** [comment]
I'm removing the "In progress" label on this one based on @SJagodzinski's example with only `<descriptiveNote>` above as well as based on the decision taken during the most recent EAC Team meeting to only look at any minimally mandatory elements to potentially require content (which would not include `<language>`.)
