### ISSUE TITLE
<script>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#99]
## Script
- **rename** to `<writingSystem>`
- add **attributes:**
`@audience`
`@conventationDeclarationReference` 
`@maintenanceEventReference`
`@scriptOfElement` 
`@sourceReference` 
- change **availability** for //languageUsed/script from _required_ to _optional_

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## Related issues / documents
[`@scriptCode`: remove and adjust tag library for `@xml:lang` / `@lang` SAA-SDT/EAD3#30](https://github.com/SAA-SDT/eac-cpf-schema/issues/30)
[`<script>` tag may be a security vulnerability SAA-SDT/eas-schemas#23](https://github.com/SAA-SDT/eas-schemas/issues/23)

## EAD3 Reconciliation
**Additional EAD 3 attributes**
`@altrender` - Optional
`@audience` - Optional (values limited to: external, internal)
`@encodinganalog` - Optional
`@label` - Optional
`@script` - Optional

**May occur within**: `<languageset>`
**Availability:** Within `<languageset>:` Required, repeatable

## Context
The specification of a particular script used in the EAC-CPF instance or in the creative work of the CPF entity being described.

**May contain**: [text]
**May occur within**: `<languageDeclaration>`, `<languageUsed>`
**Attributes:** 
`@scriptCode` - Required
`@xml:id`, `@xml:lang` - all optional
**Availability:** Mandatory, Non-repeatable

## Solution documentation
Rephrasing _Summary_, _Description and Usage_ and _Attribute usage_ needed?

**May contain**: [text]
**May occur within**: `<languageUsed>`
**Attributes:**  
`@audience` - optional (values limited to: external, internal)
`@conventationDeclarationReference` - optional
`@id` - optional
`@languageCode` - optional
`@languageOfElement` - optional 
`@maintenanceEventReference` - optional
`@scriptCode` - optional
`@scriptOfElement` - optional
`@sourceReference` - optional

**Availability:** Optional, repeatable

- New or other example needed
- Topic for Best Practise Guide

# Example encoding
```
<languageUsed>
 <language>English</language>
 <writingSystem audience="external" conventionDeclarationReference="conventiondeclaration1" id="script1" languageOfElement="en" maintenanceEventReference="maintenancevent1" scriptCode="lat" scriptOfElement="lat" sourceReference="source1">Latin</writingSystem>
</languageUsed>
```

**Comment by SJagodzinski** [comment]
About renaming:

TEI P5 is using element name `<scriptDesc>` for description of the scripts used in a manuscript or other object, cf. https://tei-c.org/release/doc/tei-p5-doc/de/html/ref-scriptDesc.html.

**Comment by SJagodzinski** [comment]
Decision of EAD meeting, 20 April 2020:

Rename `<script>` to `<writingsystem>`.

**Comment by SJagodzinski** [comment]
Decision of EAC meeting, 24 April 2020:

1. Confirmation to rename `<script>` to `<writingsystem>.`
2. Keep both attributes `@scriptcode` and `@script` as optional attributes. Change occurance of `@scriptcode` from _required_ to _optional._
3. Rename language and script attributes `@lang` and `@script` to `@languageofelement` and `@scriptofelement`.
4. Change occurance of `<writingsystem>` within `<languageused>` from _required_ to _optional._

**Comment by ailie-s** [comment]
Tag Library Text:

**`<writingSystem>`  Writing System**

**Summary:** An optional child element of `<languageUsed>` that identifies the writing script for a language in which the CPF entity being described was creative or productive.
**May contain:** [text]
**May occur within:** `<languageUsed>`
**Attributes:**
`@audience` - optional (values limited to: external, internal)
`@id` - optional
`@languageOfElement` - optional
`@scriptCode` - optional
`@scriptOfElement` - optional
**Description and Usage:**
An optional element within `<languageUsed>` that gives the main script used by the CPF entity being described in his/her creative or productive work.
**Attribute Usage:** The `@scriptCode` attribute can be used to encode a valid code from ISO 15924.
**Availability:** Optional, repeatable

**Comment by kerstarno** [comment]
Tested as part of Schema team's schema testing:

- `<script>` is not available anymore in `<languageDeclaration>` (nor in `<languageUsed>`)
- `<writingSystem>` is optional in `<languageUsed>`
- `<writingSystem>` can be repeated in `<languageUsed>`
- `<writingSystem>` can contain text 
- `<writingSystem>` can be used to the optional attributes `@audience`, `@conventionDeclarationReference`, `@id`, `@languageOfElement`, `@maintenanceEventReference`, `@scriptCode`, `@scriptOfElement`, `@sourceReference`, and `@target`
- `<writingSystem>` can also be used with optional attributes from other namespaces (tested with XLink)

The above applies to both, RNG and XSD. 

Test successful.

@ailie-s - the `@...Reference` attributes are currently missing from the TL draft, as is `@target` (though the latter might be pending the January meeting).
